### ISSUE TITLE
首页访问跳转http://cmdb.bk.com/account/login?cburl=    但页面为空白

### ISSUE THREAD

**Issue by Gourgii** [Tencent/bk-cmdb#10]
数据库中无数据，执行php index.php /cli/Init/initUserData没有报错，求解释一下

**Comment by radiogit** [comment]
一样的问题，还没有解决

**Comment by Fchrisqing** [comment]
可以检查一下config.php中配置的BASE_URL和nginx中配置的域名是否一致

**Comment by Gourgii** [comment]
是一致的。

**Comment by huangmeng4520** [comment]
php index.php /cli/Init/initUserData 看程序日志有没有抛错，另外用php -m|grep mysql 看下mysql是安装了扩展，这个命令执行之后，数据库里面是有数据的。如果没有数据证明没有初始化成功

**Comment by lowenitt** [comment]
把production/constants/php中的配置截取我们看下吧

**Comment by Gourgii** [comment]
![image](https://cloud.githubusercontent.com/assets/17631767/21445390/4c3015e2-c8f3-11e6-8110-d752a768bb94.png)

**Comment by lowenitt** [comment]
合并一下之前的issue，确定下session的读写路径有没权限

**Comment by Gourgii** [comment]
读写权限有的，现在的问题是我执行/usr/local/php/bin/php index.php  /cli/Init/initUserData 无返回，而且数据库也没有数据，检查数据库配置没有问题，麻烦大神帮忙分析下问题

**Comment by raindylong** [comment]
@Gourgii ， 楼上@huangmeng4520 大神已经提示了， 运行php -m| grep mysql 看看有木有安装mysql扩展，如下：
`
~$ /usr/bin/php -m | grep mysql
mysql   #必须要有这个模块，bk-cmdb应该是用旧版本mysql驱动写的，还不支持其他新版本mysql驱动
mysqli
mysqlnd
pdo_mysql
`

**Comment by Gourgii** [comment]
谢谢了，重新编译了个5.6.9的php搞定了，因为我这边自己安装的php7.1，所有没有get到这个梗，多谢各位大神@Gourgii  @huangmeng4520 @raindylong @all
