### ISSUE TITLE
主机支持跨业务管理

### ISSUE THREAD

**Issue by owenlxu** [Tencent/bk-cmdb#101]
主机支持跨业务管理

**Comment by lowenitt** [comment]
### 导入主机到模块
1.主机属于资源池如何处理？
2.主机归属于某一个业务如何处理？
### 业务内主机转移
1.覆盖如何处理？
2.更新如何处理？
### 主机转移到空闲机/故障机
1 .属于多业务如何处理？
### 主机从空闲机回收到资源池
1. 属于多业务如何处理？
@techfindd

**Comment by techfindd** [comment]
导入主机到模块
1.主机属于资源池如何处理？
 
     主机属于资源池就当作一次正常的资源池分配到业务，表现为资源池中的主机消失，转移到了业务的模块

2.主机归属于某一个业务如何处理？

    如果主机X属于已经属于业务A， 此时转移到业务B的时候，不会改动X在A中的关系，会在B中的模块增加这个关系

业务内主机转移
1.覆盖如何处理？

   覆盖只重置这个主机在当前业务A内的所属模块关系，不影响所属业务B甚至C里面所属模块的关系

2.更新如何处理？
   
   更新正常逻辑即可，就是在当前主机上增加一个模块的所属关系


主机转移到空闲机/故障机
1 .属于多业务如何处理？

    X从A转移到空闲机/故障机，X在B中的模块关系没有变化

主机从空闲机回收到资源池
属于多业务如何处理？

    X从A转移到资源池，判断X是否是A中空闲机模块，如果是，这个主机可以从空闲机中转到资源池。这时候判断主机是否还在其他业务存在所属模块关系，如果是，这个主机不会被转移到资源池中
