### ISSUE TITLE
模型删除操作忽略了cc_PropertyGroup表中模型属性分组信息的删除

### ISSUE THREAD

**Issue by scarpdiem** [Tencent/bk-cmdb#1026]
问题描述
===========
创建模型对象时，会在cc_ObjDes,cc_ObjAttDes, cc_PropertyGroup三个表中写入模型对象，模型默认属性，模型默认分组信息，但是删除模型的api只删除了cc_ObjDes,cc_ObjAttDes两个表中的信息，cc_PropertyGroup表中的信息被忽略。此结论来自于对src/scene_server/topo_server/core/operation/object.go文件中DeleteObject()方法的分析

重现方法
================
页面操作删除模型，然后使用robot 3T查看mongodb中 cc_PropertyGroup表内包含此bk_obj_id的单元

关键信息
=========

请提供以下信息:

 - [ ] bk-cmdb   版本 (发布版本号 或 git tag): `<master: faee2d9>`
 - [ ] Redis     版本: `<3.2.11>`
 - [ ] MongoDB   版本: `<2.8.0-rc5>`
 - [ ] ZooKeeper 版本: `<3.4.11>`
 - [ ] 操作系统      : `<CentOS 7.2.1511>`
 - [ ] bk-cmdb 模型属性分组不能被正确删除

**Comment by lowenitt** [comment]
@uriwang
