### ISSUE TITLE
设备管理实现

### ISSUE THREAD

**Issue by wusendong** [Tencent/bk-cmdb#1077]

**Comment by freakkid** [comment]
## 设备

### 新增设备

- API: POST /api/{version}/netcollect/device/action/create
- API 名称: create_device
- 功能说明：
	- 中文：新增设备
	- English: create device

- input body:

``` json
[
    {
        "bk_obj_id": "bk_switch",
        "bk_obj_name": "交换机",
        "device_model": "NX120",
        "device_name": "交换机20000",
	    "bk_vendor": "厂商1"
    },
    {
        "bk_obj_id": "bk_load_balance",
        "bk_obj_name": "负载均衡",
        "device_model": "NX122",
        "device_name": "负载均衡20000",
	    "bk_vendor": "厂商2"
    }
]
```

- input 字段说明

|字段|类型|是否必须|默认值|说明|Description|
|---|---|---|---|---|---|
|bk_obj_id|string|是|无|网络设备对应的模型ID，bk_switch, bk_router, bk_load_balance, bk_firewall|the object id of net device，bk_switch, bk_router, bk_load_balance, bk_firewall|
|bk_obj_name|string|是|无|模型的名字，用于展示|the object name ,it will be used to shown|
|device_model|string|是|无|设备型号|device model|
|device_name|string|是|无|设备名|the device's name|
|bk_vendor|string|是|无|厂商|the vendor's name|

- output:

```json
{
    "result": true,
    "bk_error_code": 0,
    "bk_error_msg": "",
    "data": [
        {
            "result": true,
            "error_msg": "",
            "device_id": 1
        },
        {
            "result": true,
            "error_msg": "",
            "device_id": 2
        }
    ]
}
```


### 查询设备

- API: POST /api/{version}/netcollect/device/action/search
- API 名称: search_device
- 功能说明：
	- 中文：查询设备
	- English: search device

- input body

``` json
{
    "fields": [],
    "page": {
        "start": 0,
        "limit": 10,
        "sort": "device_id"
    },
    "condition": [
        {
            "field": "device_id",
            "operator": "$ne",
            "value": 1
        },
        {
            "field": "bk_obj_id",
            "operator": "$eq",
            "value": "bk_switch"
        }
    ]
}
```

- input 参数说明

| 字段|类型|必填|默认值|说明|Description|
|---|---|---|---|---|---|
| page | object | 是|无|分页参数 |page parameter|
| fields | array | 是| 无|查询字段|search fields|
| condition |  object | 是| 无|查询条件|search condition|

page 参数说明：

| 名称  | 类型 |必填| 默认值 | 说明 | Description|
| ---  | ---  | --- |---  | --- | ---|
| start | int | 是|无|记录开始位置 |start record|
| limit | int | 是| 无|每页限制条数|page limit |
| sort | string | 否| 无|排序字段|the field for sort|

**注：sort 字段通过在字段前面增加 -，如 sort:"-field" 可以表示按照字段field降序。**

fields参数说明：

参数为设备的任意属性，如果不填写字段信息，系统会返回设备的所有字段。

**注：需要填写的参数取决于用户自己定义的属性字段。**

condition 参数说明：

condition 参数为设备的任意属性，如果不写代表搜索全部数据。

**注：需要填写的参数取决于用户自己定义的属性字段。**

- output:

``` json
{
    "result": true,
    "bk_error_code": 0,
    "bk_error_msg": null,
    "data": {
        "count": 2,
        "info": [
            {
                "device_id": 1,
                "device_model": "NX120",
                "device_name": "交换机20000",
                "bk_obj_name": "交换机",
                "bk_object_id": "bk_switch",
                "bk_vendor": "厂商1"
            },
            {
                "device_id": 2,
                "device_model": "NX220",
                "device_name": "路由20000",
                "bk_obj_name": "路由",
                "bk_object_id": "bk_router",
                "bk_vendor": "厂商2"
            }
        ]
    }
}
```

### 删除设备

- API: DELETE /api/{version}/netcollect/device/{device_id}/action/delete
- API 名称: delete_device
- 功能说明：
	- 中文：删除设备
	- English: delete device

- input body

    无

- input参数说明

| 字段|类型|必填|默认值|说明|Description|
|---|---|---|---|---|---|
|device_id|int|是|无|设备id|the device id|

- output:

```json
{
	"result": true,
	"bk_error_code": 0,
	"bk_error_msg": null,
	"data": "success"
}
```
