### ISSUE TITLE
属性管理实现

### ISSUE THREAD

**Issue by wusendong** [Tencent/bk-cmdb#1078]

**Comment by freakkid** [comment]
## 属性

### 新增属性

- API: POST /api/{version}/netcollect/property/action/create
- API 名称: create_netcollect_property
- 功能说明：
	- 中文：新增属性
	- English: create netcollect property

- input body:

``` json
[
    {
        "bk_property_id": "bk_asset_id",
        "bk_property_name": "固资编号",
        "bk_obj_id": "bk_switch",
        "bk_obj_name": "交换机",
        "device_id": 1,
        "device_name": "交换机20000",
        "oid": "1.3.6.1.2.1.2.2.1.14",
        "period": "20M",
        "action": "get"
    },
    {
        "bk_property_id": "bk_sn",
        "bk_property_name": "SN",
        "bk_obj_id": "bk_balance",
        "bk_obj_name": "负责均衡",
        "device_id": 2,
        "device_name": "负载均衡20000",
        "oid": "1.3.6.1.2.1.2.2.1.34",
        "period": "20M",
        "action": "get"
    }
]
```

- input参数说明

| 字段|类型|必填|默认值|说明|Description|
|---|---|---|---|---|---|
|bk_property_id|string|是|无|模型的属性ID|property id|
|bk_property_name|string|是|无|属性名|property name|
|device_id|int|是|无|设备iID|device id|
|device_name|string|是|无|设备名|device name|
|bk_obj_id|string|是|无|对应模型ID|object id|
|bk_obj_name|string|是|无|对应模型名|object name|
|oid|string|是|无|对象标识符 |object Identifier|
|period|string|是|无|采集周期，后缀：D,H,M,S|collect period, suffix: D, H, M, S|
|action|enum|否|get|采集方式：get/walk（get：获取单个，walk：批量获取）|action: get/walk|


- output:
```json
{
    "result": true,
    "bk_error_code": 0,
    "bk_error_msg": "",
    "data": [
        {
            "result": true,
            "error_msg": "",
            "netcollect_property_id": 1
        },
        {
            "result": true,
            "error_msg": "",
            "netcollect_property_id": 2
        }
    ]
}
```

###  查询属性

- API: POST /api/{version}/netcollect/property/action/search
- API 名称: search_netcollect_property
- 功能说明：
	- 中文：查询属性
	- English: search netcollect property


- input body:

``` json
{
    "fields": [],
    "page": {
        "start": 0,
        "limit": 10,
        "sort": "bk_property_name"
    },
    "condition":  [
        {
            "field": "netcollect_property_id",
            "operator": "$ne",
            "value": 1
        },
        {
            "field": "action",
            "operator": "$eq",
            "value": "get"
        }
    ]     
}
```


- input 参数说明

| 字段|类型|必填|默认值|说明|Description|
|---|---|---|---|---|---|
| page | object | 是|无|分页参数 |page parameter|
| fields | array | 是| 无|查询字段|search fields|
| condition |  object | 是| 无|查询条件|search condition|

page 参数说明：

| 名称  | 类型 |必填| 默认值 | 说明 | Description|
| ---  | ---  | --- |---  | --- | ---|
| start | int | 是|无|记录开始位置 |start record|
| limit | int | 是| 无|每页限制条数|page limit |
| sort | string | 否| 无|排序字段|the field for sort|

**注：sort 字段通过在字段前面增加 -，如 sort:"-field" 可以表示按照字段field降序。**

fields参数说明：

参数为设备属性的任意字段，如果不填写字段信息，系统会返回业务的所有字段。

**注：需要填写的参数取决于用户自己定义的属性字段。**

condition 参数说明：

condition 参数为设备属性的任意字段，如果不写代表搜索全部数据。

**注：需要填写的参数取决于用户自己定义的属性字段。**

- output:

``` json
{
    "result": true,
    "bk_error_code": 0,
    "bk_error_msg": null,
    "data": {
        "count": 2,
        "info": [
            {
                "netcollect_property_id": 1,
                "device_id": 3,
                "device_name": "交换机20000",
                "bk_property_id": 34,
                "bk_property_name": "固资编号",
                "unit":"",
                "oid": "1.3.6.1.2.1.2.2.1.14",
                "bk_obj_id": "bk_switch",
                "bk_obj_name": "交换机",
                "period": "30M",
                "action": "get"
            },
            {
                "netcollect_property_id": 2,
                "device_id": 2,
                "device_name": "负载均衡20000",
                "bk_property_id": 34,
                "bk_property_name": "厂商",
                "unit":"",
                "oid": "1.3.6.1.2.1.2.2.1.34",
                "bk_obj_id": "bk_load_balance",
                "bk_obj_name": "负载均衡",
                "period": "20M",
                "action": "get"
            }
        ]
    }
}
```


### 删除属性

- API: DELETE /api/{version}/netcollect/property/{netcollect_property_id}/action/delete
- API 名称: delete_netcollect_property
- 功能说明：
	- 中文：删除属性
	- English: delete netcollect property

- input body

    无

- input参数说明

| 字段|类型|必填|默认值|说明|Description|
|---|---|---|---|---|---|
|netcollect_property_id|int|是|无|属性id|the netcollect property id|

- output:

```json
{
	"result": true,
	"bk_error_code": 0,
	"bk_error_msg": null,
	"data": "success"
}
```
