### ISSUE TITLE
网络设备采集功能设计

### ISSUE THREAD

**Issue by wusendong** [Tencent/bk-cmdb#1079]

**Comment by freakkid** [comment]
## 设备

### 新增设备

- API: POST /api/{version}/netcollect/device/action/create
- API 名称: create_device
- 功能说明：
	- 中文：新增设备
	- English: create device

- input body:

``` json
[
    {
        "bk_obj_id": "bk_switch",
        "bk_obj_name": "交换机",
        "device_model": "NX120",
        "device_name": "交换机20000",
	    "bk_vendor": "厂商1"
    },
    {
        "bk_obj_id": "bk_load_balance",
        "bk_obj_name": "负载均衡",
        "device_model": "NX122",
        "device_name": "负载均衡20000",
	    "bk_vendor": "厂商2"
    }
]
```

- input 字段说明

|字段|类型|是否必须|默认值|说明|Description|
|---|---|---|---|---|---|
|bk_obj_id|string|是|无|网络设备对应的模型ID，bk_switch, bk_router, bk_load_balance, bk_firewall|the object id of net device，bk_switch, bk_router, bk_load_balance, bk_firewall|
|bk_obj_name|string|是|无|模型的名字，用于展示|the object name ,it will be used to shown|
|device_model|string|是|无|设备型号|device model|
|device_name|string|是|无|设备名|the device's name|
|bk_vendor|string|是|无|厂商|the vendor's name|

- output:

```json
{
    "result": true,
    "bk_error_code": 0,
    "bk_error_msg": "",
    "data": [
        {
            "result": true,
            "error_msg": "",
            "device_id": 1
        },
        {
            "result": true,
            "error_msg": "",
            "device_id": 2
        }
    ]
}
```


### 查询设备

- API: POST /api/{version}/netcollect/device/action/search
- API 名称: search_device
- 功能说明：
	- 中文：查询设备
	- English: search device

- input body

``` json
{
    "fields": [],
    "page": {
        "start": 0,
        "limit": 10,
        "sort": "device_id"
    },
    "condition": [
        {
            "field": "device_id",
            "operator": "$ne",
            "value": 1
        },
        {
            "field": "bk_obj_id",
            "operator": "$eq",
            "value": "bk_switch"
        }
    ]
}
```

- input 参数说明

| 字段|类型|必填|默认值|说明|Description|
|---|---|---|---|---|---|
| page | object | 是|无|分页参数 |page parameter|
| fields | array | 是| 无|查询字段|search fields|
| condition |  object | 是| 无|查询条件|search condition|

page 参数说明：

| 名称  | 类型 |必填| 默认值 | 说明 | Description|
| ---  | ---  | --- |---  | --- | ---|
| start | int | 是|无|记录开始位置 |start record|
| limit | int | 是| 无|每页限制条数|page limit |
| sort | string | 否| 无|排序字段|the field for sort|

**注：sort 字段通过在字段前面增加 -，如 sort:"-field" 可以表示按照字段field降序。**

fields参数说明：

参数为设备的任意属性，如果不填写字段信息，系统会返回设备的所有字段。

**注：需要填写的参数取决于用户自己定义的属性字段。**

condition 参数说明：

condition 参数为设备的任意属性，如果不写代表搜索全部数据。

**注：需要填写的参数取决于用户自己定义的属性字段。**

- output:

``` json
{
    "result": true,
    "bk_error_code": 0,
    "bk_error_msg": null,
    "data": {
        "count": 2,
        "info": [
            {
                "device_id": 1,
                "device_model": "NX120",
                "device_name": "交换机20000",
                "bk_obj_name": "交换机",
                "bk_object_id": "bk_switch",
                "bk_vendor": "厂商1"
            },
            {
                "device_id": 2,
                "device_model": "NX220",
                "device_name": "路由20000",
                "bk_obj_name": "路由",
                "bk_object_id": "bk_router",
                "bk_vendor": "厂商2"
            }
        ]
    }
}
```

### 删除设备

- API: DELETE /api/{version}/netcollect/device/{device_id}/action/delete
- API 名称: delete_device
- 功能说明：
	- 中文：删除设备
	- English: delete device

- input body

    无

- input参数说明

| 字段|类型|必填|默认值|说明|Description|
|---|---|---|---|---|---|
|device_id|int|是|无|设备id|the device id|

- output:

```json
{
	"result": true,
	"bk_error_code": 0,
	"bk_error_msg": null,
	"data": "success"
}
```

**Comment by wusendong** [comment]
1.       网络发现独立一个功能页面

a)         首页就是网络设备发现界面

b)        按照子网区域区分, 每个子网区域只显示一条数据

                         i.              配置信息: 现在各个类型分别发生了多少条设备的变动(包含新增新增/更新/删除之和)

                       ii.              发现时间: 以最近的一次发现为主

                      iii.              详情确认: 打开新的操作界面2*

![image](https://user-images.githubusercontent.com/9442975/45791209-4528ad00-bcbb-11e8-9705-db599a9c12b3.png)


 

 

2.       确认页面

a)         罗列出此云区域的所有改动, 以实例为主体, 区别新增/变更/删除

b)        用户对于每个实例可以采取两种做法

                         i.              详情 见3*

                       ii.              忽略, 被标记为忽略, 用户可以通过取消忽略把状态加回来


![image](https://user-images.githubusercontent.com/9442975/45791220-5376c900-bcbb-11e8-8c31-0a9cb23444dd.png)



![image](https://user-images.githubusercontent.com/9442975/45791226-5ec9f480-bcbb-11e8-81f1-b54f24afd458.png)


 

 

3.       详情

a)         进入到实例详情中, 会显示当前实例变动的所有信息, 分为两类:

                         i.              属性

                       ii.              关系

b)        用户可以选择忽略属性和关系, 在最终变更的时候, 可以选择恢复回来

c)         用户可以选择是否要导入整个实例(左下角切换按钮)

                         i.              当选择不导入, 整个页面其他按钮都置灰, 不能够进行编辑

![image](https://user-images.githubusercontent.com/9442975/45791231-67222f80-bcbb-11e8-807d-cbde52c6ca34.png)


4.       查看已经完成

![image](https://user-images.githubusercontent.com/9442975/45791240-6c7f7a00-bcbb-11e8-8d21-84f8ec930359.png)


 

 

 

 

5.       配置界面:采集器管理

a)         第一个界面你是采集器管理, CC不负责采集器的下发卸载, 但是会显示当前有多少采集器在活跃

b)        用户可以主动触发某些采集器的执行, 触发过程中 , 采集器不可重复触发除非状态为已经完成上次的任务

![image](https://user-images.githubusercontent.com/9442975/45791247-730df180-bcbb-11e8-91fe-7d7e4fb0fff4.png)


6.       配置界面: 厂商管理

![image](https://user-images.githubusercontent.com/9442975/45791254-786b3c00-bcbb-11e8-93a3-02aa5fbde1c6.png)


7.       配置界面: 设备管理

![image](https://user-images.githubusercontent.com/9442975/45791259-7d2ff000-bcbb-11e8-9267-54a5b697ed0b.png)


 

8.       配置界面: 属性管理

![image](https://user-images.githubusercontent.com/9442975/45791261-815c0d80-bcbb-11e8-98c6-b103d149223d.png)
