### ISSUE TITLE
枚举字段升级

### ISSUE THREAD

**Issue by rentiansheng** [Tencent/bk-cmdb#108]
枚举字段升级
1.  枚举中的项目，加上ID，
2. 升级现有数据
3. 修改，新加枚举值使用枚举ID
4. 展示枚举需要通过ID查找对应的展示名字

**Comment by rentiansheng** [comment]
@joe511230 @ProtosL Pr @techfindd 

前提：
预定义字段：系统初始化就有的字段
预定义字段预定义枚举值：  枚举值是系统初始化就有的枚举类型字段的值

经过讨论确定枚举字段升级方案
1. 枚举字段新加id字段，作为数据的值。原来的name作为展示字段，id 只能有数字和字符组成
2. 枚举字段国际化，只有预定义字段枚举的预定枚举值支持多语言，用户加枚举字段和预定义枚举字段中用户自己家的枚举值不支持多语言
3.  语言定义枚举字段国际化，如果用户修改了预定义枚举字段预定义的枚举值，只是修改当前语言展示的值，其他语言不做修改。
4.  如果用户删除枚举字段中枚举值，以后数据不会变化。 
5. 使用被删除枚举字段中枚举值做为修改值，会提示报错。

**Comment by joe511230** [comment]
@rentiansheng 升级方案中的第四点表述不够清晰

**Comment by rentiansheng** [comment]
已修改

**Comment by wusendong** [comment]
今天讨论结果：
1. 预置字段改为不允许修改删除
2. 后端输出逻辑改为：优先用```"模型字段名前缀+枚举的KEY"```查语言包，没有则用数据库里的name字段，再没有则输出key
3. 前端直接用后端输出的name显示

**Comment by rentiansheng** [comment]
get

**Comment by techfindd** [comment]
OK

**Comment by joe511230** [comment]
GET
