### ISSUE TITLE
请问关于属性编辑里面的输入框标签内容不合法的匹配规则代码在哪里修改

### ISSUE THREAD

**Issue by guangzhimen** [Tencent/bk-cmdb#1090]
问题描述
===========
请问关于属性编辑里面的输入框标签内容不合法的匹配规则代码在哪里修改

重现方法
================
![image](https://user-images.githubusercontent.com/19423001/45806277-3958dd00-bcf3-11e8-8f95-6ab27fe246dc.png)
图上那样的输入框内容不合法了，我想修改匹配规则，不知道在哪个代码文件里面修改。

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): `<示例： v3.0.6-alpha 或者 git sha. 请不要使用 "最新版本" 或 "当前版本"等无法准确定位代码版本的语句描述>`
 - [ ] Redis     版本: `<示例： 3.2.11>`
 - [ ] MongoDB   版本: `<示例： 2.8.0>`
 - [ ] ZooKeeper 版本: `<示例： 3.4.11>`
 - [ ] 操作系统      : `<示例： Centos 5 (x64)>`
 - [ ] bk-cmdb 异常日志
![image](https://user-images.githubusercontent.com/19423001/45806371-745b1080-bcf3-11e8-8f47-9d9267ff6b78.png)

**Comment by lowenitt** [comment]
这里是应该改模型的配置

**Comment by guangzhimen** [comment]
我就是不知道该哪个模型，主要是不清楚代码逻辑。不知道在哪改

**Comment by guangzhimen** [comment]
> 这里是应该改模型的配置

就是不知道该哪个模型文件，不清楚代码逻辑，我在源码里找了半天没找到。

**Comment by guangzhimen** [comment]
@lowenitt @uriwang 就是不知道该哪个模型文件，不清楚代码逻辑，我在源码里找了半天没找到。

**Comment by breezelxp** [comment]
@guangzhimen 你好，可以在下图所示的位置修改：
![image](https://user-images.githubusercontent.com/26254420/49070729-5a93f780-f267-11e8-9848-3af3e6717fec.png)

**Comment by breezelxp** [comment]
@guangzhimen 你好，由于你长时间未回复，我们将关闭此issue，如果后边还有问题，你可以再次打开此issue。
