### ISSUE TITLE
执行 php index.php /cli/Init/initUserData  报错如下：

### ISSUE THREAD

**Issue by xingliguang** [Tencent/bk-cmdb#11]
begin truncate table
end truncate table
begin create classify host property 
INSERT INTO `cc_HostPropertyClassify` VALUES ('1', 'AssetID', '固资编号', 'basic', 'AssetID','12', '2016-02-24 11:26:57', '2016-02-24 18:00:57')
INSERT INTO `cc_HostPropertyClassify` VALUES ('7', 'DeviceClass', '设备类型', 'basic', 'DeviceClass','11', '2016-02-24 17:24:04', '2016-02-24 18:01:24')
INSERT INTO `cc_HostPropertyClassify` VALUES ('8', 'HostName', '主机名称', 'basic', 'HostName', '6','2016-02-24 17:26:00', '2016-02-24 18:01:48')
INSERT INTO `cc_HostPropertyClassify` VALUES ('9', 'Status', '运行状态', 'basic', 'Status', '7','2016-02-24 18:02:23', '2016-02-25 14:45:38')
INSERT INTO `cc_HostPropertyClassify` VALUES ('10', 'Operator', '维护人', 'basic', 'Operator','3', '2016-02-24 18:02:41', '2016-02-24 18:03:14')
INSERT INTO `cc_HostPropertyClassify` VALUES ('11', 'BakOperator', '备份维护人', 'basic', 'BakOperator','4', '2016-02-24 18:03:37', '2016-02-24 18:03:37')
INSERT INTO `cc_HostPropertyClassify` VALUES ('12', 'InnerIP', '内网IP', 'basic', 'InnerIP','1', '2016-02-24 18:04:01', '2016-02-24 18:04:01')
INSERT INTO `cc_HostPropertyClassify` VALUES ('13', 'OuterIP', '外网IP', 'basic', 'OuterIP','2', '2016-02-24 18:04:31', '2016-02-24 18:04:31')
INSERT INTO `cc_HostPropertyClassify` VALUES ('14', 'OSName', '操作系统', 'basic', 'OSName','7', '2016-02-24 18:04:53', '2016-02-24 18:04:53')
INSERT INTO `cc_HostPropertyClassify` VALUES ('15', 'Description', '备注', 'basic', 'Description','13', '2016-02-24 18:05:10', '2016-02-24 18:05:10')
INSERT INTO `cc_HostPropertyClassify` VALUES ('16', 'ZoneName', '可用区', 'basic', 'ZoneName','15', '2016-02-24 18:05:39', '2016-02-24 18:05:39')
INSERT INTO `cc_HostPropertyClassify` VALUES ('17', 'ZoneID', '可用区ID', 'basic', 'ZoneID', '14','2016-02-24 18:06:07', '2016-02-24 18:06:07')
INSERT INTO `cc_HostPropertyClassify` VALUES ('47', 'CreateTime', '入库时间', 'basic', 'CreateTime', '17','2016-02-24 19:11:25', '2016-02-24 19:11:25')
INSERT INTO `cc_HostPropertyClassify` VALUES ('49', 'Region', '机房城市', 'basic', 'Region','16', '2016-02-24 19:12:21', '2016-02-24 19:12:21')
INSERT INTO `cc_HostPropertyClassify` VALUES ('51', 'Cpu', 'Cpu', 'basic', 'Cpu', '8','2016-02-24 19:13:12', '2016-02-24 19:13:12')
INSERT INTO `cc_HostPropertyClassify` VALUES ('52', 'Mem', '内存', 'basic', 'Mem', '9','2016-02-24 19:13:37', '2016-02-24 19:13:37')
INSERT INTO `cc_HostPropertyClassify` VALUES ('60', 'HostID', '主机ID', 'basic', 'HostID','0', '2016-02-24 19:16:54', '2016-02-24 19:16:54')
INSERT INTO `cc_HostPropertyClassify` VALUES ('72', 'ModuleName', '模块名称', 'basic', 'ModuleName','5', '2016-02-24 18:02:41', '2016-02-24 18:02:41')
end create classify host property  
begin create set property 
INSERT INTO `cc_HostPropertyClassify` VALUES ('72', 'ModuleName', '模块名称', 'basic', 'ModuleName','5', '2016-02-24 18:02:41', '2016-02-24 18:02:41')
end create set property  
begin create admin user 
end create admin user 
begin create resource pool 

Database error: A Database Error Occurred

        Error Number: 1364
        Field 'LifeCycle' doesn't have a default value
        INSERT INTO `cc_ApplicationBase` (`ApplicationName`, `Creator`, `CreateTime`, `Default`, `Display`, `Level`, `Maintainers`, `Owner`, `Type`, `Source`, `CompanyID`) VALUES ('资源池', '公司名称', '2016-12-22 15:31:13', 1, 1, 2, '公司名称', '公司名称', 0, 0, 0)
        Filename: models/ApplicationBaseModel.php
        Line Number: 88
然后到数据库为LifeCycle设置默认值：
alter table cc_ApplicationBase modify column `LifeCycle` varchar(16) NOT NULL DEFAULT '100';
再次执行php index.php /cli/Init/initUserData ，继续报错如下：
Field 'ProductPm' doesn't have a default value
重新修改，然后继续执行，继续报错…………
后来终于将没有报错信息了，执行php index.php /cli/Init/initUserData 提示：
skip init data
环境描述：
Centos 6.6 x86_64 
软件都是编译安装，按照说明的参数来编译的，都编译OK的！
nginx 1.10.2  
php  5.6.29
mysql 5.6.19 二进制安装 
测试php和mysql的连通也是测试OK的!麻烦有空请解答关于描述的问题，万分感谢!

**Comment by Fchrisqing** [comment]
这个情况的出现主要是mysql不同版本的兼容问题，需要刷新一下初始化脚本

**Comment by xingliguang** [comment]
@Fchrisqing  刷新初始化脚本是什么意思？还是需要将bk-cmdb.sql重新从源码中clone下来？

**Comment by xingliguang** [comment]
好吧，开发者修改了初始化脚本，重新导入bk-cmdb.sql 就OK了！
将几个字段添加了default ''如下：
 `LifeCycle` varchar(16) NOT NULL default '',              #添加了default ''
  `ProductPm` varchar(128) NOT NULL default '',       #添加了default ''
  `Source` varchar(16) NOT NULL default '',                #添加了default ''
  `BusinessDeptName` varchar(64) NOT NULL default '', #添加了default ''   --这一个开发者忘记修改了！

**Comment by lowenitt** [comment]
更新下初始化sql,脚本，大家有兼容性方面的solution或者fix 也可以发起pull request
