### ISSUE TITLE
执行 bash ./init_db.sh 时报错

### ISSUE THREAD

**Issue by weizouzhou** [Tencent/bk-cmdb#113]
问题描述
===========
安装部署时，./start.sh看到12个进程已经成功启动，但执行 bash ./init_db.sh 初始化数据时报错：
{"result":false,"code":1199022,"message":"依赖服务[[proc]]未启动","data":null}
zookeeper、redis和MongoDB都已经启动，不知还有哪个服务没启？

重现方法
================
执行 bash ./init_db.sh 初始化数据

关键信息
=========
 - [x] bk-cmdb   版本v3.0.6
 - [ ] Redis     版本:  3.2.11
 - [ ] MongoDB   版本: 2.8.0
 - [ ] ZooKeeper 版本:  3.4.11
 - [ ] 操作系统      : centos 7.4
 - [ ] bk-cmdb 异常日志

**Comment by PhoenSXar** [comment]
@weizouzhou 你好，能问问你这边是出现了啥问题是怎么解决的吗。
