### ISSUE TITLE
cmdb_adminserver进程无法启动

### ISSUE THREAD

**Issue by arleyGuo** [Tencent/bk-cmdb#1146]
问题描述
===========
cmdb_adminserver进程无法启动

日志信息：
[root@bogon logs]# cat cmdb_adminserver.ERROR
Log file created at: 2018/09/28 18:18:36
Running on machine: bogon
Binary: Built with gc go1.10.1 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0928 18:18:36.385819    4457 error.go:89] LoadErrorResourceFromDir error: invalid character '\x00' looking for beginning of value, file: conf/errors/common/default/._apiserver_v2.json
E0928 18:18:36.386176    4457 conf.go:75] fail to write error resource to center, err:load error resource error: invalid character '\x00' looking for beginning of value
E0928 18:18:36.386273    4457 conf.go:87] fail to write languate packages to center, err:load language resource error: unmarshal language file conf/language/default/._api.json, error: invalid character '\x00' looking for beginning of value
E0928 18:18:36.386609    4457 error.go:89] LoadErrorResourceFromDir error: invalid character '\x00' looking for beginning of value, file: conf/errors/common/default/._apiserver_v2.json
E0928 18:18:36.386616    4457 ccapi.go:97] failed to create errors object, error info is  invalid character '\x00' looking for beginning of value
E0928 18:18:36.398563    4457 ccapi.go:136] exit! err:invalid character '\x00' looking for beginning of value

**Comment by uriwang** [comment]
@arleyGuo 从日志上看，json 文件里有非法字符，json 不合法。请把有问题的文件内容贴出来。

**Comment by breezelxp** [comment]
@arleyGuo 你好，由于你长时间没有再更新状态信息，现将该issue关闭，如果你还有关于此issue的任何疑问，可以重新开启该issue.
