### ISSUE TITLE
关联类型定义和管理

### ISSUE THREAD

**Issue by uriwang** [Tencent/bk-cmdb#1149]
-  关联类型用户自行定义，系统提供管理功能
-  需要封装配套的API

**Comment by breezelxp** [comment]
PR https://github.com/Tencent/bk-cmdb/pull/1214

**Comment by breezelxp** [comment]
PR https://github.com/Tencent/bk-cmdb/pull/1230

**Comment by breezelxp** [comment]
PR https://github.com/Tencent/bk-cmdb/pull/1258
