### ISSUE TITLE
请求200 ，浏览器显示空白页

### ISSUE THREAD

**Issue by xingliguang** [Tencent/bk-cmdb#12]
这个问题已经有朋友提出来了，不过好像没有解决，我这里在描述一下：
首先解析好了  xxxx  cmdb.wkzf.com  
然后本机使用curl请求是OK的，如下：
#curl -i  http://cmdb.wkzf.com
HTTP/1.1 200 OK
Server: nginx/1.10.2
Date: Thu, 22 Dec 2016 10:33:35 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.6.29
Set-Cookie: ci_session=83c3b679dd28eb3d4a9a4daf80503d7ca8fe3508; expires=Thu, 22-Dec-2016 12:33:35 GMT; Max-Age=7200; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
然后使用google浏览器访问（物理机也已经修改了hosts解析）
http://cmdb.wkzf.com    #然后页面就是空白的，
nginx日志和php日志也没看到有报错日志出现。
所以想问一下开发者或者其他朋友这是什么问题导致的？是我配置步骤不对，还是github上帮助文档没有描述清楚
@zhujianfeng @lowenitt 请大神指点，非常感谢！

**Comment by huangmeng4520** [comment]
你看下数据里面有数据没有，cc_user表
![image](https://cloud.githubusercontent.com/assets/8178576/21424403/a86d2d16-c87d-11e6-9fe3-58b818f65d1f.png)

**Comment by xingliguang** [comment]
是有数据的。如下：
mysql> select * from  cc_user;
+----+----------+--------------------------------------------------------------+-----------------+--------------+-------------+-------+------------------+-------+--------+-------------+
| id | UserName | Password                                                     | ChName          | Company      | Tel         | QQ    | Email            | Role  | Status | TokenExpire |
+----+----------+--------------------------------------------------------------+-----------------+--------------+-------------+-------+------------------+-------+--------+-------------+
|  1 | admin    | $2y$10$dBv5y.ArJAMkzJQ4f4X7Pe40thyfJujNYIcXhPpPrwn6rPRJzMNDy | 公司管理员      | 公司名称     | 13111112222 | 12345 | admin@sample.com | admin | ok     |           0 |
+----+----------+--------------------------------------------------------------+-----------------+--------------+-------------+-------+------------------+-------+--------+-------------+
1 row in set (0.00 sec)

**Comment by raindylong** [comment]
初始化数据那一步继续有如下返回才是正常的，供参考：
$ /usr/bin/php index.php /cli/Init/initUserData
begin truncate table
end truncate table
begin create classify host property 
INSERT INTO `cc_HostPropertyClassify` VALUES ('1', 'AssetID', '固资编号', 'basic', 'AssetID','12', '2016-02-24 11:26:57', '2016-02-24 18:00:57')
INSERT INTO `cc_HostPropertyClassify` VALUES ('7', 'DeviceClass', '设备类型', 'basic', 'DeviceClass','11', '2016-02-24 17:24:04', '2016-02-24 18:01:24')
INSERT INTO `cc_HostPropertyClassify` VALUES ('8', 'HostName', '主机名称', 'basic', 'HostName', '6','2016-02-24 17:26:00', '2016-02-24 18:01:48')
INSERT INTO `cc_HostPropertyClassify` VALUES ('9', 'Status', '运行状态', 'basic', 'Status', '7','2016-02-24 18:02:23', '2016-02-25 14:45:38')
INSERT INTO `cc_HostPropertyClassify` VALUES ('10', 'Operator', '维护人', 'basic', 'Operator','3', '2016-02-24 18:02:41', '2016-02-24 18:03:14')
INSERT INTO `cc_HostPropertyClassify` VALUES ('11', 'BakOperator', '备份维护人', 'basic', 'BakOperator','4', '2016-02-24 18:03:37', '2016-02-24 18:03:37')
INSERT INTO `cc_HostPropertyClassify` VALUES ('12', 'InnerIP', '内网IP', 'basic', 'InnerIP','1', '2016-02-24 18:04:01', '2016-02-24 18:04:01')
INSERT INTO `cc_HostPropertyClassify` VALUES ('13', 'OuterIP', '外网IP', 'basic', 'OuterIP','2', '2016-02-24 18:04:31', '2016-02-24 18:04:31')
INSERT INTO `cc_HostPropertyClassify` VALUES ('14', 'OSName', '操作系统', 'basic', 'OSName','7', '2016-02-24 18:04:53', '2016-02-24 18:04:53')
INSERT INTO `cc_HostPropertyClassify` VALUES ('15', 'Description', '备注', 'basic', 'Description','13', '2016-02-24 18:05:10', '2016-02-24 18:05:10')
INSERT INTO `cc_HostPropertyClassify` VALUES ('16', 'ZoneName', '可用区', 'basic', 'ZoneName','15', '2016-02-24 18:05:39', '2016-02-24 18:05:39')
INSERT INTO `cc_HostPropertyClassify` VALUES ('17', 'ZoneID', '可用区ID', 'basic', 'ZoneID', '14','2016-02-24 18:06:07', '2016-02-24 18:06:07')
INSERT INTO `cc_HostPropertyClassify` VALUES ('47', 'CreateTime', '入库时间', 'basic', 'CreateTime', '17','2016-02-24 19:11:25', '2016-02-24 19:11:25')
INSERT INTO `cc_HostPropertyClassify` VALUES ('49', 'Region', '机房城市', 'basic', 'Region','16', '2016-02-24 19:12:21', '2016-02-24 19:12:21')
INSERT INTO `cc_HostPropertyClassify` VALUES ('51', 'Cpu', 'Cpu', 'basic', 'Cpu', '8','2016-02-24 19:13:12', '2016-02-24 19:13:12')
INSERT INTO `cc_HostPropertyClassify` VALUES ('52', 'Mem', '内存', 'basic', 'Mem', '9','2016-02-24 19:13:37', '2016-02-24 19:13:37')
INSERT INTO `cc_HostPropertyClassify` VALUES ('60', 'HostID', '主机ID', 'basic', 'HostID','0', '2016-02-24 19:16:54', '2016-02-24 19:16:54')
INSERT INTO `cc_HostPropertyClassify` VALUES ('72', 'ModuleName', '模块名称', 'basic', 'ModuleName','5', '2016-02-24 18:02:41', '2016-02-24 18:02:41')
end create classify host property  
begin create set property 
INSERT INTO `cc_HostPropertyClassify` VALUES ('72', 'ModuleName', '模块名称', 'basic', 'ModuleName','5', '2016-02-24 18:02:41', '2016-02-24 18:02:41')
end create set property  
begin create admin user 
end create admin user 
begin create resource pool 
end create resource pool 
begin create example app 
end create example app 
begin create example set 
end create example set 
begin create example module 
end create example module

**Comment by xingliguang** [comment]
@raindylong 初始化数据输出信息和你贴出来的是一样的。所以很不解啊，为啥都正常，依然是空白页……

**Comment by lowenitt** [comment]
把index.php中的报错打开吧，看下是不是session配置的的路径不对或者没有写权限
config.php中

**Comment by jiajiren** [comment]
一样的问题。数据库中也有数据。返回也是200OK。但是就是空白

**Comment by jiajiren** [comment]
我的解决了。是权限问题。 我把目录的权限改了就有页面了。

**Comment by xingliguang** [comment]
@lowenitt @jiajiren 是的，我傻逼了，/data/session目录没有配置写权限！但是问题来了，/data/session目录我修改为了777权限，然后访问我自己的域名（hosts解析过的）http://cmdb.wkzf.com 结果浏览器url跳转成了http://open.bk.com/account/login?cburl=    然后依然是空白页面。在/data/session目录看到3个ci_session*文件……

**Comment by lowenitt** [comment]
![image](https://cloud.githubusercontent.com/assets/14356794/21445643/912b0906-c8f6-11e6-944f-9e4b5c290374.png)
把index.php的报错打开吧

**Comment by lowenitt** [comment]
选项都设置为 1 ，保证能看到错误

**Comment by jiajiren** [comment]
@xingliguang 根据配置的环境类型找到对应的常量文件,例如前面环境类型配置的为 development 则在/config/development/constants.php中定义
  define('BASE_URL', 'http://cmdb.bk.com');   //访问主域名,务必带上http://

上边的BASE_URL你改了么。

**Comment by xingliguang** [comment]
@lowenitt @jiajiren 我想弱弱的问下---- 根目录中index.php中配置环境类型为 (development/testing/production)之一。  这个如何配置？

**Comment by raindylong** [comment]
@xingliguang 仔细看readme啊。 :)
index.php中不是有这么一行么：
`define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'development');`

**Comment by xingliguang** [comment]
@jiajiren @raindylong @lowenitt 谢谢，搞定了！终于出现页面了。还是太粗心了，惭愧！

**Comment by lowenitt** [comment]
好的

**Comment by lowenitt** [comment]
看下日志中的报错是什么吧

**Comment by xingliguang** [comment]
@lowenitt 看了nginx 和 php的日志，没有看到error之类的错误日志。
就是访问的时候页面有这样的错误：
A PHP Error was encountered

Severity: Warning

Message: mysql_num_rows() expects parameter 1 to be resource, null given

Filename: mysql/mysql_result.php

Line Number: 63

Backtrace:

File: /data/htdocs/cc_openSource/application/models/UserModel.php
Line: 20
Function: get

File: /data/htdocs/cc_openSource/application/libraries/Login.php
Line: 115
Function: getUserByUsername

File: /data/htdocs/cc_openSource/application/libraries/Login.php
Line: 86
Function: isValidUserPassword

File: /data/htdocs/cc_openSource/application/libraries/Login.php
Line: 186
Function: isCcTokenValid

File: /data/htdocs/cc_openSource/application/controllers/Account.php
Line: 91
Function: loginUser

File: /data/htdocs/cc_openSource/index.php
Line: 293
Function: require_once

**Comment by xingliguang** [comment]
@lowenitt  问题解决了。db.php配置文件中是127.0.0.1:3306，但是本机127.0.0.1无法连接数据库。数据库中只配置了
‘localhost’@‘root’账号，所以用localhost连接数据库是可以的。后来添加了‘127.0.0.1’@‘root’，重新导入数据，重新初始化之后好了！但是让我不解的是本机ping localhost 是127.0.0.1响应的……
登录之后，其他功能都没问题，我点击左侧的“主机管理”，页面出现错误，如下：
A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: controllers/Host.php

Line Number: 117

Backtrace:

File: /data/htdocs/cc_openSource/application/controllers/Host.php
Line: 117
Function: _error_handler

File: /data/htdocs/cc_openSource/application/controllers/Host.php
Line: 52
Function: getHostFieldSelect

File: /data/htdocs/cc_openSource/index.php
Line: 293
Function: require_once
出错界面如下：
![image](https://cloud.githubusercontent.com/assets/24713062/21449783/b594ba82-c92b-11e6-9d3d-462f76f002a8.png)
请大神指点。

**Comment by rockzhouj** [comment]
各位大神圣诞快乐！今天在配置的时候出现的以下问题：
1、CentOS6.8的系统 使用rpm安装的mysq5.6.35版本。在导入sql语句的时候出现 ERROR 1101 (42000) at line 348: BLOB/TEXT column 'DefaultColumn' can't have a default value 错误 网上找了一些方法无法解决 最后只能将DefaultColumn的default去掉 才能导入成功 不知对后续使用是否有影响。
2、在执行/opt/php/bin/php index.php /cli/Init/initUserData 的时候没有任何输出 也查看过cc_user表 为空
![image](https://cloud.githubusercontent.com/assets/24588144/21470114/496db468-cab5-11e6-8bf2-c1bf411f4fa3.png)
访问页面的时候还出现过500报错 目前是空白页
日志也看不到相关报错信息。

**Comment by xingliguang** [comment]
@rockzhouj  第一个问题，关于这个  can't have a default value 错误，需要重新拉最新的代码，然后重新导入bk-cmdb.sql ,开发者已经修改了。
第二个问题，你到application/logs目录看看日志，说不定是数据库权限的问题等等。

**Comment by rockzhouj** [comment]
@xingliguang 感谢您的回复 我查看了一下logs 日志没有报错记录 还有就是我本地的db.php是这样配置的
![image](https://cloud.githubusercontent.com/assets/24588144/21474769/80e9bf78-cb5e-11e6-8673-92a37c30d330.png)
还麻烦您看一下是否有问题 谢谢了

**Comment by xingliguang** [comment]
@rockzhouj 仔细看源代码里面的README说明。还有你是development环境的话，index.php中要修改这一段：修改为如下，
define('ENVIRONMENT', isset($_SERVER['CI_ENV']) ? $_SERVER['CI_ENV'] : 'development');
如果你已经修改了，可以将index.php改为debug模式，看看日志输出：
switch (ENVIRONMENT)
{
        case 'development':
                error_reporting(-1);
                ini_set('display_errors', 0);    ##0修改为1，就可以看debug日志了。
        break;

**Comment by rockzhouj** [comment]
@xingliguang 你好打扰了 请问您的那个主机管理报错的页面解决了吗？ 我也遇到相同的问题了 还望赐教 谢谢了。

**Comment by xingliguang** [comment]
没有解决。没有错误日志，也不懂php开发，所以无法排查

**Comment by lowenitt** [comment]
@xingliguang     看下日志目录有没读写权限吧

**Comment by jiajiren** [comment]
@xiangliguang 主机管理页面报错你可以看看报的那个文件的权限。我之前也遇到这个问题。是有一些文件的权限不对。改过就好了

**Comment by xingliguang** [comment]
@jiajiren 点击“主机管理”页面，除了上图截图的php报错之外，今天再次点击，日志里面也有报错如下：
DEBUG - 2016-12-27 10:08:10 --> Global POST, GET and COOKIE data sanitized
INFO - 2016-12-27 10:08:10 --> Input Class Initialized
INFO - 2016-12-27 10:08:10 --> Language Class Initialized
INFO - 2016-12-27 10:08:10 --> Loader Class Initialized
DEBUG - 2016-12-27 10:08:10 --> Config file loaded: /data/htdocs/cc_openSource/application/config/errorcode.php
INFO - 2016-12-27 10:08:10 --> Session: Class initialized using 'files' driver.
DEBUG - 2016-12-27 10:08:10 --> Session class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 10:08:10 --> Session class already loaded. Second attempt ignored.
INFO - 2016-12-27 10:08:10 --> Controller Class Initialized
INFO - 2016-12-27 10:08:10 --> Parser Class Initialized
INFO - 2016-12-27 10:08:10 --> Language file loaded: language/english/zh_cn_lang.php
DEBUG - 2016-12-27 10:08:10 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 10:08:10 --> Encryption: Auto-configured driver 'openssl'.
INFO - 2016-12-27 10:08:10 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2016-12-27 10:08:10 --> Encryption Class Initialized
INFO - 2016-12-27 10:08:10 --> Database Driver Class Initialized
INFO - 2016-12-27 10:08:10 --> Final output sent to browser
DEBUG - 2016-12-27 10:08:10 --> Total execution time: 0.1209
INFO - 2016-12-27 10:08:11 --> Config Class Initialized
INFO - 2016-12-27 10:08:11 --> Hooks Class Initialized
DEBUG - 2016-12-27 10:08:11 --> UTF-8 Support Enabled
INFO - 2016-12-27 10:08:11 --> Utf8 Class Initialized
INFO - 2016-12-27 10:08:11 --> URI Class Initialized
INFO - 2016-12-27 10:08:11 --> Router Class Initialized
INFO - 2016-12-27 10:08:11 --> Output Class Initialized
INFO - 2016-12-27 10:08:11 --> Security Class Initialized
DEBUG - 2016-12-27 10:08:11 --> Global POST, GET and COOKIE data sanitized
INFO - 2016-12-27 10:08:11 --> Input Class Initialized
INFO - 2016-12-27 10:08:11 --> Language Class Initialized
INFO - 2016-12-27 10:08:11 --> Loader Class Initialized
DEBUG - 2016-12-27 10:08:11 --> Config file loaded: /data/htdocs/cc_openSource/application/config/errorcode.php
INFO - 2016-12-27 10:08:11 --> Session: Class initialized using 'files' driver.
DEBUG - 2016-12-27 10:08:11 --> Session class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 10:08:11 --> Session class already loaded. Second attempt ignored.
INFO - 2016-12-27 10:08:11 --> Controller Class Initialized
INFO - 2016-12-27 10:08:11 --> Parser Class Initialized
INFO - 2016-12-27 10:08:11 --> Language file loaded: language/english/zh_cn_lang.php
DEBUG - 2016-12-27 10:08:11 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 10:08:11 --> Encryption: Auto-configured driver 'openssl'.
INFO - 2016-12-27 10:08:11 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2016-12-27 10:08:11 --> Encryption Class Initialized
INFO - 2016-12-27 10:08:11 --> Database Driver Class Initialized
INFO - 2016-12-27 10:08:11 --> Final output sent to browser
DEBUG - 2016-12-27 10:08:11 --> Total execution time: 0.1701
INFO - 2016-12-27 10:08:11 --> Config Class Initialized
INFO - 2016-12-27 10:08:11 --> Hooks Class Initialized
DEBUG - 2016-12-27 10:08:11 --> UTF-8 Support Enabled
INFO - 2016-12-27 10:08:11 --> Utf8 Class Initialized
INFO - 2016-12-27 10:08:11 --> URI Class Initialized
INFO - 2016-12-27 10:08:11 --> Router Class Initialized
INFO - 2016-12-27 10:08:11 --> Output Class Initialized
INFO - 2016-12-27 10:08:11 --> Security Class Initialized
DEBUG - 2016-12-27 10:08:11 --> Global POST, GET and COOKIE data sanitized
INFO - 2016-12-27 10:08:11 --> Input Class Initialized
INFO - 2016-12-27 10:08:11 --> Language Class Initialized
INFO - 2016-12-27 10:08:11 --> Loader Class Initialized
DEBUG - 2016-12-27 10:08:11 --> Config file loaded: /data/htdocs/cc_openSource/application/config/errorcode.php
INFO - 2016-12-27 10:08:11 --> Session: Class initialized using 'files' driver.
DEBUG - 2016-12-27 10:08:11 --> Session class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 10:08:11 --> Session class already loaded. Second attempt ignored.
INFO - 2016-12-27 10:08:11 --> Controller Class Initialized
INFO - 2016-12-27 10:08:11 --> Parser Class Initialized
INFO - 2016-12-27 10:08:11 --> Language file loaded: language/english/zh_cn_lang.php
DEBUG - 2016-12-27 10:08:11 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 10:08:11 --> Encryption: Auto-configured driver 'openssl'.
INFO - 2016-12-27 10:08:11 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2016-12-27 10:08:11 --> Encryption Class Initialized
INFO - 2016-12-27 10:08:11 --> Database Driver Class Initialized
ERROR - 2016-12-27 10:08:11 --> Query error: Field 'DefaultCon' doesn't have a default value - Invalid query: INSERT INTO `cc_UserCustom` (`DefaultColumn`, `UserName`) VALUES ('[\"InnerIP\",\"OuterIP\",\"SetName\",\"ModuleName\",\"HostName\"]', 'admin')
ERROR - 2016-12-27 10:08:11 --> [上海好居科技]  [admin]  [10.0.90.8]  添加用户定制, 失败!mysql_errno: 1364, mysql_error: Field 'DefaultCon' doesn't have a default value
INFO - 2016-12-27 10:08:11 --> Final output sent to browser
DEBUG - 2016-12-27 10:08:11 --> Total execution time: 0.1128

**Comment by jiajiren** [comment]
@xingliguang 我发生这个问题就看了看index.php   config.php db.php的权限发现是不对的  改过之后就好了。不知道跟你的是不是一样

**Comment by xingliguang** [comment]
@jiajiren 我将application权限递归修改为777，资源池导入主机的问题解决了，点击左侧的“主机管理”也不会报php相关的错误了。但是会在日志中看到如下错误日志：
DEBUG - 2016-12-27 10:54:32 --> Config file loaded: /data/htdocs/cc_openSource/application/config/errorcode.php
INFO - 2016-12-27 10:54:32 --> Session: Class initialized using 'files' driver.
DEBUG - 2016-12-27 10:54:32 --> Session class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 10:54:32 --> Session class already loaded. Second attempt ignored.
INFO - 2016-12-27 10:54:32 --> Controller Class Initialized
INFO - 2016-12-27 10:54:32 --> Parser Class Initialized
INFO - 2016-12-27 10:54:32 --> Language file loaded: language/english/zh_cn_lang.php
DEBUG - 2016-12-27 10:54:32 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 10:54:32 --> Encryption: Auto-configured driver 'openssl'.
INFO - 2016-12-27 10:54:32 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2016-12-27 10:54:32 --> Encryption Class Initialized
INFO - 2016-12-27 10:54:32 --> Database Driver Class Initialized
ERROR - 2016-12-27 10:54:32 --> Query error: Field 'DefaultCon' doesn't have a default value - Invalid query: INSERT INTO `cc_UserCustom` (`DefaultColumn`, `UserName`) VALUES ('[\"InnerIP\",\"OuterIP\",\"SetName\",\"ModuleName\",\"HostName\"]', 'admin')
ERROR - 2016-12-27 10:54:32 --> [上海]  [admin]  [10.0.90.8]  添加用户定制, 失败!mysql_errno: 1364, mysql_error: Field 'DefaultCon' doesn't have a default value
INFO - 2016-12-27 10:54:32 --> Final output sent to browser
DEBUG - 2016-12-27 10:54:32 --> Total execution time: 0.1130
不知道为何……

**Comment by jiajiren** [comment]
@xingliguang 我看报错是报的数据库里的某一列没有默认值啊。初始化的时候的问题吧应该是。你自己找一找原因吧。

**Comment by xingliguang** [comment]
@jiajiren 初始化的时候没有报错啥的。好的，谢谢，我再找找问题。

**Comment by rockzhouj** [comment]
@jiajiren@xingliguang@lowenitt 楼上大神们 目前配置改平台 卡在了 主机配置页面的php报错上报错的页面内容与上面的一模一样 您们之前的讨论我检查了权限 确保没问题 还有目前站点文件的 属主属组是nginx  日志内容为
![image](https://cloud.githubusercontent.com/assets/24588144/21492988/dc96eedc-cc43-11e6-8202-be5ec17a37bc.png) 我想问一下 除了配置说明中 文字列出的php要安装的扩展外 你们还装了什么扩展

**Comment by xingliguang** [comment]
@ rockzhouj  日志内容报错解决方法：
DROP TABLE IF EXISTS `cc_UserPermissions`;
重新修改建表语句，改为如下：
CREATE TABLE `cc_UserCustom` (
  `UserName` varchar(16) NOT NULL default '',
  `DefaultApplication` int(11) NOT NULL default '0',
  `DefaultColumn` varchar(512) NOT NULL default '',  
  `DefaultPageSize` int(2) NOT NULL default '20',
  `DefaultField` varchar(512) NOT NULL default '' COMMENT '主机查询字段',
  `DefaultCon` varchar(512) NOT NULL default '' COMMENT '主机查询条件',
  `Description` varchar(256) NOT NULL default '',
  `SetGseCol` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY  (`UserName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='用户定制表';
然后再试试

**Comment by rockzhouj** [comment]
@xingliguang 非常感谢 报错是解决了 但是 主机配置的 php错误页面 还是那样 不过 我找到了错误日志
ERROR - 2016-12-27 17:15:26 --> Severity: Warning --> Invalid argument supplied for foreach() /data/www/cmdb/application/controllers/Host.php 117    刚刚找了个php语言大神改了下代码 目测问题是解决了 分享给大家 
![image](https://cloud.githubusercontent.com/assets/24588144/21496562/5783d5a4-cc5a-11e6-828f-3920d6ca45d8.png)

**Comment by rockzhouj** [comment]
@xingliguang你好 我想问一下这个蓝鲸是最新的 2.0版本吗？

**Comment by lowenitt** [comment]
这个是蓝鲸的开源版本，2.0的社区版可以在蓝鲸官网下载获取

**Comment by haodongz** [comment]
![error](https://cloud.githubusercontent.com/assets/24855321/25162452/5634fcac-24f5-11e7-98fb-875afd2992d0.png)
我这个执行错误了

**Comment by haodongz** [comment]
![default](https://cloud.githubusercontent.com/assets/24855321/25166520/600396a8-250e-11e7-9117-f338e5b07a08.png)
mysql表里面也没用户数据导过了。。。

**Comment by luluming** [comment]
2017/08/03 05:25:52 [error] 2952#0: *70 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/var/bk-cmdb-master/application/config/constants.php): failed to open stream: Permission denied in /var/bk-cmdb-master/system/core/CodeIgniter.php on line 71
PHP message: PHP Fatal error:  require_once(): Failed opening required '/var/bk-cmdb-master/application/config/constants.php' (include_path='.:/usr/local/php/lib/php') in /var/bk-cmdb-master/system/core/CodeIgniter.php on line 71" while reading response header from upstream, client: 192.168.112.1, server: localhost, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.112.225:8081"
2017/08/03 05:25:52 [error] 2952#0: *70 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/var/bk-cmdb-master/application/config/constants.php): failed to open stream: Permission denied in /var/bk-cmdb-master/system/core/CodeIgniter.php on line 71
PHP message: PHP Fatal error:  require_once(): Failed opening required '/var/bk-cmdb-master/application/config/constants.php' (include_path='.:/usr/local/php/lib/php') in /var/bk-cmdb-master/system/core/CodeIgniter.php on line 71" while reading response header from upstream, client: 192.168.112.1, server: localhost, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.112.225:8081"
2017/08/03 05:25:52 [error] 2952#0: *70 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/var/bk-cmdb-master/application/config/constants.php): failed to open stream: Permission denied in /var/bk-cmdb-master/system/core/CodeIgniter.php on line 71
PHP message: PHP Fatal error:  require_once(): Failed opening required '/var/bk-cmdb-master/application/config/constants.php' (include_path='.:/usr/local/php/lib/php') in /var/bk-cmdb-master/system/core/CodeIgniter.php on line 71" while reading response header from upstream, client: 192.168.112.1, server: localhost, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.112.225:8081"

**Comment by luluming** [comment]
我搭建蓝鲸日志总是提示不能打开，想请教一下各位，怎么来解决啊？问题出现在哪里啊？

**Comment by luluming** [comment]
- 根据配置的环境类型找到对应的常量文件,例如前面环境类型配置的为 development 则在/config/development/constants.php中定义
 ```sh
    define('BASE_URL', 'http://cmdb.bk.com');   //访问主域名,务必带上http://
    define('COMPANY_NAME', '公司名称');        //当前公司名
    define('COOKIE_DOMAIN', '.bk.com');         //cookie访问域

**Comment by luluming** [comment]
这个这个 域名填写什么内容啊？

**Comment by tangyawen** [comment]
http://cmdb.jj-inn.com 结果浏览器url跳转成了http://cmdb.jj-inn.com/account/login?cburl= 然后依然是空白页面。在/data/session目录看到3个ci_session*文件…… 请问如何解决此问题

**Comment by tangyawen** [comment]
@lowenitthttp://cmdb.jj-inn.com 结果浏览器url跳转成了http://cmdb.jj-inn.com/account/login?cburl= 然后依然是404页面。在/data/session目录看到3个ci_session*文件…… 请问如何解决此问题

**Comment by tangyawen** [comment]
@lowenitt http://cmdb.jj-inn.com 结果浏览器url跳转成了http://cmdb.jj-inn.com/account/login?cburl= 然后依然是空白页面。在/data/session目录看到3个ci_session*文件…… 请问如何解决此问题
