### ISSUE TITLE
单独安装使用配置平台，通过api查询主机(post http://x.x.x.x:8083/api/v3/hosts/search)，返回错误结果

### ISSUE THREAD

**Issue by dreamflies** [Tencent/bk-cmdb#1213]
问题描述
===========
单独安装使用配置平台，通过api查询主机(post http://x.x.x.x:8083/api/v3/hosts/search)，返回错误结果如下：
{"result":false,"bk_error_code":1199000,"bk_error_msg":"反序列化JSON数据失败","data":null}

 bk-cmdb版本: v3.2.0

**Comment by lowenitt** [comment]
应该是参数的组装问题，不清楚参数组装，可以通过浏览器获取cmdb查询的参数，与api的是一致的

**Comment by dreamflies** [comment]
cmdb查询参数有无导致。

**Comment by airplayx** [comment]
1.设置request文件头 Content-Type:application/json;charset=UTF-8
2.发送的参数组成json格式依据实际情况urlencode编码
3.使用原始二进制数据创建post等请求发送到接口

**Comment by zhucaipeng** [comment]
![image](https://user-images.githubusercontent.com/18751306/226531642-4c31c21b-6acf-4e12-887b-86752a15871f.png)
同样的问题，究竟是哪里的问题呢？
