### ISSUE TITLE
安装后web 报错 HTTP请求失败   和 oops, there is no server can be used  。无法正常使用

### ISSUE THREAD

**Issue by linliaoy** [Tencent/bk-cmdb#1272]
问题描述
===========
安装过程正常，登陆后无法正常显示数据

重现方法
================
<列出如何重现的方法或操作步骤>

**重要提醒**: 请优先尝试最新发布的版本 (发布清单： https://github.com/Tencent/bk-cmdb/releases), 如果问题不能在最新发布的版本里重现，说明此问题已经被修复。

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): v3.1.0-rc.1
 - [ ] Redis     版本:  3.2.11
 - [ ] MongoDB   版本: 2.8.0
 - [ ] ZooKeeper 版本: 3 .4.12
 - [ ] 操作系统      : ubuntu 14.04   4.4.0-123-generic
 - [ ] bk-cmdb 异常日志
web显示 ：
1、HTTP请求失败
2、oops, there is no server can be used
cmdb_adminserver :  
E1025 16:33:49.002641    6540 conf.go:177] fail to open file(/opt/lanjing_cmdb/cmdb_adminserver/configures//txc.conf), err(open /opt/lanjing_cmdb/cmdb_adminserver/configures//txc.conf: no such file or directory)
E1025 16:34:17.801656    6540 addPresetObjects.go:129] add data for  cc_PropertyGroup table 

cmdb_webserver : 
E1025 17:32:16.906309    6811 privilege.go:105] get role privilege app error: <nil>
E1025 17:36:59.155620    6811 privilege.go:105] get role privilege app error: <nil>

**Comment by breezelxp** [comment]
@linliaoy “oops, there is no server can be used”这个错误是由于某个进程服务没有正常启动导致的。请检查一下所有的进程是否已经正常启动。
关于admin server的问题，请@wusengdong看一下。

**Comment by wusendong** [comment]
请问 git commit id 号是哪个？我好方便去排查一下问题

**Comment by wusendong** [comment]
(open /opt/lanjing_cmdb/cmdb_adminserver/configures//txc.conf: no such file or directory)

**Comment by linliaoy** [comment]
@wusendong
 777b8f10f56f41db21bb44842668e9401b4ecdc8

**Comment by linliaoy** [comment]
@breezelxp

**Comment by linliaoy** [comment]
@breezelxp      cmdb_auditcontroller 这个项目没有起来  
错误如下：
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1025 16:33:48.803379    6571 cc.go:221] sync process config failed, err: zk: node does not exist
E1025 16:33:48.809305    6571 cc.go:254] sync process config failed, err: zk: node does not exist
E1025 16:33:48.811892    6571 cc.go:287] sync process config failed, err: zk: node does not exist
F1025 16:34:03.814010    6571 audit.go:45] Failed to get configuration

我是起的单节点zookeeper
查看时报错
[zk: localhost:2181(CONNECTED) 2] ls /cc 
Authentication is not valid : /cc

**Comment by linliaoy** [comment]
@wusendong 
commit id ：777b8f10f56f41db21bb44842668e9401b4ecdc8
按照官方说明编译的。

**Comment by wusendong** [comment]
> @breezelxp cmdb_auditcontroller 这个项目没有起来
> 错误如下：
> Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
> E1025 16:33:48.803379 6571 cc.go:221] sync process config failed, err: zk: node does not exist
> E1025 16:33:48.809305 6571 cc.go:254] sync process config failed, err: zk: node does not exist
> E1025 16:33:48.811892 6571 cc.go:287] sync process config failed, err: zk: node does not exist
> F1025 16:34:03.814010 6571 audit.go:45] Failed to get configuration
> 
> 我是起的单节点zookeeper
> 查看时报错
> [zk: localhost:2181(CONNECTED) 2] ls /cc
> Authentication is not valid : /cc

这是由于adminserver 没有成功刷配置到zk导致的，请贴上adminserver 的详细日志

**Comment by wusendong** [comment]
请问您执行init.py这个脚本了吗？

**Comment by linliaoy** [comment]
执行了 直接正常。
adminserver error log：
Log file created at: 2018/10/25 16:33:49
Running on machine: hb2e-sw2-025167
Binary: Built with gc go1.9.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1025 16:33:49.002641    6540 conf.go:177] fail to open file(/opt/lanjing_cmdb/cmdb_adminserver/configures//txc.conf), err(open /opt/lanjing_cmdb/cmdb_adminserver/configures//txc.conf: no such file or directory)
E1025 16:34:17.801656    6540 addPresetObjects.go:129] add data for  cc_PropertyGroup table
E1025 16:34:17.810877    6540 addPresetObjects.go:103] add data for  cc_ObjDes table
E1025 16:34:17.915659    6540 addPresetObjects.go:56] add data for  cc_ObjAsst table
E1025 16:34:17.917728    6540 addPresetObjects.go:67] add data for  cc_ObjAsst table
E1025 16:34:17.917740    6540 addPlatData.go:27] add data for  cc_PlatBase table

**Comment by wusendong** [comment]
> 执行了 直接正常。
> adminserver error log：
> Log file created at: 2018/10/25 16:33:49
> Running on machine: hb2e-sw2-025167
> Binary: Built with gc go1.9.2 for linux/amd64
> Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
> E1025 16:33:49.002641 6540 conf.go:177] fail to open file(/opt/lanjing_cmdb/cmdb_adminserver/configures//txc.conf), err(open /opt/lanjing_cmdb/cmdb_adminserver/configures//txc.conf: no such file or directory)
> E1025 16:34:17.801656 6540 addPresetObjects.go:129] add data for cc_PropertyGroup table
> E1025 16:34:17.810877 6540 addPresetObjects.go:103] add data for cc_ObjDes table
> E1025 16:34:17.915659 6540 addPresetObjects.go:56] add data for cc_ObjAsst table
> E1025 16:34:17.917728 6540 addPresetObjects.go:67] add data for cc_ObjAsst table
> E1025 16:34:17.917740 6540 addPlatData.go:27] add data for cc_PlatBase table

我需要的是INFO日志哈~

**Comment by linliaoy** [comment]
Binary: Built with gc go1.9.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1025 16:33:48.527418    6540 server.go:138] config updated: 
{
  "config-server.addrs": "127.0.0.1:2181",
  "confs.dir": "/opt/lanjing_cmdb/cmdb_adminserver/configures/",
  "errors.res": "conf/errors",
  "language.res": "conf/language",
  "mongodb.database": "cmdb",
  "mongodb.host": "127.0.0.1",
  "mongodb.maxIDleConns": "1000",
  "mongodb.maxOpenConns": "3000",
  "mongodb.port": "27017",
  "mongodb.pwd": "123456",
  "mongodb.usr": "mongodb",
  "register-server.addrs": "127.0.0.1:2181"
}
I1025 16:33:48.528005    6540 blog.go:35] Connected to 127.0.0.1:2181
I1025 16:33:48.743928    6540 blog.go:35] Authenticated: id=72058227852312576, timeout=10000
I1025 16:33:48.743997    6540 blog.go:35] Re-submitting `0` credentials after reconnect
I1025 16:33:48.750614    6540 server.go:70] start to discover cc component from zk, path:[/cc/services/endpoints/migrate].
I1025 16:33:48.750630    6540 server.go:70] start to discover cc component from zk, path:[/cc/services/endpoints/proc].
I1025 16:33:48.750638    6540 server.go:70] start to discover cc component from zk, path:[/cc/services/endpoints/apiserver].
I1025 16:33:48.750647    6540 server.go:70] start to discover cc component from zk, path:[/cc/services/endpoints/auditcontroller].
I1025 16:33:48.750656    6540 server.go:70] start to discover cc component from zk, path:[/cc/services/endpoints/hostcontroller].
I1025 16:33:48.750662    6540 server.go:70] start to discover cc component from zk, path:[/cc/services/endpoints/objectcontroller].
I1025 16:33:48.750671    6540 server.go:70] start to discover cc component from zk, path:[/cc/services/endpoints/proccontroller].
I1025 16:33:48.750684    6540 server.go:70] start to discover cc component from zk, path:[/cc/services/endpoints/host].
I1025 16:33:48.750697    6540 server.go:70] start to discover cc component from zk, path:[/cc/services/endpoints/eventserver].
I1025 16:33:48.750708    6540 server.go:70] start to discover cc component from zk, path:[/cc/services/endpoints/datacollection].
I1025 16:33:48.750715    6540 server.go:70] start to discover cc component from zk, path:[/cc/services/endpoints/topo].
I1025 16:33:48.751200    6540 blog.go:35] Connected to 127.0.0.1:2181
I1025 16:33:48.761897    6540 blog.go:35] Authenticated: id=72058227852312584, timeout=5000
I1025 16:33:48.761939    6540 blog.go:35] Re-submitting `0` credentials after reconnect
I1025 16:33:48.769126    6540 zkregdiscv.go:76] register server and watch it. path(/cc/services/endpoints/migrate/172.16.25.167), data({"ip":"172.16.25.167","port":60004,"hostname":"cmdbtest","scheme":"http","version":"Version  :oc-18.10.25\nTag      :\nBuildTime:  2018-10-25T16:22:39+0800\nGitHash:    \nRunMode:    product\n","pid":6540})
I1025 16:33:48.769234    6540 language.go:61] loading language from conf/language
I1025 16:33:48.780943    6540 server.go:138] config updated: 
{
  "config-server.addrs": "127.0.0.1:2181",
  "confs.dir": "/opt/lanjing_cmdb/cmdb_adminserver/configures/",
  "errors.res": "conf/errors",
  "language.res": "conf/language",
  "mongodb.database": "cmdb",
  "mongodb.host": "127.0.0.1",
  "mongodb.maxIDleConns": "1000",
  "mongodb.maxOpenConns": "3000",
  "mongodb.port": "27017",
  "mongodb.pwd": "123456",
  "mongodb.usr": "mongodb",
  "register-server.addrs": "127.0.0.1:2181"
}
I1025 16:33:48.780962    6540 backbone.go:89] load new language config success.
I1025 16:33:48.780968    6540 backbone.go:101] load new error config success.
I1025 16:33:48.780978    6540 http.go:35] start insecure server on 172.16.25.167:60004
I1025 16:33:48.783659    6540 blog.go:35] Connected to 127.0.0.1:2181
I1025 16:33:48.799758    6540 blog.go:35] Authenticated: id=72058227852312600, timeout=40000
I1025 16:33:48.799778    6540 blog.go:35] Re-submitting `0` credentials after reconnect
I1025 16:33:48.803314    6540 conf.go:188] write configure(/opt/lanjing_cmdb/cmdb_adminserver/configures//apiserver.conf), key(/cc/services/config/apiserver), data(
    )
I1025 16:33:48.966201    6540 conf.go:167] writed configure to center /cc/services/config/apiserver
I1025 16:33:48.966249    6540 conf.go:188] write configure(/opt/lanjing_cmdb/cmdb_adminserver/configures//auditcontroller.conf), key(/cc/services/config/auditcontroller), data([mongodb]
host = 127.0.0.1
usr = mongodb
pwd = 123456
database = cmdb
port = 27017
maxOpenConns = 3000
maxIdleConns = 1000
)
I1025 16:33:48.982745    6540 conf.go:167] writed configure to center /cc/services/config/auditcontroller
I1025 16:33:48.982794    6540 conf.go:188] write configure(/opt/lanjing_cmdb/cmdb_adminserver/configures//datacollection.conf), key(/cc/services/config/datacollection), data([mongodb]
host = 127.0.0.1
usr = mongodb
pwd = 123456
database = cmdb
port = 27017
maxOpenConns = 3000
maxIdleConns = 1000

[snap-redis]
host = 127.0.0.1:6379
usr = cc
pwd = 123456
database = 0
chan = 3_snapshot

[discover-redis]
host = 127.0.0.1:6379
usr = cc
pwd = 123456
database = 0
chan = 3_snapshot

[redis]
host = 127.0.0.1:6379
usr = cc
pwd = 123456
database = 0
)
I1025 16:33:48.986889    6540 conf.go:167] writed configure to center /cc/services/config/datacollection
I1025 16:33:48.986913    6540 conf.go:188] write configure(/opt/lanjing_cmdb/cmdb_adminserver/configures//host.conf), key(/cc/services/config/host), data([gse]
addr=127.0.0.1:2181
user=bkzk
pwd=L%blKas
)
I1025 16:33:48.988622    6540 conf.go:167] writed configure to center /cc/services/config/host
I1025 16:33:48.988639    6540 conf.go:188] write configure(/opt/lanjing_cmdb/cmdb_adminserver/configures//hostcontroller.conf), key(/cc/services/config/hostcontroller), data([mongodb]
host=127.0.0.1
usr=mongodb
pwd=123456
database=cmdb
port=27017
maxOpenConns=3000
maxIDleConns=1000

[redis]
host=127.0.0.1
usr=cc
pwd=123456
database=0
port=6379
maxOpenConns=3000
maxIDleConns=1000
)
I1025 16:33:48.990403    6540 conf.go:167] writed configure to center /cc/services/config/hostcontroller
I1025 16:33:48.990433    6540 conf.go:188] write configure(/opt/lanjing_cmdb/cmdb_adminserver/configures//objectcontroller.conf), key(/cc/services/config/objectcontroller), data([mongodb]
host=127.0.0.1
usr=mongodb
pwd=123456
database=cmdb
port=27017
maxOpenConns=3000
maxIDleConns=1000

[redis]
host=127.0.0.1
usr=cc
pwd=123456
database=0
port=6379
maxOpenConns=3000
maxIDleConns=1000
)
I1025 16:33:48.992359    6540 conf.go:167] writed configure to center /cc/services/config/objectcontroller
I1025 16:33:48.992387    6540 conf.go:188] write configure(/opt/lanjing_cmdb/cmdb_adminserver/configures//proc.conf), key(/cc/services/config/proc), data(
    [redis]
    host=127.0.0.1
    usr=cc
    pwd=123456
    port=6379
    database = 0
    )
I1025 16:33:48.994191    6540 conf.go:167] writed configure to center /cc/services/config/proc
I1025 16:33:48.994210    6540 conf.go:188] write configure(/opt/lanjing_cmdb/cmdb_adminserver/configures//proccontroller.conf), key(/cc/services/config/proccontroller), data([mongodb]
host=127.0.0.1
usr=mongodb
pwd=123456
database=cmdb
port=27017
maxOpenConns=3000
maxIDleConns=1000

[redis]
host=127.0.0.1
usr=cc
pwd=123456
database=0
port=6379
maxOpenConns=3000
maxIDleConns=1000
)
I1025 16:33:48.995636    6540 conf.go:167] writed configure to center /cc/services/config/proccontroller
I1025 16:33:48.995651    6540 conf.go:188] write configure(/opt/lanjing_cmdb/cmdb_adminserver/configures//topo.conf), key(/cc/services/config/topo), data([mongodb]
host=127.0.0.1
usr=mongodb
pwd=123456
database=cmdb
port=27017
maxOpenConns=3000
maxIDleConns=1000
)
I1025 16:33:48.997017    6540 conf.go:167] writed configure to center /cc/services/config/topo
I1025 16:33:48.997058    6540 conf.go:188] write configure(/opt/lanjing_cmdb/cmdb_adminserver/configures//webserver.conf), key(/cc/services/config/webserver), data([api]
version=v3
[session]
name=cc3
skip=1
defaultlanguage=zh-cn
host=127.0.0.1
port=6379
secret=123456
multiple_owner=0

[site]
domain_url=http://172.16.25.167:8083
bk_login_url=http://127.0.0.1/login/?app_id=%s&c_url=%s
app_code=cc
check_url=http://127.0.0.1/login/accounts/get_user/?bk_token=
bk_account_url=http://127.0.0.1/login/accounts/get_all_user/?bk_token=%s
resources_path=/tmp/
html_root=/opt/lanjing_cmdb/web

[app]
agent_app_url=http://127.0.0.1/console/?app=bk_agent_setup
)
I1025 16:33:49.000533    6540 conf.go:167] writed configure to center /cc/services/config/webserver
I1025 16:33:49.000555    6540 conf.go:188] write configure(/opt/lanjing_cmdb/cmdb_adminserver/configures//eventserver.conf), key(/cc/services/config/eventserver), data([mongodb]
host=127.0.0.1
usr=mongodb
pwd=123456
database=cmdb
port=27017
maxOpenConns=3000
maxIDleConns=1000

[redis]
host=127.0.0.1
usr=cc
pwd=123456
database=0
port=6379
maxOpenConns=3000
maxIDleConns=1000
)
I1025 16:33:49.002621    6540 conf.go:167] writed configure to center /cc/services/config/eventserver
E1025 16:33:49.002641    6540 conf.go:177] fail to open file(/opt/lanjing_cmdb/cmdb_adminserver/configures//txc.conf), err(open /opt/lanjing_cmdb/cmdb_adminserver/configures//txc.conf: no such file or directory)
W1025 16:33:49.002921    6540 conf.go:164] fail to write configure of module(txc) into center
I1025 16:33:49.002925    6540 conf.go:63] writed all configures resource to center /cc/services/config
I1025 16:33:49.008552    6540 conf.go:70] writed error resource to center /cc/services/errors
I1025 16:33:49.008563    6540 language.go:61] loading language from conf/language
I1025 16:33:49.030368    6540 conf.go:77] writed languate packages to center /cc/services/language
W1025 16:33:53.760530    6540 server.go:73] received one zk event from path /cc/services/endpoints/hostcontroller.
I1025 16:33:53.760590    6540 server.go:130] update component with new server instance[http://172.16.25.167:50002] about path: /cc/services/endpoints/hostcontroller
W1025 16:33:53.760614    6540 server.go:73] received one zk event from path /cc/services/endpoints/migrate.
I1025 16:33:53.760700    6540 server.go:130] update component with new server instance[http://172.16.25.167:60004] about path: /cc/services/endpoints/migrate
W1025 16:33:53.767671    6540 server.go:73] received one zk event from path /cc/services/endpoints/proc.
I1025 16:33:53.767700    6540 server.go:130] update component with new server instance[http://172.16.25.167:60003] about path: /cc/services/endpoints/proc
W1025 16:33:53.771319    6540 server.go:73] received one zk event from path /cc/services/endpoints/apiserver.
I1025 16:33:53.771357    6540 server.go:130] update component with new server instance[http://172.16.25.167:8080] about path: /cc/services/endpoints/apiserver
W1025 16:33:53.771613    6540 server.go:73] received one zk event from path /cc/services/endpoints/auditcontroller.
I1025 16:33:53.771646    6540 server.go:130] update component with new server instance[http://172.16.25.167:50005] about path: /cc/services/endpoints/auditcontroller
W1025 16:33:53.773637    6540 server.go:73] received one zk event from path /cc/services/endpoints/host.
I1025 16:33:53.773659    6540 server.go:130] update component with new server instance[http://172.16.25.167:60001] about path: /cc/services/endpoints/host
W1025 16:33:53.774837    6540 server.go:73] received one zk event from path /cc/services/endpoints/objectcontroller.
I1025 16:33:53.774868    6540 server.go:130] update component with new server instance[http://172.16.25.167:50001] about path: /cc/services/endpoints/objectcontroller
W1025 16:33:53.776440    6540 server.go:73] received one zk event from path /cc/services/endpoints/proccontroller.
I1025 16:33:53.776465    6540 server.go:130] update component with new server instance[http://172.16.25.167:50003] about path: /cc/services/endpoints/proccontroller
W1025 16:33:53.780013    6540 server.go:73] received one zk event from path /cc/services/endpoints/eventserver.
I1025 16:33:53.780042    6540 server.go:130] update component with new server instance[http://172.16.25.167:60009] about path: /cc/services/endpoints/eventserver
W1025 16:33:53.780158    6540 server.go:73] received one zk event from path /cc/services/endpoints/datacollection.
I1025 16:33:53.780186    6540 server.go:130] update component with new server instance[http://172.16.25.167:60005] about path: /cc/services/endpoints/datacollection
W1025 16:33:53.782762    6540 server.go:73] received one zk event from path /cc/services/endpoints/topo.
I1025 16:33:53.782786    6540 server.go:130] update component with new server instance[http://172.16.25.167:60002] about path: /cc/services/endpoints/topo
W1025 16:34:09.195279    6540 server.go:73] received one zk event from path /cc/services/endpoints/auditcontroller.
W1025 16:34:09.195290    6540 server.go:80] get zk event with 0 instance with path[/cc/services/endpoints/auditcontroller], reset its servers
W1025 16:34:09.195623    6540 server.go:73] received one zk event from path /cc/services/endpoints/objectcontroller.
W1025 16:34:09.195629    6540 server.go:80] get zk event with 0 instance with path[/cc/services/endpoints/objectcontroller], reset its servers
W1025 16:34:09.195950    6540 server.go:73] received one zk event from path /cc/services/endpoints/proccontroller.
W1025 16:34:09.195960    6540 server.go:80] get zk event with 0 instance with path[/cc/services/endpoints/proccontroller], reset its servers
I1025 16:34:17.799073    6540 addPresetObjects.go:117] add cc_ObjClassification rows
E1025 16:34:17.801656    6540 addPresetObjects.go:129] add data for  cc_PropertyGroup table 
E1025 16:34:17.810877    6540 addPresetObjects.go:103] add data for  cc_ObjDes table 
I1025 16:34:17.818845    6540 addPresetObjects.go:73] add data for  cc_ObjAttDes table 
E1025 16:34:17.915659    6540 addPresetObjects.go:56] add data for  cc_ObjAsst table 
E1025 16:34:17.917728    6540 addPresetObjects.go:67] add data for  cc_ObjAsst table  
E1025 16:34:17.917740    6540 addPlatData.go:27] add data for  cc_PlatBase table 
I1025 16:34:17.918198    6540 addSystemData.go:26] add data for  cc_System table 
I1025 16:34:18.030861    6540 register.go:88] upgrade to version v3.0.8 success
I1025 16:34:18.036201    6540 register.go:88] upgrade to version v3.0.9-beta.1 success
I1025 16:34:18.036869    6540 register.go:88] upgrade to version v3.0.9-beta.3 success
I1025 16:34:18.037961    6540 register.go:88] upgrade to version v3.1.0-alpha.2 success
I1025 16:34:18.039323    6540 register.go:88] upgrade to version x08.09.04.01 success
I1025 16:34:18.040100    6540 register.go:88] upgrade to version x08.09.11.01 success
I1025 16:34:18.040448    6540 upgrader.go:32] droping index _id_
I1025 16:34:18.040454    6540 upgrader.go:32] droping index bk_biz_id_1_bk_supplier_account_1
I1025 16:34:18.041071    6540 upgrader.go:32] droping index bk_supplier_account_1
I1025 16:34:18.041695    6540 upgrader.go:32] droping index ext_key_1_bk_supplier_account_1
I1025 16:34:18.042262    6540 upgrader.go:32] droping index op_target_1_inst_id_1
I1025 16:34:18.042796    6540 upgrader.go:32] droping index opt_time_1
I1025 16:34:18.046629    6540 register.go:88] upgrade to version x08.09.13.01 success
I1025 16:34:18.050514    6540 register.go:88] upgrade to version x08.09.17.01 success
I1025 16:34:18.051064    6540 register.go:88] upgrade to version x08.09.18.01 success
I1025 16:34:18.052140    6540 register.go:88] upgrade to version x08.09.26.01 success
I1025 16:34:18.053055    6540 register.go:88] upgrade to version x18.09.30.01 success
I1025 16:34:18.058790    6540 register.go:88] upgrade to version x18_10_10_01 success

**Comment by wusendong** [comment]
好的，谢谢，从日志里看各个进程配置文件已经成功发送到zk了。

**Comment by linliaoy** [comment]
cmdb_webserver 启动不起来了，没有日志

**Comment by wusendong** [comment]
请加一下这个交流群： 305496802

**Comment by wusendong** [comment]
请问现在audicontroller还是报 ```sync process config failed, err: zk: node does not exist``` 吗

**Comment by linliaoy** [comment]
不报错了，已经好了。

**Comment by pythonzm** [comment]
> 不报错了，已经好了。

大佬怎么解决的？我遇到同样的报错

**Comment by oldthreefeng** [comment]
碰到相关的问题， 是 mongodb 宕了.... 导致  cmdb_adminserver 异常...  重启 mongodb 解决。
