### ISSUE TITLE
Field  doesn't have a default value 

### ISSUE THREAD

**Issue by ShaneWan** [Tencent/bk-cmdb#13]
php-5.6.29+mysql 5.7.17+CentOS Linux release 7.3.1611 (Core) 
ERROR - 2016-12-23 08:17:03 --> Query error: Field 'Source' doesn't have a default value - Invalid query: INSERT INTO `cc_ApplicationBase` (`ApplicationName`, `Creator`, `CreateTime`, `Default`, `DeptName`, `Display`, `Type`, `Level`, `LastTime`, `Owner`, `Maintainers`, `LifeCycle`, `ProductPm`, `CompanyID`) VALUES ('test', 'admin', '2016-12-23 08:17:03', 0, '公司名称', 1, 0, 2, '2016-12-23 08:17:03', '公司名称', '_admin_', '公测', '_admin_', 0)
ERROR - 2016-12-23 08:39:14 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/bk-cmdb/application/controllers/Host.php 117
ERROR - 2016-12-23 08:39:16 --> Query error: Field 'DefaultCon' doesn't have a default value - Invalid query: INSERT INTO `cc_UserCustom` (`DefaultColumn`, `UserName`) VALUES ('[\"InnerIP\",\"OuterIP\",\"SetName\",\"ModuleName\",\"HostName\"]', 'admin')
ERROR - 2016-12-23 08:39:55 --> Severity: Warning --> Invalid argument supplied for foreach() /var/www/html/bk-cmdb/application/controllers/Host.php 117

cc_UserCustom:
`DefaultCon` text NOT NULL default '' COMMENT '主机查询条件',

**Comment by xingliguang** [comment]
你这个问题开发者已经解决了，重新下载新的bk-cmdb.sql，然后重新导入！

**Comment by lowenitt** [comment]
已经更新了sql,请更新下

**Comment by xingliguang** [comment]
@lowenitt   大神，bk-cmdb.sql 第一个表的这个字段没有修改---BusinessDeptName，也需要修改为：
`BusinessDeptName` varchar(64) NOT NULL default '',   #添加 default ''
