### ISSUE TITLE
导入xlsx模型失败

### ISSUE THREAD

**Issue by 876161249** [Tencent/bk-cmdb#1315]
问题描述
===========
导入xlsx模型失败

重现方法
================
在“后台配置——模型管理”中随便建立一个模型，添加一些字段，导出后再用该xlsx导入报错

提供以下信息:
 - [x] bk-cmdb：v3.1.0-rc1
 - [x] Redis：3.2.12
 - [ ] MongoDB：2.8.0
 - [x] ZooKeeper：3.4.10
 - [x] 操作系统：CentOS Linux release 7.4.1708 (Core)
 - [x] bk-cmdb 异常日志
E1102 16:50:58.692556   13303 excel_util.go:69] 导入不存在的字段,请重新下载模板，并且不要删除excel前三行, bk_property_id,bk_property_name,bk_property_type,bk_property_group_name,option,unit,description,placeholder,editable,isrequired,isreadonly,isonly

**Comment by breezelxp** [comment]
@876161249 请检查是否将文件头的前3行删除了，是不能删除的。

**Comment by 876161249** [comment]
> @876161249 请检查是否将文件头的前3行删除了，是不能删除的。

xlsx文件就是原样导出的，没有被编辑过

**Comment by breezelxp** [comment]
请上传一下你的excel文件看一下。


> > @876161249 请检查是否将文件头的前3行删除了，是不能删除的。
> 
> xlsx文件就是原样导出的，没有被编辑过

**Comment by rentiansheng** [comment]
@876161249  出现这个错误的原因有两中情况
1. excel 前三行，被删除
2. excel 中的字段与模型的字段，差异字段比较多。 
     情况一： 数据导出后，新加多个字段后，用之前的导出excel 文件导入
     情况二： 在a模型中导出数据，然后去b模型中导入

**Comment by 876161249** [comment]
> @876161249 出现这个错误的原因有两中情况
> 
> 1. excel 前三行，被删除
> 2. excel 中的字段与模型的字段，差异字段比较多。
>    情况一： 数据导出后，新加多个字段后，用之前的导出excel 文件导入
>    情况二： 在a模型中导出数据，然后去b模型中导入

模型中只有一个默认的bk_inst_name必填字段，没有其它字段

**Comment by 876161249** [comment]
[inst_room_.xlsx](https://github.com/Tencent/bk-cmdb/files/2541865/inst_room_.xlsx)

**Comment by rentiansheng** [comment]
@876161249  你是在github 下载的v3.1.0-rc.1 的代码 编译吗？ 我根据环境重试下

**Comment by 876161249** [comment]
>@876161249 你是在github 下载的v3.1.0-rc.1 的代码 编译吗？ 我根据环境重试下

我直接用的cmdb.tar.gz解压，部署到vm和服务器都有这种问题产生。

**Comment by rentiansheng** [comment]
@876161249  https://github.com/Tencent/bk-cmdb/tree/v3.1.0 你直接使用这个代码。

**Comment by breezelxp** [comment]
@876161249 你好，长时间 未收到你的反馈，请问这个总是是否已经解决？

**Comment by 876161249** [comment]
![image](https://user-images.githubusercontent.com/40058181/47974223-abd71e00-e0e3-11e8-8b67-fd9ab04e4285.png)

编译错误是什么原因？/data/src/configcenter/src这个路径是对的。
> @876161249 你好，长时间 未收到你的反馈，请问这个总是是否已经解决？
> 我们先暂时关闭这个issue。如果你关于这个issue后续还有问题，可以随时再次打开这个issue。

**Comment by rentiansheng** [comment]
![image](https://user-images.githubusercontent.com/3955934/47975000-fc9c4600-e0e6-11e8-9fa2-c7eff6335a28.png)
你看下你这个目录是否存在。 

请按照https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/source_compile.md  中操作

**Comment by 876161249** [comment]
@rentiansheng 
是sh文件doc和unix格式的差别，用代码编译后界面风格突变导入正常，个人建议更新cmdb.tar.gz下载内容。
