### ISSUE TITLE
这个agent在哪里安装啊

### ISSUE THREAD

**Issue by bobo200128** [Tencent/bk-cmdb#1366]
![wechat screenshot_20181113175454](https://user-images.githubusercontent.com/17403220/48405565-75497500-e76d-11e8-84a5-be9fd3a8ab53.png)
这个agent在哪里安装啊

**Comment by wusendong** [comment]
这个是agent是社区版的，如需体检这个功能请安装社区版：https://bk.tencent.com/download/

**Comment by wusendong** [comment]
相同问题请在同一个issue下回复，谢谢

**Comment by bobo200128** [comment]
https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/installation.md
我就是在这里面下载的啊

**Comment by wusendong** [comment]
> [/docs/overview/installation.md@`master`](https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/installation.md)
> 我就是在这里面下载的啊

https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/installation.md 下载的是开源版，跟社区版是不同的。社区版在这里下载https://bk.tencent.com/download/

**Comment by bobo200128** [comment]
社区版本和开源版本什么区别？
我下载的开源版本上有这个   进入节点管理  为什么  还有社区版本呢
没有这个功能的话就砍掉好了啊

**Comment by 1350368559** [comment]
@wusendong 请问开源版本的bk-cmdb agent在哪里下载？怎么安装？

**Comment by breezelxp** [comment]
@1350368559 https://github.com/Tencent/bk-cmdb/issues/1366#issuecomment-438235503
看这里。

**Comment by 1350368559** [comment]
@breezelxp 我是不是可以这样理解，现在开源版本的bk-cmdb没有agent？只有社区版本的bk-cmdb才有agent？

**Comment by breezelxp** [comment]
@1350368559 蓝鲸是一套体系，cmdb是蓝鲸体系中的一部分。cmdb使用蓝鲸体系内的gse-agent采集主机数据。社区版的意思是蓝鲸社区版，包含了蓝鲸的基础服务体系。
