### ISSUE TITLE
Field 'BusinessDeptName' doesn't have a default value

### ISSUE THREAD

**Issue by fantast-dd** [Tencent/bk-cmdb#14]
PHP 5.6.9 + mysql 5.6.31 + centos 6.8

begin create resource pool

Database error: A Database Error Occurred

	Error Number: 1364
	Field 'BusinessDeptName' doesn't have a default value
	INSERT INTO `cc_ApplicationBase` (`ApplicationName`, `Creator`, `CreateTime`, `Default`, `Display`, `Level`, `Maintainers`, `Owner`, `Type`, `Source`, `CompanyID`) VALUES ('资源池', 'zhwx', '2016-12-23 11:04:48', 1, 1, 2, 'zhwx', 'zhwx', 0, 0, 0)
	Filename: models/ApplicationBaseModel.php
	Line Number: 88

bk-cmdb.sql是导入最新的

**Comment by xingliguang** [comment]
@fantast-dd  这个是开发者估计是忽略了，你参考其他列，将bk-cmdb.sql 文件中第一个表的这个列修改为
：
`BusinessDeptName` varchar(64) NOT NULL default '',
重新导入就OK了

**Comment by fantast-dd** [comment]
ERROR 1101 (42000) at line 348: BLOB/TEXT column 'DefaultColumn' can't have a default value
ERROR 1101 (42000) at line 348: BLOB/TEXT column 'DefaultCon' can't have a default value
导入的时候这两个字段有错 我已经改了

大神再请教下 访问一直404

2016/12/23 11:44:16 [error] 25093#0: *13 open() "/storage/www/bk-cmdb/account/login" failed (2: No such file or directory), client: 172.20.1.11, server: cmdb.wifiwx.com, request: "GET /account/login?cburl= HTTP/1.1", host: "cmdb.wifiwx.com"

![image](https://cloud.githubusercontent.com/assets/7877259/21446771/6754745a-c905-11e6-8534-e448ad21d781.png)

![image](https://cloud.githubusercontent.com/assets/7877259/21446785/81aebc70-c905-11e6-8ca0-282e00fc0f4f.png)

路径没有问题  /storage/www/bk-cmdb/index.html 我放个html文件是能正常访问的

**Comment by xingliguang** [comment]
你最好按照说明中的nginx.conf配置文件来配置。

**Comment by raindylong** [comment]
@fantast-dd ，仔细看readme的这一段：
`location / {
            index  index.php index.html index.htm;
            if (!-e $request_filename) {
               rewrite ^(.*)$ /index.php?s=$1 last;
               break;}
        }`

**Comment by fantast-dd** [comment]
@raindylong 是我疏忽了 谢谢大神
