### ISSUE TITLE
按照github上的部署方式无法完成部署

### ISSUE THREAD

**Issue by godjob2014** [Tencent/bk-cmdb#1417]
问题描述
===========
按照github上的部署方式无法完成部署，后台报错连接mongodb和zookeeper失败

重现方法
================
按照安装文档步骤安装，https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/installation.md

关键信息
=========
按照安装文档步骤安装,多个组件启动失败
初始化命令如下：python init.py --discovery 192.168.1.107:2181 --database cmdb --redis_ip 127.0.0.1 --redis_port 6379 --redis_pass root --mongo_ip 192.168.1.107 --mongo_port 28123 --mongo_user cc --mongo_pass cc --blueking_cmdb_url http://192.168.1.107:8083 --listen_port 8083

cmdb_adminserver服务报错显示连接不上mongo，日志如下：
connect mongo server failed no reachable servers

其他几个服务报错找不到zookeeper，日志如下：
E1120 18:47:36.640603   29235 cc.go:287] sync process config failed, err: zk: node does not exist
fail to watch context for path(/cc/services/errors), err:zk: node does not exist
node(/cc/services/errors) is not exist, will watch after 5s
fail to watch context for path(/cc/services/language), err:zk: node does not exist
node(/cc/services/language) is not exist, will watch after 5s
fail to watch context for path(/cc/services/config/auditcontroller), err:zk: node does not exist

请提供以下信息:
操作系统：centos7.5
ZooKeeper  3.4.13
Redis >= 3.2.12
MongoDB >= 2.8.0

**Comment by breezelxp** [comment]
请检查你的zk和mongo的配置，mongo初始化不能缺。

**Comment by breezelxp** [comment]
@godjob2014 你好，请问你的问题解决了吗？由于你长时间未回复，我们将关闭此issue，如果你还有问题，可以随时再打开此issue。
