### ISSUE TITLE
跨业务添加同名层级会报错（TY）

### ISSUE THREAD

**Issue by techfindd** [Tencent/bk-cmdb#143]
正常的逻辑是，不同的节点下（包含业务），可以创建同名的节点
![image](https://user-images.githubusercontent.com/6487821/38541365-6fe521b4-3cd1-11e8-95a4-08a7f027ce43.png)

**Comment by uriwang** [comment]
1. bk_parent_id 默认配置为 bk_issystem = true
2. 查询模型接口的时候会过滤掉 bk_issystem=true的字段，不会给从api 流出；

**Comment by uriwang** [comment]
已修复
