### ISSUE TITLE
按照步骤部署安装最后执行./start.sh和./init_db.sh 会报Failed connect to 192.168.202.47:60004; Connection refused

### ISSUE THREAD

**Issue by wjan925** [Tencent/bk-cmdb#1435]
按照步骤部署安装最后执行./start.sh和./init_db.sh 会报

![_20181123123036](https://user-images.githubusercontent.com/16714959/48928588-981d1b80-ef1b-11e8-80c0-b82be8f3ce38.jpg)

process count should be: 12 , now: 11
Not Running: cmdb_adminserver
[root@localhost cmdb]# bash ./init_db.sh 
curl: (7) Failed connect to 192.168.202.47:60004; Connection refused

请问这个192.168.202.47:60004 是什么东西？该怎么解决
请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): `<示例： v3.0.6-alpha 或者 git sha. 请不要使用 "最新版本" 或 "当前版本"等无法准确定位代码版本的语句描述>`
 - [ ] Redis     版本: 3.2.11
 - [ ] MongoDB   版本: 2.8.0
 - [ ] ZooKeeper 版本: 3.4.12
 - [ ] 操作系统      :  Centos 7 (x64)
 - [ ] bk-cmdb ：process count should be: 12 , now: 11
Not Running: cmdb_adminserver
[root@localhost cmdb]# bash ./init_db.sh 
curl: (7) Failed connect to 192.168.202.47:60004; Connection refused

**Comment by wjan925** [comment]
请问init_db.sh 这个脚本里的这个端口是干什么用的
![image](https://user-images.githubusercontent.com/16714959/48928984-4e363480-ef1f-11e8-9acb-84d34f8f30db.png)

**Comment by wjan925** [comment]
最后在日志里看到这个log：connect mongo server failed server returned error on SASL authentication step: Authentication failed  请问是什么意思

**Comment by wjan925** [comment]
需要开启mongodb 的权限认证吗

**Comment by breezelxp** [comment]
https://github.com/Tencent/bk-cmdb/issues/1435#issuecomment-441162154
是需要开启认证的。请注意你使用的mongodb的版本。在安装说明中有作提示。
![image](https://user-images.githubusercontent.com/26254420/48930330-bc342900-ef2a-11e8-89e0-93a41fcbbb69.png)

**Comment by wjan925** [comment]
已经解决了 我使用mongodb 配置文件启动，会开启验证引起的失败。

**Comment by breezelxp** [comment]
好的，那我关闭此issue。有问题再提哈。

**Comment by wjan925** [comment]
好的 谢谢
