### ISSUE TITLE
怎么添加登录页面呢？使用账户进行登录和使用登出功能

### ISSUE THREAD

**Issue by wjan925** [Tencent/bk-cmdb#1436]
你好 我想添加系统的登录页面 使用用户进行登录，和登出功能 怎么设置呢？
![image](https://user-images.githubusercontent.com/16714959/48930914-70837e80-ef2e-11e8-8551-c318720d8e54.png)

**Comment by breezelxp** [comment]
@wjan925 你好，可以移步社区版看一下。https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/experience.md

**Comment by rentiansheng** [comment]
@wjan925  如果使用需要对接第三登录， 可以根据 #1091 下面的方案，实现需要的方法。

**Comment by wjan925** [comment]
好的 我现在的需求是想把它部署在daocker里 然后添加登陆页面 公司内部的人通过用户名密码进行登陆使用

发自我的 iPhone
