### ISSUE TITLE
如何通过api查询资源池的主机呢？似乎只能查询业务内主机。

### ISSUE THREAD

**Issue by argaimar** [Tencent/bk-cmdb#1448]
问题描述
===========
如何通过api查询资源池的主机呢？POST /api/{version}/hosts/search这个api似乎只能查询业务内主机。

关键信息
=========

POST /api/{version}/hosts/search已经可以查询到移至业务内的主机，设置对应的bk_biz_id即可，但不知如何查询资源池内的主机

请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): v3.2.0

**Comment by breezelxp** [comment]
@rentiansheng

**Comment by rentiansheng** [comment]
现在配置平台的api是统一。  你在页面中查看下资源池调用的是哪个接口。 用的什么样的参数。 

后续出现其他问题。都可以按照类似的方法。

**Comment by argaimar** [comment]
Done. Thank U.
