### ISSUE TITLE
通用对象的关联字段通过api怎么更新

### ISSUE THREAD

**Issue by jabbawockeez** [Tencent/bk-cmdb#1459]
问题描述
===========
官方文档的api文档关于通用对象的说明太简陋了，我有很多通用对象，里面还有单关联和多关联的对象，怎么通过api更新？上个版本还能用关联对象的id加实例id来更新，今天更新到最新版3.1.0就不行了，总是报“参数无效或不存在”的错。

重现方法
================
<列出如何重现的方法或操作步骤>

**重要提醒**: 请优先尝试最新发布的版本 (发布清单： https://github.com/Tencent/bk-cmdb/releases), 如果问题不能在最新发布的版本里重现，说明此问题已经被修复。

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   版本 3.1.0

**Comment by breezelxp** [comment]
@jabbawockeez 最新发布的版本中模型的关联关系是通过关联类型来进行关联的，可以关注下我们最新发布的release版本。
https://github.com/Tencent/bk-cmdb/releases/tag/release-v3.2.2
