### ISSUE TITLE
事件推送主机身份重复发送

### ISSUE THREAD

**Issue by linliaoy** [Tencent/bk-cmdb#1462]
问题描述
===========
事件推送---- 主机身份
机器从模块转移到空闲机器 重复发送推送

重现方法
================
<列出如何重现的方法或操作步骤>

**重要提醒**: 请优先尝试最新发布的版本 (发布清单： https://github.com/Tencent/bk-cmdb/releases), 如果问题不能在最新发布的版本里重现，说明此问题已经被修复。

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。
![image](https://user-images.githubusercontent.com/16507478/49001414-96f82280-f197-11e8-934e-a0f8fa138d60.png)

请提供以下信息:
bk-cmdb 版本 (发布版本号 或 git tag): v3.1.0-rc.1
  Redis 版本: 3.2.11
  MongoDB 版本: 2.8.0
  ZooKeeper 版本: 3 .4.12
  操作系统 : ubuntu 14.04 4.4.0-123-generic
  bk-cmdb 异常日志
 - [x] bk-cmdb   版本 (发布版本号 或 git tag): v3.1.0-rc.1
 - [ ] Redis     版本: 3.2.11
 - [ ] MongoDB   版本:   2.8.0
 - [ ] ZooKeeper 版本: 3.4.12
 - [ ] 操作系统      : ubuntu 14.04 4.4.0-123-generic

**Comment by wusendong** [comment]
因为主机转模块时是会先删除后增加“主机-模块”关系的，所以会产生多条事件。
so，这不是bug

**Comment by wusendong** [comment]
> 没有标识 删除和 增加功能，request_id 是xxx-xxxx-xxx-xxx 也没法区分（没有区分开来）。

有标识的，action字段的可选值有create, update, delete

**Comment by linliaoy** [comment]
你看下我上面截图 都是update

**Comment by wusendong** [comment]
你可以看看这两条主机身份事件前面，应该是分别有两条“主机-模块”的delete，update事件的。

主机身份只有update这一种，以为主机身份只是我们的一种虚拟的结构，你在数据库里是找不着的，所以主机身份不存在create和update

**Comment by linliaoy** [comment]
模块转移是有两条 一个delete 一个create
主机身份是2个update，就是说主机身份 推送事件 就不用了，会触发两条。

**Comment by linliaoy** [comment]
还有一个问题，只有主机身份上面标明了 转移到哪个模块了（我们需要根据转移的模块名来进行初始化）

**Comment by wusendong** [comment]
你订阅模块转移就可以啦，create的那个事件有写转到了哪里的

**Comment by wusendong** [comment]
你订阅模块转移就可以啦，create的那个事件有写转到了哪里的

**Comment by wusendong** [comment]
你订阅模块转移就可以啦，create的那个事件有写转到了哪里的

**Comment by wusendong** [comment]
你订阅模块转移就可以啦，create的那个事件有写转到了哪里的

**Comment by wusendong** [comment]
你订阅模块转移就可以啦，create的那个事件有写转到了哪里的

**Comment by wusendong** [comment]
你订阅模块转移就可以啦，create的那个事件有写转到了哪里的

**Comment by wusendong** [comment]
你订阅'主机-模块'事件就可以啦，他的create事件有写转到哪里了的

**Comment by linliaoy** [comment]
![image](https://user-images.githubusercontent.com/16507478/49080080-72767600-f27d-11e8-8f76-b4061899cb9e.png)
这个好像没写哪个模块名字

**Comment by linliaoy** [comment]
主机身份：上面有 bk_biz_name

**Comment by wusendong** [comment]
> ![image](https://user-images.githubusercontent.com/16507478/49080080-72767600-f27d-11e8-8f76-b4061899cb9e.png)
> 这个好像没写哪个模块名字

模块的ID有记录到的，你不会是用模块的名称来做判断的吧？如果需要名字重查一下模块名就可以了
