### ISSUE TITLE
服务全部启动成功之后8083端口访问不到

### ISSUE THREAD

**Issue by wjan925** [Tencent/bk-cmdb#1465]
问题描述：
服务启动完毕后 8083端口访问不到
===========
![image](https://user-images.githubusercontent.com/16714959/49069828-320afe00-f265-11e8-82a2-7f550a0dc5e8.png)

**Comment by breezelxp** [comment]
@wjan925 那应该是websever自己退出了。可以看下zk是否连接正常。重新启动一下webserver.

**Comment by breezelxp** [comment]
@wjan925 你好，由于你长时间未回复，我们将关闭此issue。如果还有其它疑问，你可以随时再次打开此issue。
