### ISSUE TITLE
删除关联会把所有关联关系都清掉

### ISSUE THREAD

**Issue by jabbawockeez** [Tencent/bk-cmdb#1472]
问题描述
===========
无论是通过web操作还是api调用，只要是删除一条关联关系，所有关联关系都会清空。

重现方法
================
在界面上创建一个一对多或多对多的关联关系，然后关联一个以上的实例，然后取消其中一个关联，就可以看到所有的关联都取消了。

**重要提醒**: 请优先尝试最新发布的版本 (发布清单： https://github.com/Tencent/bk-cmdb/releases), 如果问题不能在最新发布的版本里重现，说明此问题已经被修复。

关键信息
=========
通过查看mongodb的日志发现，删除操作传到mongo的数据只有supplier_id，其它字段（condition中的信息）全部丢失。
**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): v3.1.0
 - [ ] MongoDB   版本: 4.0.4

**Comment by breezelxp** [comment]
@jabbawockeez 请说下你具体的操作流程，删除了什么关联关系？有相关的截图，日志，或者是后台的数据吗？

**Comment by breezelxp** [comment]
@jabbawockeez 感谢你的反馈，我们看一下。

**Comment by jabbawockeez** [comment]
> @jabbawockeez 请说下你具体的操作流程，删除了什么关联关系？有相关的截图，日志，或者是后台的数据吗？

一对多、多对多里关联了多个实例后取消关联其中一个，或者一对一里取消当前关联，反正只要涉及到删除关联的操作都会把mongo里的InstAsst清空

**Comment by breezelxp** [comment]
> > @jabbawockeez 请说下你具体的操作流程，删除了什么关联关系？有相关的截图，日志，或者是后台的数据吗？
> 
> 一对多、多对多里关联了多个实例后取消关联其中一个，或者一对一里取消当前关联，反正只要涉及到删除关联的操作都会把mongo里的InstAsst清空

好的，感谢你的反馈。我们看一下哈。如果你能定位到问题，欢迎给我们提PR。
