### ISSUE TITLE
编译前端时有问题

### ISSUE THREAD

**Issue by xuql927** [Tencent/bk-cmdb#149]
问题描述
===========
 make ui时，一直卡在这边
gyp verb command install [ '8.9.3' ]
gyp verb install input version string "8.9.3"
gyp verb install installing version: 8.9.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.9.3
gyp verb ensuring nodedir is created /opt/data/src/configcenter/src/ui/node_modules/node-sass/.node-gyp/8.9.3
gyp WARN EACCES user "root" does not have permission to access the dev dir "/opt/data/src/configcenter/src/ui/node_modules/node-sass/.node-gyp/8.9.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/data/src/configcenter/src/ui/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.9.3' ]
gyp verb install input version string "8.9.3"
gyp verb install installing version: 8.9.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.9.3
gyp verb ensuring nodedir is created /opt/data/src/configcenter/src/ui/node_modules/node-sass/.node-gyp/8.9.3
gyp WARN EACCES user "root" does not have permission to access the dev dir "/opt/data/src/configcenter/src/ui/node_modules/node-sass/.node-gyp/8.9.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/data/src/configcenter/src/ui/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space

重现方法
================
<列出如何重现的方法或操作步骤>

**重要提醒**: 请优先尝试最新发布的版本 (发布清单： https://github.com/Tencent/bk-cmdb/releases), 如果问题不能在最新发布的版本里重现，说明此问题已经被修复。

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): `<示例： v3.0.6-alpha 或者 git sha. 请不要使用 "最新版本" 或 "当前版本"等无法准确定位代码版本的语句描述>`
 - [ ] Redis     版本: `<示例： 3.2.11>`
 - [ ] MongoDB   版本: `<示例： 2.8.0>`
 - [ ] ZooKeeper 版本: `<示例： 3.4.11>`
 - [ ] 操作系统      : `<示例： Centos 5 (x64)>`
 - [ ] bk-cmdb 异常日志

**Comment by xuql927** [comment]
git clone https://github.com/Tencent/bk-cmdb  configcenter

**Comment by uriwang** [comment]
大陆地区用户推荐使用npm镜像cnpm进行前端编译，cnpm安装参考cnpmjs.org，编译时需要采用以下命令：
make ui NPM=cnpm

https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/source_compile.md

@xuql927
