### ISSUE TITLE
遇到新问题，类似A PHP Error was encountered

### ISSUE THREAD

**Issue by xingliguang** [Tencent/bk-cmdb#15]
描述：都配置好之后，开始登陆，第一次登陆也是OK的，用户名admin,密码blueking. 不过过了一会，重新登陆就报错了，如下图：
![image](https://cloud.githubusercontent.com/assets/24713062/21446914/d3e566d6-c907-11e6-9478-4e05e59ccbb0.png)
然后看到很多php的warning ：
A PHP Error was encountered

Severity: Warning

Message: mysql_real_escape_string() expects parameter 2 to be resource, boolean given

Filename: mysql/mysql_driver.php

Line Number: 352

Backtrace:

File: /data/htdocs/cc_openSource/application/models/UserModel.php
Line: 19
Function: where

File: /data/htdocs/cc_openSource/application/libraries/Login.php
Line: 115
Function: getUserByUsername

File: /data/htdocs/cc_openSource/application/libraries/Login.php
Line: 86
Function: isValidUserPassword

File: /data/htdocs/cc_openSource/application/libraries/Login.php
Line: 186
Function: isCcTokenValid

File: /data/htdocs/cc_openSource/application/controllers/Account.php
Line: 91
Function: loginUser

File: /data/htdocs/cc_openSource/index.php
Line: 293
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: mysql_query() expects parameter 2 to be resource, boolean given

Filename: mysql/mysql_driver.php

Line Number: 251

Backtrace:

File: /data/htdocs/cc_openSource/application/models/UserModel.php
Line: 20
Function: get

File: /data/htdocs/cc_openSource/application/libraries/Login.php
Line: 115
Function: getUserByUsername

File: /data/htdocs/cc_openSource/application/libraries/Login.php
Line: 86
Function: isValidUserPassword

File: /data/htdocs/cc_openSource/application/libraries/Login.php
Line: 186
Function: isCcTokenValid

File: /data/htdocs/cc_openSource/application/controllers/Account.php
Line: 91
Function: loginUser

File: /data/htdocs/cc_openSource/index.php
Line: 293
Function: require_once
还有很多………………
后来想重新导入bk-cmdb.sql   -重新导入OK
然后再执行 php index.php /cli/Init/initUserData  报错：
………………太多了，省略一些
Severity: WarningMessage:  mysql_real_escape_string() expects parameter 2 to be resource, boolean givenFilename: /data/htdocs/cc_openSource/system/database/drivers/mysql/mysql_driver.phpLine Number: 352
Backtrace:
File: /data/htdocs/cc_openSource/application/libraries/xhlog/DbLog.php  Line: 51        Function: insert_batch
A PHP Error was encountered
Severity: WarningMessage:  mysql_real_escape_string() expects parameter 2 to be resource, boolean givenFilename: /data/htdocs/cc_openSource/system/database/drivers/mysql/mysql_driver.phpLine Number: 352
Backtrace:
File: /data/htdocs/cc_openSource/application/libraries/xhlog/DbLog.php  Line: 51        Function: insert_batch
A PHP Error was encountered
Severity: WarningMessage:  mysql_query() expects parameter 2 to be resource, boolean givenFilename: /data/htdocs/cc_openSource/system/database/drivers/mysql/mysql_driver.phpLine Number: 251

Backtrace:

        File: /data/htdocs/cc_openSource/application/libraries/xhlog/DbLog.php  Line: 51        Function: insert_batch

A PHP Error was encountered

Severity: WarningMessage:  mysql_affected_rows() expects parameter 1 to be resource, boolean givenFilename: /data/htdocs/cc_openSource/system/database/drivers/mysql/mysql_driver.phpLine Number: 364

Backtrace:

        File: /data/htdocs/cc_openSource/application/libraries/xhlog/DbLog.php  Line: 51        Function: insert_batch
请问大神门，这是什么情况？
@lowenitt @zhujianfeng

**Comment by lowenitt** [comment]
单独把cc_User表初始化下吧

**Comment by raindylong** [comment]
@xingliguang ，既然都已经成功了，为何后面又突然不行了呢，解释不通。
建议你把cmdb所使用的database整个删掉重建，然后把初始化流程再重新跑一遍，既然成功过一次，说明这个初始化流程就算重复进行多次的也是可以得到正确结果的。

**Comment by xingliguang** [comment]
@raindylong  nginx和php都没有错误日志。在@lowenitt提醒下才知道看application/logs下的日志，日志中显示：ERROR - 2016-12-23 15:12:55 --> connect to mysql server error! errno:1045,error:Access denied for user 'root'@'127.0.0.1' (using password: YES) 我也是百思不得其解，后来看到数据库中mysql.user表中只有
'localhost'@'root' 有用户名和密码，‘127.0.0.1’@‘root’没有密码，于是授予其密码。重新导入数据，重新初始化，就OK了！也许将db.php中改为localhost:3306也是可行的，这个问题应该是配置文件和数据库中的账号密码不匹配导致的！
