### ISSUE TITLE
跨公有云进行kafka监控

### ISSUE THREAD

**Issue by kevinsingapore** [Tencent/bk-cmdb#1528]
1、问题背景：
（1）腾讯云主机上部署的单机版蓝鲸系统，阿里云美国硅谷区开了1台proxy机（经典网络），阿里云美国硅谷区开了2台p-agent机（私有网络）；
（2）腾讯云server机----阿里云proxy机----阿里云p-agent机，硬件监控状态正常；
（3）阿里云proxy机与阿里云p-agent机内网互通；
（4）2台阿里云p-agent机部署的kafka集群；
（5）上述机器全部cento7系统，默认python2.7.1；

-------------------------------------------------------
2、问题现象描述：
（1）蓝鲸监控--组件监控中进行kafka监控，报错如下：
[datadog] 采集器安装失败: tar (child): /tmp/bkdata/download/datadog-1.1.11-linux.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
（2）同样的部署方法，在腾讯云上监控kafka集群时，没有问题，此时网络是直连方式；
（3）在阿里云上监控kafka时，就报（1）中的错；
（4）阿里云上kafka机（p-agent机）中：【1】端口9272未起来；【2】/tmp/bkdata/download下空，没有相关包；

-----------------------------------------------------------
3、请问，如上，如何处理？技术交流：微信号948876386

**Comment by lampardtang** [comment]
蓝鲸社区版蓝鲸监控的问题，我单独找你看看，不在cmdb这里讨论了

**Comment by kevinsingapore** [comment]
3、经过排查，在proxy机上没有发现datadog-1.1.11-linux.tar.gz报错中的这个包。
