### ISSUE TITLE
通用实例更新API接口在更新多个单关联时在拓扑上显示异常

### ISSUE THREAD

**Issue by argaimar** [Tencent/bk-cmdb#1579]
问题描述
===========
一个通用实例模型的两个字段单关联另外两个模型时，通过/api/{version}/inst/{bk_supplier_account}/{bk_obj_id}/{bk_inst_id}接口更新第一个实例模型的实例时，数据虽然能够更新，但拓扑中无法展开。

重现方法
================
假设有3个模型，TEST1、TEST2、TEST3
TEST1表结构：
    实例名
    test2 - 单关联TEST2模型
    test3 - 单关联TEST3模型
TEST2表结构：
    实例名
TEST3表结构：
    实例名

TEST1模型中有‘1111’和‘2222’两个实例，TEST2中有‘AAAA’一个实例，TEST3中有‘BBBB’一个实例

通过/api/{version}/inst/{bk_supplier_account}/{bk_obj_id}/{bk_inst_id}更新TEST1中‘1111’和‘2222’实例的关联属性，数据可以被正常更新，但拓扑图中点击TEST2的’AAAA‘或是TEST3的’BBBB‘无法展开。

如果是手动点击关联，就可以展开。
如果没有TEST3模型，通过API更新，也可以展开。

关键信息
=========
想了解批量更新关联关系的推荐方法

**Comment by breezelxp** [comment]
@argaimar 您好，请提供下你使用的版本信息。

**Comment by argaimar** [comment]
@breezelxp v3.2.0

**Comment by argaimar** [comment]
@breezelxp 抱歉，我下载的不是源码，我是按照“安装部署”的可执行文件linux安装的，应该是3.1.0吧，有没有命令可以看到版本的？

**Comment by argaimar** [comment]
Version  :oc-18.10.09
Tag      :
BuildTime:  2018-10-09T18:06:06+0800
GitHash:    
RunMode:    product

@breezelxp

**Comment by breezelxp** [comment]
@argaimar 你好，你可以关注下我们主库v3.2.x的新特性，现在处于预release的状态。

想请问下你是通过什么途径拿到你现在使用的版本的？

**Comment by argaimar** [comment]
https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/installation.md的linux可执行文件
@breezelxp
