### ISSUE TITLE
操作审计查询数据不准确（JW）

### ISSUE THREAD

**Issue by techfindd** [Tencent/bk-cmdb#159]
![image](https://user-images.githubusercontent.com/6487821/38558610-3c19d3a2-3d03-11e8-8edd-6941c7ab5c99.png)
详细阐述如下：
Dos系统实际上是有删除的数据的，但是将类型选择为“删除”时，操作审计查询没有结果
![image](https://user-images.githubusercontent.com/6487821/38558616-42682ac4-3d03-11e8-9761-767d37c5fc8f.png)

**Comment by joe511230** [comment]
@rentiansheng @wusendong `op_type`为`delete`时查询无数据，请确认接口

**Comment by joe511230** [comment]
163引用错误

**Comment by rentiansheng** [comment]
通过
