### ISSUE TITLE
[doc] 部署文档中提供的 zookeeper 下载地址 404 了

### ISSUE THREAD

**Issue by alastairruhm** [Tencent/bk-cmdb#1591]
问题描述
===========

https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/installation.md 部署文档中提供的 zookeeper 下载地址： 

`https://mirrors.tuna.tsinghua.edu.cn/apache/zookeeper/zookeeper-3.4.11/zookeeper-3.4.11.tar.gz`

访问返回 404。

check 了一下这个目录 https://mirrors.tuna.tsinghua.edu.cn/apache/zookeeper/ 发现正好缺了 3.4.11 的版本

```bash
zookeeper-3.4.10/       2018-05-04 19:14    -   
zookeeper-3.4.12/       2018-05-04 19:14    -   
zookeeper-3.4.13/       2018-07-16  11:40    -   
```

按照文档描述，> 3.4.11 就行，因此我选择了 3.4.12 这个版本

重现方法
================
<列出如何重现的方法或操作步骤>

**重要提醒**: 请优先尝试最新发布的版本 (发布清单： https://github.com/Tencent/bk-cmdb/releases), 如果问题不能在最新发布的版本里重现，说明此问题已经被修复。

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): `<示例： v3.0.6-alpha 或者 git sha. 请不要使用 "最新版本" 或 "当前版本"等无法准确定位代码版本的语句描述>`
 - [ ] Redis     版本: `<示例： 3.2.11>`
 - [ ] MongoDB   版本: `<示例： 2.8.0>`
 - [ ] ZooKeeper 版本: `<示例： 3.4.11>`
 - [ ] 操作系统      : `<示例： Centos 5 (x64)>`
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@alastairruhm 感谢你的反馈，我们更新下这个链接。

**Comment by breezelxp** [comment]
已更新到3.4.12版本，可正常下载
