### ISSUE TITLE
云资源发现问题汇总

### ISSUE THREAD

**Issue by techfindd** [Tencent/bk-cmdb#1615]

**Comment by techfindd** [comment]
表单没有验证必填，相应的应该也没有验证名称的唯一性

**Comment by techfindd** [comment]
云账户管理员必须不为空，新建的时候必须要包含自己的账号

**Comment by rentiansheng** [comment]
时间格式不对painc
![image](https://user-images.githubusercontent.com/3955934/50153048-396f7580-0300-11e9-9c1c-5facfc7192e6.png)

**Comment by techfindd** [comment]
![image](https://user-images.githubusercontent.com/6487821/50153109-6d4a9b00-0300-11e9-9b48-aa0d1d656ae4.png)

空白的应该是两个横线

**Comment by techfindd** [comment]
![image](https://user-images.githubusercontent.com/6487821/50153240-d5997c80-0300-11e9-9173-f676496b702b.png)

1. 详情显示的格式没有调整
2. 红色区域不应该显示

**Comment by lampardtang** [comment]
![image](https://user-images.githubusercontent.com/39146216/50153260-de8a4e00-0300-11e9-9d27-321ce160c3ab.png)
样式和时间排序不对

**Comment by lampardtang** [comment]
![image](https://user-images.githubusercontent.com/39146216/50153309-0c6f9280-0301-11e9-854f-2255d8e693fe.png)
资源确认报错

**Comment by rentiansheng** [comment]
账号类型，时间类型不对
![image](https://user-images.githubusercontent.com/3955934/50153297-011c6700-0301-11e9-8546-4c0cd2b88fac.png)

**Comment by rentiansheng** [comment]
资源确认， 没有数据返回，

**Comment by techfindd** [comment]
![image](https://user-images.githubusercontent.com/6487821/50153785-64f35f80-0302-11e9-80ea-fa1125cc8c9e.png)
表格宽度不够合理

**Comment by ProtosL** [comment]
#1616 #1617

**Comment by ProtosL** [comment]
![image](https://user-images.githubusercontent.com/28912435/50274540-7f4f4980-0478-11e9-8a5b-2f66fe268db3.png)
查询不生效

**Comment by ProtosL** [comment]
![image](https://user-images.githubusercontent.com/28912435/50274688-cccbb680-0478-11e9-996e-73f724258097.png)
国际化
