### ISSUE TITLE
【建议】关于api(go-restful)接口认证的问题

### ISSUE THREAD

**Issue by duliang123** [Tencent/bk-cmdb#162]
建议
===========
经《蓝鲸CMDB开源开发交流》QQ群了解到，开源版本BK-CMDB不提供go-restful api用户Token认证功能。
为了CMDB跟内部系统对接，如果提供类似微信Token 签名认证功能，有效期控制（2小时），这样就能保证api调用的安全性了，希望开发团队在下个版本能够考虑到这点！

**Comment by lowenitt** [comment]
@duliang123     服务之间的认证包括api的鉴权已经在项目计划中的，请留意后续的开发计划
