### ISSUE TITLE
云资源发现第二次验收

### ISSUE THREAD

**Issue by techfindd** [Tencent/bk-cmdb#1634]

**Comment by techfindd** [comment]
![image](https://user-images.githubusercontent.com/6487821/50274742-e79e2b00-0478-11e9-93f5-c89cf6983545.png)
这里的ge格式需要验证一下，无意义的英文、不符合规范的数字需要提示的

**Comment by ProtosL** [comment]
![image](https://user-images.githubusercontent.com/28912435/50274879-11575200-0479-11e9-9ec7-908a8c7a790d.png)
查询不生效

**Comment by ProtosL** [comment]
![image](https://user-images.githubusercontent.com/28912435/50274921-2e8c2080-0479-11e9-980b-7229ef2ce04a.png)
国际化

**Comment by ProtosL** [comment]
![image](https://user-images.githubusercontent.com/28912435/50275105-a2c6c400-0479-11e9-8d97-dd06250da2a8.png)
国际化

**Comment by ProtosL** [comment]
![image](https://user-images.githubusercontent.com/28912435/50275332-1072f000-047a-11e9-85f8-3d33f6921664.png)
校验问题

**Comment by ProtosL** [comment]
![image](https://user-images.githubusercontent.com/28912435/50275432-4e701400-047a-11e9-84c7-57adb3a9aee3.png)
![image](https://user-images.githubusercontent.com/28912435/50275453-57f97c00-047a-11e9-9035-f012ff385e64.png)
1、如果是自动生成的那这个字段在创建时就不要让用户填了 
2、查看时能看到这个key的内容 编辑时又看不到

**Comment by ProtosL** [comment]
![image](https://user-images.githubusercontent.com/28912435/50275647-d0f8d380-047a-11e9-97e0-b483bb2cabd8.png)
进入编辑页面不做任何修改 关闭弹窗时会弹出提示
