### ISSUE TITLE
启动出现is NOT running 怎么解决？

### ISSUE THREAD

**Issue by AngieQ1** [Tencent/bk-cmdb#1639]
问题描述
===========
cmdb启动时出现以下服务未启动的状态：
process count should be: 12 , now: 7
Not Running: cmdb_datacollection
Not Running: cmdb_eventserver
Not Running: cmdb_hostcontroller
Not Running: cmdb_objectcontroller
Not Running: cmdb_proccontroller

请提供以下信息:

 - []Cmdb 版本：http://bkopen-1252002024.file.myqcloud.com/cmdb/cmdb.tar.gz
 - [ ] Redis     版本: `<Redis-3.2.11>`
 - [ ] MongoDB   版本: ·、`<MongoDB-2.8.0>`
 - [ ] ZooKeeper 版本: `<ZooKeeper-3.4.12>`
 - [ ] 操作系统      : `<示例： Centos 6.9 (x64)>`
 - [x] bk-cmdb 异常日志

**Comment by rentiansheng** [comment]
看下你的redis, mongodb配置， 顺便提供下日志

**Comment by AngieQ1** [comment]
> 看下你的redis, mongodb配置， 顺便提供下日志

参考的这篇：https://www.jianshu.com/p/67307eed221d
redis配置：
logfile "/opt/redis-3.2.11/logs/redis.log"
daemonize yes
requirepass Root1q2w
dir /opt/redis-3.2.11/db/

mongodb配置：
> use admin
switched to db admin
> db.createUser({user:'root',pwd:'Root1q2w',roles:['root']})
Successfully added user: { "user" : "root", "roles" : [ "root" ] }
> db.auth('root','Root1q2w')
1
> use cmdb
switched to db cmdb
> db.createUser({user:"cc",pwd:"cc",roles:[{role:"readWrite",db:"cmdb"}]})
Successfully added user: {
    "user" : "cc",
    "roles" : [
        {
            "role" : "readWrite",
            "db" : "cmdb"
        }
    ]
}

请问下日志在哪里查看。。？

**Comment by breezelxp** [comment]
@AngieQ1 这个应该是你的mongodb， redis和zk的服务没有正常启动，请检查这3个依赖服务正常启动后才能启动cmdb的服务。

**Comment by AngieQ1** [comment]
> 看下你的redis, mongodb配置， 顺便提供下日志

root     13700     1  0 08:01 pts/1    00:00:00 ./cmdb_webserver --addrport=192.168.3.7:8083 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=192.168.3.7:2181
root     13821     1  0 08:01 pts/1    00:00:00 ./cmdb_eventserver --addrport=192.168.3.7:60009 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=192.168.3.7:2181
root     13837     1  0 08:01 pts/1    00:00:00 ./cmdb_hostcontroller --addrport=192.168.3.7:50002 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=192.168.3.7:2181
root     13862     1  0 08:01 pts/1    00:00:00 ./cmdb_objectcontroller --addrport=192.168.3.7:50001 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=192.168.3.7:2181
root     13877     1  0 08:01 pts/1    00:00:00 ./cmdb_proccontroller --addrport=192.168.3.7:50003 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=192.168.3.7:2181
root     23758     1  0 Dec21 ?        00:02:14 ./cmdb_adminserver --addrport=192.168.3.7:60004 --logtostderr=false --log-dir=./logs --v=3 --config=configures/migrate.conf
root     23774     1  0 Dec21 ?        00:03:54 ./cmdb_apiserver --addrport=192.168.3.7:8080 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root     23790     1  0 Dec21 ?        00:05:10 ./cmdb_auditcontroller --addrport=192.168.3.7:50005 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root     23856     1  0 Dec21 ?        00:03:44 ./cmdb_hostserver --addrport=192.168.3.7:60001 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root     23907     1  0 Dec21 ?        00:03:47 ./cmdb_procserver --addrport=192.168.3.7:60003 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root     23924     1  0 Dec21 ?        00:03:44 ./cmdb_toposerver --addrport=192.168.3.7:60002 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181

**Comment by AngieQ1** [comment]
> @AngieQ1 这个应该是你的mongodb， redis和zk的服务没有正常启动，请检查这3个依赖服务正常启动后才能启动cmdb的服务。

我看了一下是正常启动的？设了开机自启

**Comment by AngieQ1** [comment]
> @AngieQ1 看下你没有启动程序日志std.log 有什么信息
**cmdb_datacollection的日志:**
begin to discover by watch children of path(/cc/services/endpoints/eventserver)
begin to discover by watch children of path(/cc/services/endpoints/auditcontroller)
begin to discover by watch children of path(/cc/services/endpoints/objectcontroller)
begin to discover by watch children of path(/cc/services/endpoints/datacollection)
begin to discover by watch children of path(/cc/services/endpoints/migrate)
begin to discover by watch children of path(/cc/services/endpoints/proc)
begin to discover by watch children of path(/cc/services/endpoints/topo)
begin to discover by watch children of path(/cc/services/endpoints/hostcontroller)
begin to discover by watch children of path(/cc/services/endpoints/proccontroller)
begin to discover by watch children of path(/cc/services/endpoints/host)
finish register server node(/cc/services/endpoints/datacollection/192.168.1.155) and watch it
watch found the children of path(/cc/services/endpoints/datacollection) change
run datacollection routine failed ERR Client sent AUTH, but no password is set

**Not Running: cmdb_eventserver**
begin to discover by watch children of path(/cc/services/endpoints/auditcontroller)
begin to discover by watch children of path(/cc/services/endpoints/hostcontroller)
begin to discover by watch children of path(/cc/services/endpoints/objectcontroller)
begin to discover by watch children of path(/cc/services/endpoints/proccontroller)
begin to discover by watch children of path(/cc/services/endpoints/topo)
begin to discover by watch children of path(/cc/services/endpoints/datacollection)
begin to discover by watch children of path(/cc/services/endpoints/host)
begin to discover by watch children of path(/cc/services/endpoints/migrate)
begin to discover by watch children of path(/cc/services/endpoints/proc)
begin to discover by watch children of path(/cc/services/endpoints/eventserver)
finish register server node(/cc/services/endpoints/eventserver/192.168.1.155) and watch it
watch found the children of path(/cc/services/endpoints/eventserver) change
connect redis server failed ERR Client sent AUTH, but no password is set

**Not Running: cmdb_hostcontroller**
begin to discover by watch children of path(/cc/services/endpoints/auditcontroller)
begin to discover by watch children of path(/cc/services/endpoints/proccontroller)
begin to discover by watch children of path(/cc/services/endpoints/datacollection)
begin to discover by watch children of path(/cc/services/endpoints/host)
begin to discover by watch children of path(/cc/services/endpoints/migrate)
begin to discover by watch children of path(/cc/services/endpoints/topo)
begin to discover by watch children of path(/cc/services/endpoints/eventserver)
begin to discover by watch children of path(/cc/services/endpoints/hostcontroller)
begin to discover by watch children of path(/cc/services/endpoints/objectcontroller)
begin to discover by watch children of path(/cc/services/endpoints/proc)
finish register server node(/cc/services/endpoints/hostcontroller/192.168.1.155) and watch it
watch found the children of path(/cc/services/endpoints/hostcontroller) change
new redis client failed, err: ERR Client sent AUTH, but no password is set

**Not Running: cmdb_objectcontroller**
begin to discover by watch children of path(/cc/services/endpoints/objectcontroller)
begin to discover by watch children of path(/cc/services/endpoints/datacollection)
begin to discover by watch children of path(/cc/services/endpoints/migrate)
begin to discover by watch children of path(/cc/services/endpoints/eventserver)
begin to discover by watch children of path(/cc/services/endpoints/hostcontroller)
begin to discover by watch children of path(/cc/services/endpoints/proccontroller)
begin to discover by watch children of path(/cc/services/endpoints/host)
begin to discover by watch children of path(/cc/services/endpoints/proc)
begin to discover by watch children of path(/cc/services/endpoints/topo)
begin to discover by watch children of path(/cc/services/endpoints/auditcontroller)
finish register server node(/cc/services/endpoints/objectcontroller/192.168.1.155) and watch it
watch found the children of path(/cc/services/endpoints/objectcontroller) change
new redis client failed, err: ERR Client sent AUTH, but no password is set

**Not Running: cmdb_proccontroller**
begin to discover by watch children of path(/cc/services/endpoints/auditcontroller)
begin to discover by watch children of path(/cc/services/endpoints/objectcontroller)
begin to discover by watch children of path(/cc/services/endpoints/proccontroller)
begin to discover by watch children of path(/cc/services/endpoints/host)
begin to discover by watch children of path(/cc/services/endpoints/migrate)
begin to discover by watch children of path(/cc/services/endpoints/proc)
begin to discover by watch children of path(/cc/services/endpoints/topo)
begin to discover by watch children of path(/cc/services/endpoints/eventserver)
begin to discover by watch children of path(/cc/services/endpoints/hostcontroller)
begin to discover by watch children of path(/cc/services/endpoints/datacollection)
finish register server node(/cc/services/endpoints/proccontroller/192.168.1.155) and watch it
watch found the children of path(/cc/services/endpoints/proccontroller) change
new redis client failed, err: ERR Client sent AUTH, but no password is set

**Comment by AngieQ1** [comment]
> @AngieQ1 看下你没有启动程序日志std.log 有什么信息

看到原因了！已解决~谢谢！

**Comment by rentiansheng** [comment]
run datacollection routine failed ERR Client sent AUTH, but no password is set



你的redis 没有设置授权。 为了安全，所有第三方都需要经过授权的。 要和配置文件中的一致
