### ISSUE TITLE
资源池无法导入规定格式的文件

### ISSUE THREAD

**Issue by xingliguang** [Tencent/bk-cmdb#17]
蓝鲸平台配置好之后，顺利登陆系统，再测试的时候，发现“资源池管理”这个模块有个问题：点击“导入主机”按钮，会弹出对话框，上面提示：文件类型支持xls、xlsx、csv 但是我在本机按照提示的格式创建了一个xls、xlsx文件进行导入，提示如下图：
![image](https://cloud.githubusercontent.com/assets/24713062/21474160/6efb5662-cb56-11e6-892b-bd2eb522eb99.png)
点击“确定”，依然没有将自定义的xls或者xlsx文件成功导入。查看application/logs目录中的日志，也么有任何输出。请大神指点，我出现这种情况有可能是哪里配置错了吗？
@lowenitt

**Comment by kaede425** [comment]
我也遇到了同样的问题

**Comment by lowenitt** [comment]
确定下logs的目录有读写权限吗？

**Comment by xingliguang** [comment]
@lowenitt 将application/logs 目录权限修改为了777（递归修改），然后再次导入主机，有日志了，如下：
INFO - 2016-12-26 17:23:16 --> Config Class Initialized
INFO - 2016-12-26 17:23:16 --> Hooks Class Initialized
DEBUG - 2016-12-26 17:23:16 --> UTF-8 Support Enabled
INFO - 2016-12-26 17:23:16 --> Utf8 Class Initialized
INFO - 2016-12-26 17:23:16 --> URI Class Initialized
INFO - 2016-12-26 17:23:16 --> Router Class Initialized
INFO - 2016-12-26 17:23:16 --> Output Class Initialized
INFO - 2016-12-26 17:23:16 --> Security Class Initialized
DEBUG - 2016-12-26 17:23:16 --> Global POST, GET and COOKIE data sanitized
INFO - 2016-12-26 17:23:16 --> Input Class Initialized
INFO - 2016-12-26 17:23:16 --> Language Class Initialized
INFO - 2016-12-26 17:23:16 --> Loader Class Initialized
DEBUG - 2016-12-26 17:23:16 --> Config file loaded: /data/htdocs/cc_openSource/application/config/errorcode.php
INFO - 2016-12-26 17:23:16 --> Session: Class initialized using 'files' driver.
DEBUG - 2016-12-26 17:23:16 --> Session class already loaded. Second attempt ignored.
DEBUG - 2016-12-26 17:23:16 --> Session class already loaded. Second attempt ignored.
INFO - 2016-12-26 17:23:16 --> Controller Class Initialized
INFO - 2016-12-26 17:23:16 --> Parser Class Initialized
INFO - 2016-12-26 17:23:16 --> Language file loaded: language/english/zh_cn_lang.php
DEBUG - 2016-12-26 17:23:16 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-26 17:23:16 --> Encryption: Auto-configured driver 'openssl'.
INFO - 2016-12-26 17:23:16 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2016-12-26 17:23:16 --> Encryption Class Initialized
INFO - 2016-12-26 17:23:16 --> Database Driver Class Initialized
INFO - 2016-12-26 17:23:17 --> Upload Class Initialized
INFO - 2016-12-26 17:23:17 --> Language file loaded: language/english/upload_lang.php
ERROR - 2016-12-26 17:23:17 --> The upload destination folder does not appear to be writable.
INFO - 2016-12-26 17:23:17 --> Final output sent to browser
DEBUG - 2016-12-26 17:23:17 --> Total execution time: 0.1693
没有发现error，但是就是无法导入成功！

**Comment by lowenitt** [comment]
ERROR - 2016-12-26 17:23:17 --> The upload destination folder does not appear to be writable.
看下这一行吧，目标文件夹没写权限

**Comment by xingliguang** [comment]
@lowenitt  logs目录权限我修改为了777：
drwxrwxrwx 2 root root 4096 Dec 26 16:40 logs
但是logs里面新生成的log文件是644：
-rwxrwxrwx 1 root   root     59785 Dec 23 12:54 log-2016-11-15.log
-rwxrwxrwx 1 root   root    125860 Dec 23 12:54 log-2016-11-16.log
-rwxrwxrwx 1 root   root    100788 Dec 23 12:54 log-2016-11-22.log
-rwxrwxrwx 1 root   root     40742 Dec 23 12:54 log-2016-12-07.log
-rwxrwxrwx 1 root   root    127938 Dec 23 12:54 log-2016-12-09.log
-rwxrwxrwx 1 root   root    650056 Dec 23 12:54 log-2016-12-12.log
-rwxrwxrwx 1 root   root   1332007 Dec 23 16:09 log-2016-12-23.log
-rw-r--r-- 1 nobody nobody   65014 Dec 26 17:27 log-2016-12-26.log #昨天生成的log文件
理论上是修改了logs目录的权限777，新生成的log文件应该也是777才对啊，很疑惑

**Comment by xingliguang** [comment]
@lowenitt  
ERROR - 2016-12-26 17:23:17 --> The upload destination folder does not appear to be writable.
看下这一行吧，目标文件夹没写权限
这个目录文件夹是哪个？不会是将cc_openSource整个目录下的所有目录和文件都递归修改为777吧？

**Comment by xingliguang** [comment]
@lowenitt 谢谢提醒，我将整个application目录递归修改权限777，重新导入资源池，然后 “资源池无法导入规定格式的文件”这个问题解决了！！！能否麻烦大神，将源码页面的说明文档里添加上递归修改application整个目录权限为777的说明，这样其他用户就不会遇到这么多问题了。

**Comment by lowenitt** [comment]
好，我改下说明文档。
