### ISSUE TITLE
导入模版优化、支持关联关系的导入

### ISSUE THREAD

**Issue by techfindd** [Tencent/bk-cmdb#171]
RT

**Comment by uriwang** [comment]
# 关联导入的场景划分为以下四种情况

1.  单唯一、单关联
2.  单唯一、多关联
3.  多唯一、单关联
4.  多唯一、多关联

**注：以上唯一指的是被关联模型的唯一标识字段的个数**

# 逻辑约定

1.  除云区域外，除关联模型的唯一标识字段不允许是关联字段 ；
2.  云区域模型不允许关联其它模型，云区域的名字在同一个供应商下保持唯一， 云区域模型不允许用户编辑；
3.  在主机模型中，云区域是主机模型的关联字段，同时也是主机的唯一标识字段，所以导入主机时云区域字段要特殊处理，用户在输入的时候需要填写云区域的名字。
4.   主线模型（包括主线上用户自定义的模型）不允许用户导入；
5.   主线模型不允许用户关联；

@techfindd 确认并补充excel 模板
@rentiansheng 确认

**Comment by techfindd** [comment]
[2018-04-17 CC 导入模版_主机.xlsx](https://github.com/Tencent/bk-cmdb/files/1922751/2018-04-17.CC._.xlsx)

**Comment by uriwang** [comment]
1. 主机导出，业务拓扑只导出不导入；
2. 主机关联关系导入导出。

**Comment by techfindd** [comment]
表头宽度规则：16个中文字符，和现有的name规则一致

**Comment by rentiansheng** [comment]
excel 类库调研结束，  支持文字颜色， 枚举字段选择列表（自开发的代码）
效果实例如下
![excel_enum](https://user-images.githubusercontent.com/3955934/39133501-f0b83928-4746-11e8-88c4-4fdf499b192e.png)

**Comment by rentiansheng** [comment]
任务分解
1. excel 调研1 天
2. excel 模版采用标准头部 1天
3. excel 导入到处格式一直及数据处理 1

@techfindd

**Comment by techfindd** [comment]
宽度固定为140px

**Comment by techfindd** [comment]
导入导出都需要有模版中的注释内容

**Comment by techfindd** [comment]
目前做不到字段排序，暂时把必填字段放到第一位 @rentiansheng
