### ISSUE TITLE
Invalid namespace name (bk.io). Only [a-z0-9-_] are allowed

### ISSUE THREAD

**Issue by liubean** [Tencent/bk-cmdb#1714]
问题描述
===========
docker pull 错误

重现方法
================
docker pull ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:latest

Invalid namespace name (bk.io). Only [a-z0-9-_] are allowed.

**Comment by breezelxp** [comment]
@liubean 你好，请问你的docker版本是多少？
