### ISSUE TITLE
可以在api里面进行JOIN查询吗？

### ISSUE THREAD

**Issue by JulianZhang** [Tencent/bk-cmdb#1758]
我们现在有需要对于存在CMDB中的模型进行关联查询，请问现在有api可以进行多个模型间的JOIN查询吗？

**Comment by breezelxp** [comment]
@JulianZhang 你好，cmdb支持模型之间通过关联关系进行模型间的关联。可以根据关联关系进行模型的查询。

**Comment by JulianZhang** [comment]
你好，请问这种根据关联关系进行查询是否有说明文档或者范例

**Comment by JulianZhang** [comment]
谢谢答复
