### ISSUE TITLE
编译完成后发现缺少web目录导致部署完成后页面无法访问

### ISSUE THREAD

**Issue by argaimar** [Tencent/bk-cmdb#1764]
问题描述
===========
根据编译步骤进行编译，编译完成后发现缺少web目录导致部署完成后页面无法访问。

重现方法
================
make ui会显示：
building web... 
然后直接返回命令行

如果make && make package后，解压package后发现比直接下载的可执行文件中缺少了web目录。

请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): v3.1.0
 - [ ] 操作系统      : CentOS6.8

**Comment by joe511230** [comment]
请问一下编译机的内存是多大？
