### ISSUE TITLE
有个建议哈

### ISSUE THREAD

**Issue by maogaf** [Tencent/bk-cmdb#179]
问题描述
===========
<有个建议哈，现在企业的信息系统都很复杂，各个应用系统的关联关系如何梳理，如何展现一直是我们头疼的问题，通过蓝鲸可以实现系统和系统关联的展现，但是还无法细致到端口级别的关联体现。同时我觉得应用型cmdb能否将交易流的展现体现出来。能否通过蓝鲸把交易流、数据流都给展现出来呢。>

重现方法
================
<列出如何重现的方法或操作步骤>

**重要提醒**: 请优先尝试最新发布的版本 (发布清单： https://github.com/Tencent/bk-cmdb/releases), 如果问题不能在最新发布的版本里重现，说明此问题已经被修复。

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): `<示例： v3.0.6-alpha 或者 git sha. 请不要使用 "最新版本" 或 "当前版本"等无法准确定位代码版本的语句描述>`
 - [ ] Redis     版本: `<示例： 3.2.11>`
 - [ ] MongoDB   版本: `<示例： 2.8.0>`
 - [ ] ZooKeeper 版本: `<示例： 3.4.11>`
 - [ ] 操作系统      : `<示例： Centos 5 (x64)>`
 - [ ] bk-cmdb 异常日志

**Comment by maogaf** [comment]
3123123123

**Comment by lowenitt** [comment]
你好，可否在issue下回复下 现有一些具备交易流和数据流产品的产品形态，方便大家讨论与学习
