### ISSUE TITLE
可否支持模型新建字段和已有模型实例内容关联

### ISSUE THREAD

**Issue by makerwei** [Tencent/bk-cmdb#1818]
问题描述
===========
比如已经存在一个【业务线】的模型，实例内容为:A,B,C
现需要新建【机器】和【应用】两个模型，两模型中都有  **业务线**（枚举类型）字段。
目前版本 如果业务线新增了一个D，我分别要去两个模型中  **业务线字段** 新增一个D，后续如果现在其他模型的也要用到**业务线**字段的话维护起来很不方便。如果能和业务线模型关联起来的话就好了。而且当新增了业务线后，可以推送给其他相关系统。

重现方法
================
无

关键信息
=========
目前所有版本都不支持此功能

**Comment by techfindd** [comment]
很好的建议，我们先记录此需求，加入后续的设计规划中实现

**Comment by makerwei** [comment]
@techfindd 谢谢
