### ISSUE TITLE
sync.WaitGroup.Add不应放在goroutine里

### ISSUE THREAD

**Issue by 360CodeSafe** [Tencent/bk-cmdb#1854]
https://github.com/Tencent/bk-cmdb/blob/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced/src/scene_server/event_server/distribution/transaction.go#L75
https://github.com/Tencent/bk-cmdb/blob/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced/src/scene_server/event_server/distribution/transaction.go#L98

goroutine的执行时间不确定，有可能导致Wait()时Add()并没有执行。
应该将Add语句放在调用goroutine的语句之前。

**Comment by wusendong** [comment]
经翻阅，这段代码的原意是希望这个transaction协程永远执行，所以waitgroup是非必须的，而应该重构为更合适的可重复执行结构。
