### ISSUE TITLE
是否存在反射型xss

### ISSUE THREAD

**Issue by 360CodeSafe** [Tencent/bk-cmdb#1858]
https://github.com/Tencent/bk-cmdb/blob/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced/src/scene_server/datacollection/datacollection/manager.go#L73

此处的mockmesg.Name来源于http请求的输入，没有经过处理直接输入到resp。
由于不清楚此处的业务逻辑，请确认是否存在问题。

**Comment by wusendong** [comment]
这个mockmesg正如其名，是在调试中用来产生模拟输入的，37行有写，生产环境是不会启动该mock服务的。故不存在问题
https://github.com/Tencent/bk-cmdb/blob/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced/src/scene_server/datacollection/datacollection/manager.go#L37

**Comment by 360CodeSafe** [comment]
是工具扫描的，但是检测结果目前没有开放下载。相关下载申请流程还在设计中。

**Comment by wusendong** [comment]
> 是工具扫描的，但是检测结果目前没有开放下载。相关下载申请流程还在设计中。

好的，谢谢您对开源工作及代码安全的支持，我们将关注相关issue并及时修复，共勉:)
