### ISSUE TITLE
可能的空指针异常

### ISSUE THREAD

**Issue by 360CodeSafe** [Tencent/bk-cmdb#1859]
https://github.com/Tencent/bk-cmdb/blob/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced/src/framework/core/config/factory.go#L45

此处的err由cc.Start()返回，而该函数可能返回nil，导致程序异常。

**Comment by 360CodeSafe** [comment]
同样的还有
https://github.com/Tencent/bk-cmdb/blob/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced/src/web_server/middleware/user/public.go#L161

**Comment by rentiansheng** [comment]
> 同样的还有
> [bk-cmdb/src/web_server/middleware/user/public.go](https://github.com/Tencent/bk-cmdb/blob/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced/src/web_server/middleware/user/public.go#L161)
> 
> Line 161 in [dd5d1e7](/Tencent/bk-cmdb/commit/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced)
> 
>  return user.GetLoginUrl(c, m.config.ConfigMap, params) 
> 
> [bk-cmdb/src/web_server/middleware/user/public.go](https://github.com/Tencent/bk-cmdb/blob/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced/src/web_server/middleware/user/public.go#L123)
> 
> Line 123 in [dd5d1e7](/Tencent/bk-cmdb/commit/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced)
> 
>  userList, err = user.GetUserList(c, m.config.ConfigMap) 
> 
> [bk-cmdb/src/web_server/middleware/user/public.go](https://github.com/Tencent/bk-cmdb/blob/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced/src/web_server/middleware/user/public.go#L53)
> 
> Line 53 in [dd5d1e7](/Tencent/bk-cmdb/commit/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced)
> 
>  userInfo, loginSucc = user.LoginUser(c, m.config.ConfigMap, isMultiOwner)

m.config.ConfgMap 在启动时刻会做检查，如果为空将会启动失败

**Comment by nabice** [comment]
> > 同样的还有
> > [bk-cmdb/src/web_server/middleware/user/public.go](https://github.com/Tencent/bk-cmdb/blob/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced/src/web_server/middleware/user/public.go#L161)
> > Line 161 in [dd5d1e7](/Tencent/bk-cmdb/commit/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced)
> > return user.GetLoginUrl(c, m.config.ConfigMap, params)
> > [bk-cmdb/src/web_server/middleware/user/public.go](https://github.com/Tencent/bk-cmdb/blob/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced/src/web_server/middleware/user/public.go#L123)
> > Line 123 in [dd5d1e7](/Tencent/bk-cmdb/commit/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced)
> > userList, err = user.GetUserList(c, m.config.ConfigMap)
> > [bk-cmdb/src/web_server/middleware/user/public.go](https://github.com/Tencent/bk-cmdb/blob/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced/src/web_server/middleware/user/public.go#L53)
> > Line 53 in [dd5d1e7](/Tencent/bk-cmdb/commit/dd5d1e7bd1ca272d97ac520b9a7e975008b25ced)
> > userInfo, loginSucc = user.LoginUser(c, m.config.ConfigMap, isMultiOwner)
> 
> m.config.ConfgMap 在启动时刻会做检查，如果为空将会启动失败

user有没有可能为nil？还是说此处逻辑plugins.CurrentPlugin返回不会为nil？

**Comment by rentiansheng** [comment]
这个地方在逻辑上不会为空。一致都会有一个默认组件的。 

![image](https://user-images.githubusercontent.com/3955934/53800573-068c6380-3f78-11e9-83a7-170ed2442eb0.png)

除非手动将注入代码删掉

**Comment by nabice** [comment]
好的，没问题就好
