### ISSUE TITLE
自定义业务拓扑后，又在模型拓扑中修改业务、集群、模块关联关系产生的问题

### ISSUE THREAD

**Issue by makerwei** [Tencent/bk-cmdb#1864]
问题描述
===========
业务拓扑中新增了一层：业务线 后
业务拓扑为：业务-业务线-集群-模块
增加几个业务：A、B、C
在对应业务下 增加 几个业务线、集群、模块
在模型拓扑中，删除业务和业务线  或 业务线和集群 或集群和模块的关联后，再重新设置好关联关系(**注：这里是可以直接删除内置模型的关联关系的**。)
发现实例化的业务拓扑树中数据都没有了，包括蓝鲸的。
是不是内置的业务拓扑关联关系不应该可以修改呢？

重现方法
================
如上

关键信息
=========
bk-cmdb 版本:
Version : v3.2.2
Tag : release-v3.2.2
Branch : v3.2.x
BuildTime: 2019-02-19T16:48:36+0800
GitHash : 3185b32
RunMode : product

**Comment by makerwei** [comment]
补充：业务拓扑页面数据展示没有，不知道数据中数据是否还在

**Comment by breezelxp** [comment]
@makerwei 是的，内置的关联类型是不能删除的，这个已经修复了，但未对外发布，可以关注下我们接下来要发布的版本。谢放。

**Comment by wusendong** [comment]
删除业务拓扑关联功能已经在后续版本下线，故不会再出现。可以close了
