### ISSUE TITLE
新建模型报数据唯一性校验失败

### ISSUE THREAD

**Issue by zqzqy04** [Tencent/bk-cmdb#1879]
问题描述
===========

![image](https://user-images.githubusercontent.com/48232141/53937991-bcc38a80-40e9-11e9-8097-af7777bd125d.png)

如图：

在新增模型的时候，报数据唯一性校验失败。

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
Version  : v3.2.2
Tag      : release-v3.2.2
Branch   : v3.2.x
BuildTime: 2019-02-19T16:48:36+0800
GitHash  : 3185b32956a6e59df1ee0744c6edf72e09828778
RunMode  : product
 -->
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@zqzqy04 我们测试是可以正常创建的，请问你的环境是新部署的，还是从别的版本升级过来的？
![image](https://user-images.githubusercontent.com/26254420/54012500-3bcfc600-41b1-11e9-9cf4-81aad41a0f3c.png)
