### ISSUE TITLE
业务模型-新建层级报数据校验失败 

### ISSUE THREAD

**Issue by zqzqy04** [Tencent/bk-cmdb#1880]
问题描述
===========

![image](https://user-images.githubusercontent.com/48232141/53938607-b7673f80-40eb-11e9-9d58-1d9e9a4ba872.png)
业务模型-新建层级报数据校验失败

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
Version  : v3.2.2
Tag      : release-v3.2.2
Branch   : v3.2.x
BuildTime: 2019-02-19T16:48:36+0800
GitHash  : 3185b32956a6e59df1ee0744c6edf72e09828778
RunMode  : product
 -->
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@zqzqy04 请补充你的版本信息。

**Comment by zqzqy04** [comment]
cmdb_oc_v3.2.2.tar

**Comment by breezelxp** [comment]
你好，请检查一下你“department”这个唯一标识，应该是和现有的有冲突。
此外可以看下这模型的唯一校验规则，校验的规则依赖于唯一校验的规则，你建立的规则可能有冲突。

![image](https://user-images.githubusercontent.com/26254420/54012743-ef38ba80-41b1-11e9-9e7e-a02095bece58.png)

**Comment by zqzqy04** [comment]
> 你好，请检查一下你“department”这个唯一标识，应该是和现有的有冲突。
> 此外可以看下这模型的唯一校验规则，校验的规则依赖于唯一校验的规则，你建立的规则可能有冲突。
> 
> ![image](https://user-images.githubusercontent.com/26254420/54012743-ef38ba80-41b1-11e9-9e7e-a02095bece58.png)

我测试了 两个问题：
1、CI模型--模型--新建模型时（自定义组中新建），会报上述校验失败的错误，唯一性肯定是没有冲突，报失败之后刷新页面，模型创建成功
2、CI模型--业务模型--业务，在拓扑图中“业务”下，点击“+”号，新建层级，也会报校验失败错误。但是刷新后，拓扑中没有创建完成。在CI模型--模型--业务拓扑下却显示创建成功，且不能删除。但是如果直接在CI模型--模型下，新建模型却不能选择“”业务拓扑“
