### ISSUE TITLE
创建层级、模型报错

### ISSUE THREAD

**Issue by zqzqy04** [Tencent/bk-cmdb#1884]
问题描述
===========
1、在CI模型--业务模型 创建层级时，报错“数据唯一性校验失败，唯一组合【%s】重复’”，保存不成功，拓扑图上不会出现新增的层级。但是在CI模型-模型的业务拓扑中，却看到创建成功。

2、在CI模型--模型 新增模型时，报错“数据唯一性校验失败，唯一组合【%s】重复’”，保存不成功，但刷新页面后，模型新建成功。

![image](https://user-images.githubusercontent.com/48232141/54020186-1dc19000-41c8-11e9-9ce6-f95bca0da900.png)

 

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 Version : v3.2.2
Tag : release-v3.2.2
Branch : v3.2.x
BuildTime: 2019-02-19T16:48:36+0800
GitHash : 3185b32
RunMode : product
 -->
 - [ ] Redis     版本: 3.2.11
 - [ ] MongoDB   版本:2.8.0
 - [ ] ZooKeeper 版本: 3.4.12
 - [ ] 操作系统      : centos 7.6.1810
 - [ ] bk-cmdb 异常日志

[root@D2-CMDBTEST210 logs]# more cmdb_toposerver.D2-CMDBTEST210.root.log.ERROR.20190308-163951.14268
Log file created at: 2019/03/08 16:39:51
Running on machine: D2-CMDBTEST210
Binary: Built with gc go1.11 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0308 16:39:51.921824   14268 unique.go:91] [model-unique] failed to create the unique(metadata.ObjectUnique{ID:0x0, ObjID:"securit
y_audit", MustCheck:true, Keys:[]metadata.UinqueKey{metadata.UinqueKey{Kind:"property", ID:0x9f}}, Ispre:false, OwnerID:"0", LastTi
me:metadata.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}}), error info is is 数据唯一性校验失败，唯一组合 [%s] 
重复
E0308 16:39:51.922107   14268 object.go:399] [operation-obj] failed to create the default inst name field, err: 数据唯一性校验失败
，唯一组合 [%s] 重复
E0308 16:42:29.731440   14268 unique.go:91] [model-unique] failed to create the unique(metadata.ObjectUnique{ID:0x0, ObjID:"aa", Mu
stCheck:true, Keys:[]metadata.UinqueKey{metadata.UinqueKey{Kind:"property", ID:0xa0}}, Ispre:false, OwnerID:"0", LastTime:metadata.
Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}}), error info is is 数据唯一性校验失败，唯一组合 [%s] 重复
E0308 16:42:29.731504   14268 object.go:399] [operation-obj] failed to create the default inst name field, err: 数据唯一性校验失败
，唯一组合 [%s] 重复
E0308 16:43:25.704072   14268 unique.go:91] [model-unique] failed to create the unique(metadata.ObjectUnique{ID:0x0, ObjID:"d", Mus
tCheck:true, Keys:[]metadata.UinqueKey{metadata.UinqueKey{Kind:"property", ID:0xa1}}, Ispre:false, OwnerID:"0", LastTime:metadata.T
ime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}}), error info is is 数据唯一性校验失败，唯一组合 [%s] 重复
E0308 16:43:25.704121   14268 object.go:399] [operation-obj] failed to create the default inst name field, err: 数据唯一性校验失败
，唯一组合 [%s] 重复
E0308 16:47:09.465096   14268 unique.go:91] [model-unique] failed to create the unique(metadata.ObjectUnique{ID:0x0, ObjID:"bm", Mu
stCheck:true, Keys:[]metadata.UinqueKey{metadata.UinqueKey{Kind:"property", ID:0xa2}, metadata.UinqueKey{Kind:"property", ID:0xa3}}
, Ispre:false, OwnerID:"0", LastTime:metadata.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}}), error info is is 
数据唯一性校验失败，唯一组合 [%s] 重复
E0308 16:47:09.465156   14268 object.go:399] [operation-obj] failed to create the default inst name field, err: 数据唯一性校验失败
，唯一组合 [%s] 重复
E0308 16:51:48.342371   14268 unique.go:91] [model-unique] failed to create the unique(metadata.ObjectUnique{ID:0x0, ObjID:"dd", Mu
stCheck:true, Keys:[]metadata.UinqueKey{metadata.UinqueKey{Kind:"property", ID:0xa4}, metadata.UinqueKey{Kind:"property", ID:0xa5}}
, Ispre:false, OwnerID:"0", LastTime:metadata.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}}), error info is is 
数据唯一性校验失败，唯一组合 [%s] 重复
E0308 16:51:48.342429   14268 object.go:399] [operation-obj] failed to create the default inst name field, err: 数据唯一性校验失败
，唯一组合 [%s] 重复

**Comment by rentiansheng** [comment]
提供下 cmdb_toposerver 的error 日志

**Comment by rentiansheng** [comment]
@breezelxp

**Comment by breezelxp** [comment]
@zqzqy04 
这个在我们自己的环境里没有复现出来。根据你提供的错误信息，应该是你这个模型和之前的模型名称有冲突，你确认下看看。

**Comment by breezelxp** [comment]
@wusendong 优化下这个唯一校验的报错信息。
![image](https://user-images.githubusercontent.com/26254420/54170219-c3b71800-44b0-11e9-9458-7d52326beeb2.png)

**Comment by kofeng** [comment]
这个问题我已经复现了，原因为部署文档https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/installation.md 推荐的mongodb版本为2.8.0，而最新的realease版本源码里面使用了新版mongodb的$count,导致报错

在release-v3.5.18版本 新建模型 时报错： 数据唯一性校验失败，instance 重复
在release-v3.2.2版本   新建模型 时报错： 数据唯一性校验失败，唯一组合[%s]重复

**/v3.5.18/cmdb_coreservice/logs下日志报错内容：**
Binary: Built with gc go1.13.4 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
**E1109 16:02:57.716581    7896 model/unique_crud.go:315] [ObjectUnique] recheckUniqueForExistsInsts failed exception: Unrecognized pipeline stage name: '$count', pipeli**
ne: [{"$match":{"bk_obj_id":"siyouyunxuji","metadata.label.bk_biz_id":{"$exists":false}}},{"$group":{"_id":{"bk_inst_name":"$bk_inst_name"},"total":{"$sum":1}}},{"$mat
ch":{"total":{"$gt":1}}},{"$count":"unique_count"}], rid: "cc0000bn375c8tkql1v0onh860"
E1109 16:02:57.717794    7896 model/unique_crud.go:77] [CreateObjectUnique] recheckUniqueForExistsInsts for siyouyunxuji with metadata.CreateModelAttrUnique{Data:metad
ata.ObjectUnique{ID:0x0, ObjID:"siyouyunxuji", MustCheck:true, Keys:[]metadata.UniqueKey{metadata.UniqueKey{Kind:"property", ID:0xa1}}, Ispre:false, OwnerID:"", Metada
ta:metadata.Metadata{Label:metadata.Label(nil)}, LastTime:metadata.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}}} err: &mgo.QueryError{Code:16436, 
**Message:"exception: Unrecognized pipeline stage name: '$count'", Assertion:false}, rid: cc0000bn375c8tkql1v0onh860**


**解决办法：升级mongodb至3.4以上，我升级至4.2.1后问题解决；**https://docs.mongodb.com/manual/reference/operator/aggregation/count/
