### ISSUE TITLE
cmdb模型和主机数据导出时按照界面展示的字段进行优先排序

### ISSUE THREAD

**Issue by japlee** [Tencent/bk-cmdb#1886]
问题描述
===========
tapd: 
https://tapd.tencent.com/20365752/bugtrace/bugs/view?bug_id=1120365752058385580&url_cache_key=57e816020969d4bae144d3e675cb1afd

host和inst实例的字段属性很多时，导出到excel的数据是没有规则排序的，有些客户想在excel
中就可以直接看到那些期望看到字段，而不用去滚轮翻到右边去看需要的字段了。在cmd界面
展现中，很多客户会把期望看到的字段都展现出来，其他不重要的字段隐藏掉。

所以基于此，想按照界面中展现的字段优先在excel导出时排序在前面

重现方法
================
模型的inst和主机数据导出时，可以看到里面的字段排序是无序的，如一些重要的bk_host_innerip都要到很右边才能看到

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

解决思路
===========
界面展示时，用户的实例和host的展示字段存放在mongo数据库cc_UserCustom表中：
如：
"admin_host_2_table_columns" : [
		"bk_host_innerip",
		"bk_cloud_id",
		"bk_module_name",
		"bk_set_name",
		"bk_host_outerip",
		"bk_mac",
		"bk_outer_mac"
	],
"admin_test_2_table_columns" : [
		"bk_inst_name",
		"jw_test_1",
		"jw_test_2",
		"jw_test_4",
		"jw_test_3",
		"jw_test_5",
		"jw_test_6"
	],

所以在前端界面点击导出时，把用户的custom table columns传入到api调用参数中，
在export函数时，解析出此参数：
customFieldsStr := c.PostForm(common.BKInstCustomColumns)

然后传入到GetObjFieldIDs函数中，对其customFieldsStr进行处理后，结合此来进行fields中的ExcelColIndex排序：
func (lgc *Logics) GetObjFieldIDs(objID string, filterFields []string, customFieldsStr string, header http.Header, meta metadata.Metadata) (map[string]Property, error) {

	fields, err := lgc.getObjFieldIDs(objID, header, meta)
	if nil != err {
		return nil, err
	}
	groups, err := lgc.getObjectGroup(objID, header, meta)
	if nil != err {
		return nil, err
	}

	customFields := strings.Split(customFieldsStr, ",")
	customFieldsList := make([]string, 0)
	for _, fieldID := range customFields {
		if util.InStrArr(filterFields, fieldID) {
			continue
		}
		customFieldsList = append(customFieldsList, fieldID)
	}

	ret := make(map[string]Property)
	indexCustom := 0
	indexOthers := len(customFieldsList)

	for _, group := range groups {
		for _, field := range fields {
			if field.Group == group.ID {
				if util.InStrArr(filterFields, field.ID) {
					field.NotExport = true
				} else if util.InStrArr(customFieldsList, field.ID){
					field.ExcelColIndex = indexCustom
					indexCustom++
				} else {
					field.ExcelColIndex = indexOthers
					indexOthers++
				}
				ret[field.ID] = field

			}
		}
	}
	return ret, nil
}

**Comment by breezelxp** [comment]
@rentiansheng @lowenitt @wusendong 看下。
