### ISSUE TITLE
自带模型修改名称操作无效

### ISSUE THREAD

**Issue by DeKaiju** [Tencent/bk-cmdb#1890]
问题描述
===========
![image](https://user-images.githubusercontent.com/10413226/54098171-5478ef80-43ee-11e9-939a-64aba1ccbde7.png)
cmdb自带模型修改名称后刷新页面名称并没有被更改

重现方法
================

模型->apache->名称右侧编辑按钮->输入新名称->保存->刷新页面

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
github release 3.2.2

**Comment by breezelxp** [comment]
@DeKaiju 
感谢您的反馈，经过我们的测试，这个问题确实存在，我们处理一下。

@joe511230 请关注一下。
