### ISSUE TITLE
主机查询接口没有返回新增的业务拓扑项

### ISSUE THREAD

**Issue by makerwei** [Tencent/bk-cmdb#1895]
问题描述
===========
业务拓扑新增  【层级】
![image](https://user-images.githubusercontent.com/43264876/54111783-b0a83780-441f-11e9-8c00-5209ca179286.png)
![image](https://user-images.githubusercontent.com/43264876/54111816-bef65380-441f-11e9-830b-4d1a17c95ad7.png)
以上接口没有返回主机所属的 【层级】

重现方法
================
如上

关键信息
=========

bk-cmdb 版本:
Version : v3.2.2
Tag : release-v3.2.2
Branch : v3.2.x
BuildTime: 2019-02-19T16:48:36+0800
GitHash : 3185b32
RunMode : product

**Comment by breezelxp** [comment]
@makerwei 请给出你具体的调用参数。
