### ISSUE TITLE
 CMDB在搜索业务名称和用户名称时英文字母大小写敏感

### ISSUE THREAD

**Issue by vlon** [Tencent/bk-cmdb#1896]
问题描述
===========
CMDB在搜索业务名称和用户名称时英文字母大小写敏感，当业务项多，用户也多的时候给CMDB的管理造成不便，根据客户的体验和使用需求，希望CMDB在搜索业务名称和用户名称时英文字母大小写不敏感，并带有模糊查询的功能

重现方法
================
如问题描述

关键信息
=========

请提供以下信息:
Version  :  v3.1.0-alpha1
Branch   : v3.1.0
GitHash:    a67a8d5faef79a1cf55dd397d2d22e6c1fa4eebd
RunMode:    product

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@vlon 感谢你的反馈，@techfindd 关注一下。
