### ISSUE TITLE
用户管理界面添加用户无法成功

### ISSUE THREAD

**Issue by xingliguang** [Tencent/bk-cmdb#19]
描述：
点击“用户管理”页面，然后再点击“新增用户”，填写好用户信息之后提交，无法成功创建用户，日志如下：
INFO - 2016-12-27 11:35:39 --> Config Class Initialized
INFO - 2016-12-27 11:35:39 --> Hooks Class Initialized
DEBUG - 2016-12-27 11:35:39 --> UTF-8 Support Enabled
INFO - 2016-12-27 11:35:39 --> Utf8 Class Initialized
INFO - 2016-12-27 11:35:39 --> URI Class Initialized
INFO - 2016-12-27 11:35:39 --> Router Class Initialized
INFO - 2016-12-27 11:35:39 --> Output Class Initialized
INFO - 2016-12-27 11:35:39 --> Security Class Initialized
DEBUG - 2016-12-27 11:35:39 --> Global POST, GET and COOKIE data sanitized
INFO - 2016-12-27 11:35:39 --> Input Class Initialized
INFO - 2016-12-27 11:35:39 --> Language Class Initialized
INFO - 2016-12-27 11:35:39 --> Loader Class Initialized
DEBUG - 2016-12-27 11:35:39 --> Config file loaded: /data/htdocs/cc_openSource/application/config/errorcode.php
INFO - 2016-12-27 11:35:39 --> Session: Class initialized using 'files' driver.
DEBUG - 2016-12-27 11:35:39 --> Session class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 11:35:39 --> Session class already loaded. Second attempt ignored.
INFO - 2016-12-27 11:35:39 --> Controller Class Initialized
INFO - 2016-12-27 11:35:39 --> Parser Class Initialized
INFO - 2016-12-27 11:35:39 --> Language file loaded: language/english/zh_cn_lang.php
DEBUG - 2016-12-27 11:35:39 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 11:35:39 --> Encryption: Auto-configured driver 'openssl'.
INFO - 2016-12-27 11:35:39 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2016-12-27 11:35:39 --> Encryption Class Initialized
INFO - 2016-12-27 11:35:39 --> Database Driver Class Initialized
DEBUG - 2016-12-27 11:35:39 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 11:35:39 --> Login class already loaded. Second attempt ignored.
INFO - 2016-12-27 11:35:39 --> File loaded: /data/htdocs/cc_openSource/application/views/account/index.php
INFO - 2016-12-27 11:35:39 --> File loaded: /data/htdocs/cc_openSource/application/views/layout.php
INFO - 2016-12-27 11:35:39 --> Final output sent to browser
DEBUG - 2016-12-27 11:35:39 --> Total execution time: 0.2377
然后点击“主机管理”页面，页面不会报错了，但是日志中有如下错误：
INFO - 2016-12-27 11:37:11 --> Config Class Initialized
INFO - 2016-12-27 11:37:11 --> Hooks Class Initialized
DEBUG - 2016-12-27 11:37:11 --> UTF-8 Support Enabled
INFO - 2016-12-27 11:37:11 --> Utf8 Class Initialized
INFO - 2016-12-27 11:37:11 --> URI Class Initialized
INFO - 2016-12-27 11:37:11 --> Router Class Initialized
INFO - 2016-12-27 11:37:11 --> Output Class Initialized
INFO - 2016-12-27 11:37:11 --> Security Class Initialized
DEBUG - 2016-12-27 11:37:11 --> Global POST, GET and COOKIE data sanitized
INFO - 2016-12-27 11:37:11 --> Input Class Initialized
INFO - 2016-12-27 11:37:11 --> Language Class Initialized
INFO - 2016-12-27 11:37:11 --> Loader Class Initialized
DEBUG - 2016-12-27 11:37:11 --> Config file loaded: /data/htdocs/cc_openSource/application/config/errorcode.php
INFO - 2016-12-27 11:37:11 --> Session: Class initialized using 'files' driver.
DEBUG - 2016-12-27 11:37:11 --> Session class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 11:37:11 --> Session class already loaded. Second attempt ignored.
INFO - 2016-12-27 11:37:11 --> Controller Class Initialized
INFO - 2016-12-27 11:37:11 --> Parser Class Initialized
INFO - 2016-12-27 11:37:11 --> Language file loaded: language/english/zh_cn_lang.php
DEBUG - 2016-12-27 11:37:11 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 11:37:11 --> Encryption: Auto-configured driver 'openssl'.
INFO - 2016-12-27 11:37:11 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2016-12-27 11:37:11 --> Encryption Class Initialized
INFO - 2016-12-27 11:37:11 --> Database Driver Class Initialized
INFO - 2016-12-27 11:37:11 --> File loaded: /data/htdocs/cc_openSource/application/views/host/hostQuery.php
INFO - 2016-12-27 11:37:11 --> File loaded: /data/htdocs/cc_openSource/application/views/layout.php
INFO - 2016-12-27 11:37:11 --> Final output sent to browser
DEBUG - 2016-12-27 11:37:11 --> Total execution time: 0.2681
INFO - 2016-12-27 11:37:11 --> Config Class Initialized
INFO - 2016-12-27 11:37:11 --> Hooks Class Initialized
DEBUG - 2016-12-27 11:37:11 --> UTF-8 Support Enabled
INFO - 2016-12-27 11:37:11 --> Utf8 Class Initialized
INFO - 2016-12-27 11:37:11 --> URI Class Initialized
INFO - 2016-12-27 11:37:11 --> Router Class Initialized
INFO - 2016-12-27 11:37:11 --> Output Class Initialized
INFO - 2016-12-27 11:37:11 --> Security Class Initialized
DEBUG - 2016-12-27 11:37:11 --> Global POST, GET and COOKIE data sanitized
INFO - 2016-12-27 11:37:11 --> Input Class Initialized
INFO - 2016-12-27 11:37:11 --> Language Class Initialized
INFO - 2016-12-27 11:37:11 --> Loader Class Initialized
DEBUG - 2016-12-27 11:37:11 --> Config file loaded: /data/htdocs/cc_openSource/application/config/errorcode.php
INFO - 2016-12-27 11:37:11 --> Session: Class initialized using 'files' driver.
DEBUG - 2016-12-27 11:37:11 --> Session class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 11:37:11 --> Session class already loaded. Second attempt ignored.
INFO - 2016-12-27 11:37:11 --> Controller Class Initialized
INFO - 2016-12-27 11:37:11 --> Parser Class Initialized
INFO - 2016-12-27 11:37:11 --> Language file loaded: language/english/zh_cn_lang.php
DEBUG - 2016-12-27 11:37:11 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 11:37:11 --> Encryption: Auto-configured driver 'openssl'.
INFO - 2016-12-27 11:37:11 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2016-12-27 11:37:11 --> Encryption Class Initialized
INFO - 2016-12-27 11:37:11 --> Database Driver Class Initialized
INFO - 2016-12-27 11:37:11 --> Final output sent to browser
DEBUG - 2016-12-27 11:37:11 --> Total execution time: 0.2273
INFO - 2016-12-27 11:37:12 --> Config Class Initialized
INFO - 2016-12-27 11:37:12 --> Hooks Class Initialized
DEBUG - 2016-12-27 11:37:12 --> UTF-8 Support Enabled
INFO - 2016-12-27 11:37:12 --> Utf8 Class Initialized
INFO - 2016-12-27 11:37:12 --> URI Class Initialized
INFO - 2016-12-27 11:37:12 --> Router Class Initialized
INFO - 2016-12-27 11:37:12 --> Output Class Initialized
INFO - 2016-12-27 11:37:12 --> Security Class Initialized
DEBUG - 2016-12-27 11:37:12 --> Global POST, GET and COOKIE data sanitized
INFO - 2016-12-27 11:37:12 --> Input Class Initialized
INFO - 2016-12-27 11:37:12 --> Language Class Initialized
INFO - 2016-12-27 11:37:12 --> Loader Class Initialized
DEBUG - 2016-12-27 11:37:12 --> Config file loaded: /data/htdocs/cc_openSource/application/config/errorcode.php
INFO - 2016-12-27 11:37:12 --> Session: Class initialized using 'files' driver.
DEBUG - 2016-12-27 11:37:12 --> Session class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 11:37:12 --> Session class already loaded. Second attempt ignored.
INFO - 2016-12-27 11:37:12 --> Controller Class Initialized
INFO - 2016-12-27 11:37:12 --> Parser Class Initialized
INFO - 2016-12-27 11:37:12 --> Language file loaded: language/english/zh_cn_lang.php
DEBUG - 2016-12-27 11:37:12 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 11:37:12 --> Encryption: Auto-configured driver 'openssl'.
INFO - 2016-12-27 11:37:12 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2016-12-27 11:37:12 --> Encryption Class Initialized
INFO - 2016-12-27 11:37:12 --> Database Driver Class Initialized
INFO - 2016-12-27 11:37:12 --> Final output sent to browser
DEBUG - 2016-12-27 11:37:12 --> Total execution time: 0.1176
INFO - 2016-12-27 11:37:12 --> Config Class Initialized
INFO - 2016-12-27 11:37:12 --> Hooks Class Initialized
DEBUG - 2016-12-27 11:37:12 --> UTF-8 Support Enabled
INFO - 2016-12-27 11:37:12 --> Utf8 Class Initialized
INFO - 2016-12-27 11:37:12 --> URI Class Initialized
INFO - 2016-12-27 11:37:12 --> Router Class Initialized
INFO - 2016-12-27 11:37:12 --> Output Class Initialized
INFO - 2016-12-27 11:37:12 --> Security Class Initialized
DEBUG - 2016-12-27 11:37:12 --> Global POST, GET and COOKIE data sanitized
INFO - 2016-12-27 11:37:12 --> Input Class Initialized
INFO - 2016-12-27 11:37:12 --> Language Class Initialized
INFO - 2016-12-27 11:37:12 --> Loader Class Initialized
DEBUG - 2016-12-27 11:37:12 --> Config file loaded: /data/htdocs/cc_openSource/application/config/errorcode.php
INFO - 2016-12-27 11:37:12 --> Session: Class initialized using 'files' driver.
DEBUG - 2016-12-27 11:37:12 --> Session class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 11:37:12 --> Session class already loaded. Second attempt ignored.
INFO - 2016-12-27 11:37:12 --> Controller Class Initialized
INFO - 2016-12-27 11:37:12 --> Parser Class Initialized
INFO - 2016-12-27 11:37:12 --> Language file loaded: language/english/zh_cn_lang.php
DEBUG - 2016-12-27 11:37:12 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-27 11:37:12 --> Encryption: Auto-configured driver 'openssl'.
INFO - 2016-12-27 11:37:12 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2016-12-27 11:37:12 --> Encryption Class Initialized
INFO - 2016-12-27 11:37:12 --> Database Driver Class Initialized
ERROR - 2016-12-27 11:37:12 --> Query error: Field 'DefaultCon' doesn't have a default value - Invalid query: INSERT INTO `cc_UserCustom` (`DefaultColumn`, `UserName`) VALUES ('[\"InnerIP\",\"OuterIP\",\"SetName\",\"ModuleName\",\"HostName\"]', 'admin')
ERROR - 2016-12-27 11:37:12 --> [上海]  [admin]  [10.0.90.8]  添加用户定制, 失败!mysql_errno: 1364, mysql_error: Field 'DefaultCon' doesn't have a default value
INFO - 2016-12-27 11:37:12 --> Final output sent to browser
DEBUG - 2016-12-27 11:37:12 --> Total execution time: 0.1128
之前的导入最新的bk-cmdb.sql 无报错，执行 php index.php /cli/Init/initUserData都没有报错。然后我手动修改报错表的字段，提示错误：
mysql> alter table cc_UserCustom modify column `DefaultCon` text NOT NULL default '' COMMENT '主机查询条件';
ERROR 1101 (42000): BLOB/TEXT column 'DefaultCon' can't have a default value
不知道是什么问题，请指导

**Comment by xingliguang** [comment]
我发现切换到主机管理界面，就会报上面的错，能不能将建表语句修改一下呢?
将
CREATE TABLE `cc_UserCustom` (
  `UserName` varchar(16) NOT NULL default '',
  `DefaultApplication` int(11) NOT NULL default '0',
  `DefaultColumn` text NOT NULL default '',
  `DefaultPageSize` int(2) NOT NULL default '20',
  `DefaultField` varchar(512) NOT NULL default '' COMMENT '主机查询字段',
  `DefaultCon` text NOT NULL default '' COMMENT '主机查询条件',    #这里的错误
  `Description` varchar(256) NOT NULL default '',
  `SetGseCol` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY  (`UserName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='用户定制表';
改为：
CREATE TABLE `cc_UserCustom` (
  `UserName` varchar(16) NOT NULL default '',
  `DefaultApplication` int(11) NOT NULL default '0',
  `DefaultColumn` text NOT NULL default '',
  `DefaultPageSize` int(2) NOT NULL default '20',
  `DefaultField` varchar(512) NOT NULL default '' COMMENT '主机查询字段',
  `DefaultCon` varchar(512) NOT NULL default '' COMMENT '主机查询条件',  #改成这样？
  `Description` varchar(256) NOT NULL default '',
  `SetGseCol` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY  (`UserName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='用户定制表';
@lowenitt

**Comment by xingliguang** [comment]
@lowenitt  我将上面表结构改为了如下：
DROP TABLE IF EXISTS `cc_UserCustom`;
CREATE TABLE `cc_UserCustom` (
  `UserName` varchar(16) NOT NULL default '',
  `DefaultApplication` int(11) NOT NULL default '0',
  `DefaultColumn` varchar(512) NOT NULL default '',    #原来是text
  `DefaultPageSize` int(2) NOT NULL default '20',
  `DefaultField` varchar(512) NOT NULL default '' COMMENT '主机查询字段',
  `DefaultCon` varchar(512) NOT NULL default '' COMMENT '主机查询条件', #原来是text
  `Description` varchar(256) NOT NULL default '',
  `SetGseCol` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY  (`UserName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='用户定制表';
重新创建此表，点击“主机管理”页面，log中不会出现第一次描述中的那种错误了，不知道我这种修改，会不会影响后续平台的使用？
但是无法添加新用户的情况依然存在。

**Comment by lowenitt** [comment]
嗯，明白你的意思了，你可以把字段长度设置长一点，比如1024 ，然后发起pull request  ，我们鼓励大家和我们一起改进系统和代码

**Comment by xingliguang** [comment]
@lowenitt 那么，想问一下， 无法添加用户的情况，如何解决呢？

**Comment by lowenitt** [comment]
请更新下代码，如果输入有错误，会提示的

**Comment by xingliguang** [comment]
@lowenitt  我是这样更新的代码，不知道符合要求不：
重新clone 代码，使用新的代码，没有重新导入数据（bk-cmdb.sql）,没有重新执行初始化数据
（php index.php /cli/Init/initUserData ）然后重启nginx和php，重新添加用户：
![image](https://cloud.githubusercontent.com/assets/24713062/21535807/6e6c3c0a-cdb5-11e6-84d7-5220c5e3af87.png)
也已经将index.php 中改为了 ini_set('display_errors', 1);
没有看到错误日志，日志中内容如下：
INFO - 2016-12-29 10:45:31 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2016-12-29 10:45:31 --> Encryption Class Initialized
INFO - 2016-12-29 10:45:31 --> Database Driver Class Initialized
DEBUG - 2016-12-29 10:45:31 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-29 10:45:31 --> Login class already loaded. Second attempt ignored.
INFO - 2016-12-29 10:45:31 --> File loaded: /data/htdocs/cc_openSource/application/views/account/index.php
INFO - 2016-12-29 10:45:31 --> File loaded: /data/htdocs/cc_openSource/application/views/layout.php
INFO - 2016-12-29 10:45:31 --> Final output sent to browser
DEBUG - 2016-12-29 10:45:31 --> Total execution time: 0.2387
INFO - 2016-12-29 10:54:08 --> Config Class Initialized
INFO - 2016-12-29 10:54:08 --> Hooks Class Initialized
DEBUG - 2016-12-29 10:54:08 --> UTF-8 Support Enabled
INFO - 2016-12-29 10:54:08 --> Utf8 Class Initialized
INFO - 2016-12-29 10:54:08 --> URI Class Initialized
INFO - 2016-12-29 10:54:08 --> Router Class Initialized
INFO - 2016-12-29 10:54:08 --> Output Class Initialized
INFO - 2016-12-29 10:54:08 --> Security Class Initialized
DEBUG - 2016-12-29 10:54:08 --> Global POST, GET and COOKIE data sanitized
INFO - 2016-12-29 10:54:08 --> Input Class Initialized
INFO - 2016-12-29 10:54:08 --> Language Class Initialized
INFO - 2016-12-29 10:54:08 --> Loader Class Initialized
DEBUG - 2016-12-29 10:54:08 --> Config file loaded: /data/htdocs/cc_openSource/application/config/errorcode.php
INFO - 2016-12-29 10:54:08 --> Session: Class initialized using 'files' driver.
DEBUG - 2016-12-29 10:54:08 --> Session class already loaded. Second attempt ignored.
DEBUG - 2016-12-29 10:54:08 --> Session class already loaded. Second attempt ignored.
INFO - 2016-12-29 10:54:08 --> Controller Class Initialized
INFO - 2016-12-29 10:54:08 --> Parser Class Initialized
INFO - 2016-12-29 10:54:08 --> Language file loaded: language/english/zh_cn_lang.php
DEBUG - 2016-12-29 10:54:08 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-29 10:54:08 --> Encryption: Auto-configured driver 'openssl'.
INFO - 2016-12-29 10:54:08 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2016-12-29 10:54:08 --> Encryption Class Initialized
INFO - 2016-12-29 10:54:08 --> Database Driver Class Initialized
DEBUG - 2016-12-29 10:54:08 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-29 10:54:08 --> Login class already loaded. Second attempt ignored.
INFO - 2016-12-29 10:54:08 --> File loaded: /data/htdocs/cc_openSource/application/views/account/index.php
INFO - 2016-12-29 10:54:08 --> File loaded: /data/htdocs/cc_openSource/application/views/layout.php
INFO - 2016-12-29 10:54:08 --> Final output sent to browser
DEBUG - 2016-12-29 10:54:08 --> Total execution time: 0.1178
INFO - 2016-12-29 10:54:10 --> Config Class Initialized
INFO - 2016-12-29 10:54:10 --> Hooks Class Initialized
DEBUG - 2016-12-29 10:54:10 --> UTF-8 Support Enabled
INFO - 2016-12-29 10:54:10 --> Utf8 Class Initialized
INFO - 2016-12-29 10:54:10 --> URI Class Initialized
INFO - 2016-12-29 10:54:10 --> Router Class Initialized
INFO - 2016-12-29 10:54:10 --> Output Class Initialized
INFO - 2016-12-29 10:54:10 --> Security Class Initialized
DEBUG - 2016-12-29 10:54:10 --> Global POST, GET and COOKIE data sanitized
INFO - 2016-12-29 10:54:10 --> Input Class Initialized
INFO - 2016-12-29 10:54:10 --> Language Class Initialized
INFO - 2016-12-29 10:54:10 --> Loader Class Initialized
DEBUG - 2016-12-29 10:54:10 --> Config file loaded: /data/htdocs/cc_openSource/application/config/errorcode.php
INFO - 2016-12-29 10:54:10 --> Session: Class initialized using 'files' driver.
DEBUG - 2016-12-29 10:54:10 --> Session class already loaded. Second attempt ignored.
DEBUG - 2016-12-29 10:54:10 --> Session class already loaded. Second attempt ignored.
INFO - 2016-12-29 10:54:10 --> Controller Class Initialized
INFO - 2016-12-29 10:54:10 --> Parser Class Initialized
INFO - 2016-12-29 10:54:10 --> Language file loaded: language/english/zh_cn_lang.php
DEBUG - 2016-12-29 10:54:10 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-29 10:54:10 --> Encryption: Auto-configured driver 'openssl'.
INFO - 2016-12-29 10:54:10 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2016-12-29 10:54:10 --> Encryption Class Initialized
INFO - 2016-12-29 10:54:10 --> Database Driver Class Initialized
DEBUG - 2016-12-29 10:54:10 --> Login class already loaded. Second attempt ignored.
DEBUG - 2016-12-29 10:54:10 --> Login class already loaded. Second attempt ignored.
INFO - 2016-12-29 10:54:10 --> File loaded: /data/htdocs/cc_openSource/application/views/account/index.php
INFO - 2016-12-29 10:54:10 --> File loaded: /data/htdocs/cc_openSource/application/views/layout.php
INFO - 2016-12-29 10:54:10 --> Final output sent to browser
DEBUG - 2016-12-29 10:54:10 --> Total execution time: 0.1170

**Comment by sunssy** [comment]
描述：
点击“用户管理”页面，然后点击“新增用户”，填写好用户信息后，点击新增无报错无反应，也无法成功添加用户。
![image](https://cloud.githubusercontent.com/assets/13249280/22817111/65460f22-efa0-11e6-879b-041b146fb99d.png)

日志如下：
INFO - 2017-02-10 14:42:58 --> Config Class Initialized
INFO - 2017-02-10 14:42:58 --> Hooks Class Initialized
DEBUG - 2017-02-10 14:42:58 --> UTF-8 Support Enabled
INFO - 2017-02-10 14:42:58 --> Utf8 Class Initialized
INFO - 2017-02-10 14:42:58 --> URI Class Initialized
INFO - 2017-02-10 14:42:58 --> Router Class Initialized
INFO - 2017-02-10 14:42:58 --> Output Class Initialized
INFO - 2017-02-10 14:42:58 --> Security Class Initialized
DEBUG - 2017-02-10 14:42:58 --> Global POST, GET and COOKIE data sanitized
INFO - 2017-02-10 14:42:58 --> Input Class Initialized
INFO - 2017-02-10 14:42:58 --> Language Class Initialized
INFO - 2017-02-10 14:42:58 --> Loader Class Initialized
DEBUG - 2017-02-10 14:42:58 --> Config file loaded: /data/webapp/bk_cmdb/application/config/errorcode.php
INFO - 2017-02-10 14:42:58 --> Session: Class initialized using 'files' driver.
DEBUG - 2017-02-10 14:42:58 --> Session class already loaded. Second attempt ignored.
DEBUG - 2017-02-10 14:42:58 --> Session class already loaded. Second attempt ignored.
INFO - 2017-02-10 14:42:58 --> Controller Class Initialized
INFO - 2017-02-10 14:42:58 --> Parser Class Initialized
INFO - 2017-02-10 14:42:58 --> Language file loaded: language/english/zh_cn_lang.php
DEBUG - 2017-02-10 14:42:58 --> Login class already loaded. Second attempt ignored.
DEBUG - 2017-02-10 14:42:58 --> Encryption: Auto-configured driver 'openssl'.
INFO - 2017-02-10 14:42:58 --> Encryption: OpenSSL initialized with method AES-128-CBC.
INFO - 2017-02-10 14:42:58 --> Encryption Class Initialized
INFO - 2017-02-10 14:42:58 --> Database Driver Class Initialized
DEBUG - 2017-02-10 14:42:58 --> Encryption class already loaded. Second attempt ignored.
DEBUG - 2017-02-10 14:42:58 --> Login class already loaded. Second attempt ignored.
DEBUG - 2017-02-10 14:42:58 --> Login class already loaded. Second attempt ignored.
INFO - 2017-02-10 14:42:58 --> File loaded: /data/webapp/bk_cmdb/application/views/account/index.php
INFO - 2017-02-10 14:42:58 --> File loaded: /data/webapp/bk_cmdb/application/views/layout.php
INFO - 2017-02-10 14:42:58 --> Final output sent to browser
DEBUG - 2017-02-10 14:42:58 --> Total execution time: 0.0944

**Comment by lowenitt** [comment]
尝试更新下版本吧
