### ISSUE TITLE
cmdb自定义模型导出报错500

### ISSUE THREAD

**Issue by japlee** [Tencent/bk-cmdb#1914]
问题描述
===========
v3.3的分支编译打包后运行，发现自定义的模型导出时报错500，
然后会导致在import模型实例时也会报同样的错误

其他的内置模型导出是正常的，如交换机，路由器

重现方法
================

1. 新建模型分组，创建一个自定义模型，然后点模型上的导出，就会报错500

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志：
webserver
I0315 17:11:58.926826   25757 logics/object.go:38] [apimachinary][peek] POST http://10.3.10.210:8080/api/v3/object/search/batch with body {"condition":["test"],"metadata":{"label":null}}, response {"result":false,"bk_error_code":1101016,"bk_error_msg":"'test' 参数无效或不存在","data":null}, rid:
E0315 17:11:58.926923   25757 service/object.go:242] 'test' 参数无效或不存在

操作了其他的内置模型，如交换机，路由器，导出模型和自定义模型进行比较，发现在toposerver的日志记录中：
调用同样的api：POST http://10.3.10.210:50009/api/v3/read/model with body
 {"fields":null,"limit":{"start":0,"limit":0},"sort":null,"condition":{"bk_obj_id":"bk_router","metadata.label.bk_biz_id":{"$exists":false}}}
内置的模型是有数据data info返回的"data":{"count":1,"info" XXX
但是自定义模型data info是null："data":{"count":0,"info":null}}
mongo数据库中是有模型数据的

**Comment by breezelxp** [comment]
问题已经修复
