### ISSUE TITLE
主机变更记录，变更前和变更后的数据相同，都是修改后的数据

### ISSUE THREAD

**Issue by vlon** [Tencent/bk-cmdb#1921]
问题描述
===========

主机变更记录，变更前和变更后的数据相同，都是修改后的数据
![image](https://user-images.githubusercontent.com/29192868/54576769-6a149780-4a34-11e9-8560-fe8424587efb.png)

重现方法
================

修改主机实例，查看变更记录

关键信息
=========

请提供以下信息:
Branch: v3.2.x，master，企业版2.14
 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@rentiansheng 这个是不是已经修复了？

**Comment by rentiansheng** [comment]
已经修复，在最新的v3.2.v
