### ISSUE TITLE
主机及模型关联查询

### ISSUE THREAD

**Issue by rentiansheng** [Tencent/bk-cmdb#194]
需求描述
===========

1. 主机需要通过直接关联的实例属性查询
    耗时预估:1.5天
2. 普通模型管理属性查询
    普通模型关联查询，根据关联的属性做查询。
    耗时预估:1.5天
@techfindd  补充下

**Comment by techfindd** [comment]
Duplicate of #170

**Comment by uriwang** [comment]
模型实例关联改动方案：
1. 增加关联关系表，表中包含四个字段（实例id，实例模型id，被关联实例id，被关联实例模型id）；
2. 创建实例的时候输入参数不变，但是后台需要增加自动识别输入的字段中关联字段的，并提取数据自动将数据写入关联表；
3. 实例数据查询结构调整，输入参数：
   ``` json
   {
    "page":{
        "start":0,
        "limit":10,
        "sort":"字段"
       },
       "condition":{
                 "模型id":{
                    "field":"字段id",
                    "operator":"",
                    "value":“字段取值”
                }
       },
      "fileds":{
                 "模型id":["字段"]
       }
   }
  ```

**Comment by uriwang** [comment]
已完成部分：
1. 关联表的创建；
2. 在原有的增、删、更新的api内增加维护关联表的逻辑；

**Comment by uriwang** [comment]
已经实现关联查询api。
https://github.com/Tencent/bk-cmdb/blob/master/docs/apidoc/object_common_inst.md

**Comment by uriwang** [comment]
初始化需要增加：
cc_InstAsst 表，表结构如下：
// InstAsst an association definition between instances.
type InstAsst struct {
	ID           int64  `bson:"id" json:"id"`   // 记录标识
	InstID       int64  `bson:"bk_inst_id" json:"bk_inst_id"`  // 关联实例的实例id
	ObjectID     string `bson:"bk_obj_id" json:"bk_obj_id"`  // 关联实例的模型标识 bk_obj_id 的取值
	AsstInstID   int64  `bson:"bk_asst_inst_id" json:"bk_asst_inst_id"` // 被关联实例的实例id
	AsstObjectID string `bson:"bk_asst_obj_id" json:"bk_asst_obj_id"` // 被关联实例的模型标识 bk_obj_id的取值
}

如果初始化的时候有对某些实例设置关联，需要保持原有写入数据方式不便的情况下，增加在此表中写入关联关系。
（调用 场景层api 创建实例会自动处理）

@wusendong
