### ISSUE TITLE
3.2.X前端文字调整

### ISSUE THREAD

**Issue by lampardtang** [Tencent/bk-cmdb#1942]
![image](https://user-images.githubusercontent.com/39146216/54978839-622c9880-4fdc-11e9-890d-92ab4f4e95aa.png)

事件推送页面调整：
“新增推送”按钮和上面的一句话去掉
换成：事件推送功能能够实现当配置信息发生变化的时候，实时通知到关联的系统中，目前支持 http 的推送方式

跟“动态分组”页面一样
![image](https://user-images.githubusercontent.com/39146216/54978879-87210b80-4fdc-11e9-9134-0bf5a0498c37.png)

**Comment by Thinkzhuo** [comment]
前端代码ui 调试有什么好的平台、工具，谢谢。

**Comment by joe511230** [comment]
> 前端代码ui 调试有什么好的平台、工具，谢谢。

前端是vue全家桶开发的，前端使用dev模式启动，chrome结合vue-devtools插件调试即可，无前端经验的话还请自行了解具体细节
