### ISSUE TITLE
优化批量创建实例接口返回

### ISSUE THREAD

**Issue by xinxin01234** [Tencent/bk-cmdb#1964]
问题描述
===========
v3.1.0 版本中的批量创建实例的接口返回有两个问题：
1. 没有返回新建实例的id
2. 接口中不传 `input_type: "excel"` 时，返回正确，但是实例没添加进去

重现方法
================
发送请求体：
{
	"BatchInfo":{
	   "1":{
	      "bk_inst_name": "api添加核心交换机9"
	    },
	    "2":{
	      "bk_inst_name": "api添加核心交换机10"
	    }
	}
}
返回结果：
{
  "result": true,
  "bk_error_code": 0,
  "bk_error_msg": "success",
  "data": {
    "error": null,
    "success": null,
    "update_error": null
  }
}
实际数据没有添加成功，但返回结果是正确的

关键信息
=========
•	API POST /api/v3/inst/0/{bk_obj_id}

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by hoffermei** [comment]
重现方法：
```
curl --request POST \
  --url http://127.0.0.1:8083/api/v3/inst/0/aaa \
  --header 'content-type: application/json' \
  --cookie 'blueking_language=zh-cn; HTTP_BLUEKING_SUPPLIER_ID=0' \
  --data '{
  "BatchInfo": {
    "5": {
      "bk_inst_name": "api添加核心交换机9"
    },
    "6": {
      "bk_inst_name": "api添加核心交换机10"
    }
  },
	"input_type": "excel"
}'
```

**Comment by hoffermei** [comment]
## 优化后接口返回：
- 正确请求
```
curl --request POST \
  --url http://127.0.0.1:8083/api/v3/inst/0/aaa \
  --header 'content-type: application/json' \
  --cookie 'blueking_language=zh-cn; HTTP_BLUEKING_SUPPLIER_ID=0' \
  --data '{
  "BatchInfo": {
    "5": {
      "bk_inst_name": "api添加核心交换机9"
    },
    "6": {
      "bk_inst_name": "api添加核心交换机10"
    }
  },
	"input_type": "excel"
}'
```
- input_type 参数无效
```
{
  "result": false,
  "bk_error_code": -1,
  "bk_error_msg": "unexpected input_type: ",
  "data": null
}
```
