### ISSUE TITLE
模型自关联

### ISSUE THREAD

**Issue by uriwang** [Tencent/bk-cmdb#198]
几个特殊的模型不能够被关联或者自我关联：
1. 主干之上的模型（包含后期自定义创建的），具体是：集群、模块
2. 进程

但是他们可以关联其他模型

**Comment by uriwang** [comment]
评估结果如下：

需要做以下这些事情：
1. 普通模型自关联没有限制，暂时不需要调整；
2. 主线模型需要增加限制自关联逻辑的代码；
3. 需要跟前端联调、并处理联调中出现的问题；
4. 主线模型需要实现禁止被关联的逻辑；
——————
预计时间花费：
1. 修改代码+自测时间：2~3小时
2. 预留与前端联调测试时间：0.5天

预计总花费时间预估：0.5~1天


@techfindd  有待最后排期讨论

**Comment by hustcr** [comment]
@uriwang 更新一下排期信息吧

**Comment by uriwang** [comment]
@hustcr @techfindd 当前无排期
