### ISSUE TITLE
【建议】日志中打印redis等明文密码 不安全

### ISSUE THREAD

**Issue by Thinkzhuo** [Tencent/bk-cmdb#1986]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@Thinkzhuo 建议非常好，我们调整下。

**Comment by breezelxp** [comment]
@hoffermei 看下这个，调整下。
