### ISSUE TITLE
查询实例的接口存在问题

### ISSUE THREAD

**Issue by xinxin01234** [Tencent/bk-cmdb#1997]
问题描述
===========
Method: http.MethodPost, Path: "/inst/search/owner/{owner_id}/object/{obj_id}", HandlerFunc: s.SearchInstByObject
这个接口返回的交换机数量不对，实际上只有四个，但是返回了23个

Path: "/inst/association/search/owner/{owner_id}/object/{obj_id}", HandlerFunc: s.SearchInstByAssociation
3.1.0版本的这个接口返回的信息是正确的，但是在高版本中这个接口已经被下线了

重现方法
================
请求：/api/v3/inst/search/owner/0/object/core_switch
消息体：{
  "bk_supplier_account":"0",
"page":{
        "start":0,
        "limit":10,
        "sort":"-bk_inst_id"
    },
    "fields":[]
}
返回结果：
{
    "result":true,
    "bk_error_code":0,
    "bk_error_msg":"success",
    "data":{
        "count":23,
        "info":[
            Object{...},
            Object{...},
            Object{...},
            Object{...},
            Object{...},
            Object{...},
            Object{...},
            Object{...},
            Object{...},
            Object{...}
        ]
    }
}

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@xinxin01234 请提供下你使用的版本，谢谢。

**Comment by breezelxp** [comment]
@wusendong 关注下。

**Comment by xinxin01234** [comment]
@wusendong 使用的版本是3.1.0

**Comment by xinxin01234** [comment]
@wusendong 上述问题我又重新测试了下，该方法在post请求体的加上condition条件，如下"condition":{
  "bk_obj_id":"core_switch"
}，就可以搜出core_switch模型下的实例了，但是接口path中“/inst/search/owner/{owner_id}/object/{obj_id}”仍然需要带着{obj_id}。期望修改结果：path中去掉{obj_id}
