### ISSUE TITLE
期望产品文档区分版本号，尤其是接口文档

### ISSUE THREAD

**Issue by xinxin01234** [Tencent/bk-cmdb#1998]
问题描述
===========

重现方法
================
期望产品文档区分版本号，还有就是最好能兼容。背景：在3.10中看到的一个接口，在最新的产品文档中已被取消，这样如果版本升级，已完成的接口就不能再使用

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@xinxin01234 
这个已经在做了，在下个大版本里就会有，请关注。
