### ISSUE TITLE
导入数据报错-ERROR 1046 (3D000) at line 1: No database selected

### ISSUE THREAD

**Issue by Jun2013** [Tencent/bk-cmdb#20]
环境说明：
Centos7.2

1）已经安装完了nginx 和php，且通过编译安装
[root@salt local]# ll
total 4
drwxr-xr-x. 2 root root    6 Aug 12  2015 bin
drwxr-xr-x. 2 root root    6 Aug 12  2015 etc
drwxr-xr-x. 2 root root    6 Aug 12  2015 games
drwxr-xr-x. 2 root root    6 Aug 12  2015 include
drwxr-xr-x. 2 root root    6 Aug 12  2015 lib
drwxr-xr-x. 2 root root    6 Aug 12  2015 lib64
drwxr-xr-x. 2 root root    6 Aug 12  2015 libexec
drwxr-xr-x  6 root root   61 Dec 26 20:03 **nginx**
drwxr-xr-x  9 root root   81 Dec 26 13:35 php
drwxr-xr-x. 2 root root    6 Aug 12  2015 sbin
drwxr-xr-x. 5 root root   46 Dec 20 16:45 share
drwxr-xr-x. 4 root root 4096 Dec 26 19:54 src
[root@salt local]# 
nginx 可以正常访问，

2.数据库设置：
MariaDB [(none)]> create database cmdb;

MariaDB [(none)]> grant all privileges on cmdb.* to root@localhost identified by ‘123456‘;
MariaDB [(none)]> flush privileges;
以上命令都正常

3.导入数据库报错：

[root@salt bk-cmdb]# pwd
/opt/bk-cmdb

[root@salt bk-cmdb]# mysql -u root -p123456 < bk-cmdb.sql
Enter password: 
ERROR 1046 (3D000) at line 1: No database selected
[root@salt bk-cmdb]#

可否告知如何fix it

**Comment by shpdnkti** [comment]
你没选择数据库啊，怎么导入呢~

**Comment by lowenitt** [comment]
use cmdb之后再导入数据
