### ISSUE TITLE
cmd_adminserver无法连接云数据库（Mongodb）

### ISSUE THREAD

**Issue by Thinkzhuo** [Tencent/bk-cmdb#2007]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
具体报什么错？

**Comment by Thinkzhuo** [comment]
connect mongo server failed no reachable servers，我看了mongodb client的代码，没有配置 passwordDigestor: "server” 参数，云数据库创建用户时必须添加passwordDigestor: "server” 配置项。不知两者有没有直接关系？

**Comment by breezelxp** [comment]
我们没有你的环境，你如果熟悉go，可以自己修改配置后测试下是不是你提到的原因，然后反馈给我们。

**Comment by ToukitsuLin** [comment]
腾讯云mongoDb服务连接的时候需要使用admin库鉴权。直接连接应用的库是连不上的。这个有什么配置可以解决吗？用客户端连接的话 需要添加authenticationDataBase 这个参数指定鉴权的库。但是生成配置的时候好像没有这个参数。
