### ISSUE TITLE
交流帖

### ISSUE THREAD

**Issue by grunmin** [Tencent/bk-cmdb#201]
之前有关注2.0版本, 最近看到更新到了3.0, 赞!
发现3.0的实现跟我们的有一些共同之处, 可以一起交流下

放俩截图
![image](https://user-images.githubusercontent.com/4323398/38793959-db2574c0-4185-11e8-915b-405a33a6be1a.png)

![image](https://user-images.githubusercontent.com/4323398/38794116-8f2c5fb0-4186-11e8-93a4-638f4255e541.png)

**Comment by hustcr** [comment]
赞~ @techfindd

**Comment by lowenitt** [comment]
您好：
关于产品方面的交流可以直接在issue下面回复或者加入
![image](https://user-images.githubusercontent.com/14356794/39856283-cdebb2da-5461-11e8-9f74-5a50feabef38.png)
配置平台开源群，我们有第一时间回复
