### ISSUE TITLE
独立部署cmdb,指定蓝鲸paas平台地址， 用户体系没有生效

### ISSUE THREAD

**Issue by makerwei** [Tencent/bk-cmdb#2060]
问题描述
===========
在独立部署了开源cmdb时，生成配置文件时指定了blueking_cmdb_url=http://cmdb.test.cn 和blueking_paas_url=paas.test.cn
服务启动后，也能跳转到登录页面，也能登录成功，但是登录成功后，用户还是admin,并不是我的登录用户

重现方法
================
如上

关键信息
=========

Version  : v3.2.2
Tag      : release-v3.2.2
Branch   : v3.2.x
BuildTime: 2019-02-19T16:48:43+0800
GitHash  : 3185b32956a6e59df1ee0744c6edf72e09828778
RunMode  : product

**Comment by hackeryard** [comment]
你好，我也遇到类似的问题，想问下单机版cmdb要配置paas，只需要部署paas，然后init.py的时候，加上blueking_paas_url吗

我部署paas之后，发现登录成功后跳回cmdb，发出了500错误，所以问下是否还有其他需要配置的？

**Comment by makerwei** [comment]
@hackeryard 我没有发生500，可以正常登录，只是不管用什么用户登录，进入cmdb后还是admin用户，目前还不知道什么原因。

**Comment by wusendong** [comment]
> @hackeryard 我没有发生500，可以正常登录，只是不管用什么用户登录，进入cmdb后还是admin用户，目前还不知道什么原因。

webserver的配置文件里需要把skip改为0，否则登录不会启用

**Comment by makerwei** [comment]
@wusendong  我把cmdb/cmdb_adminserver/configures/webserver.conf 中的skip改为0后，重启服务，登录后还是显示的admin，还要做什么操作吗？

**Comment by hackeryard** [comment]
@wusendong 你好，skip=0之前设置过了，就是跳转回cmdb界面的时候，500了。
webserver的INFO日志如下：
![image](https://user-images.githubusercontent.com/24410509/56402429-d5e65c00-628f-11e9-98d0-80908c6fcc1e.png)

**Comment by makerwei** [comment]
@hackeryard 我可以了 
![image](https://user-images.githubusercontent.com/43264876/56403626-c7e70a00-6294-11e9-97dc-7c53723bbb7c.png)这 个参数你写对没

**Comment by hackeryard** [comment]
@makerwei 我安装的默认是cc，另外paas我安装的是社区版本（release的），我试试这个配置
![image](https://user-images.githubusercontent.com/24410509/56404320-94a67a00-6298-11e9-9112-6307efb65040.png)

**Comment by hackeryard** [comment]
@makerwei 现在拿bk_token去访问paas的用户信息没有问题(比如/userinfo,/user/list)，就是跳转回cmdb首页500了

**Comment by makerwei** [comment]
@hackeryard 那我也不清楚了，我直接用的官方编译好的cmdb.

**Comment by hackeryard** [comment]
@makerwei 感谢，马上去试试这个release，之前是自己编译的

**Comment by hackeryard** [comment]
@makerwei 这个release的确能适配上，但是权限分配有问题，比如我分配了普通用户runking所有的系统权限，然后以防万一，在业务权限的每个角色都分配了所有的权限：
![image](https://user-images.githubusercontent.com/24410509/56409629-85c9c280-62ac-11e9-8718-299782da18f5.png)
注销admin后重新登录runking，还是对业务无操作权：
![image](https://user-images.githubusercontent.com/24410509/56409647-a003a080-62ac-11e9-84d7-e905da25ae5a.png)

**Comment by hackeryard** [comment]
@makerwei @wusendong  可以了 感觉权限更新有滞后。感谢你们的帮助。
