### ISSUE TITLE
CMDB录入时间字段导出空白

### ISSUE THREAD

**Issue by jsksnick** [Tencent/bk-cmdb#2073]
问题描述
===========
蓝鲸2.0升级2.2.9后，模型数据导出后录入时间出现k空白
![image](https://user-images.githubusercontent.com/17331795/55792585-8ebfd480-5af3-11e9-93b9-d0c8be94ddfe.png)
![image](https://user-images.githubusercontent.com/17331795/55792604-954e4c00-5af3-11e9-9be9-328703fd1599.png)

关键信息
=========

请提供以下信息:

bk-cmdb   版本: 3.2.6

**Comment by rentiansheng** [comment]
主机的创建时间是不到出的。 我在cmdb 3.2.6版本中 为发现该问题。
