### ISSUE TITLE
模型关联中唯一标识不一致

### ISSUE THREAD

**Issue by jsksnick** [Tencent/bk-cmdb#2078]
问题描述
===========
蓝鲸2.0升级到2.2.9后，模型关联中唯一标识显示异常，不一致
![image](https://user-images.githubusercontent.com/17331795/55796356-6ab4c100-5afc-11e9-937c-6c4ca9400693.png)

重现方法
================

关键信息
=========
bk-cmdb   版本: 3.2.6

**Comment by xiexianbin** [comment]
修复脚本：

```
db.getCollection('cc_ObjAsst').find({'id': {$gt:1}}).forEach(
    function(item){  
        db.getCollection('cc_ObjAsst').update(
          {"_id": item._id},
          {$set: {'bk_obj_asst_id': item.bk_obj_id + '_' + item.bk_asst_id + '_' + item.bk_asst_obj_id}})
    }
)
```

**Comment by wusendong** [comment]
用 @xiexianbin 的脚本时可行的，也可以用最新的v3.2.x分支编译后重新从老版本升级上来
