### ISSUE TITLE
【help】重新写的中间件，如何加入到login登录验证中

### ISSUE THREAD

**Issue by Thinkzhuo** [Tencent/bk-cmdb#2097]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by rentiansheng** [comment]
https://github.com/Tencent/bk-cmdb/issues/1091  登录的扩展 可以参照这个代码。第三方登录 需要编译成so

**Comment by Thinkzhuo** [comment]
如果基于现有的改造，只想加入对固定url的过滤器呢？

**Comment by rentiansheng** [comment]
https://github.com/Tencent/bk-cmdb/blob/master/src/web_server/service/service.go#L46

**Comment by Thinkzhuo** [comment]
已实现 感谢
