### ISSUE TITLE
master分支的badge中版本号和version.md不一致

### ISSUE THREAD

**Issue by pagezhou** [Tencent/bk-cmdb#2098]
问题描述
===========
master分支badge版本号是3.1.2，version.md是3.2.2
![image](https://user-images.githubusercontent.com/8849151/55927335-44e80300-5c47-11e9-9405-ecca326a5977.png)

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 <!-- 示例： ./cmdb/cmdb-apiserver --version 输出的内容:
Version  : V3.3.2
Branch   : master

**Comment by breezelxp** [comment]
已经更新
