### ISSUE TITLE
ubuntu编译cmdb出错

### ISSUE THREAD

**Issue by makerwei** [Tencent/bk-cmdb#2099]
问题描述
===========
在ubuntu里面编译cmdb报错
![image](https://user-images.githubusercontent.com/43264876/55936371-b71d0f80-5c68-11e9-9a15-b26a95bf318e.png)

重现方法
================

关键信息
=========

golang版本：go version go1.12 linux/amd64

go env
GOARCH="386"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/bobwei/workplace"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
GO386="sse2"
CC="gcc"
CXX="g++"
CGO_ENABLED="0"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m32 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build206649137=/tmp/go-build -gno-record-gcc-switches"

 - [ ] 操作系统      :

**Comment by rentiansheng** [comment]
你的系统是32bit 吗？

**Comment by makerwei** [comment]
x86_64   的

**Comment by rentiansheng** [comment]
你这个是硬件架构。 你安装的ubuntu 是什么版本。 这个是提示是int 类型值溢出了

**Comment by makerwei** [comment]
@rentiansheng 
Ubuntu 7.3.0-16ubuntu3
代码里面是这样写的。
![image](https://user-images.githubusercontent.com/43264876/55943556-619d2e80-5c79-11e9-93b7-1b1dfe581c76.png)

**Comment by rentiansheng** [comment]
GOARCH="386" 这个显示的看应该是32bit， 你执行下 uname -a

**Comment by makerwei** [comment]
@rentiansheng 
![image](https://user-images.githubusercontent.com/43264876/55943835-ebe59280-5c79-11e9-87a0-08be75ec9dda.png)

**Comment by rentiansheng** [comment]
@makerwei   https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63 

从goarch 你的编译目标的二进制是32bit的。 修改你的goarch 到64
![image](https://user-images.githubusercontent.com/3955934/55944200-b0979380-5c7a-11e9-8ffd-3d6b6765cb76.png)

**Comment by makerwei** [comment]
@rentiansheng 可以了，我把环境变量设置错了，非常感谢大佬耐心的回答。
