### ISSUE TITLE
config.php 配置时区要区分大小写

### ISSUE THREAD

**Issue by gavindev** [Tencent/bk-cmdb#21]
###错误位置：
>application/config/config.php line +33
$config['time_zone']=date_default_timezone_set('Asia/shanghai');

###设置Asia/shanghai在Linux下报错 
>Severity: Notice --> date_default_timezone_set(): Timezone ID 'Asia/shanghai' is invalid 

###需要改为首字母大写：
> 'Asia/Shanghai'

**Comment by lowenitt** [comment]
好的，如果有建议，可以给我们提代码合并请求
