### ISSUE TITLE
无法重复导入数据，导入报错

### ISSUE THREAD

**Issue by zqzqy04** [Tencent/bk-cmdb#2100]
问题描述
===========

已经存在的主机列表，当修改某个字段信息后重新导入报错，只要IP存在导入就失败。
把原有的数据导出，然后直接导入也报错
报错如下：
![image](https://user-images.githubusercontent.com/48232141/55943232-c99f4500-5c78-11e9-812e-75189b2d9898.png)

重现方法
================

1、把数据导出，再直接导入，报错
2、只要IP已经存在，再次导入后便会导入失败

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@zqzqy04 版本？

**Comment by rentiansheng** [comment]
你这个event server服务启动吗？

**Comment by zqzqy04** [comment]
是启动状态的






在 2019-04-11 16:44:29，"rentiansheng" <notifications@github.com> 写道：


你这个event server服务启动吗？

**Comment by rentiansheng** [comment]
看下的hostserver 的日志。

**Comment by zqzqy04** [comment]
能否只QQ沟通





在 2019-04-12 09:40:49，"rentiansheng" <notifications@github.com> 写道：


看下的hostserver 的日志。

**Comment by zqzqy04** [comment]
warning日志


W0314 07:57:47.243912     183 hostsearch.go:430] hostSearch not found module id, moduleID:64, hostModuleMap:map[], rid:cc0000bi50iurqbt6g0o1a7su0



error 日志：
E0412 02:16:27.962914     173 host.go:267] add host failed, succ: [], update: [4行10.156.1.10更新失败<nil>, 推送事件失败], err: 导入主机出现错误, []



在 2019-04-12 09:40:49，"rentiansheng" <notifications@github.com> 写道：


看下的hostserver 的日志。
