### ISSUE TITLE
业务级模型无法将唯一约束字段删除

### ISSUE THREAD

**Issue by hoffermei** [Tencent/bk-cmdb#2106]
问题描述
===========
业务级模型无法将唯一约束字段删除

![image](https://user-images.githubusercontent.com/13761028/55964403-3a5d5600-5ca7-11e9-9845-5d22820d0bf7.png)

关键信息
=========
 - [x] bk-cmdb   版本: v3.4.x

**Comment by hoffermei** [comment]
问题原因：
- 前端通过 DELETE /api/v3/delete/objectunique/object/test10/unique/16，没有请求body
- 后端通过请求参数没有发现metadata信息，于是限制删除范围是公共model，这样就没找到了

**Comment by hoffermei** [comment]
修复方案：
1. 方案一，让前端提供metadata信息，好处修复快，缺点以后所有的接口调用都要求提供对应的业务信息
2. 方案二，自动根据unique id计算出业务信息，优点：用户不用单独提供业务信息，缺点：实现成本高，需要考虑到历史数据缺失业务id信息问题

目前方案：前端提供metadata信息。 @joe511230 帮忙处理下这个问题

**Comment by joe511230** [comment]
DELETE默认不带body体，如需支持，需后端实现
