### ISSUE TITLE
feature-v3.4.x mapstr panic 问题

### ISSUE THREAD

**Issue by rentiansheng** [Tencent/bk-cmdb#2154]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本:  v3.4.x
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by hoffermei** [comment]
最近又遇到类似的mapstr异常问题

![image](https://user-images.githubusercontent.com/13761028/56561448-bd50ab80-65d9-11e9-8677-54b3612c9371.png)

- 请求地址 `/api/v3/topo/privilege/group/detail/0/biumtf6v50u4ahgnbs6g`

```
{
  "model_config": {
    "bk_network": {
      "bk_switch": [
        "search",
        "update",
        "delete"
      ]
    }
  }
}
```

- 返回内容

```
{
  "result": false,
  "bk_error_code": 1199011,
  "bk_error_msg": "not support data type. field name: ModelConfig",
  "data": null
}
```

**Comment by rentiansheng** [comment]
这个本来就是用来处理。不支持的类型直接报错的

**Comment by hoffer32** [comment]
mapstr 变动导致的问题，还是保存权限配置一直就有问题呢

**Comment by rentiansheng** [comment]
这个是遗留问题。之前这个位置是直接panic了。我现在改成返回错误了
