### ISSUE TITLE
【help】网络拓扑可拖拽构建 需要掌握什么技术

### ISSUE THREAD

**Issue by Thinkzhuo** [Tencent/bk-cmdb#2156]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@Thinkzhuo 你是说前端？还是后台？

**Comment by Thinkzhuo** [comment]
前端 用的什么插件呢
