### ISSUE TITLE
实例单关联字段存储格式不统一

### ISSUE THREAD

**Issue by xinxin01234** [Tencent/bk-cmdb#2165]
问题描述
===========
业务场景描述：有园区和交换机两个模型，然后交换机模型单关联到了园区上。
操作描述：通过api接口创建园区下的一台交换机，然后查询这个园区下的交换机时可以查出来(通
                 过园区的那个单关联，比如园区的bk_inst_id是162，通过162可以查出来)；然后在蓝鲸
                界面上解绑了该园区，随后又重新关联上，然后再查询园区下的交换机就查不出来了，
                但是改变condition条件由162改成"162"后又可以查出来了。
存在的问题：交换机的园区关联那个属性中应该存放园区的bk_inst_id，也就是int 162，但是通过
                     蓝鲸界面操作后，那个属性中把162的类型变成了字符型“162”，导致查询失败

重现方法
================
通过api接口创建交换机后第一次查询：
url：/api/v3/inst/search/owner/0/object/access_switch  
body：{
"bk_supplier_account":"0",
"page":{
"start":0,
"limit":0,
"sort":"-bk_inst_id"
},
"fields":[],
"condition":{
        "bk_obj_id":"access_switch",
        "park_id":162
}
}
结果：
{
    "result":true,
    "bk_error_code":0,
    "bk_error_msg":"success",
    "data":{
        "count":2,
        "info":Array[2]
    }
}
在蓝鲸界面上删除某台交换机的园区关联，然后再次重新关联该园区后：
url：/api/v3/inst/search/owner/0/object/access_switch  
body：{
"bk_supplier_account":"0",
"page":{
"start":0,
"limit":0,
"sort":"-bk_inst_id"
},
"fields":[],
"condition":{
        "bk_obj_id":"access_switch",
        "park_id":162
}
}
结果：
{
    "result":true,
    "bk_error_code":0,
    "bk_error_msg":"success",
    "data":{
        "count":1,
        "info":Array[1]
    }
}

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: cmdb 3.1.0

 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by hoffermei** [comment]
## 重现方法
- 如下图所示 `xx` 字段是一个由 `weblogic` 到 `apache` 的单关联
- 通过前端页面进行实例关联，点击关联时请求格式如下，可以看出 xx 字段传递的值是字符串
  - `curl 'http://127.0.0.1:8083/api/v3/inst/0/bk_weblogic/8' -X PUT --data-binary '{"xx":"10"}'`

- 将上述`xx`字段的值改成整形10，发现请求可以同样成功
  - `curl 'http://127.0.0.1:8083/api/v3/inst/0/bk_weblogic/8' -X PUT --data-binary '{"xx":10}'`

- 但是两次操作前后mongodb中存储的xx字段类型发生了变化，前者是字符串，后者是整形

![image](https://user-images.githubusercontent.com/13761028/56886142-d73e3280-6aa0-11e9-96c2-30a6d1c98cd0.png)

![image](https://user-images.githubusercontent.com/13761028/56886360-6fd4b280-6aa1-11e9-8334-34bda4da22b6.png)
