### ISSUE TITLE
实例查询没有按path参数指定的类型过滤

### ISSUE THREAD

**Issue by xinxin01234** [Tencent/bk-cmdb#2166]
问题描述
===========
业务场景描述：有两类模型接入交换机模型和核心交换机模型，然后需要通过查询方法查出接入
                         交换机模型下的实例，查询方式是通过path /api/v3/inst/search/owner/0/object/{bk_obj_id}，然后如下设置condition：
                         "condition":{
                                  "bk_obj_id":"access_switch"
                          }
存在的问题：path中的{bk_obj_id}没有实际存在作用，即使设置bk_obj_id为核心交换机模型id如
                      core_switch，上述方式仍然能查询出接入交换机的实例，但是path中的{bk_obj_id}
                     这个内容又不能去掉，必须填上蓝鲸模型中已经存在的任意模型id

期待结果：重新修正查询path /api/v3/inst/search/owner/0/object/{bk_obj_id}的写法

重现方法
================
url地址：
/api/v3/inst/search/owner/0/object/core_switch
body消息体：
{
"bk_supplier_account":"0",
"page":{
"start":0,
"limit":0,
"sort":"-bk_inst_id"
},
"fields":[],
"condition":{
        "bk_obj_id":"access_switch"
}
}
查询结果：
{
    "result":true,
    "bk_error_code":0,
    "bk_error_msg":"success",
    "data":{
        "count":3,
        "info":[
            Object{...},
            Object{...},
            Object{...}
        ]
    }
}

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: cmdb 3.1.0版本

**Comment by breezelxp** [comment]
@xinxin01234 你好，由于版本迭代的原因，这个v3.1.0分支的版本不会继续再发，修复的问题，环境更新还请您自行编译。

另外，如果可以，欢迎您使用最新的release版本，release见这里：
https://github.com/Tencent/bk-cmdb/releases

**Comment by breezelxp** [comment]
由于此问题已经修复，将关闭此issue,如有需要您可重新打开此issue。
