### ISSUE TITLE
利用imge.sh自己构建镜像，需要指定一个base image，这个base image可以是centos7或者Ubuntu16.04吗？

### ISSUE THREAD

**Issue by zengqingfu1442** [Tencent/bk-cmdb#2175]
问题描述
===========

利用imge.sh自己构建镜像，需要指定一个base image，这个base image可以是centos7或者Ubuntu16.04吗？

**Comment by hoffermei** [comment]
可以

**Comment by zengqingfu1442** [comment]
那然后怎么样把构建的多个镜像合成一个镜像呢？

**Comment by hoffermei** [comment]
为啥要合成一个镜像呢，如果真要这么干，可以把 dockerfile 的步骤合并起来

**Comment by zengqingfu1442** [comment]
合成一个镜像就可以只运行一个容器就能把真个系统运行起来了，就像这里介绍的一样：https://github.com/Tencent/bk-cmdb/blob/master/docs/wiki/container-support.md

**Comment by hoffermei** [comment]
这个dockerfile好像不行，你可以自己写个dockerfile把centos上编译好的二进制和配置文件拷贝到镜像里面打成一个新的镜像
