### ISSUE TITLE
开源的蓝鲸跟社区版的蓝鲸智云有较大区别吗？

### ISSUE THREAD

**Issue by zengqingfu1442** [Tencent/bk-cmdb#2187]
问题描述
===========

开源的蓝鲸跟社区版的蓝鲸智云有较大区别吗？

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@zengqingfu1442 没有太大区别。
