### ISSUE TITLE
上传xlsx文件，提示文件内容不能为空。我上传的是按照下载下来的template_host写的

### ISSUE THREAD

**Issue by zengqingfu1442** [Tencent/bk-cmdb#2188]
问题描述
===========

上传xlsx文件，提示文件内容不能为空。我上传的是按照下载下来的template_host写的。
如下：
我的Linux虚机 | 10.10.14.34 | NA | david.zeng | david.zeng | 43 | SN2344 | 3 | High | 北京 | China | Beijing | Chinanet | centos7-6 | linux | centos7-6 | centos7.6 | 64 | 4 | 2500MHz | Intel | 8GB | 100GB | 52:54:00:76:13:0e | NA | 20190420 | 手工

**Comment by hoffermei** [comment]
请提供CMDB版本信息，如果方便的话把xlsx文件也提供下

**Comment by zengqingfu1442** [comment]
就是https://github.com/Tencent/bk-cmdb/blob/master/docs/wiki/container-support.md这个，用容器爬起来的，直接下载template_host.xlsx后，只填写一个内网IP地址，然后上传上去，就报上面说的这个错误。
