### ISSUE TITLE
操作审计页面，左边栏点开时，查询按钮被覆盖

### ISSUE THREAD

**Issue by toddyhan** [Tencent/bk-cmdb#2190]
问题描述
===========
操作审计页面，左边栏点开时，查询按钮被覆盖

重现方法
================

![image](https://user-images.githubusercontent.com/7975419/56466780-a75fb100-6448-11e9-9e66-a65b107f39aa.png)

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
```bash
# docker images
REPOSITORY                                     TAG                 IMAGE ID            CREATED             SIZE
ccr.ccs.tencentyun.com/bk.io/cmdb-standalone   latest              7430bd1d9f16        2 months ago        1.67GB

```

**Comment by joe511230** [comment]
小于最低宽度，注意下方横向滚动条。

**Comment by toddyhan** [comment]
提这个issue的原因是老版本里面（V3.0.8）是自动伸缩，而不是直接右移。个人觉得自动伸缩易用性稍微高些。
