### ISSUE TITLE
新增模型字段，看不到保存按钮

### ISSUE THREAD

**Issue by toddyhan** [Tencent/bk-cmdb#2191]
问题描述
===========
新增模型字段，看不到保存按钮。也无法上下拖动查看。

重现方法
================

![image](https://user-images.githubusercontent.com/7975419/56467144-a1b89a00-644d-11e9-9f14-c66d24afb9dc.png)

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 ```bash
# docker images
REPOSITORY                                     TAG                 IMAGE ID            CREATED             SIZE
ccr.ccs.tencentyun.com/bk.io/cmdb-standalone   latest              7430bd1d9f16        2 months ago        1.67GB
```

**Comment by joe511230** [comment]
后续版本已修复
