### ISSUE TITLE
bk-cmdb 在windows上部署

### ISSUE THREAD

**Issue by dsfzt** [Tencent/bk-cmdb#2199]
问题描述
===========

bk-cmdb 可以在windows上部署吗？

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@dsfzt 你可以自已编译，然后在windows上部署。或者你使用容器在windows上部署，release里有对应的容器镜像可以使用。
