### ISSUE TITLE
connect mongodb error exit! err:no reachable servers

### ISSUE THREAD

**Issue by Scofields** [Tencent/bk-cmdb#221]
问题描述
===========
cmdb_adminserver启动报错
E0418 16:38:23.680622   27147 ccapi.go:127] connect mongodb error exit! err:no reachable servers
E0418 16:38:23.681444   27147 ccapi.go:140] exit! err:no reachable servers

显示连接mongodb失败，但是手动连接mongodb正常
./bin/mongo --host 10.26.31.144  --port 27019 -u "cc" -p "cc" --authenticationDatabase "cmdb"
MongoDB shell version v3.4.0
connecting to: mongodb://10.26.31.144:27019/
MongoDB server version: 3.4.0
> 

重现方法
================
<列出如何重现的方法或操作步骤>

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   cmdb-3.0.6.tar.gz 
 - [ ] Redis     版本: 3.2.11
 - [ ] MongoDB   版本: 3.4.0
 - [ ] ZooKeeper 版本: 3.4.11
 - [ ] 操作系统      : centos7
 - [ ] bk-cmdb 异常日志  more cmdb_adminserver.ERROR
Log file created at: 2018/04/18 16:38:23
Running on machine: qd01-stop-cloud001
Binary: Built with gc go1.8.7 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0418 16:38:23.680622   27147 ccapi.go:127] connect mongodb error exit! err:no reachable servers
E0418 16:38:23.681444   27147 ccapi.go:140] exit! err:no reachable servers

**Comment by uriwang** [comment]
1. 请参照FAQ自查
https://github.com/Tencent/bk-cmdb/wiki/FAQ
2. 重点检查mongodb 的连通性
3. 执行init.py 初始化时配置的参数，zk redis mongodb 的地址，必需为对应服务实际监听的地址；
4. redis 不可以监听在127.0.0.1 的地址，建议所有服务都不要监听在127.0.0.1 而是选用实际可达的ip；
5. 如果 通过 init.py 重置了配置，需要重启所有的cmdb 服务；

@Scofields
