### ISSUE TITLE
启动后报错biz参数无效或不存在

### ISSUE THREAD

**Issue by yangbojun** [Tencent/bk-cmdb#2219]
问题描述
===========

cmdb部署安装完成后运行start.sh，可以正常启动服务，访问http:ip:8083可以看到服务页面，但是上方报错显示biz参数无效或不存在。
![image](https://user-images.githubusercontent.com/49931460/56648024-19d4c900-66b5-11e9-9091-e4a44a10c0ab.png)

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
Version  : master
Tag      : master
BuildTime: 2019-04-24T15:38:29+0800
GitHash  : 8f346dfa615589dfac0b523c007a37f2e60d3da1
RunMode  : product
 - [ ] Redis     版本: 5.0.3 
 - [ ] MongoDB   版本: 4.0.9
 - [ ] ZooKeeper 版本:3.4.12 
 - [ ] 操作系统      : Centos 7.5 (x64）
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@yangbojun 你好，请使用v3.2.x分支的版本。或者去release页面下载对应的部署包。

**Comment by yangbojun** [comment]
@breezelxp 非常感谢您的解答，嗯我从release里下载3.2.2版本的部署包可以使用，但是还是有这个报错。
![image](https://user-images.githubusercontent.com/49931460/56657231-15ff7180-66ca-11e9-9503-fae346bd2818.png)
可能是因为我在同一台机器上安装了开源版的paas？我看paas后台有这么个报错
![image](https://user-images.githubusercontent.com/49931460/56657454-9faf3f00-66ca-11e9-8f35-78bc6b18355e.png)
顺便也跟您问一下我想使用开源版的paas能自动发现添加到开源的cmdb中这个怎么实现呢

**Comment by breezelxp** [comment]
> @breezelxp 非常感谢您的解答，嗯我从release里下载3.2.2版本的部署包可以使用，但是还是有这个报错。
> ![image](https://user-images.githubusercontent.com/49931460/56657231-15ff7180-66ca-11e9-9503-fae346bd2818.png)
> 可能是因为我在同一台机器上安装了开源版的paas？我看paas后台有这么个报错
> ![image](https://user-images.githubusercontent.com/49931460/56657454-9faf3f00-66ca-11e9-8f35-78bc6b18355e.png)
> 顺便也跟您问一下我想使用开源版的paas能自动发现添加到开源的cmdb中这个怎么实现呢

1. 关于这个报错，你可能没有初始化数据库导致的，请参照部署文档看一下。
2. 请你你说的自动必现是主机的自动必现吗？

**Comment by yangbojun** [comment]
@breezelxp 再次感谢您的耐心解答
1、昨天初始化数据库有报错404，今天把paas停掉后重新初始化成功了，报错也随之消失
2、是的主机自动发现，所以部署了paas，这两个服务该怎么关联上呢
