### ISSUE TITLE
前端根据配置的鉴权方案采用对应的鉴权方案

### ISSUE THREAD

**Issue by hoffermei** [Tencent/bk-cmdb#2234]
问题描述
===========

相关信息
=========
- index.html 渲染上下文变量，[index.go源文件](https://github.com/Tencent/bk-cmdb/blob/v3.4.x/src/web_server/service/index.go#L93)
```
c.HTML(200, "index.html", gin.H{
  | "site":        s.Config.Site.DomainUrl,
  | "version":     s.Config.Version,
  | "authscheme":  s.Config.Site.AuthScheme,
  | "role":        role,
  | "curl":        s.Config.LoginUrl,
  | "userName":    userName,
  | "agentAppUrl": s.Config.AgentAppUrl,
  | "authCenter":  s.Config.AuthCenter,
  | })
 ```

- `authscheme` 可选值 `internal`, `iam`，分别表示之前CMDB内置的权限方案和权限中心方案，前端需要根据`authscheme`进行相应的交互

版本
=========
 - [x] bk-cmdb   版本: v3.4.x
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by joe511230** [comment]
#2225
