### ISSUE TITLE
全局模型修改名称不生效

### ISSUE THREAD

**Issue by hoffermei** [Tencent/bk-cmdb#2241]
问题描述
===========
全局模型修改名称后，刷新页面看到的全局模型名称还是原有值

关键信息
=========
 - [x] bk-cmdb   版本: v3.2.x
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by hoffermei** [comment]
- 修改全局模型`防火墙`名称为`防火墙xx`后mongodb数据如下:

```
{
    "_id" : ObjectId("5cc17b82a5b2b920056e0fcd"),
    "metadata" : {
        "label" : {}
    },
    "position" : "{\"bk_network\":{\"x\":-650,\"y\":-50}}",
    "creator" : "cc_system",
    "bk_classification_id" : "bk_network",
    "ispre" : false,
    "last_time" : "2019-04-28 10:10:27",
    "id" : NumberLong(10),
    "bk_obj_icon" : "icon-cc-firewall",
    "bk_obj_id" : "bk_firewall",
    "bk_obj_name" : "防火墙xx",
    "bk_ispaused" : false,
    "bk_supplier_account" : "0",
    "description" : "",
    "modifier" : "admin",
    "create_time" : ISODate("2019-04-25T09:18:58.871Z")
}
```

**Comment by hoffermei** [comment]
跟踪代码发现 object controller将查询到的object根据object_id进行翻译，相关代码路径如下:

- [SelectObjects](https://github.com/Tencent/bk-cmdb/blob/v3.2.x/src/source_controller/objectcontroller/service/object_action.go#L195)
- `results[index].ObjectName = cli.TranslateObjectName(defLang, &results[index])` [TranslateObjectName](https://github.com/Tencent/bk-cmdb/blob/v3.2.x/src/source_controller/objectcontroller/service/common.go#L129:21)
- `return util.FirstNotEmptyString(defLang.Language("object_"+obj.ObjectID), obj.ObjectName, obj.ObjectID)`  [FirstNotEmptyString](https://github.com/Tencent/bk-cmdb/blob/v3.2.x/src/common/util/struti.go#L85:6)

通过上述调用栈可以发现，问题根本原因是翻译方案设计的时候没有考虑到模型重命名的情况，将翻译的优先级设置成了最高优先级

**Comment by breezelxp** [comment]
这个确实是个问题。

**Comment by hoffermei** [comment]
> 这个确实是个问题。这个应该是只有内置模型存在这个问题。

所有经过国际化的名称都会有这样的问题

如果目前没有比较轻的解决方案，建议先在前端禁止掉修改内置模型名称的功能
