### ISSUE TITLE
v3.2.2版本操作bug-资源发现配置好同步任务之后没有同步腾讯云的数据

### ISSUE THREAD

**Issue by dok8s** [Tencent/bk-cmdb#2266]
问题描述
===========

配置好腾讯云的同步任务之后，启动之后没有同步数据
![image](https://user-images.githubusercontent.com/24632466/57011963-bdceef00-6c36-11e9-9377-a752b2743c3d.png)
![image](https://user-images.githubusercontent.com/24632466/57011970-c58e9380-6c36-11e9-98d4-a0d692736821.png)
![image](https://user-images.githubusercontent.com/24632466/57011974-ca534780-6c36-11e9-851e-0bbc3f7578c6.png)
![image](https://user-images.githubusercontent.com/24632466/57011976-cd4e3800-6c36-11e9-9f5a-6515089537ad.png)
![image](https://user-images.githubusercontent.com/24632466/57011982-d2ab8280-6c36-11e9-8391-6bfde8fae632.png)

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
Version  : oc-19.03.26
Tag      : 
Branch   : master
BuildTime: 2019-03-26T18:15:49+0800
GitHash  : dd5d1e7bd1ca272d97ac520b9a7e975008b25ced
RunMode  : product
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by rentiansheng** [comment]
提供下版本。 可以用./cmdb_apiserver --verison获取

**Comment by dok8s** [comment]
Version  : oc-19.03.26
Tag      : 
Branch   : master
BuildTime: 2019-03-26T18:15:49+0800
GitHash  : dd5d1e7bd1ca272d97ac520b9a7e975008b25ced
RunMode  : product

**Comment by rentiansheng** [comment]
@vlon
