### ISSUE TITLE
文档中GSE指的是什么？

### ISSUE THREAD

**Issue by zhangjianweibj** [Tencent/bk-cmdb#2271]
你好！
CMDB的文档中（https://docs.bk.tencent.com/bkce_install_guide/setup/install_bkdata.html），经常出现GSE这个词，但是没有说明这是个什么组件，是什么作用的？

![image](https://user-images.githubusercontent.com/18585129/57189672-e2331000-6f43-11e9-9cf9-ad1678dbdb2a.png)

**Comment by jerry-tom** [comment]
GSE是整个蓝鲸平台的底层管控系统，是蓝鲸所有其他服务的基础，是蓝鲸服务体系与用户机器的连接器
