### ISSUE TITLE
cmdb agent问题

### ISSUE THREAD

**Issue by zhangjianweibj** [Tencent/bk-cmdb#2272]
你好！
通过docker镜像，安装了cmdb系统。不知道agent到哪个地方下载？另外agent是开源的吗？
谢谢！

![image](https://user-images.githubusercontent.com/18585129/57189696-34743100-6f44-11e9-9d5c-c8d8ac6ad427.png)

**Comment by breezelxp** [comment]
@zhangjianweibj 你好，要使用这个功能，需要使用蓝鲸社区版，具体信息可以参看这里bk.tencent.com。
