### ISSUE TITLE
确定查看模型拓扑鉴权action

### ISSUE THREAD

**Issue by hoffermei** [Tencent/bk-cmdb#2276]
问题描述
===========
![image](https://user-images.githubusercontent.com/13761028/57191254-ed8f3700-6f55-11e9-8e61-a7c89cc22f81.png)

## 问题分析
查看模型拓扑时，做了如下鉴权，但是跟iam对接发现并没有对应的操作类型 modelTopologyView 这个东西
```
POST /bkiam/api/v1/perm/systems/bk_cmdb/any-resources-perms/batch-verify with body {"principal_type":"user","principal_id":"hofferadmin","scope_type":"system","scope_id":"bk_cmdb","resources_actions":[{"resource_type":"sysSystemBase","action_id":"modelTopologyView"}]}
response status: 200 OK, response body: {"code":0,"data":[{"action_id":"modelTopologyView","is_pass":false,"resource_type":"sysSystemBase"}],"message":"","request_id":"32f5a4a20b404a66b2c38b003c7395cb","result":true},
```
- 目前iam中针对systemBase只有如下两种动作类型
  - modelTopologyOperation
  - adminEntry

## 现阶段遇到的问题
- 如果改成 modelTopologyOperation 的话，查看模型拓扑校验操作权限不合适
- 应该用什么action鉴权，还是单独增加 modelTopologyView 类型？

关键信息
=========
 - [x] bk-cmdb   版本: v3.4.x
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by techfindd** [comment]
编辑不设权限，谁都可以编辑视图位置
在编辑视图中对模型关联的操作（创建删除）有权限控制，依据是否具备双方的模型修改权限进行控制
