### ISSUE TITLE
缺少二进包

### ISSUE THREAD

**Issue by vacheli** [Tencent/bk-cmdb#2279]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by vacheli** [comment]
从3.2.3之后没有了二进制包，很不方面。繁琐的编译环境配置，希望像prometheus一样提供二进制包。

**Comment by breezelxp** [comment]
@vacheli 
你也，请在release页面下载部署包，现在也提供容器部署能力，可以关注下。

**Comment by Alibner** [comment]
**既然不提供二进制包，那文档是不是也更新一下呢？**
