### ISSUE TITLE
v3.4.x 权限问题集

### ISSUE THREAD

**Issue by hoffermei** [Tencent/bk-cmdb#2293]
问题描述
===========
在这里记录CMDB权限这块目前还存在的问题

## 权限问题记录
- 现在cmdb的大部分请求都是要先经过权限中心直接调用的，这个地方建议做个缓存策略或者其它的容灾策略，  现在可能碰到的是权限中心本身调用效率的问题，  后面即使效率提升了，后面也可能会有频率、负载的问题，甚至因为部署在不同机房模块服务的ping值都会影响接口调用效率

关键信息
=========
 - [x] bk-cmdb   版本: v3.4.x

**Comment by hoffermei** [comment]
### 资源注销机制优化
资源注销机制主要分成两个步骤：1. 获取资源完整的ID，比如主机资源，包括业务ID+模块ID+主机ID；2. 用拼接出来的资源ID向权限中心请求注销资源。
目前这两个操作是合并在一个步骤中，在CMDB资源删除前一刻执行的，这会带来一个问题，如果资源在权限中心的ID注销了，但是在CMDB中删除失败了，用户可能因此失去对资源的操作权限。
为了解决这个问题，可以将上述两个步骤拆开执行，分别在CMDB资源删除前一刻和CMDB资源成功删除后执行。

**Comment by lowenitt** [comment]
可以考虑下通过内部的事件流转来注册权限，这样减少代码中打点的次数

**Comment by hoffermei** [comment]
## 列表查询鉴权问题
列表读权限方案上有个一直没解决的问题：如何将查询结果分页跟读权限合并处理，全部查出来再鉴权后分页对两边系统压力都很大，如果只查一页再鉴权去掉没权限的记录，可能一条记录都没有

**Comment by wusendong** [comment]
> ## 列表查询鉴权问题
> 列表读权限方案上有个一直没解决的问题：如何将查询结果分页跟读权限合并处理，全部查出来再鉴权后分页对两边系统压力都很大，如果只查一页再鉴权去掉没权限的记录，可能一条记录都没有

这个之前我跟IAM商量过他那边提供一个查某人有权限的所有资源接口的，先拿到这些资源后再去作为条件查我们自己数据库，就可以分页了。但这个方案还有不妥的地方的，当时结论是在2期时再详细的联合讨论。

先去IAM查这种方式会让我们变得跟IAM绑得更死的，所以并不想用这种方法
