### ISSUE TITLE
空闲机池的主机上交所属业务的模块，不报错但是主机回到空闲机池，另无法添加用户，不报错

### ISSUE THREAD

**Issue by lyy8510a** [Tencent/bk-cmdb#23]
PHP5.6.20
NGINX 1.8
RH系统
MYSQL 5.7

**Comment by lowenitt** [comment]
无法添加用户的问题，更新下代码吧，就会有报错了
上交主机的逻辑就是把主机上交到空闲机池

**Comment by lyy8510a** [comment]
googleapi有时候老是超时，怎么彻底替换掉？我替换了2个引用，但是添加模块的时候发现还有在调用。
