### ISSUE TITLE
CMDB升级后进程管理无法编辑保存

### ISSUE THREAD

**Issue by jsksnick** [Tencent/bk-cmdb#2327]
问题描述
===========

从1.2.319升级到2.2.9版本后，进程管理无法新建或者编辑保存
![image](https://user-images.githubusercontent.com/17331795/57500190-0c564a80-7315-11e9-8a4f-625e4cd39589.png)

重现方法
================
新建或者编辑，无法保存

请提供以下信息:
CMDB版本：3.2.6

**Comment by wusendong** [comment]
版本号，请写清楚。执行一下cmdb_adminserver --version把输出信息提供一下哈，你提的几个issue都提供了错误的版本号给我，实在很难给你提供帮助
