### ISSUE TITLE
[help]创建主机api

### ISSUE THREAD

**Issue by yangbojun** [Tencent/bk-cmdb#2345]
[help]
问题描述
===========

使用api创建主机时返回值500
具体报错为
{"result":false,"code":1199027,"message":"[owner_id]授权信息查询失败","data":null}

重现方法
================

发送的请求以添加127.0.0.1为例
add_host_to_resource={
           'BK_USER':'admin',
           'HTTP_BLUEKING_SUPPLIER_ID':'0',
           "host_info":{
                   0:{
                      "bk_host_innerip":"127.0.0.1",
                      "import_from":"3",
                      "bk_cloud_id":"0"
                     }
                      },
                    "bk_supplier_id":'0'
        }
使用的是python中requests.post
requests.post("http://{hostip}:8080/api/v3/hosts/add",data=json.dumps(add_host_to_resource,ensure_ascii=False))

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
Version  : oc-19.05.13
Tag      : 
Branch   : master
BuildTime: 2019-05-13T17:47:52+0800
GitHash  : fc06356cc2586f0dc2db4f60118ac0f4df405f09
RunMode  : product
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
这个是缺少owner id 头导致的
![image](https://user-images.githubusercontent.com/26254420/58703060-116d5d80-83da-11e9-90ee-91df71df7afa.png)
