### ISSUE TITLE
 编译3.2.6 release后无法启动部分服务connect mongo server failed no reachable servers

### ISSUE THREAD

**Issue by red-alert** [Tencent/bk-cmdb#2356]
问题描述
===========

编译3.2.6 release后无法启动部分服务
cmdb_adminserver的log 报 connect mongo server failed no reachable servers
已经检查redis，zookeeper，mongod服务及网络连接无问题
配置文件无问题，mongod部分包含mechanism=SCRAM-SHA-1内容

查看mongod日志，无cmdb服务发起的连接

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
Version  : 3.2.6
Tag      : 3.2.6
Branch   : 
BuildTime: 2019-05-14T00:08:14-0400
GitHash  : 881507a9b9b87d3449e16981632bd3c8ccf2b056
RunMode  : product

 - [x] Redis     版本: 4.0.12
 - [x] MongoDB   版本: 4.0.9
 - [x] ZooKeeper 版本: 3.4.13
 - [x] 操作系统      : ubuntu1404
 - [x] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@red-alert 请问现在还有这个问题吗？如果还有，麻烦把日志发一下，我们给你排查一下。

**Comment by red-alert** [comment]
[cmdb_adminserver.FATAL.txt](https://github.com/Tencent/bk-cmdb/files/3185284/cmdb_adminserver.FATAL.txt)

我尝试build了一下tag3.2.6和tag3.2.8，换了mongo版本为3.6.12还是一样的问题

**Comment by hoffermei** [comment]
检查下 migrate.conf 中 mongo 地址

**Comment by red-alert** [comment]
[mongodb]
host = xx.xx.xx.xx
usr = xxx
pwd = xxx
database = xxx
port = 27017
maxOpenConns = 3000
maxIDleConns = 1000
mechanism=SCRAM-SHA-1

这个配置检查没有问题

**Comment by red-alert** [comment]
找到问题了，mongo数据库密码中包含“@”字符，导致无法连接至数据库，密码格式修改后解决
