### ISSUE TITLE
请问有多个CMDB数据同步的使用指导吗？

### ISSUE THREAD

**Issue by toddyhan** [Tencent/bk-cmdb#2358]
问题描述
===========
搜索issue了解到（#2247，#1780），目前已具备了多个CMDB间数据同步的功能，请问是否有该功能的使用文档？
在wiki、doc中都没有搜索到。如果有相关说明、使用指导，请提供下。非常感谢。

**Comment by rentiansheng** [comment]
@toddyhan  https://github.com/Tencent/bk-cmdb/issues/1780 按照这个配置即可。 目前不支持多个cmdb之间同时修改。

**Comment by toddyhan** [comment]
谢谢。
