### ISSUE TITLE
安装完成之后在login页面使用admin/blueking登录提示“用户名密码错误”

### ISSUE THREAD

**Issue by dangxiaojun** [Tencent/bk-cmdb#24]
系统环境：Ubuntu 10.10
nginx：1.8.0
php：5.6.9
mysql：5.1.49
按照README文档安装，数据库导入正常
begin truncate table
end truncate table
begin create classify host property 
INSERT INTO `cc_HostPropertyClassify` VALUES ('1', 'AssetID', '固资编号', 'basic', 'AssetID','12', '2016-02-24 11:26:57', '2016-02-24 18:00:57')
INSERT INTO `cc_HostPropertyClassify` VALUES ('7', 'DeviceClass', '设备类型', 'basic', 'DeviceClass','11', '2016-02-24 17:24:04', '2016-02-24 18:01:24')
INSERT INTO `cc_HostPropertyClassify` VALUES ('8', 'HostName', '主机名称', 'basic', 'HostName', '6','2016-02-24 17:26:00', '2016-02-24 18:01:48')
INSERT INTO `cc_HostPropertyClassify` VALUES ('9', 'Status', '运行状态', 'basic', 'Status', '7','2016-02-24 18:02:23', '2016-02-25 14:45:38')
INSERT INTO `cc_HostPropertyClassify` VALUES ('10', 'Operator', '维护人', 'basic', 'Operator','3', '2016-02-24 18:02:41', '2016-02-24 18:03:14')
INSERT INTO `cc_HostPropertyClassify` VALUES ('11', 'BakOperator', '备份维护人', 'basic', 'BakOperator','4', '2016-02-24 18:03:37', '2016-02-24 18:03:37')
INSERT INTO `cc_HostPropertyClassify` VALUES ('12', 'InnerIP', '内网IP', 'basic', 'InnerIP','1', '2016-02-24 18:04:01', '2016-02-24 18:04:01')
INSERT INTO `cc_HostPropertyClassify` VALUES ('13', 'OuterIP', '外网IP', 'basic', 'OuterIP','2', '2016-02-24 18:04:31', '2016-02-24 18:04:31')
INSERT INTO `cc_HostPropertyClassify` VALUES ('14', 'OSName', '操作系统', 'basic', 'OSName','7', '2016-02-24 18:04:53', '2016-02-24 18:04:53')
INSERT INTO `cc_HostPropertyClassify` VALUES ('15', 'Description', '备注', 'basic', 'Description','13', '2016-02-24 18:05:10', '2016-02-24 18:05:10')
INSERT INTO `cc_HostPropertyClassify` VALUES ('16', 'ZoneName', '可用区', 'basic', 'ZoneName','15', '2016-02-24 18:05:39', '2016-02-24 18:05:39')
INSERT INTO `cc_HostPropertyClassify` VALUES ('17', 'ZoneID', '可用区ID', 'basic', 'ZoneID', '14','2016-02-24 18:06:07', '2016-02-24 18:06:07')
INSERT INTO `cc_HostPropertyClassify` VALUES ('47', 'CreateTime', '入库时间', 'basic', 'CreateTime', '17','2016-02-24 19:11:25', '2016-02-24 19:11:25')
INSERT INTO `cc_HostPropertyClassify` VALUES ('49', 'Region', '机房城市', 'basic', 'Region','16', '2016-02-24 19:12:21', '2016-02-24 19:12:21')
INSERT INTO `cc_HostPropertyClassify` VALUES ('51', 'Cpu', 'Cpu', 'basic', 'Cpu', '8','2016-02-24 19:13:12', '2016-02-24 19:13:12')
INSERT INTO `cc_HostPropertyClassify` VALUES ('52', 'Mem', '内存', 'basic', 'Mem', '9','2016-02-24 19:13:37', '2016-02-24 19:13:37')
INSERT INTO `cc_HostPropertyClassify` VALUES ('60', 'HostID', '主机ID', 'basic', 'HostID','0', '2016-02-24 19:16:54', '2016-02-24 19:16:54')
INSERT INTO `cc_HostPropertyClassify` VALUES ('72', 'ModuleName', '模块名称', 'basic', 'ModuleName','5', '2016-02-24 18:02:41', '2016-02-24 18:02:41')
end create classify host property  
begin create set property 
INSERT INTO `cc_HostPropertyClassify` VALUES ('72', 'ModuleName', '模块名称', 'basic', 'ModuleName','5', '2016-02-24 18:02:41', '2016-02-24 18:02:41')
end create set property  
begin create admin user 
end create admin user 
begin create resource pool 
end create resource pool 
begin create example app 
end create example app 
begin create example set 
end create example set 
begin create example module 
end create example module

但是在网页首页login登录的时候，使用admin/blueking登录失败
提示“用户名密码错误”

**Comment by dangxiaojun** [comment]
我看了一下数据库中的数据，select * from cc_User;  显示的是Empty set (0.00 sec)   我要怎么做，重新初始化吗，还是哪里权限不对了。

**Comment by dangxiaojun** [comment]
资源池管理，不可导入文件，文件格式正确，内容正确。

**Comment by lowenitt** [comment]
请确认下日志中的报错信息
