### ISSUE TITLE
Docker容器启动时python: can't open file 'ip.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Thinkzhuo** [Tencent/bk-cmdb#2414]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by hoffermei** [comment]
你需要cd到start.sh所在的目录启动进程

**Comment by Thinkzhuo** [comment]
已经设置了WORKDIR=/cmdb_adminserver 还需要上述操作吗？修改为WORKDIR 后，服务仍旧无法启动，但不报错python can't open file 'ip.py'

**Comment by hoffermei** [comment]
看下admin server的日志，目前猜测是 ip.py 中根据 eth0 拿ip出问题了，容器内一般没有 eth0

**Comment by Thinkzhuo** [comment]
好的 谢谢

**Comment by Thinkzhuo** [comment]
容器中能正常获取ip

**Comment by Thinkzhuo** [comment]
编译好的dockerfile中Entrypoint 可以写作cd a  && b.sh 吗

**Comment by Thinkzhuo** [comment]
已解决，谢谢
