### ISSUE TITLE
web页面很多页签、内容显示the language code is 'zh-cn', unknown meaning

### ISSUE THREAD

**Issue by Thinkzhuo** [Tencent/bk-cmdb#2431]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
截图，版本？

**Comment by Thinkzhuo** [comment]
3.1.0版本 ，内部不允许截图，抱歉，我利用的是3.1.0版本进行的编译，分布式容器化部署的。eg. 左侧导航栏：“组织架构”的位置不能正常显示，显示内容为“the language code is 'zh-cn', unknown meaning”。

**Comment by breezelxp** [comment]
你反馈的这个问题，我们目前还没有碰到过，可以F12看下具体的错误是什么，有没有错误码？如果不行，建议你升级。

3.1.0的版本社区后续社区维护的周期可能比较长。

**Comment by Thinkzhuo** [comment]
如果我不编译前台页面，能够正常显示。 F12 无错误提示，均正常加载。

**Comment by breezelxp** [comment]
你前后端不是同一份代码编的？

**Comment by Thinkzhuo** [comment]
1、一起编译的时候，出现“the language code is 'zh-cn', unknown meaning”。2、只编译后端，前端用git上编译好的，可以正常显示。

**Comment by rentiansheng** [comment]
@Thinkzhuo 
1.  去zookeeper 中。 然后执行授权。 看下  get  /cc/services/errors， get  /cc/services/errors 看下有内容不。  如果有内容看下一步
2. 将启动命令中的--v=3,改为--v=5.  启动coreservice，apiserver, toposerver. 然后grep -ri " sync language config, after change is:"  上面服务的日志。 看下是没有有一个json格式的内容。内容类似下面：
![image](https://user-images.githubusercontent.com/3955934/58221677-08c7b800-7d46-11e9-8ebb-8cc5d23c8fb3.png)

**Comment by Thinkzhuo** [comment]
我试下 谢谢

**Comment by Thinkzhuo** [comment]
get /cc/services/errors   有中英文2份信息, coreopsservice 是对应的v3.1.0版本中的adminserver吗？

**Comment by Thinkzhuo** [comment]
初步判断为dockerFile generate的时候，COPY language 出了问题。 dockerFile 自动生成的脚本可能有问题

**Comment by Thinkzhuo** [comment]
已解决，dockerFile文件的问题，导致language文件夹的json文件命名有错误，少了“/”
