### ISSUE TITLE
【help】如何运行前端项目，与后台进行联调

### ISSUE THREAD

**Issue by Thinkzhuo** [Tencent/bk-cmdb#2459]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by joe511230** [comment]
前端为vue-cli 2.x搭建的项目，可先行了解vue-cli 2.x 如何创建、调试项目；
了解vue项目的构成后，进入src/ui目录后，修改confing/index.js中的dev配置后，执行dev脚本命令即可
