### ISSUE TITLE
事件推送关于“删除事件”信息缺失

### ISSUE THREAD

**Issue by vacheli** [Tencent/bk-cmdb#2476]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by vacheli** [comment]
主机从module转移到“空闲池”后无法获取该主机之前的数据

删除事件推送的数据如下：
-------------------------------------------
{
  "txn_id": "",
  "event_type": "relation",
  "action": "delete",
  "action_time": "2019-05-30T02:00:55Z",
  "obj_type": "moduletransfer",
  "data": [
    {
      "cur_data": null,
      "pre_data": {
        "bk_biz_id": 9,
        "bk_host_id": 1680,
        "bk_module_id": 503,
        "bk_set_id": 108,
        "bk_supplier_account": "0"
      }
    }
  ],
  "bk_supplier_account": "0",
  "request_id": "cc0000bjnjilohutt5qpknmpeg",
  "request_time": "2019-05-30T02:00:55Z",
  "distribution_id": 125,
  "subscription_id": 7
}

**Comment by rentiansheng** [comment]
提供下cmdb的版本。 ./cmdb_apiserver --version

**Comment by vacheli** [comment]
> 提供下cmdb的版本。 ./cmdb_apiserver --version

![image](https://user-images.githubusercontent.com/5040231/58773080-55d14700-85ee-11e9-8170-7f718c579768.png)
