### ISSUE TITLE
cmdb主机转移获取数据不正确

### ISSUE THREAD

**Issue by vacheli** [Tencent/bk-cmdb#2478]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by vacheli** [comment]
cmdb版本：3.2.5
cmdb接口地址： /api/v3/hosts/0/

**Comment by rentiansheng** [comment]
描述下错误场景的。 是有主机返回的模块和集群为空吗？

**Comment by vacheli** [comment]
> 描述下错误场景的。 是有主机返回的模块和集群为空吗？

有数据返回，但是返回的数据不对。而且返回的数据里面没有应对的“bk_host_id”数据。
