### ISSUE TITLE
报这个错误怎么解决 谢谢 

### ISSUE THREAD

**Issue by liuwangfa0512** [Tencent/bk-cmdb#25]
A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: core/Common.php

Line Number: 196

**Comment by liuwangfa0512** [comment]
数据库配置如下：
$active_group = 'default_'.ENVIRONMENT;
$query_builder = TRUE;

$db['default_development'] = array(
        'dsn'   => '',
        'hostname' => '192.168.86.121:3306',
        'username' => 'cmdb',
        'password' => '123456',
        'database' => 'cmdb',
        'dbdriver' => 'mysql',
        'dbprefix' => 'cc_',
        'pconnect' => FALSE,
        'db_debug' => TRUE,
        'cache_on' => FALSE,
        'cachedir' => '',
        'char_set' => 'utf8',
        'dbcollat' => 'utf8_general_ci',
        'swap_pre' => '',
        'encrypt' => FALSE,
        'compress' => FALSE,
        'stricton' => FALSE,
        'failover' => array(),
        'save_queries' => TRUE,
    'query_builder'=>TRUE
);

确定用户名密码都可以连上

**Comment by liuwangfa0512** [comment]
修改了 'db_debug' => TRUE,  为'db_debug' => FALSE, 可以到登录界面了 但是登录不了

**Comment by lowenitt** [comment]
用客户端连接下数据库，看能都连接上
