### ISSUE TITLE
能否加个一键启动的docker镜像,用作单机版demo

### ISSUE THREAD

**Issue by modeyang** [Tencent/bk-cmdb#250]
如题

**Comment by lowenitt** [comment]
您好：
docker 镜像的制作，目前主要是镜像仓库的选择问题，目前我们还提供dockerfile文件用于制作docker镜像

**Comment by NingLee** [comment]
请问下dockerfile在哪里，代码里好像没有看到，谢谢

**Comment by uriwang** [comment]
编译打包后会有 image.sh 的脚本辅助制作镜像
