### ISSUE TITLE
数据模型预研

### ISSUE THREAD

**Issue by hoffermei** [Tencent/bk-cmdb#2505]
## 背景
> CMDB项目中几乎所有的模型支持用于定义自定义字段，这带来一个问题，如何用golang接收创建实例的请求参数，并处理请求参数。因为用户可以给模型定义自定义字段，没办法用一个固定的golang struct接收请求参数。

## 当前方案：mapstr
为了解决这一问题，当前CMDB项目实现了一个`mapstr`包来接收参数（类似`map[string]interface{}`结构），它不依赖固定的struct来解析json参数，而是直接将json中每个字段对应解析成一个mapstr结构的一个字段。mapstr的方案成功解决了缺少struct的问题，但在应用过程中也暴露出一些不足，比如如：

- json中多有字段都保存到了解析结果中，不是像struct只接收定义的值，而要求的字段又无法确保存在，给业务逻辑代码中增加了不必要的校验。
- 所有解析出来的值都严重依赖json中输入的类型，无法只接收固定类型值，这给后面的参数校验和使用带来了很多麻烦，比如几乎所有实例都有的 `id` 字段，CMDB代码从mapstr中使用它之前，都需要检查/转换成整数，导致整个项目随处可见一些数据解析/类型转换代码。
- 目前mapstr的实现不完备，只处理了部分常见的字段类型；从mapstr转换成struct时不支持指针类型。

从上面分析可以看出 mapstr 相比 map[string]interface{} 暴露相同的缺陷，主要原因是它们都非常的灵活，字段可有可无，可多可少，字段值也不受限制。

## map 与 struct 使用方式对比
`map[string]interface{}`和`mapstr`, 相比`struct`， 在使用方式上，主要体现如下不足：

1. 无法直接引用字段，不能字段是否存在
2. 无法直接使用字段值，需要转换到预期类型
3. 缺少基本校验，比如正则校验，数据范围校验
4. 不用担心将多余字段存入数据库

### 动态构建 Struct
由于用户可以运行时增删字段，通过在代码中定义一个固定的的struct，来解析用户输入是无法实现的。
本 issue 尝试通过动态定义struct的方式解决，用户参数解析的问题。主要使用go语言中的反射机制来构建动态struct, 实现原理可参考 [Reflect Example](https://golang.org/src/reflect/type.go?s=64896:64936#L2332)。
通过动态构建的struct可以解决上面对比中的1,3,4三个问题，但是还不能解决问题2，因为通过动态Struct解析出来的数据仍然是接口类型，仍然需要转到目标类型才能使用。

### 半动态
动态构建的 Struct 在字段引用方面，表现出比较麻烦，需要对interface类型进行转换。CMDB项目的实践经验表明，代码中经常访问的字段是那些硬编码内置的字段，比如id和名称字段等，对于用户自定义的字段，由于跟CMDB项目业务逻辑关联不大，很少在代码中直接访问到。
半动态Struct是一种基于这种思路的改进版本，它将每个模型中内置的字段直接在硬编码定义在CMDB代码中，用户自定义的字段通过动态构建 Struct 的方式解决。如下为一个半动态模型的struct定义：

```
type SimpleModelBase struct {
	ID   int64
	Name string
}
type SimpleModel struct {
	DynamicStructure
	SimpleModelBase
}
```

半动态Struct `SimpleModel` 主要分成两部分，动态部分表示在 `DynamicStructure` 结构中，固定的字段记录在 `SimpleModelBase`。通过半动态Struct方式表示的model可以非常方便的访问内置字段（与普通Struct没有区别），动态部分 `DynamicStructure` 可以通过 `DynamicStructure.Get(name string)` 接口获取动态字段interface类型值，并可以直接转到到解析后的类型。

另外，采用struct结构之后，每个字段可以结合 [go-playground/validator](https://github.com/go-playground/validator) 定义自己的校验规则。帮忙减少了大量原始处理的工作。

### json 解析问题
半动态struct相比普通struct和完全动态struct有一点不足，主要表现在json解析，因为动态字段需要内嵌到原始struct结构中，但是`DynamicStructure`结构又需要定义自己的json解析方法，因此`DynamicStructure`的json解析方法会覆盖掉整个`SimpleModel`的默认解析方法，导致 ID 和 Name 等内置字段无法解析。为了解决改问题，目前的解决办法是将所有内置字段定义在一个单独的结构体中，然后内嵌到 `SimpleModel` 中（也就是本 issue 中示范的效果），然后给SimpleModel也定义一个自定义json解析方法，在解析方法中分别调用两个动态和固定部分的json解析。

issue 中记录方案的详细实现请查看关联 PR #2506

**Comment by wusendong** [comment]
DDD了解一下？VO、DTO、DO和PO等全齐后就没这个问题了，就是写struct麻烦了一些，但事实上DDD中真就这么干的

**Comment by wusendong** [comment]
另外一种方式是两次UnmarshalJSON，一次Unmarshal到structure的实体Entity，一次Unmarshal到structure的Vaule-Object, 其中Entity用structure书写，Value-Object仅为一个不导出的变量。Entity和Value-Object组成DO，实际操作中Entity仅参加逻辑判断不参与数据流动过程。

样例, 模型属性值更新接口：
前端（有时前端不单单指UI，有时还可以指查询类北向接口（严谨一点应该为DTO，但大多人会混在一个叫VO））使用的VO：
```JSON
{
	"bk_object_id": "switch",
	"name": "name",
	"vendor": "huawei",
	"model_id": "P3000"
}
```

DO：
```go
type UpdatePropertyDO struct{
	ModelID string `json:"bk_object_id"`
	valueObject ValueObject `json:"-"`
}

func (d *UpdatePropertyDO) UnmarshalJSON(data []byte) error{
	if err:=json.Unmarshal(data, d);err!=nil{
		return err
	}
	return json.Unmarshal(data, &d.valueObject)
}

func (d *UpdatePropertyDO) MarshalJSON() ([]byte, error){
	return json.Marshal(d.valueObject) // 从这里可以看出，数据交互仅使用Vaule-Object
}
```

ValueObject 需要提供基础的数据操作, 注意不能含有写入类操作，因为ValueObject并不能反射到上层的DO进行同步修改
```go
type ValueObject struct {
	data map[string]interface{}
}

func (d *UpdatePropertyDO) Exists(key string) bool
func (d *UpdatePropertyDO) String(key string) bool, error
func (d *UpdatePropertyDO) Int(key string) int, error
```

可以看出DO中有Entity和Vaule-Object，他们的数据集是存在交集的，所以需要做数据同步，使用Getter，Setter可以做到，虽然golang官方不太推荐使用Getter，Setter，但我也没想到更好的方式

持久化时也是从Vaule-Object转为PO，而不是DO或Entity转为PO。

这个方案我在以前做网盘时用过，但那时候是JAVA，Java的切面技术比较好做这个方案，golang会麻烦不少。可以集思广益怎么golang中实践

**Comment by hoffer32** [comment]
> DDD了解一下？VO、DTO、DO和PO等全齐后就没这个问题了，就是写struct麻烦了一些，但事实上DDD中真就这么干的

先提出现在方案的问题，再提供新方案的解决思路

**Comment by wusendong** [comment]
> > DDD了解一下？VO、DTO、DO和PO等全齐后就没这个问题了，就是写struct麻烦了一些，但事实上DDD中真就这么干的
> 
> 先提出现在方案的问题，再提供新方案的解决思路

问题不是你提出的么(；´д｀)ゞ，这方案就是为了解决你上面提出的问题的呀
