### ISSUE TITLE
社区版4.0了，开源什么发布4.0版

### ISSUE THREAD

**Issue by hadoop835** [Tencent/bk-cmdb#252]
社区版4.0了，开源什么发布4.0版

**Comment by hustcr** [comment]
蓝鲸社区版的版本号和cmdb的版本号是分开的。4.0是社区版版本号，对应的cmdb版本是3.0.6。

**Comment by aryaky** [comment]
蓝鲸社区版4.1.15对应的cmdb版本是多少
