### ISSUE TITLE
[入手难]一些建议

### ISSUE THREAD

**Issue by hktalent** [Tencent/bk-cmdb#2525]
### 1、运维对象：资产识别
能否集成nmap、masscan等自动获取运维等资产清单
或者配置192.168.0.0/16的模式
资产识别后，能否自动图形化展示出关联关系

端口开放情况
安全诊断情况（包含安全配置检查情况）

IP导入，建议支持nmap的xml文件格式
### 2、配置问题
能否配置key，或者ssh、port，密码等，然后自动连接，设施运维活动

### 3、安全加固、安全巡检、安全监控
启动docker版本的，没有找到安全加固、安全巡检模版

### 4、agent的安装
能否优化，当给ssh相关账号后，提示yes /no，然后自动部署，当然支持各种系统（golang）

**Comment by hktalent** [comment]
### 没有看到接口、插件文档
非常感谢开源

**Comment by breezelxp** [comment]
@hktalent 你好，感谢你的反馈。针对你反馈的上面这些点，我做下简单的说明：
首先，bk-cmdb是腾讯蓝鲸智云的几大基础服务之一，bk-cmdb承担着蓝鲸底层配置服务的管理职能，并联动蓝鲸的其它服务解决海量运维服务过程中遇到的各种难题，提供灵活、可靠的解决方案。关于蓝鲸的具体信息可以关注这里https://bk.tencent.com/ 。

其次，关于你提到的几个方面，我逐个简要说明下：
1. 运维对象的资产识别，我们整合了蓝鲸的其它服务，提供了资产资源的服务发现等能力，提供灵活的资产发现，关联等能力。该功能还未对外发布，敬请关注。
2，4 这两点提到的内容，由蓝鲸体系下的节点管理服务提供。
3. 社区提供的docker版本本意是为了让大家快速体验蓝鲸cmdb服务，降低体验成本。如果有特殊需求可根据自身的需要制作镜像。

如果想深入了解蓝鲸，可以试用下蓝鲸社区版服务。

**Comment by breezelxp** [comment]
> ### 没有看到接口、插件文档
> 非常感谢开源

接口文档参看这里：
https://github.com/Tencent/bk-cmdb/tree/master/docs/apidoc

**Comment by hktalent** [comment]
@breezelxp 谢谢了

**Comment by hktalent** [comment]
恕我直言，这个开源项目有点鸡肋，食之无肉、弃之可惜
<img width="734" alt="image" src="https://user-images.githubusercontent.com/18223385/59326585-8c5b4000-8d19-11e9-870a-c4f33fbe2cfc.png">
有用、有价值的、精华的，都没有开源
本开源看上去定位是仅仅吸引人气
