### ISSUE TITLE
【help】 前端的服务启动时，在哪里配置apiserver的地址

### ISSUE THREAD

**Issue by Thinkzhuo** [Tencent/bk-cmdb#2539]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@Thinkzhuo 
这个都是通过zk服务发现做的，不需要手动配置。
