### ISSUE TITLE
登录的时候报错 用户名密码错误

### ISSUE THREAD

**Issue by liuwangfa0512** [Tencent/bk-cmdb#26]
A PHP Error was encountered

Severity: Warning

Message: mysql_real_escape_string() expects parameter 2 to be resource, boolean given

Filename: mysql/mysql_driver.php

Line Number: 352

Backtrace:

File: /opt/bk-cmdb-master/application/models/UserModel.php
Line: 19
Function: where

File: /opt/bk-cmdb-master/application/libraries/Login.php
Line: 115
Function: getUserByUsername

File: /opt/bk-cmdb-master/application/libraries/Login.php
Line: 182
Function: isValidUserPassword

File: /opt/bk-cmdb-master/application/controllers/Account.php
Line: 91
Function: loginUser

File: /opt/bk-cmdb-master/index.php
Line: 293
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: mysql_query() expects parameter 2 to be resource, boolean given

Filename: mysql/mysql_driver.php

Line Number: 251

Backtrace:

File: /opt/bk-cmdb-master/application/models/UserModel.php
Line: 20
Function: get

File: /opt/bk-cmdb-master/application/libraries/Login.php
Line: 115
Function: getUserByUsername

File: /opt/bk-cmdb-master/application/libraries/Login.php
Line: 182
Function: isValidUserPassword

File: /opt/bk-cmdb-master/application/controllers/Account.php
Line: 91
Function: loginUser

File: /opt/bk-cmdb-master/index.php
Line: 293
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: mysql_num_rows() expects parameter 1 to be resource, null given

Filename: mysql/mysql_result.php

Line Number: 63

Backtrace:

File: /opt/bk-cmdb-master/application/models/UserModel.php
Line: 20
Function: get

File: /opt/bk-cmdb-master/application/libraries/Login.php
Line: 115
Function: getUserByUsername

File: /opt/bk-cmdb-master/application/libraries/Login.php
Line: 182
Function: isValidUserPassword

File: /opt/bk-cmdb-master/application/controllers/Account.php
Line: 91
Function: loginUser

File: /opt/bk-cmdb-master/index.php
Line: 293
Function: require_once

**Comment by liuwangfa0512** [comment]
数据库中有数据

**Comment by lowenitt** [comment]
数据库的配置正确了吗
