### ISSUE TITLE
连接redis sentinel高可用集群超时

### ISSUE THREAD

**Issue by yunfeil** [Tencent/bk-cmdb#2606]
问题描述
===========

1.redis、mongodb高可用文档没有，希望后续能补充
2.不会go语言，自己艰难摸索了下redis sentinel高可用配置
以webserver.conf为例，添加了
`address=10.139.11.18:26379;10.139.11.169:26379;10.139.11.178:26379`
`mastername=redis-server`
启动后报错
`F0624 18:05:18.106798    5741 service.go:60] failed to create new redis store, error info is %vredigo: no sentinels available; last error: dial tcp 10.139.11.178:26379: i/o timeout`

看了源码，发现用了这个库：
[https://github.com/holmeswang/redistore/blob/master/redistore.go](url)
里面的NewRedisStoreWithSentinel方法写死了超时时间，为500 * time.Microsecond
这个超时时间是不是也太短了

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@yunfeil 这个用户自己解决

**Comment by yunfeil** [comment]
> @yunfeil 这个用户自己解决

redis sentinel超时问题是不是bug
