### ISSUE TITLE
通过Excel导入数据时唯一校验不生效

### ISSUE THREAD

**Issue by forestsissi** [Tencent/bk-cmdb#2609]
问题描述
模型中新建校验字段，创建数据时，如果该字段值重复，则会提示唯一校验不通过；如果通过excel导入数据，重复数据不会有提示，并且都导入成功

重现方法
必现

**Comment by rentiansheng** [comment]
导入的时候，如果没有实例ID， 唯一字段值一样，表示更新唯一值相同的的实例
