### ISSUE TITLE
如何将github的cmdb分支版本直接docker build 成镜像

### ISSUE THREAD

**Issue by jackxiao007** [Tencent/bk-cmdb#2625]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@jackxiao007 
社区目前还未统一提供cmdb各个服务的容器镜像，不过在排期里，请关注社区后续的动态。
