### ISSUE TITLE
CBDB 是怎么保证数据的正确性的？内部有LOCK 或者 TRANSACTION 之类或者类似的功能吗？

### ISSUE THREAD

**Issue by xmanjack** [Tencent/bk-cmdb#265]
问题描述
===========
CBDB 是怎么保证数据的正确性的？内部有LOCK 或者 TRANSACTION 之类或者类似的功能吗？

只是一些问题。不是ISSUE.

**Comment by lowenitt** [comment]
数据的事务性，目前还缺乏事物级别的，完整的事物引擎目前还在设计中
