### ISSUE TITLE
mongodb密码包括特殊字符@导致拼接的URI无法连接到mongodb

### ISSUE THREAD

**Issue by lirizhong** [Tencent/bk-cmdb#2690]
问题描述
===========

mongodb密码包括特殊字符@导致拼接的URI无法连接到mongodb

重现方法
================

mongodb的用户密码包含特殊字符 @ 

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [x] Redis     版本: 4.0.6
 - [x] MongoDB   版本: 3.2.21
 - [x] ZooKeeper 版本: 3.4.14
 - [x] 操作系统      : CentOS Linux release 7.4.1708 (Core)
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@lirizhong 收到反馈，我们看下。
