### ISSUE TITLE
googleapi有时候老是超时，怎么彻底替换掉？

### ISSUE THREAD

**Issue by lyy8510a** [Tencent/bk-cmdb#27]
我已替换了2个可搜索到的引用，但是添加模块的时候发现还有在调用googleapi的js。

Searching 621 files for "googleapi"

0 matches

**Comment by shpdnkti** [comment]
fonts.googleapis.com ————–> fonts.lug.ustc.edu.cn
ajax.googleapis.com —————> ajax.lug.ustc.edu.cn
themes.googleusercontent.com –> google-themes.lug.ustc.edu.cn
fonts.gstatic.com —————–> fonts-gstatic.lug.ustc.edu.cn

**Comment by shpdnkti** [comment]
用中国科学技术大学镜像资源去代替googleapi，速度杠杠的，适合墙外的用户

**Comment by lowenitt** [comment]
我会把文件打到本地项目中吧

**Comment by lowenitt** [comment]
可以更新下代码
