### ISSUE TITLE
【需求】同一主机可分配至多个模块下，因为有些机器承载了业务的多种功能

### ISSUE THREAD

**Issue by Thinkzhuo** [Tencent/bk-cmdb#2700]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@Thinkzhuo cmdb目前是支持一个主机在同一业务下的多个模块。
