### ISSUE TITLE
查询指定模型的指定实例关联top报错

### ISSUE THREAD

**Issue by makerwei** [Tencent/bk-cmdb#2773]
问题描述
===========
通过api网关接口调用没有问题

当通过s.CoreAPI.TopoServer().Instance().SelectAssociationTopo调用时，结果返回空，错误日志为：
![image](https://user-images.githubusercontent.com/43264876/61613890-070e6800-ac95-11e9-84d2-15e5c12f1e01.png)

日志：E0722 15:17:24.239094    2076 request.go:309] invalid response body, unmarshal json failed, reply:{"result":true,"bk_error_code":0,"bk_error_msg":"success","data":[{"prev":[{"id":"","bk_obj_id":"public_depart_model","bk_obj_icon":"icon-cc-department","bk_inst_id":0,"bk_obj_name":"部门信息","bk_inst_name":"","asso_id":0,"count":1,"children":[{"id":"26378","bk_obj_id":"public_depart_model","bk_obj_icon":"icon-cc-department","bk_inst_id":26378,"bk_obj_name":"部门信息","bk_inst_name":"aaa","asso_id":37955}]}],"next":[],"curr":{"id":"26057","bk_obj_id":"public_busline_model","bk_obj_icon":"icon-cc-default","bk_inst_id":26057,"bk_obj_name":"业务线","bk_inst_name":"ai_lab","asso_id":0}}]}, error:json: cannot unmarshal array into Go struct field SearchInstResult.data of type metadata.InstResult

重现方法
================
如上

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 所有版本，最近版本也存在这个问题

**Comment by breezelxp** [comment]
@makerwei 看下你的场景，你是说调用apiserver的接口没有问题是吗？

**Comment by makerwei** [comment]
@breezelxp 调用apiserver没有问题，这个问题我自己解决了
![image](https://user-images.githubusercontent.com/43264876/62096014-cf1aac80-b2b4-11e9-9858-51592b785b28.png)

**Comment by breezelxp** [comment]
> @breezelxp 调用apiserver没有问题，这个问题我自己解决了
> ![image](https://user-images.githubusercontent.com/43264876/62096014-cf1aac80-b2b4-11e9-9858-51592b785b28.png)

@makerwei 👍🏻可以提个PR上来修复你说的这个问题。
