### ISSUE TITLE
拆分/重构现有主机查询接口

### ISSUE THREAD

**Issue by hoffermei** [Tencent/bk-cmdb#2796]
背景-现有主机查询接口的问题
===========
- 接口返回内容除了主机属性，还包含所属业务/集群/模块等信息，权限接入后，主机是公开的，但是业务等信息不是公开的
- 现有主机查询接口支持用于自定义查询语句，由于查询参数完全由用户控制，后端很难对接口进行场景优化
- 支持用户自定义查询语句存在一定的安全隐患，比如sql注入问题比较难规避
- 查询接口没有统一标准，各种接口都是根据开发者当时的理解设计

关键信息
=========
 - [x] bk-cmdb   版本: v3.5.x

**Comment by hoffermei** [comment]
```json
{
	"metadata": {
		"label": {
			"bk_biz_id": "{{ bizID  }}"
		}
	},
	"bk_set_ids": [11],
	"bk_module_ids": [56],
	"std_property": {
		"bk_cloud_id": [0],
		"import_from": ["1"]
	},
	"exclude_std_property": {
				"bk_host_innerip": ["10.27.2.5"]
	}
}
```

**Comment by breezelxp** [comment]
主要包含以下几个接口：
* 根据业务ID和主机字段查询主机
* 根据set/module和主机字段查询主机
* 根据自定义层级查主机
* 根据动态分组查主机
* 查主机相关的业务、set、module之间的关系信息
* 查找全量主机接口，包括2个维度、云区域和开发商。

**Comment by hoffermei** [comment]
该接口实现的内容包括：
- [x] 根据业务ID和主机字段查询主机
- [x] 根据set/module查询主机
- [ ] 根据自定义层级查主机(可以用业务拓扑树将自定义层级转化成set，考虑到未来版本中自定义层级将替换成目录树，不打算支持该特性)
- [x]  查找全量主机接口，包括2个维度、云区域和开发商。

`根据动态分组查主机` 其实是查询参数的一个快捷方式，不应该直接实现将动态分组转化成db过滤条件，而是尽可能的考虑如何将动态分组转化成本issue接口的查询条件

`查主机相关的业务、set、module之间的关系信息` 不属于查询主机的范围，目前主机模块关系已经有接口可以直接查询

**Comment by hoffermei** [comment]
目前接口设计上遇到的问题：
1. 模糊搜索如何支持
2. 如何处理没有业务ID的主机查询
3. 动态分组中支持 1,2 ，如果不再支持1,2，如何推动使用者进行改动

**Comment by hoffermei** [comment]
## 通用查询语言方案选型
主机查询条件（后期考虑作为CMDB通用查询语言）准备参考 [QueryBuilder](https://querybuilder.js.org/index.html) 项目规范来搞，后端写个转换逻辑将过滤规则转化成mongo的查询条件。

参考这个规范的原因：
1. 语义跟mongo比较接近，但是仅仅支持有限的操作符，不容易出现sql注入问题
2. 相对较全面，能覆盖到常见的过滤场景，相比自己考虑不容易漏掉
3. 有对应的UI和文档，在业界也一定程度被接受，接口交互设计相对更容易被用户接受
4. 相比es，graphql等查询语言，用户更容易理解，学习成本更低，cmdb代码复杂度更低，更适用于作为基本功能，es/graphql等特性可以作为扩展功能支持

## Query Builder

### 通过UI配置查询条件
![image](https://user-images.githubusercontent.com/13761028/62180952-36ebf880-b384-11e9-9d0b-1308bf72c979.png)


### 生成的查询条件demo

```json
{
  "condition": "AND",
  "rules": [
    {
      "id": "price",
      "field": "price",
      "type": "double",
      "input": "number",
      "operator": "less",
      "value": 10.25
    },
    {
      "condition": "OR",
      "rules": [
        {
          "id": "category",
          "field": "category",
          "type": "integer",
          "input": "select",
          "operator": "equal",
          "value": 2
        },
        {
          "id": "category",
          "field": "category",
          "type": "integer",
          "input": "select",
          "operator": "equal",
          "value": 1
        }
      ]
    }
  ],
  "valid": true
}
```

### 支持的运算符
- equal
- not_equal
- in
- not_in
- less
- less_or_equal
- greater
- greater_or_equal
- between
- not_between
- begins_with
- not_begins_with
- contains
- not_contains
- ends_with
- not_ends_with
- is_empty
- is_not_empty
- is_null
- is_not_null
