### ISSUE TITLE
请求失败 HTTP 404 Not Found

### ISSUE THREAD

**Issue by mega-Q** [Tencent/bk-cmdb#28]
**执行命令，报错：**
#curl -i http://cmdb.bk.com/
HTTP/1.1 404 Not Found
Server: nginx/1.10.2
Date: Fri, 30 Dec 2016 09:23:31 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.6.29

File not found.

---
**主要是对root路径定义不理解，不知道是从哪里来的，（find也没找到）
或者说我应该指向哪里：**
server {
        listen       80;
        server_name  cmdb.bk.com;
        root   /data/htdocs/cc_openSource; 

使用上来说，
这种conf文件可不可以单独建立，我们直接拷贝到conf.d/下呢

---
**另：**
能不能有一个目录结构的解释？
因为没有什么经验，怎么感觉“安装步骤”这一段理解起来不是太顺畅。

**Comment by lowenitt** [comment]
我们是单入口应用，另外应用是基于CI 框架开发，可以基本不用理解目录结构的

**Comment by mega-Q** [comment]
对于这三个目录，我想知道他们分别的作用，以便快速定位，
另外：
关于404的问题能不能指点一下。
@lowenitt

**Comment by raindylong** [comment]
@mega-Q ，你提的问题似乎都是nginx相关，可以搜索一下nginx相关文档，这个似乎不在bk-cmdb的讨论范围内。

**Comment by mega-Q** [comment]
你看我的第二段中提到“root /data/htdocs/cc_openSource;” 的疑惑，
问题是我找不到这个路径，不是我nginx配置错误，
@raindylong 你是怎么定义server 80的root的呢？

**Comment by raindylong** [comment]
@mega-Q ，你下载后的项目代码放在哪里是由你自己规划的，例如你放在/home/mega/cmdb，你就应该改动这个配置为：
`
root /home/mega/cmdb ;
`
readme的作用是参考和引导，各种变化是由自己掌握的。

**Comment by mega-Q** [comment]
@raindylong 非常感谢，已经成功展现。

---
# 整理解决办法：
# 环境准备：
centos7.3上yum安装php、nginx、percona
# 修改配置文件
以下所有操作均在工程目录下：
cd /usr/share/nginx/html/bk-cmdb-master 
vim /etc/nginx/conf.d/bk-cmdb.conf
server {
        listen       80;
        server_name  cmdb.bk.com;
        root   /usr/share/nginx/html/bk-cmdb-master;    #修改“工程目录“即可
...     #具体参考https://github.com/Tencent/bk-cmdb
    }
