### ISSUE TITLE
Excel导入时间问题

### ISSUE THREAD

**Issue by chainingning** [Tencent/bk-cmdb#2801]
问题描述
===========

自己新建一个模型，字段中有一个短字符的创建时间，然后通过excel导入时，数据由2019-07-29 10:31:56变成了
2019-07-29T16:24:57.178+08:00

重现方法
================
在模型管理中心新建一个模型，然后添加一个短字符的时间字段
通过excel导入数据

关键信息
=========
 - [x] bk-cmdb   版本: 
Tag      : release-v3.2.15
Branch   : v3.2.15
BuildTime: 2019-01-30T11:29:27+0800
GitHash  : a75ebb3676875cd2075c8e85139426fcbb72e5bf

**Comment by rentiansheng** [comment]
这个是由于数据序列化的关系。 设计excel， json 等数据类型的转换。 这个问题已知。 我们会尽快解决

@breezelxp
