### ISSUE TITLE
自定义API接口是否支持对自定义模型查询？

### ISSUE THREAD

**Issue by 15290182197** [Tencent/bk-cmdb#2815]
问题描述
===========

自定义一个模型，然后通过自定义API查询无结果，info为空。
![image](https://user-images.githubusercontent.com/53323278/62177077-3fd5cd80-b376-11e9-8402-11eca549a374.png)

------------------------------------------------
问题重现：
正确流程下通过新增一条自定义API：查询内网ip不等于172.0.0.1 的host
![image](https://user-images.githubusercontent.com/53323278/62176153-0485cf80-b373-11e9-843e-e5648fa87d74.png)
是可以成功实现查询的 如下图
![image](https://user-images.githubusercontent.com/53323278/62176221-35fe9b00-b373-11e9-9621-975bcc0a4d59.png)

失败情况：新增一条自定义API：查询bk_inst_name 不等于aaa的tomcat
![image](https://user-images.githubusercontent.com/53323278/62176393-e10f5480-b373-11e9-8b31-68b102961850.png)
如上图新增api成功，但是查询这条api却没有结果info为空，如下图
![image](https://user-images.githubusercontent.com/53323278/62176438-14ea7a00-b374-11e9-81d7-8736788cbdb2.png)

我已经建立一个名为tom1的实例并没有查到
![image](https://user-images.githubusercontent.com/53323278/62176505-6135ba00-b374-11e9-9057-274565b1d9d4.png)
查询文档得知其支持  对象名,可以为biz,set,module,host,object
![image](https://user-images.githubusercontent.com/53323278/62176569-a528bf00-b374-11e9-8888-2b79535d49d4.png)

1 请问自定义接口可以支持对象名为 biz,set,module,host 以外的模型查询吗
2 自定义接口支持对象为Object的查询，这个Object是指什么？是指自定义模型吗  
3 如果自定义接口不支持自定义模型的查询，在未来计划里是否考虑支持

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: v3.5.x
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by rentiansheng** [comment]
自定义查询目前，只支持主机。
