### ISSUE TITLE
有蓝鲸的同学想来阿里做CMDB的，可以联系我哈，待遇丰厚，机会很多

### ISSUE THREAD

**Issue by ylxfc** [Tencent/bk-cmdb#2831]
问题描述
===========

有蓝鲸的同学想来阿里做CMDB的，可以联系我哈，待遇丰厚，机会很多

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by ylxfc** [comment]
邮箱 yiming.yl@alibaba-inc.com

**Comment by breezelxp** [comment]
@ylxfc 同学，请不要发与cmdb本身无关的问题，谢谢。

**Comment by hustcr** [comment]
bk-cmdb也在招人，欢迎推荐或自荐😆
@ylxfc

**Comment by hsdtsyl** [comment]
@ylxfc 
广州视源股份也在**招聘运维开发**，不论*腾讯*还是*阿里*，欢迎投简历过来

peizhenfei@cvte.com

**Comment by coffeedang** [comment]
一起开源协同嘛，阿里腾讯都用的东西，就成了行业标准了，回头我去问问华为，挖来挖去的多麻烦

**Comment by liangfm117** [comment]
兄弟你这挖人广告有点过分了呦

**Comment by dongyuanxin** [comment]
这操作太秀了哟

**Comment by chenamy2017** [comment]
请走正道。

**Comment by fengsi** [comment]
@ylxfc 太不专业了

**Comment by jbiao520** [comment]
真的low

**Comment by jhoneybee** [comment]
> 这操作太秀了哟

简直是天秀

**Comment by cjim8889** [comment]
太不专业了

**Comment by TonyAble** [comment]
贵司这么滥用issue?

**Comment by keepersay** [comment]
一波天秀，armory团队记得也不小啊

**Comment by xiaohuilam** [comment]
## 蔡徐坤邀你打篮球
- [ ] 同意
- [ ] 拒绝
- [ ] 和篮球一起打蔡徐坤

**Comment by xiaohuilam** [comment]
## 蔡徐坤邀你打篮球
- [ ] 同意
- [ ] 拒绝
- [ ] 和篮球一起打蔡徐坤

**Comment by DoctorLai** [comment]
666

**Comment by lslie** [comment]
服服服

**Comment by alfedsun** [comment]
果然HR的思维无法用常理推测

**Comment by YouRNotPaulChan** [comment]
666，这HR的逆向思维能力挺强的，支持！🐶

**Comment by BlueNoob** [comment]
V2过来的, 无关阿里, ylxfc你个垃圾
