### ISSUE TITLE
Docker镜像部署体验，用户注销跳转异常

### ISSUE THREAD

**Issue by Koooooo-7** [Tencent/bk-cmdb#2847]
问题描述
===========

采用[Docker极速体验](https://github.com/Tencent/bk-cmdb/blob/master/docs/wiki/container-support.md)部署在内网服务器上（eg:192.168.0.87）后。
在自己本地可以正常访问`http://192.168.0.87:8081/#/index`，但是点击注销后。
注销跳转地址为：
`http://127.0.0.1/login/?app_id=cc&c_url=http://127.0.0.1:8090`

重现方法
================

采用Docker部署在内网服务器上（eg:192.168.0.87）。
- `docker pull ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:latest`
- `docker run -d -p 8081:8090 ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:latest`  

在自己本地访问远端服务器`http://192.168.0.87:8081/#/index`点击**注销**。

可能原因：没有获取宿主机的IP，接收到的请求都来自宿主机本地转发。

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: latest
镜像信息

| REPOSITORY                                   | TAG          | IMAGE ID     |
| -------------------------------------------- | ------------ | ------------ |
| ccr.ccs.tencentyun.com/bk.io/cmdb-standalone | latest| e901f1a49400 |

 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@Koooooo-7 你好，镜像体验本身不带用户管理，所以注册功能是无法使用的。
如果还有其它问题请再反馈。

**Comment by wanghaisheng** [comment]
@breezelxp 哪个版本是包含用户管理的呢？

**Comment by breezelxp** [comment]
@wanghaisheng 请关注蓝鲸社区版 www.bk.tencent.com

**Comment by wanghaisheng** [comment]
@breezelxp 链接给错了吗
