### ISSUE TITLE
部署文档中 mongodb版本不对

### ISSUE THREAD

**Issue by makerwei** [Tencent/bk-cmdb#2850]
问题描述
===========

![image](https://user-images.githubusercontent.com/43264876/62342654-37b69300-b51a-11e9-8f13-545ac88f16ee.png)
如果mongodb版本低于 3.4版本
会出现模型唯一校验字段设置失败。
经查看源码是因为 在聚合查询中 使用的了 $count
![image](https://user-images.githubusercontent.com/43264876/62342753-8fed9500-b51a-11e9-9a2f-6117516ba23e.png)

而 $count是在mongo3.4以后支持的
![image](https://user-images.githubusercontent.com/43264876/62342772-a1cf3800-b51a-11e9-8946-449da9ff8658.png)

重现方法
================
mongo版本用低于 3.4的版本，然后设置模型的唯一校验字段

关键信息
=========

**Comment by breezelxp** [comment]
@makerwei 感谢反馈，我们更新下说明文档

**Comment by makerwei** [comment]
@breezelxp 是不是应该都兼容一下呢？我们公司现在还是3.2的。。。

**Comment by breezelxp** [comment]
@makerwei 我们v3.2的版本还在继续发包，可以提交兼容代码，我们审核合入。

**Comment by makerwei** [comment]
@breezelxp 好的。
