### ISSUE TITLE
记录有问题的接口

### ISSUE THREAD

**Issue by wcy00000000000000** [Tencent/bk-cmdb#2855]
问题描述
===========
/api/{version}/objectatt/group/update 非必填字段填充默认值
/objectatt/group/owner/{owner_id}/object/{bk_object_id}/propertyids/{property_id}/groupids/{group_id} 删除不成功
/api/{version}/module/{bk_biz_id}/{bk_set_id} 必填字段bk_parent_id未校验是否赋值
/inst/search/{owner_id}/{bk_obj_id}/{inst_id} url参数解析错误

请提供以下信息:

 - [x] bk-cmdb   版本: 3.5
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by wcy00000000000000** [comment]
hosts/property/clone 克隆资源池主机时bizid填-1时返回业务[-1]不存在克隆失败，再填1之后返回数据唯一性校验失败
/api/{version}/hosts/modules 从业务内模块转移到故障机/空闲机后主机同时存在于2个模块

**Comment by rentiansheng** [comment]
/api/{version}/hosts/modules 从业务内模块转移到故障机/空闲机后主机同时存在于2个模块

已经处理。

**Comment by rentiansheng** [comment]
hosts/property/clone  已经处理

**Comment by wcy00000000000000** [comment]
/create/proc/service_instance 进程创建不成功时未回滚
create/proc/process_instance 使用相同进程别名时错误信息为进程别名[%!s(*string=0xc0002ed990)]唯一校验失败
update/proc/process_instance 使用相同进程别名时错误信息为进程别名[%!s(*string=0xc000358100)]唯一校验失败
/module/{bk_biz_id}/{bk_set_id} 未校验service_category_id对应的服务分类是否存在
createmany/proc/proc_template 可以创建bk_func_name和bk_process_name均为空的进程模板
find/proc/service_instance/difference 返回值中added数组中的service_instances数组包含已有新增进程模板对应进程的service_instance。删除进程模板后removed数组为空。
/createmany/proc/service_instance/labels 批量添加时其中有非法service_instance时之前的添加成功
/deletemany/proc/service_instance/labels  批量删除时其中有非法service_instance时之前的删除成功
更新服务模板的服务分类后使用模板的模块的服务分类未同步更新导致模块的服务分类与模板的服务分类不匹配

**Comment by hoffermei** [comment]
单独起issue跟进 #2927

**Comment by wcy00000000000000** [comment]
/object/host/audit/search缺少使用/hosts/modules/idle/set从模块转移到空闲池的记录
/hosts/add 添加主机时云区域未做校验
/hosts/modules 转移空闲主机到业务内模块报错拓扑模块没找到，主机未判断模块是否为业务内模块
/hosts/modules/idle/set 未校验业务、集群、模块是否存在和匹配
/hosts/modules/fault 有一个不存在的hostid时前面的转移成功，且把故障机再次转移到故障机模块时报错主机不存在
/hosts/batch 更新和删除接口均在有一个不存在的hostid时前面的操作成功，更新有不存在属性时成功
/hosts/sync/new/host 同步主机到多个不同业务的模块成功
/hosts/favorites 没有校验必填字段是否填写
/userapi 没有校验必填字段是否填写
/hosts/favorites/{id} 未判断id是否存在
userapi/data/{bk_biz_id}/{id}/{start}/{limit} 未校验start和limit是否合法

**Comment by fireyun** [comment]
单独起issue跟进 #3169
