### ISSUE TITLE
能否做一个主机配置变通自动通知的功能

### ISSUE THREAD

**Issue by liuhanbo123** [Tencent/bk-cmdb#2861]
问题描述
===========

成功安装agent的主机，在自动发现的配置变成的时候，发出通知，比如CPU由1个变成2个，发送通知。

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by rentiansheng** [comment]
可以使用事件订阅的功能的。

**Comment by liuhanbo123** [comment]
如何使用呢，能否有详细告知？

**Comment by liuhanbo123** [comment]
> 可以使用事件订阅的功能的。

如何使用呢，能否详细告知
