### ISSUE TITLE
配置平台Agent问题

### ISSUE THREAD

**Issue by PolarPeak** [Tencent/bk-cmdb#2911]
问题描述
===========

配置平台安装成功，但是怎么弄Agent呢

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@PolarPeak 请关注蓝鲸社区版了解相关agent的信息。 www.bk.tencent.com
