### ISSUE TITLE
建议官方更新docker image，镜像版本是三个月前的V3.2.2，现在最新release已经是3.2.17了~

### ISSUE THREAD

**Issue by pythonton** [Tencent/bk-cmdb#2923]
问题描述
===========

![image](https://user-images.githubusercontent.com/50493427/62817008-2c8ae500-bb62-11e9-943e-df4fd0cd2e69.png)

![image](https://user-images.githubusercontent.com/50493427/62817016-49271d00-bb62-11e9-830c-e99c9e24d848.png)

**Comment by breezelxp** [comment]
@pythonton 社区会在社区版正式发布release后会发布v3.2.17的容器镜像，届时请关注。
