### ISSUE TITLE
规范时间格式

### ISSUE THREAD

**Issue by hoffermei** [Tencent/bk-cmdb#2931]
问题描述
===========
## 背景
最近job系统对cmdb项目的返回格式进行了严格校验，如果不符合预期直接异常，但是最近cmdb项目出现了返回时间串没有毫秒的情况，导致job系统崩溃。

## 目标
- 输入输出时间格式需要统一起来

## 暂定时间格式  
- RFC3339Nano = "2006-01-02T15:04:05Z07:00"
- 参考资料 [go-time](https://golang.org/pkg/time/)

## 改善措施
- 检查所有的输入时间串格式
- 检查所有的输入出时间格式串
- 添加migrate对历史数据变更

关键信息
=========
 - [x] bk-cmdb   版本: v3.5.x

**Comment by rentiansheng** [comment]
现在最主要的问题是是反序列。带代码统一使用 util.GetCurrentTimePtr(), metadata.Time

**Comment by hoffermei** [comment]
需要统一时间处理方法，目前有三个源：
- common.metadata.time
- common.util.time
- go/time
