### ISSUE TITLE
v3.5.2 自己创建的节点不能删除，不能编辑信息

### ISSUE THREAD

**Issue by Icedroid** [Tencent/bk-cmdb#2971]
问题描述
===========
最新的发布版本服务拓扑的节点无法删除，无法编辑信息。

重现方法
================
在服务中新建节点，删除节点，编辑节点

请提供以下信息:

 - [x] bk-cmdb   版本: 
 ./cmdb/cmdb-apiserver --version 输出的内容:
./cmdb_apiserver --version
Version  : v3.5.1
Tag      :
BuildTime: 2019-08-19T14:58:17+0800
GitHash  :
RunMode  : product

**Comment by joe511230** [comment]
提供一下问题截图，前端控制台消息等信息
