### ISSUE TITLE
请求200,  首页显示空白

### ISSUE THREAD

**Issue by zhoushiyang** [Tencent/bk-cmdb#3]
request 200 OK
but Unable to display index page
index page is blank
what's that?

log info
172.26.1.118 - - [19/Dec/2016:18:21:21 +0800] "GET / HTTP/1.1" 200 5 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36"

**Comment by zhoushiyang** [comment]
ask for help

**Comment by zhoushiyang** [comment]
php index.php /cli/Init/initUserData 执行初始化时有报错
打印如下：
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Asia/Chongqing' for 'CST/8.0/no DST' instead in /opt/bkcmdb/bk-cmdb-master/system/core/Log.php on line 176
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Asia/Chongqing' for 'CST/8.0/no DST' instead in /opt/bkcmdb/bk-cmdb-master/system/core/Log.php on line 204

**Comment by zhoushiyang** [comment]
切换到工程根目录下执行php index.php /cli/Init/initUserData
没有数据插入到表中，目前整个数据库实例的所有表中均没有数据，是否导致空白的原因，请官方尽快给个答复, 谢谢！

**Comment by huangmeng4520** [comment]
我的问题和你一样，在日志里面发现问题了，执行php index.php /cli/Init/initUserData命令时，报错了
ERROR - 2016-12-21 15:23:59 --> Severity: error --> Exception: Call to undefined function mysql_connect() /var/www/system/database/drivers/mysql/mysql_driver.php 136

**Comment by huangmeng4520** [comment]
@tencent-adm  

1. 本人使用docker搭建环境

/config/development/constants.php 里面的配置已经改成主机访问地址
![image](https://cloud.githubusercontent.com/assets/8178576/21380975/a5828500-c793-11e6-9fd3-10a42ef00870.png)

创建数据库，导入sql文件执行数据初始化已经完成

执行 php index.php /cli/Init/initUserData 命令时报错
![Uploading image.png…]()

导致访问时主机空白 /account/login?cburl=  默认缺少cbcurl参数

**Comment by lowenitt** [comment]
请按以下顺序配置：
1.建数据库，导入项目中提供的sql文件
2.在db.php中配置数据库访问
3.执行命令

**Comment by huangmeng4520** [comment]
就是按照这个顺序执行的，sql已经导入cmdb库，db.php已经配置。执行命令时日志就报错，我用的php是7.0.2版本。

**Comment by huangmeng4520** [comment]
就是按照这个顺序执行的，sql已经导入cmdb库，db.php已经配置。执行命令时日志就报错，我用的php是7.0.2版本。

**Comment by vipsql** [comment]
同样的问题

**Comment by lowenitt** [comment]
也都是php7 执行命令报错吗？

**Comment by raindylong** [comment]
一样的梗，php7.0缺省已经不支持老版本的"mysql"扩展了，php7以后都是推荐直接用pdo_mysql了。

**Comment by lowenitt** [comment]
可以直接切换
	'dbdriver' => 'mysql',
修改下php下的驱动吧

**Comment by gavindev** [comment]
空白页还有一种可能是$config['sess_save_path'] 指定的路径不能写，可以指定为
>$config['sess_save_path'] = '/tmp/session';

**Comment by vipsql** [comment]
php版本7.0+;修改dbdriver=>'mysqli'即可

**Comment by zhoushiyang** [comment]
已找到原因，php执行程序的版本过低，执行初始化的时候没有插入数据。
