### ISSUE TITLE
主机查询菜单出错

### ISSUE THREAD

**Issue by jcqxr** [Tencent/bk-cmdb#30]
主机查询菜单出错：

A PHP Error was encountered
Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: controllers/Host.php

Line Number: 117

Backtrace:

File: /DATA/app/bk/bk-cmdb/application/controllers/Host.php
Line: 117
Function: _error_handler 

File: /DATA/app/bk/bk-cmdb/application/controllers/Host.php
Line: 52
Function: getHostFieldSelect 

File: /DATA/app/bk/bk-cmdb/index.php
Line: 293
Function: require_once 

这有办法处理吗？求问

**Comment by lowenitt** [comment]
有截图吗，页面的错误截图，日报报的warning日志基本可以忽略

**Comment by jcqxr** [comment]
关闭index.php的报错后，网页显示正常了
