### ISSUE TITLE
内置模型初始位置信息

### ISSUE THREAD

**Issue by ProtosL** [Tencent/bk-cmdb#300]
以下位置信息写入对应模型的position字段中
========
主机：          `{"bk_host_manage":{"x":-600,"y":-650}}`
进程：           `{"bk_host_manage":{"x":-450,"y":-650}}`
子网区域：   `{"bk_host_manage":{"x":-600,"y":-500}}`

业务：          `{"bk_organization":{"x":-100,"y":-100}}`

交换机：       `{"bk_network":{"x":-200,"y":-50}}`
路由器：       `{"bk_network":{"x":-350,"y":-50}}`
防火墙：       `{"bk_network":{"x":-500,"y":-50}}`
负载均衡：   `{"bk_network":{"x":-650,"y":-50}}`

weblogic：  `{"bk_middleware":{"x":-200,"y":-50}}`
apache：     `{"bk_middleware":{"x":-500,"y":-50}}`
tomcat：     `{"bk_middleware":{"x":-350,"y":-50}}`

**Comment by wusendong** [comment]
已更新
