### ISSUE TITLE
release版本未提供二进制包 docker镜像未更新

### ISSUE THREAD

**Issue by sakura1357** [Tencent/bk-cmdb#3059]
问题描述
===========
1.release版本未提供二进制包；
2.docker镜像长时间没更新，当前最新版已经3.5.x了；
3.未及时更新README等文档。
为了部署方便用的docker latest镜像，发现导入主机失败，页面就显示一个红×窗口，什么提示都没有，发现docker镜像的版本还在3.2.x，然后就想换最新版的试试。找官方最新release二进制包，结果release的都是源码包，还要搞半天编译环境。本身就是想快速部署试用一下，结果搞得这么麻烦。既然是开源出来了，希望能认真对待一下，及时更新文档，最起码二进制包及时release出来吧。

**Comment by breezelxp** [comment]
@sakura1357 由于最新的版本还未product ready，所以一直未发布正式的release。不过近期会发布两个release版本v3.2的最新版本和v3.5的最新版本，届时请关注下。
