### ISSUE TITLE
一句话出现了2次是有什么深意吗 没看懂

### ISSUE THREAD

**Issue by zixiliuyue** [Tencent/bk-cmdb#3065]
问题描述
===========
一句话出现了2次是有什么深意吗 没看懂
https://github.com/Tencent/bk-cmdb/blob/master/src/apiserver/app/server.go

关键信息
=========

![image](https://user-images.githubusercontent.com/12575317/64087410-78026e80-cd6f-11e9-871b-8d9c87e0908e.png)

**Comment by breezelxp** [comment]
@zixiliuyue 感谢反馈，已经处理。
