### ISSUE TITLE
如何修改通过更改源码制作能连接外部mongodb的docker镜像

### ISSUE THREAD

**Issue by whb1998a** [Tencent/bk-cmdb#3067]
问题描述
===========
docker体验版cmdb使用镜像内置的mongodb，如何通过修改配置的方式制作一个能够向容器外部的mongodb存取数据的docker镜像。

重现方法
无

关键信息
=========
docker镜像版本：ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:v3.2.2

**Comment by breezelxp** [comment]
@whb1998a 你好，你的场景是什么？这个只是为了让大家体验方便，并不适合用于生产环境。

**Comment by whb1998a** [comment]
我想运行多个cmdb容器，共享外界的一个mongodb，而不是镜像中自带的那个

**Comment by whb1998a** [comment]
@breezelxp 
我想运行多个cmdb容器，共享外界的一个mongodb，而不是镜像中自带的那个

**Comment by breezelxp** [comment]
> @breezelxp
> 我想运行多个cmdb容器，共享外界的一个mongodb，而不是镜像中自带的那个

你好，容器化部署的方式需要用户对容器本身比较了解，社区在考虑提供容器化的生产环境部署方式，但这个同时也依赖于用户使用的容器编排系统。

如果有什么想法，我们可以深入沟通一下，看看你的使用场景。
