### ISSUE TITLE
新增用户在 主机管理-主机查询-查询结果-点击内网IP报错

### ISSUE THREAD

**Issue by lyy8510a** [Tencent/bk-cmdb#31]
A Database Error Occurred

Error Number: 1364

Field 'DefaultColumn' doesn't have a default value

INSERT INTO `cc_UserCustom` (`UserName`) VALUES ('22222')

Filename: models/UserCustomModel.php

Line Number: 38

**Comment by lowenitt** [comment]
给数据库字段添加一个默认值吧，不同数据库版本的兼容性有点问题
