### ISSUE TITLE
编译报错，怎么处理？

### ISSUE THREAD

**Issue by amoyx** [Tencent/bk-cmdb#3200]
下载的release包，目录结构
![image](https://user-images.githubusercontent.com/19795002/65567533-38532f00-df89-11e9-8093-90ebf6e034f0.png)
？
但是安装文档给出的目录结构
![image](https://user-images.githubusercontent.com/19795002/65567566-515be000-df89-11e9-908c-496455a3e509.png)

想着自己编译, 编译时报错？
![image](https://user-images.githubusercontent.com/19795002/65567598-6b95be00-df89-11e9-8071-e6fe235f7aa5.png)

**Comment by breezelxp** [comment]
@amoyx 你好，你的GOPATH没有配置对，请确认下你的GOPATH是否正确。
