### ISSUE TITLE
3.5.x版本 模型管理中字段分组，字段不能编辑移动

### ISSUE THREAD

**Issue by zqzqy04** [Tencent/bk-cmdb#3202]
问题描述
===========
3.5.x版本 模型管理中字段分组，字段不能编辑移动

重现方法
================
查看--模型管理-模型-字段分组

不能移动字段，之前版本可以自由拖动

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by joe511230** [comment]
@zqzqy04 这个应该是cmdb依赖的vuedraggable组件，其内部依赖sortablejs升级了导致vuedraggable不可用引起的，可以在src\ui\package.json中的dependencies中声明sortablejs版本为1.8.4解决

**Comment by zqzqy04** [comment]
@joe511230 测试了，不行，dragable这个包版本依赖的是 ^x.x.x,大版本，不变回还是自动拉最新版本。

**Comment by zqzqy04** [comment]
按提供方法修改，已经解决，tks！
