### ISSUE TITLE
glog 引用问题

### ISSUE THREAD

**Issue by appendHan** [Tencent/bk-cmdb#3222]
vendor 下面的这个[glog](https://github.com/Tencent/bk-cmdb/tree/master/vendor/github.com/golang/glog)是二次开发的吧，我在你们[云容器管理平台](https://github.com/Tencent/bk-bcs/tree/master/bcs-common/common/blog)搜到了一样的这部分代码，是不是可以复制到本地或者引用其他项目，不要直接修改vendor代码好点

**Comment by breezelxp** [comment]
@appendHan glog的代码是做了部分调整。怎么用这个，你根据实际情况用就行了。
