### ISSUE TITLE
梳理并移除已下线接口

### ISSUE THREAD

**Issue by hoffermei** [Tencent/bk-cmdb#3237]
问题描述
===========
部分看起来是给前端提供的接口，前端已经没有使用，可以清理，清理前需要确保在网关中没有注册

关键信息
=========
 - [x] bk-cmdb   版本: v3.6.x

**Comment by breezelxp** [comment]
toposerver: 
/findmany/inst/association/object/{bk_obj_id}/inst_id/{id}/offset/{start}/limit/{limit}

**Comment by hoffermei** [comment]
toposerver:
/api/v3/find/insttopo/object/[^\s/]+/inst/[0-9]+/?$

**Comment by hoffermei** [comment]
toposerver:
/api/v3/delete/objectattgroupasst/object/[^\s/]+/property/[^\s/]+/group/[^\s/]+/?$

**Comment by hoffermei** [comment]
toposerver:
- [ ] `^/api/v3/topoinstchild/object/[^\s/]+/biz/[0-9]+/inst/[0-9]+/?$`
