### ISSUE TITLE
php7.1.1  都正常，主页HTTP ERROR 500

### ISSUE THREAD

**Issue by opser-gavin** [Tencent/bk-cmdb#33]
![image](https://cloud.githubusercontent.com/assets/25680177/22816739/ad2d0680-ef9e-11e6-972b-b81691d42338.png)

phpinfo ,, mysqli 都正常。

求大大解答 跪谢，  gongshubing.vip@qq.com

**Comment by lowenitt** [comment]
这种应该是服务器没配置好吧

**Comment by zhankaiwen** [comment]
看下app里面的日志，我估计和php 7的问题有关 #7

**Comment by zhankaiwen** [comment]
@lowenitt 看下，cmdb的应用里是有日志的，我估计应该是php7的mysql支持问题。参考： #7 
推荐安装5.6.9以上，7.0以下版本。个人理解

**Comment by lowenitt** [comment]
可以通过设置
		error_reporting(1);
		ini_set('display_errors', 1);
把报错打开。
