### ISSUE TITLE
有没有最新的版本的docker 体验包

### ISSUE THREAD

**Issue by smile-wang** [Tencent/bk-cmdb#3319]
问题描述
===========
docke 的体验包，不是最新的版本，安装之后 跟官网完整包里面的有很大区别

重现方法
================
1、拉取docker 快速体验包

2、安装  完整包

关键信息
=========
演示的版本差异，没有做到演示 统一

**Comment by breezelxp** [comment]
@smile-wang 今天会更新在线体验的cmdb版本

**Comment by smile-wang** [comment]
啥时候，快下班了。。。。今天还能出么。不能出，我明天在看

**Comment by breezelxp** [comment]
@smile-wang 已经更新了，你看下

**Comment by smile-wang** [comment]
还是跟社区办 不一样。~~纠结。。社区办 太大了。。我用不到那么多功能 只需要 CMDB 就足够了。。
