### ISSUE TITLE
蓝鲸CMDB模型关联

### ISSUE THREAD

**Issue by lich-y** [Tencent/bk-cmdb#3350]
问题描述
===========

在CMDB的模型关联中，没有批量关联的功能
CMDB的模型关联中没有通过两个模型中的共同属性进行关联的功能

重现方法
================

例如host主机和虚机之间的关联，在虚机中会有host主机的主机名属性，建议增加一个通过共同属性来进行模型拓扑关联的功能
还有就是在做了1对N的关联后，在点击关联的时候，右侧没有下拉列表，只能显示搜索出来的10条记录

**Comment by breezelxp** [comment]
@lich-y 你好，收到你的建议，我们考虑下这个形态。

**Comment by breezelxp** [comment]
@lich-y 请问你使用的是那个版本？
