### ISSUE TITLE
特性：给操作自定义层级上锁

### ISSUE THREAD

**Issue by hoffermei** [Tencent/bk-cmdb#3370]
问题描述
===========
增加/减少自定义层级时，需要对所有业务对应增加减少自定义层级的实例，耗时较长，如果这期间出现其它用户增加/减少自定义层级，或者新增集群操作，容易出现数据完整性问题

## 方案
- 增加/较少自定义层级时，上全局锁，如果上锁失败，则提示错误，请稍后重试
- 添加集群/自定义层级节点/创建业务时，检查全局锁，如果被锁定状态，则不进行变更操作，直接错误，请稍后重试

关键信息
=========
 - [x] bk-cmdb   版本: v3.5.x

**Comment by rentiansheng** [comment]
疑问：
1. 业务展示是基于拓扑模版。 在修改主线模型的同时，展示业务会有问题？ 
2. 如何避免前端由于也没有刷新。传过来的parent id 错误的问题？ 
3. 自定义层级新加/删除中断。 是死锁，还是回滚，还是重试？

建议
1. 对主线做版本控制或者是快照
2. 业务中新加主线版本
3. 记录主线变更策略
