### ISSUE TITLE
【调研】改动方案评审

### ISSUE THREAD

**Issue by uriwang** [Tencent/bk-cmdb#339]
1. 对实施方案进行梳理；
2. 评估改动影响涉及到的所有功能项；
3. 确定修改后需要重点测试的功能点；

**Comment by uriwang** [comment]
# 需求由： 
拓扑关系的管理，可以支持正向拓扑结构的查询，也支持逆向拓扑结构的查询。 

# 增加至： 
1. 取消模型通过字段与另一个实例进行关联的设计； 
2. 关联关系提升为一类资源来管理，并提供管理的API 
3. 模型之间的关联关系不再通过模型的字段进行配置，改为通过关联对象进行描述 关联改动项特别多需要重新评估开发时间。

**Comment by uriwang** [comment]
已确定最终产品形态是 关联关系是做为一个独立的资源进行管理，未来模型的字段里不会在出现关联字段。

需要结合现在的情况 设计实施方案以平稳安全的达到最终状态。

@techfindd

**Comment by techfindd** [comment]
已经确认

**Comment by uriwang** [comment]
1. 开辟专有的关联关系关联的接口用于关联关系管理；
2. 给定节点的父子节点的关联拓扑查询用新API 来支持；
3. 关联分两类，一类是通过模型字段来实现；另一类是将关联作为独立的资源来管理， 通过独立的关系描述来实现两个模型间的关联管理；
4. 关联作为独立的资源管理，需要提供一组专用的API来实现，在新的API实现后再将老的API做兼容处理；
5. 在完成API切换后需要对存量数据做升级迁移到新的模式下工作；

**Comment by techfindd** [comment]
目前需要支持显示实例的上下关联项，只需要实现要点2即可
