### ISSUE TITLE
企业信息化资产CMDB，无法适配模型

### ISSUE THREAD

**Issue by net592** [Tencent/bk-cmdb#3492]
问题描述
===========
我的环境，有大量异构环境设备。我想使用蓝鲸CMDB来套用 我们资产环境
但是我根据目前demo，发现我们是完全是根据 主机 维度的 CMDB。
不太适配，企业信息化CMDB系统，
比如我们一组业务，下面有一些主机，网络设备，UPS，某某设备。无法适配企业需求。
蓝鲸团队有啥想法，我得厂家网络设备和服务器都很多，感谢~蓝鲸很棒的项目

**Comment by breezelxp** [comment]
除了主机维度的管理外，蓝鲸cmdb还有模型与模型实例，关联关系的管理，根据你描述的场景，适合用模型与模型的实例管理你们的网络设备等。

**Comment by net592** [comment]
嗯嗯感谢。
我也想基于蓝鲸做二次开发，
但是模型与模型实际我测试来看，没办法满足，企业级CMDB需求
具体，我一个业务团队组拥有：服务器，交换机，路由器，等设备资产，我需要给他划分到业务树上。
我尝试各种方式，无法这样绑定，只能绑定服务器而且还必须有IP，在一些场景下我的设备可能没有IP，如二层MAC环境和IOT环境，可能是通过别的非IP方式连接。
可能咱们适配在纯服务器有IP的运维场景， 一些传统运维场景没有itop
我的业务服务树，应该只是逻辑组，我把我自定义资产能往篮子里放就行了，限制死主机，零活度就下降了，我是偏网络部门运维团队，大概有1W台设备资产。。。

**Comment by breezelxp** [comment]
请问你是单独使用cmdb呢，还是使用的蓝鲸社区版呢?

服务器，交换机这些属于公共资产，应该和业务本身无关，所以在形态上目前还没有纳入业务的管理范畴。如果是不同的团队管理不同的公共资产，目前是可以管理的，可以配合相应的权限管理分团队管理。

**Comment by net592** [comment]
就是当前开源版本  https://github.com/Tencent/bk-cmdb
可能我的环境比较封闭偏基础设备团队，虽然是某东类互联网公司，和咱们是战略合作友军。
网络一类基础设备不是公用是我们来运维管理的，只是我们提供更多业务团队使用，他们是公共资产。
但是对于我们来说，是管理的资产，包括服务器，可能理解上偏传统CMDB场景

**Comment by breezelxp** [comment]
欢迎**战略友军**加入我们的开源社区😄
我们也有业务级模型的管理，但是目前还未外放，看你的场景应该是需要这种形态，可以后续关注一下。或者有什么想法也可以交流下。

**Comment by net592** [comment]
好的😄，感谢希望能早日放出，已加群，持续关注。
 cmdb是最基础功能，这个开放的号，其他相关 模块才有机会用起来，哪怕付费使用也有经费预算哈，
看来没有现成只能先拿某团服务树代码自己改了，希望咱们开源的项目越来越好，众人拾柴火焰高，目前来看蓝鲸还是目前最成熟的项目

**Comment by breezelxp** [comment]
@net592 🌹可以去bk.tencent.com这里看下，我们有蓝鲸社区版，免费的，是完整的企业运维解决方案，而且蓝鲸的很多服务现在也在逐步开源，欢迎试用。

**Comment by breezelxp** [comment]
@net592 我QQ号，2859592807，可以加下聊聊哈😄

**Comment by net592** [comment]
@breezelxp 好的哈，Thk🌹

**Comment by net592** [comment]
关闭问题原因：持续关注，该需求目前木有，待开发开放.
