### ISSUE TITLE
主机身份定义

### ISSUE THREAD

**Issue by wusendong** [Tencent/bk-cmdb#357]
@techfindd 
请bence在下方定义主机身份

**Comment by techfindd** [comment]
[agent身份信息下发.txt](https://github.com/Tencent/bk-cmdb/files/1978476/agent.txt)

**Comment by wusendong** [comment]
@techfindd 请问下面几个字段哪里在哪里找到？
主机运行状态（bk_host_status）  数字
集群服务状态（bk_set_status）   数字
环境类型（bk_set_type）         数字
