### ISSUE TITLE
不能通过IP进行跨业务查询，只能精确到业务进行搜索

### ISSUE THREAD

**Issue by kyyang** [Tencent/bk-cmdb#368]
问题描述
===========
只知道IP情况下不能快速查询到IP所在业务及相关主机信息

不能通过IP进行跨业务查询，只能精确到业务进行搜索

**Comment by lowenitt** [comment]
@techfindd     是的，按照目前的设计，  只吃下在业务下和资源池下搜索主机

**Comment by kyyang** [comment]
这需求在后续会考虑进去吗？

**Comment by joe511230** [comment]
新版首页已支持跨业务搜索主机，点击搜索结果会跳转到对应的资源池或业务下，并精确筛选出该主机
