### ISSUE TITLE
数据唯一性校验失败， instance 重复

### ISSUE THREAD

**Issue by maguic** [Tencent/bk-cmdb#3689]
问题描述
===========
1、创建模型A的时候弹出“数据唯一性校验失败， instance 重复”
2、A下新建实例，导出实例，报“Download failure”

重现方法
================

1、直接通过源码部署，不通过docker方式部署。其中mongodb是2.8版本
2、创建新的模型分组
3、在新的分组下创建新的模型

3.5.15、3.6.2和master三个版本部署都有这个问题

关键信息
=========

 - [x] bk-cmdb   版本: 
Version  : v3.6.2
Tag      : release-v3.6.2
BuildTime: 2019-12-24T07:40:15+0000
GitHash  : 0578fa016d82b64d5ec68515228994f7a2aa043f
RunMode  : product

Redis：3.2.12
zooKeeper：3.4.14
MongoDB：MongoDB shell version: 2.8.0-rc5

 - [ ] bk-cmdb 异常日志
pipeline:  [{"$match":{"bk_obj_id":"aaccd","metadata.label.bk_biz_id":{"$exists":false}}},{"$group":{"_id":{"bk_inst_name":"$bk_inst_name"},"total":{"$sum":1}}},{"$match":{"total":{"$gt":1}}},{"$count":"unique_count"}]
E1226 08:29:46.544102   16192 model/unique_crud.go:333] [ObjectUnique] recheckUniqueForExistsInsts failed exception: Unrecognized pipeline stage name: '$count', pipeline: [{"$match":{"bk_obj_id":"aaccd","metadata.label.bk_biz_id":{"$exists":false}}},{"$group":{"_id":{"bk_inst_name":"$bk_inst_name"},"total":{"$sum":1}}},{"$match":{"total":{"$gt":1}}},{"$count":"unique_count"}], rid: "cc0000bo26uuh9mjejvsstisog"
E1226 08:29:46.544120   16192 model/unique_crud.go:84] [CreateObjectUnique] recheckUniqueForExistsInsts for aaccd with metadata.CreateModelAttrUnique{Data:metadata.ObjectUnique{ID:0x0, ObjID:"aaccd", MustCheck:true, Keys:[]metadata.UniqueKey{metadata.UniqueKey{Kind:"property", ID:0xbe}}, Ispre:false, OwnerID:"", Metadata:metadata.Metadata{Label:metadata.Label(nil)}, LastTime:metadata.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}}} err: &mgo.QueryError{Code:16436, Message:"exception: Unrecognized pipeline stage name: '$count'", Assertion:false}, rid: cc0000bo26uuh9mjejvsstisog

**Comment by breezelxp** [comment]
好的，我们看一下

**Comment by breezelxp** [comment]
@maguic 应该是你的mongodb版本过底导致，聚合的命令没支持。所以你升下mongodb的版本，可以升到v4.2看下。
