### ISSUE TITLE
事件推送失败没有重试机制

### ISSUE THREAD

**Issue by bigV0616** [Tencent/bk-cmdb#369]
问题描述
===========
<这里写问题描述>

重现方法
================
<列出如何重现的方法或操作步骤>

**重要提醒**: 请优先尝试最新发布的版本 (发布清单： https://github.com/Tencent/bk-cmdb/releases), 如果问题不能在最新发布的版本里重现，说明此问题已经被修复。

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): `<示例： v3.0.6-alpha 或者 git sha. 请不要使用 "最新版本" 或 "当前版本"等无法准确定位代码版本的语句描述>`
 - [ ] Redis     版本: `<示例： 3.2.11>`
 - [ ] MongoDB   版本: `<示例： 2.8.0>`
 - [ ] ZooKeeper 版本: `<示例： 3.4.11>`
 - [ ] 操作系统      : `<示例： Centos 5 (x64)>`
 - [ ] bk-cmdb 异常日志

**Comment by wusendong** [comment]
谢谢您的回馈。是的，目前是没有事件推送重试机制的，因为没法完全的确认订阅者收到了消息，为了避免订阅者收到重复的事件所以没有主动重试。
想到有两种方法解决这个问题：
1. 只要没收到用户的确认收到标志，必须重传。这个方案会要求订阅者自己对重复事件去重（因为订阅者在较差的网络环境下还是可能收到消息但确认标志却发送失败的情况的），而且增加服务器的负担。
2. 每条事件消息只发一次，订阅者根据推送的自增ID主动查询漏收的事件。这个方案会减轻服务器负担，在大数据量事件推送中有优势。

至于采用哪种方案，我们会在后续的规划中深入讨论。
