### ISSUE TITLE
支持Helm Chart部署

### ISSUE THREAD

**Issue by hoffermei** [Tencent/bk-cmdb#3721]
需求描述
===========
- 支持通过 helm chart 部署到 kubernetes 环境

关键信息
=========
 - [x] bk-cmdb   版本: v3.6.x

**Comment by 27149chen** [comment]
@hoffermei  @breezelxp @joe511230 helm chart 只能支持到3.6，请问是否有计划支持最新的release（3.9）。我直接用3.9 的image 安装这个chart会有错误

**Comment by breezelxp** [comment]
近期会有3.9的镜像放出，具体时间还未定。

**Comment by 27149chen** [comment]
@breezelxp 会有对应的helm chart 吗？镜像可以自己打包，但是helm chart比较麻烦。
