### ISSUE TITLE
蓝鲸配置平台-》业务主机里面，主机基础属性问题

### ISSUE THREAD

**Issue by binema** [Tencent/bk-cmdb#3751]
问题描述
===========
蓝鲸配置平台-》业务主机里面，点击其中一个主机，再右侧弹出页面进行属性基础信息（主要维护人，备份维护人等）保存后，回到列表后，多选框勾选一个主机，此时点击左上角编辑按钮时，弹出的基础信息页面信息为空，不是应该显示我刚编辑完成的信息吗？

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by binema** [comment]
补充版本信息：
bk-cmdb 版本:3.2.21
 Redis 版本:4.0.12
 MongoDB 版本:3.6.3
 ZooKeeper 版本:3.4.10
 操作系统 :centos7.5
 bk-cmdb 异常日志

**Comment by techfindd** [comment]
第一个操作，点击主机进入是单个主机编辑
第二个操作，选中主机，然后点击“编辑”按钮是批量的操作，批量操作确实是空白，需要勾选字段进行批量调整。即使选中的是台主机，也是批量编辑的模式。

后续会优化这块的用户体验，勾选单个主机避免出现这个误解
