### ISSUE TITLE
接口调用能否给example

### ISSUE THREAD

**Issue by gqdw** [Tencent/bk-cmdb#376]
问题描述
===========
接口调用能否给example

**Comment by lowenitt** [comment]
https://documenter.getpostman.com/view/4203015/cmdb30-api-verify/RW1XKLaZ#intro   你好可以参考下这个postman文档中的调用示例

**Comment by gqdw** [comment]
收到，目前似乎不支持api登录，后期能否放开？

**Comment by lowenitt** [comment]
api 调用的话目前还是免登陆状态的
