### ISSUE TITLE
字段约束功能扩展

### ISSUE THREAD

**Issue by chestarss** [Tencent/bk-cmdb#3845]
问题描述
===========
比如有两个模型，
dns_domain 模型
b.com
c.com

dns_record 模型
中的domain_name字段只能从 b.com/c.com中选一个。

其中dns_record模型中有一个字段叫domain_name, 希望这个字段的约束是在 dns_domain 的记录里的

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@chestarss 你是希望模型之间的字段信息，可以有公共信息进行管理？

**Comment by chestarss** [comment]
@breezelxp 是的，就像外键一样，A模型的a字段约束限制在 另一个B模型b字段的所有取值范围里。
还有最好字段取值列表也支持对接外部接口返回的数据

**Comment by breezelxp** [comment]
@chestarss 大概了解你的意思了，社区考虑一下这种场景的解决方案
