### ISSUE TITLE
Bug机器变更记录里每10分钟会增加一条记录，但是字段没有变化

### ISSUE THREAD

**Issue by chestarss** [Tencent/bk-cmdb#3869]
问题描述
===========
变更记录里有大量这样的记录，点开查看字段前后并没有变化。

变更内容       变更账号        变更时间
-------------------------------------
 修改主机        |      cc_collector     |      2020-03-03 16:41:07
修改主机         |      cc_collector     |      2020-03-03 16:31:07
修改主机         |      cc_collector     |      2020-03-03 16:21:07

重现方法
安装gse_agent后， 点主机->变更记录查看

================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: V3.6.5
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by rentiansheng** [comment]
审计操作在对比修改前后变化的数据时候， 由于获取变更前的数据的数据包含_id字段，造成对比结果是发生变化。 从而记录变更日志。 

修复注意项目：
1. 忽略db系统字段。例如：mongodb 的_id字段
2. 忽略自动刚更新字段。 例如： last_time
3. 处理模型固定字段。例如： id，default 等不可能修改字段。
