### ISSUE TITLE
初步使用发现的问题

### ISSUE THREAD

**Issue by tristan-tsl** [Tencent/bk-cmdb#3881]
### 数据

数据导入方式贫乏, 例如主机无法从云平台导入数据

数据层叠关系不够, 功能使用的舒适度不够

数据展示不够清晰且不方便, 对比grafana

### 指令

没有打通指令->数据,同时数据->指令开放度不够/没有

### 业务

大量的运维业务被固化在产品中, 适配不易

开放程度不够, cmdb数据没有指向分发库导致多家公司/组织的数据模型建设工作重复

### 权限&审计

权限/审计系统内嵌到cmdb中, 导致权限/审计复杂且不易管理

### issue

issue重视程度不够

### 可用功能

收费功能相对于免费比率较大

**Comment by breezelxp** [comment]
欢迎体验使用蓝鲸配置平台(bk_cmdb)，云资源的管理（包含主机）能力目前社区正在开发迭代，不久即可对社区开发。
蓝鲸配置平台是蓝鲸智云体系的一部分，是蓝鲸PaaS平台中的一个原子平台。对于蓝鲸的整体能力可以移步bk.tencent.com了解。

关于你提到的权限部分，bk_cmdb适配了蓝鲸体系的权限管理能力，和蓝鲸体系的权限管理能力打能。当然社区在设计上，仍然是以插件的方式，向社区用户提供自主开发对接自有权限管理平台的能力。

最后，bk_cmdb不存在收费和免费功能一说，所有功能全部开源、开放。对于bk_cmdb依赖的一些能力，比如主机快照数据采集，需要配合蓝鲸社区版使用才可以，而蓝鲸社区版也是对外免费使用，具体信息也请移步bk.tencent.com了解。

**Comment by tristan-tsl** [comment]
我正在设计并编写一版CMDB系统, 希望后续能够继续跟进
