### ISSUE TITLE
编译安装报错

### ISSUE THREAD

**Issue by ma53192190** [Tencent/bk-cmdb#3892]
问题描述
===========
编译安装下载golang包时报错
go: found github.com/holmeswang/redistore in github.com/holmeswang/redistore v0.0.0-20181030115202-a3e76541222d
go: configcenter/src/web_server/app imports
        github.com/holmeswang/contrib/sessions imports
        github.com/holmeswang/redistore: github.com/holmeswang/redistore@v0.0.0-20181030115202-a3e76541222d: parsing go.mod:
        module declares its path as: github.com/boj/redistore
                but was required as: github.com/holmeswang/redistore

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
看起来像是没有指定gopath
