### ISSUE TITLE
port 31001 start failed, please check

### ISSUE THREAD

**Issue by ziflyingyo** [Tencent/bk-cmdb#3969]
问题描述
===========
 ./bk_install cmdb执行过程中提示错误port 31001 start failed, please check如何解决。

重现方法
================
cd /data/install
 ./bk_install cmdb

关键信息
使用标准部署方法执行部署cmdb脚本时出现如下错误。
172   exec initdata_cmdb on 172.28.65.46
104   start to make migration for cmdb ...
112   on-migrate ... /data/bkce/cmdb/server/on_migrate
22   waitting for ports ready ...
153   **port 31001 start failed, please check**
153   migrate failed for cmdb(server)
179   Abort

**Comment by breezelxp** [comment]
@ziflyingyo 看下31001是那个服务的端口，是什么原因这个服务没有启动起来。

**Comment by sdsz666** [comment]
遇到同样的问题
