### ISSUE TITLE
Standalone 镜像 latest 标签没有指向最新版本

### ISSUE THREAD

**Issue by AnyISalIn** [Tencent/bk-cmdb#3979]
问题描述
===========
公共仓库的 Standalone 镜像 latest 标签没有指向最新版本

![image](https://user-images.githubusercontent.com/16937838/77715685-39881600-7017-11ea-9825-14d85bc67a0b.png)

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@AnyISalIn 是的，我们会在社区版发布release后更新。
