### ISSUE TITLE
独立版的CMDB怎么对接权限中心

### ISSUE THREAD

**Issue by Coyote5** [Tencent/bk-cmdb#3986]
问题描述
===========
新手，请教大家两个问题：
1、独立版的CMDB怎么对接权限中心？
2、权限中心的代码在哪个库里，是否支持独立部署？

**Comment by breezelxp** [comment]
@Coyote5 你是要对接自己的权限中心，还是蓝鲸的权限中心？

**Comment by Coyote5** [comment]
蓝鲸的权限中心。早期的独立版CMDB里有模型的权限管理功能，3.6.5版没有了。是不是移到蓝鲸的权限中心了？

**Comment by breezelxp** [comment]
是的，是移到蓝鲸权限中心，原生就支持，不需要你额外对接。
你是用的蓝鲸社区版吗？还是只用了我们bk-cmdb?

**Comment by Coyote5** [comment]
只用了bk-cmdb，但需要权限功能。麻烦指点一下，谢谢。

**Comment by breezelxp** [comment]
你是只想用bk-cmdb,然后想带权限管理能力？
建议你还是用社区版。如果不用社区版，你需要利用已有的插件接口自已开发。

**Comment by Coyote5** [comment]
@breezelxp 是的，只想用bk-cmdb，然后想带权限管理能力。可以单独部署一个蓝鲸权限中心，用于bk-cmdb的权限管理吗？

**Comment by breezelxp** [comment]
蓝鲸权限中心是一个saas，依托于蓝鲸paas。所以不能单独部署蓝鲸权限中心。再有，有权限管理能力，还得配套有用户管理，用户管理也是一个saas。

**Comment by Coyote5** [comment]
谢谢。

**Comment by datuxing** [comment]
请问我单独部署了cmdb 3.6.5, 并且部署了蓝鲸社区版paas，请问cmdb应该怎么配置和paas关联？

**Comment by breezelxp** [comment]
你用的社区版? 社区版目前还没有蓝鲸权限中心

**Comment by datuxing** [comment]
> 你用的社区版? 社区版目前还没有蓝鲸权限中心

对，社区版的蓝鲸paas，所以cmdb我也应该用社区版的？3.2.x的cmdb自带权限管理？
