### ISSUE TITLE
咨询：多用户数据和权限隔离实现方案

### ISSUE THREAD

**Issue by l10178** [Tencent/bk-cmdb#4015]
问题描述
===========
实现类似于公有云多租户的功能。我有多个用户（租户）都是admin权限，每个用户之间的数据做到完全隔离，用户A看不到用户B的业务、拓扑、组织架构等等。

如何实现此类功能。

**Comment by breezelxp** [comment]
v3.5版本以上，结合蓝鲸权限中心的管理能力，即可满足你的需求

**Comment by l10178** [comment]
“权限中心”是一个新的独立的模块吗，没有看到这方便的介绍。
看到了一个“权限控制”的菜单，这里的权限控制满足不了我的要求，我想把模型、模型拓扑、业务模型这些各用户之间也可隔离。

**Comment by breezelxp** [comment]
@l10178 
1. 权限中心是蓝鲸的一个新的saas，用于管理蓝鲸产品的权限。不太清楚你用的是cmdb的那个版本，看起来是3.2的版本吧。借助于权限中心的能力可以做到模型和实例级别的权限管理能力，粒度已经非常细了。
2. 开发商是对标的租户的概念，但是管理不在蓝鲸cmdb，在蓝鲸的其它saas。

**Comment by l10178** [comment]
目前看来bk_supplier_id就是我想要的效果，我先把issues关了，如果有问题再来请教。
