### ISSUE TITLE
下载源码编码失败

### ISSUE THREAD

**Issue by jsyhsz** [Tencent/bk-cmdb#4052]
问题描述
===========

参照 下载编译 中的说明进行编译，在执行 make 时报错：
building server... 
bash: ./build.sh: 没有那个文件或目录
make: *** [default] 错误 127

重现方法
================

1、安装go环境；
2、下载源代码：git clone https://github.com/Tencent/bk-cmdb  configcenter  
3、到  configcenter/src目录下，执行：make

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by ericdong2012** [comment]
一样的问题，上午成功了一次，但是后面的部署各种问题，怀疑是版本问题，下午拉了个新的版本，结果到好，直接报错了，晕

**Comment by rentiansheng** [comment]
请使用v3.5.x 或者v3.8.x 的分支， 检查下是否安转了go ， 并且设置GOROOT 和GOPATH 相关的。

**Comment by rentiansheng** [comment]
@ericdong2012  请使用v3.5.x 或者v3.8.x 的分支， 检查下是否安转了go ， 并且设置GOROOT 和GOPATH 相关的。

**Comment by ericdong2012** [comment]
这个是我的锅，之前只是命令行export下，没有写到profile文件中，重开的窗口就没用了，导致make失效



---原始邮件---
发件人: "rentiansheng"<notifications@github.com&gt;
发送时间: 2020年7月22日(周三) 下午2:15
收件人: "Tencent/bk-cmdb"<bk-cmdb@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"ericdong2012"<2979544546@qq.com&gt;;
主题: Re: [Tencent/bk-cmdb] 下载源码编码失败 (#4052)




 
请使用v3.5.x 或者v3.8.x 的分支， 检查下是否安转了go ， 并且设置GOROOT 和GOPATH 相关的。
