### ISSUE TITLE
云区域只能通过 API 添加么？一个字段包含多个值除了拆分出模块还有什么方案么

### ISSUE THREAD

**Issue by AnyISalIn** [Tencent/bk-cmdb#4055]
问题描述
===========

最近基于蓝鲸进行平台的开发，遇到一些问题，希望蓝鲸团队能够解答一下，谢谢。

云区域只能通过 API 添加么？一个字段包含多个值除了拆分出一个单独的模型还有什么方案么？列表的使用场景是什么，目前没看出来和枚举的实际区别。

重现方法
================

关键信息
=========

请提供以下信息:

 - [ ] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by AnyISalIn** [comment]
主机有多个ip除了单独抽象出模型或者单独加一个字段外还有其他方案么？

**Comment by breezelxp** [comment]
多个IP，可以用逗号分开写入。

**Comment by AnyISalIn** [comment]
> 多个IP，可以用逗号分开写入。

字段不支持 Multi Value 还是觉得很诡异啊。。
