### ISSUE TITLE
按照github上的部署安装流程，部署失败

### ISSUE THREAD

**Issue by 1123183721** [Tencent/bk-cmdb#4107]
问题描述
===========
./start.sh执行后各进程启动ok，但是日志文件有异常日志，web无法访问
我太难了😭
关键信息
=========
请提供以下信息:

 - [x] bk-cmdb   版本: 
Version  : master
Tag      : master
BuildTime: 2020-04-23T08:31:04+0800
GitHash  : 011400903fb92cf1c444ea32a6196ae4c457ee37
RunMode  : product
 - [x] Redis     版本: 5.0.8，单机
 - [x] MongoDB   版本: mongodb-community@3.6，单机副本集
 - [x] ZooKeeper 版本: 3.4.14 单机
 - [x] elasticsearch 版本:5.6     
 - [x] 操作系统      : macos Catalina 10.15.4
 - [x] bk-cmdb 异常日志

Binary: Built with gc go1.12.17 for darwin/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0423 15:36:24.568256   53423 backbone/notice.go:57] log watch failed, will watch after 10s, path: /cc/services/notice/log/172.16.99.168:60004/v, err: zk: node does not exist
E0423 15:36:24.572233   53423 configures/conf.go:189] fail to open file(/Users/ruiliping/jishi/lanjin-cmdb/cmdb/cmdb_adminserver/configures/sync.conf), err(open /Users/ruiliping/jishi/lanjin-cmdb/cmdb/cmdb_adminserver/configures/sync.conf: no such file or directory)

# zk配置文件内容如下：
tickTime=2000
initLimit=10
syncLimit=5
dataDir=/tmp/zookeeper
clientPort=2181

**Comment by breezelxp** [comment]
这些信息太少，页面有什么报错，有什么异常信息，都提供下

**Comment by 1123183721** [comment]
页面无法访问。。。是不是zk得部成集群，我看RunMode 是product

**Comment by 1123183721** [comment]
所有logs/*的错误日志都是err: zk: node does not exist，也没有更多的信息了

**Comment by 1123183721** [comment]
集群也不行，zk执行getAcl /cc提示：
Authentication is not valid : /cc

**Comment by 1123183721** [comment]
master和3.8换了2环境还是都无法安装。。。我换个低版本试下

**Comment by lanfen100** [comment]
> 所有logs/*的错误日志都是err: zk: node does not exist，也没有更多的信息了

你这个问题 最后解决了么？ 我也出现跟你一样这个情况 3.8.x,所有进程都是正常的 web 无法访问
