### ISSUE TITLE
3.2发布版本按照github的文档部署成功了，3.8和master都跪了...坑啊

### ISSUE THREAD

**Issue by 1123183721** [Tencent/bk-cmdb#4115]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
@1123183721 报了什么错，出了什么问题？

**Comment by ahhqlrg** [comment]
Binary: Built with gc go1.14.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0506 14:30:10.473324  121627 app/server.go:70] parse authcenter error: missing "address" configuration for auth center, config: map[auth.appCode:bk_cmdb auth.enableSync:false auth.syncIntervalMinutes:45 auth.syncWorkers:100 config-server.addrs:182.180.199.77:2181 confs.dir:/umos/BlueKing/cmdbv3.8.3/cmdb_adminserver/configures/ errors.res:conf/errors language.res:conf/language mongodb.database:cmdb mongodb.host:182.180.199.77 mongodb.maxIdleConns:100 mongodb.maxOpenConns:3000 mongodb.mechanism:SCRAM-SHA-1 mongodb.port:27017 mongodb.pwd:cc mongodb.rsName:rs0 mongodb.txnEnabled:false mongodb.usr:cc redis.database:0 redis.host:182.180.199.77:6379 redis.maxIDleConns:1000 redis.maxOpenConns:3000 redis.pwd:1111 register-server.addrs:182.180.199.77:2181]
E0506 14:30:10.493305  121627 backbone/notice.go:57] log watch failed, will watch after 10s, path: /cc/services/notice/log/182.180.199.77:60004/v, err: zk: node does not exist
E0506 14:30:58.895692  121627 upgrader/register.go:274] get system version error,err:server selection error: server selection timeout
current topology: Type: ReplicaSetNoPrimary
Servers:
E0506 14:30:58.895736  121627 service/migrate.go:41] db upgrade failed, err: getVersion failed, err: server selection error: server selection timeout
current topology: Type: ReplicaSetNoPrimary
Servers:
, rid: cc0000bqp5j1595o8dm6rd02kg

**Comment by breezelxp** [comment]
3.8以上分支版本要求Mognodb需要为rs工作模式。允许为单点的rs模式
