### ISSUE TITLE
新增模型失败

### ISSUE THREAD

**Issue by 1123183721** [Tencent/bk-cmdb#4117]
问题描述
===========
创建模型时不管填写任何数据都会提示数据唯一性校验失败

重现方法
================
创建模型

关键信息
=========

 - [x] bk-cmdb   版本: 
 ./cmdb/cmdb-apiserver --version 这个命令输出的内容有些只有key没有value是什么回事😭，我装的是
bk-cmdb-release-v3.2.23.tar.gz这个版本

Version  : 
Tag      : 
BuildTime: 2020-04-26T18:07:35+0800
GitHash  : 
RunMode  : product
 - [x] Redis     版本: 4.0.14
 - [x] MongoDB   版本:2.8.0
 - [x] ZooKeeper 版本: 3.4.14
 - [x] 操作系统      CentOS Linux release 7.7.1908 (x64>
 - [x] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
你这个包，是你自己编的吧

**Comment by 1123183721** [comment]
对的

**Comment by 1123183721** [comment]
虽然提示数据唯一性校验失败，但是我手动刷新页面首页能看到新增的模型，但是不刷新是看不到的
