### ISSUE TITLE
v3.7.x 版本api查询进程信息 404: Page Not Found

### ISSUE THREAD

**Issue by yezihongle** [Tencent/bk-cmdb#4156]
问题描述
===========
v3.7.x 版本如何api查询进程信息？ 按照api 文档里 /api/{version}/proc/search/{bk_supplier_account}/{bk_biz_id} 方式提示“404: Page Not Found”

v3.2.x版本使用此方法查询没问题。

**Comment by yezihongle** [comment]
有大佬能帮忙解答下这个问题吗？谢谢。

**Comment by breezelxp** [comment]
产品形态调整，该接口在新版本中已经下线了
