### ISSUE TITLE
一台机器只能属于一个业务

### ISSUE THREAD

**Issue by HuHaichun** [Tencent/bk-cmdb#4166]
问题描述
===========
使用CMDB　３.２.２１版本。使用过程中发现一台机器只能转移到一个业务中。
现在机器不同业务模块的混部情况还是很常见的，希望不要限制一台机器只能属于一个业务。

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 3.2.21

**Comment by breezelxp** [comment]
你好，目前是这样限制的。后续可能会考虑一个机器可以属于多个业务，可以关注后续动态。
