### ISSUE TITLE
文档有误

### ISSUE THREAD

**Issue by Mrfogg** [Tencent/bk-cmdb#4170]
https://github.com/Tencent/bk-cmdb/blob/master/docs/wiki/container-support.md
用docker启动蓝鲸的命令：
```
docker run -d -p 8081:8090 ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:latest
```
无法成功启动蓝鲸，需要更改成
```
docker run -d -p 8090:8090 ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:latest
```
猜测是url重定向的问题

**Comment by breezelxp** [comment]
这个是端口映射的，不会影响启动。你启动不了，报什么错？端口冲突？

**Comment by Mrfogg** [comment]
> 这个是端口映射的，不会影响启动。你启动不了，报什么错？端口冲突？

访问localhost:8081, url会跳转到
http://127.0.0.1:8090/login?c_url=http://127.0.0.1:8090/
访问失败
