### ISSUE TITLE
添加openldap ssl支持，修改./application/libraries/Login.php中isValidUserPassword部分

### ISSUE THREAD

**Issue by zhihuicRepo** [Tencent/bk-cmdb#42]
/**
     * 判断用户的用户名和密码是否有效
     * @param $username
     * @param $password
     * @return bool $userInfo
     */
    public function isValidUserPassword($username, $password){
        if(empty($username)){
            return false;
        }
        # 从DB查询出用户信息
        $this->ci->load->model('UserModel');
        try {
            $userInfo = $this->ci->UserModel->getUserByUsername($username);
            if(empty($userInfo)){
                return false;
            }
// add for ldap function 2017-05-18
    if ($username == admin) {
            $passwordHash = $userInfo['Password'];
            if($passwordHash == $password){
                # 如果用户批量导入， 那么初始密码校验也可以通过
                return $userInfo;
            }
            $result = password_verify($password, $passwordHash);
            if(empty($result)){
                return false;
            }
            return $userInfo;
}
 // associated ldap info  password
    $ldapserver = 'ldaps://ldap2.example.com:636';
    $basedn = 'ou=People,dc=example,dc=com';
    $ldaprdn  = "uid=$username,$basedn";
putenv('LDAPTLS_REQCERT=allow');
putenv("LDAPCONF=/etc/openldap/ldap.conf");
    // connect to ldap server
    $ldapconn = ldap_connect($ldapserver)
            or die("Could not connect to LDAP server.");

    // Set some ldap options for talking to
    ldap_set_option($ldapconn, LDAP_OPT_PROTOCOL_VERSION, 3);
    ldap_set_option($ldapconn, LDAP_OPT_REFERRALS, 0);

    if ($ldapconn) {
            // binding to ldap server
            $ldapbind = @ldap_bind($ldapconn, $ldaprdn, $password);
            // verify binding
            if ($ldapbind) {
                return $userInfo;
            } else {
                return false;
            }
    }
            /**
            *  $passwordHash = $userInfo['Password'];
            * if($passwordHash == $password){
            *    # 如果用户批量导入， 那么初始密码校验也可以通过
            *    return $userInfo;
            * }
            * $result = password_verify($password, $passwordHash);
            * if(empty($result)){
            *    return false;
            * }
            * return $userInfo;
            */
        }catch (Exception $ex){
            return false;
        }
    }

**Comment by zhihuicRepo** [comment]
$ldapserver = 'ldaps://ldap2.example.com:636';
$basedn = 'ou=People,dc=example,dc=com';
改为自己的openldap相关信息

**Comment by lowenitt** [comment]
合适的可以提交merge request的
