### ISSUE TITLE
cmdb存储密码时无法输入特殊字符

### ISSUE THREAD

**Issue by hivehu** [Tencent/bk-cmdb#4200]
问题描述
===========

cmdb存储密码时无法输入’！% $^&*'这些特殊字符。

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 原来是社区版3.2.21，后用开源版release-v3.2.24替换了社区版
 Version  : v3.2.24
Tag      : ocr-v3.2.24
BuildTime: 2020-05-12T15:24:40+0800
GitHash  : v3.2.24
RunMode  : product

 - [ ] Redis     版本:   4.0.12
 - [ ] MongoDB   版本:   3.6.3
 - [ ] ZooKeeper 版本:   3.4.10
 - [ ] 操作系统      :   Centos 7.6（x64）
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
你说的太简单的，你是用什么字段类型存的？
再有cmdb不适合存密钥信息。

**Comment by hivehu** [comment]
用的短字符和长字符类型都不行，部分服务器不能按装agent进行自动化管理，故需要用cmdb存储系统或数据库密码信息。

**Comment by hivehu** [comment]
可以请教下如果在cmdb中存储密码，有什么其它好的解决方案吗？谢谢！
