### ISSUE TITLE
3.8.3版本执行初始化数据库版本失败

### ISSUE THREAD

**Issue by wisre** [Tencent/bk-cmdb#4224]
问题描述
===========
自己编译v3.8.3版本后，生成配置文件后，最后执行init_db.sh脚本初始化数据库时失败，报错：
{"result":false,"bk_error_code":1105000,"bk_error_msg":"迁移数据失败, getVersion failed, err: server selection error: server selection timeout\ncurrent topology: Type: ReplicaSetNoPrimary\nServers:\n","permission":null,"data":null}

报错日志：
E0518 16:45:52.744693    4668 upgrader/register.go:274] get system version error,err:server selection error: server selection timeout
current topology: Type: ReplicaSetNoPrimary
Servers:
E0518 16:45:52.744720    4668 service/migrate.go:41] db upgrade failed, err: getVersion failed, err: server selection error: server selection timeout
current topology: Type: ReplicaSetNoPrimary
Servers:
, rid: cc0000br14m8l6h7sh4f7rjvqg
E0518 17:54:54.837203    4668 upgrader/register.go:274] get system version error,err:server selection error: server selection timeout
current topology: Type: ReplicaSetNoPrimary
Servers:
E0518 17:54:54.837239    4668 service/migrate.go:41] db upgrade failed, err: getVersion failed, err: server selection error: server selection timeout
current topology: Type: ReplicaSetNoPrimary
Servers:
, rid: cc0000br15mk56h7sh4f7rjvr0

重现方法
================
按照文档步骤，编译，配置初始化，启动服务，数据库初始化即可复现

关键信息
=========

请提供以下信息:

 ./cmdb_adminserver --version
Version  : v3.8.3
Tag      : release-v3.8.3
BuildTime: 2020-05-18T16:35:23+0800
GitHash  : 701f977692434de538180bc5dc74b1894c7fc81f
RunMode  : product

mongo:4.0
zk:3.6

**Comment by breezelxp** [comment]
@wisre 你这个是db账户的权限不够造成的。两个解决方案：
1. 升权限，cmdb这个db可执行version权限即可。
2. 你用v3.8分支最新的代码编译一下重新部署即可，新的版本里放宽了这个限制。

**Comment by wisre** [comment]
好的，我用最新的代码编译下看看。然后你说的“cmdb这个db可执行version权限”是啥意思啊，我已经为这个库设置了用户名的readwrite权限啊。

**Comment by wisre** [comment]
> @wisre 你这个是db账户的权限不够造成的。两个解决方案：
> 
> 1. 升权限，cmdb这个db可执行version权限即可。
> 2. 你用v3.8分支最新的代码编译一下重新部署即可，新的版本里放宽了这个限制。

用最新的v3.8.x分支的代码编译了，还是报一样的错误了
E0518 18:50:03.695698   89946 upgrader/register.go:274] get system version error,err:server selection error: server selection timeout
current topology: Type: ReplicaSetNoPrimary
Servers:
E0518 18:50:03.695721   89946 service/migrate.go:41] db upgrade failed, err: getVersion failed, err: server selection error: server selection timeout
current topology: Type: ReplicaSetNoPrimary
Servers:
, rid: cc0000br16gfd6h7slummgmpdg

版本：
./cmdb_adminserver  --version
Version  : v3.8.x
Tag      : v3.8.x
BuildTime: 2020-05-18T18:38:05+0800
GitHash  : 9a90c3bca292217beb776920d2288554f7182dce
RunMode  : product

**Comment by breezelxp** [comment]
mongodb要用rs模式，单节点的也可以

**Comment by wisre** [comment]
> mongodb要用rs模式，单节点的也可以

配置的就是单节点的模式

配置如下：
 10 [mongodb]
  11 host =127.0.0.1
  12 port = 17017
  13 usr = cc
  14 pwd = cc
  15 database = cmdb
  16 maxOpenConns = 5
  17 maxIdleConns = 1
  18 mechanism = SCRAM-SHA-1
  19 rsName = rs0

127.0.0.1:17017是一个单节点的mongo

**Comment by wisre** [comment]
> mongodb要用rs模式，单节点的也可以

换成rs模式ok了
