### ISSUE TITLE
3.6.5版本api 如何鉴权获取权限？

### ISSUE THREAD

**Issue by yezihongle** [Tencent/bk-cmdb#4273]
部分接口需要鉴权才能查询，如何鉴权呢？

405: Method Not Allowed

**Comment by breezelxp** [comment]
请问你使用的是什么版本，开源版的，还是社区版的？
默认的鉴权对接的是蓝鲸权限中心，可以在蓝鲸权限中心进行权限管理。
也可以根据自己的需求，以插件的形式对接自己的权限系统。

**Comment by yezihongle** [comment]
你好，用的开源版本；目前用api 部分操作（如删除云区域）会报405: Method Not Allowed

因只是内部使用了cmdb，对权限没有要求，所以不想用蓝鲸权限中心，请问可以放弃鉴权吗？如何获取所有api的操作权限？

**Comment by breezelxp** [comment]
可以禁用你用./cmdb_apiserver --help 可以看到禁用的flag。

**Comment by yezihongle** [comment]
已经设置了--enable-auth=false  ，但是还是会报405: Method Not Allowed

**Comment by yezihongle** [comment]
starting: cmdb_adminserver
starting: cmdb_apiserver
starting: cmdb_coreservice
starting: cmdb_datacollection
starting: cmdb_eventserver
starting: cmdb_hostserver
starting: cmdb_operationserver
starting: cmdb_procserver
starting: cmdb_taskserver
starting: cmdb_tmserver
starting: cmdb_toposerver
starting: cmdb_webserver
root      33218      1  0 May25 ?        01:17:25 ./cmdb_coreservice --addrport=10.36.52.135:50009 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root      33381      1  0 May25 ?        01:16:45 ./cmdb_procserver --addrport=10.36.52.135:60003 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
root      55392      1 12 12:01 pts/0    00:00:00 ./cmdb_apiserver --addrport=10.36.52.135:8080 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
root      55432      1 14 12:01 pts/0    00:00:00 ./cmdb_datacollection --addrport=10.36.52.135:60005 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
root      55465      1  9 12:01 pts/0    00:00:00 ./cmdb_eventserver --addrport=10.36.52.135:60009 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
root      55500      1 12 12:01 pts/0    00:00:00 ./cmdb_hostserver --addrport=10.36.52.135:60001 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
root      55532      1 12 12:01 pts/0    00:00:00 ./cmdb_operationserver --addrport=10.36.52.135:60011 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root      55574      1 14 12:01 pts/0    00:00:00 ./cmdb_taskserver --addrport=10.36.52.135:60012 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root      55608      1  9 12:01 pts/0    00:00:00 ./cmdb_tmserver --addrport=10.36.52.135:60008 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root      55642      1  0 12:01 pts/0    00:00:00 ./cmdb_toposerver --addrport=10.36.52.135:60002 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
root      55677      1  0 12:01 pts/0    00:00:00 ./cmdb_webserver --addrport=10.36.52.135:80 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181

**Comment by yezihongle** [comment]
Log file created at: 2020/06/02 15:31:57
Running on machine: dc1-vm-cmdb-prod01
Binary: Built with gc go1.11.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0602 15:31:57.792992   17560 util/flags.go:54] [auth] enableAuth: false
