### ISSUE TITLE
coreservice mongodb watch failed， process stopped 

### ISSUE THREAD

**Issue by DemoLiang** [Tencent/bk-cmdb#4330]
问题描述
===========

使用V3.8.4版本，初始化配置后，通过./restart.sh启动所有，发现coreservice有报错，启动不了。
测试了V3.8.x应该也有类似问题，偶现性，咨询过群里的大佬，使用flushdb redis 后，重启cmdb 可以解决问题

[root@localhost cmdb_coreservice]# tailf logs/cmdb_coreservice.ERROR
Log file created at: 2020/06/15 20:35:59
Running on machine: localhost
Binary: Built with gc go1.13.6 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0615 20:35:59.215422    1219 event/watch.go:42] mongodb watch failed with conf: {Options:{MajorityCommitted:0xc001190ff0 MaxAwaitTime:1s OperationType:<nil> Filter:map[] EventStruct:0xc0000bc7e0 Collection:cc_HostBase StartAfterToken:0xc000f7ae60 StartAtTime:<nil>}}, err: (InvalidResumeToken) Attempted to resume a stream on a collection which has been dropped. The change stream's pipeline may need to make comparisons which should respect the collection's default collation, which can no longer be determined. If you wish to resume this change stream you must specify a collation with the request.
E0615 20:35:59.215890    1219 event/flow.go:141] run flow, but watch failed, err: watch collection: cc_HostBase failed, err: (InvalidResumeToken) Attempted to resume a stream on a collection which has been dropped. The change stream's pipeline may need to make comparisons which should respect the collection's default collation, which can no longer be determined. If you wish to resume this change stream you must specify a collation with the request.
E0615 20:35:59.215932    1219 event/event.go:35] run host event flow failed, err: watch collection: cc_HostBase failed, err: (InvalidResumeToken) Attempted to resume a stream on a collection which has been dropped. The change stream's pipeline may need to make comparisons which should respect the collection's default collation, which can no longer be determined. If you wish to resume this change stream you must specify a collation with the request.
E0615 20:35:59.215954    1219 service/service.go:152] new watch event failed, err: watch collection: cc_HostBase failed, err: (InvalidResumeToken) Attempted to resume a stream on a collection which has been dropped. The change stream's pipeline may need to make comparisons which should respect the collection's default collation, which can no longer be determined. If you wish to resume this change stream you must specify a collation with the request.
E0615 20:35:59.215989    1219 coreservice/main.go:46] process stopped by watch collection: cc_HostBase failed, err: (InvalidResumeToken) Attempted to resume a stream on a collection which has been dropped. The change stream's pipeline may need to make comparisons which should respect the collection's default collation, which can no longer be determined. If you wish to resume this change stream you must specify a collation with the request.

重现方法
================

1.  编译make 编译所有组件
2. 启动MongoDBdb,启动redis,启动zk
3 ./start.sh 启动cmdb

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 3.8.4
 
 - [ ] Redis     版本: 3.2.11
 - [ ] MongoDB   版本:  4.1.6
 - [ ] ZooKeeper 版本: 3.4.14
 - [ ] 操作系统      :  Centos 7 (x64
 - [ ] bk-cmdb 异常日志

E0615 20:35:59.215422    1219 event/watch.go:42] mongodb watch failed with conf: {Options:{MajorityCommitted:0xc001190ff0 MaxAwaitTime:1s OperationType:<nil> Filter:map[] EventStruct:0xc0000bc7e0 Collection:cc_HostBase StartAfterToken:0xc000f7ae60 StartAtTime:<nil>}}, err: (InvalidResumeToken) Attempted to resume a stream on a collection which has been dropped. The change stream's pipeline may need to make comparisons which should respect the collection's default collation, which can no longer be determined. If you wish to resume this change stream you must specify a collation with the request.

**Comment by breezelxp** [comment]
好的，我们看下。

**Comment by LieLieLiekey** [comment]
v3.9版本我有遇到过这种问题，应该是停太久了，把redis清一下就好。

**Comment by Baiang** [comment]
@breezelxp 3.8x 同样遇到这种问题

**Comment by LieLieLiekey** [comment]
> @breezelxp 3.8x 同样遇到这种问题
试过redis清空没。

**Comment by Baiang** [comment]
> > @breezelxp 3.8x 同样遇到这种问题
> > 试过redis清空没。
清空就好了
