### ISSUE TITLE
HELP API查询主机报owner_id授权失败

### ISSUE THREAD

**Issue by ZakZhu** [Tencent/bk-cmdb#4353]
问题描述
===========

API查询主机报owner_id授权失败
求提供一个带owner_id查询主机的完整示例, 拜托

重现方法
================

sh-4.2# curl --location --request GET 'http://172.17.0.2:8080/api/v3/hosts/0/2'

{"result":false,"bk_error_code":1199027,"bk_error_msg":"[owner_id]授权信息查询失败","data":null}

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
Version  : v3.2.21
Tag      : release-v3.2.21
BuildTime: 2020-01-03T10:59:08+0800
GitHash  : a3d53898f2c517cb02150bc4861176ee8498110c
RunMode  : product
 -->
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
在请示里带上头：
 -H "Content-Type:application/json" -H "HTTP_BLUEKING_SUPPLIER_ID:0" -H "BK_USER:demo"

**Comment by ZakZhu** [comment]
Thanks very much
