### ISSUE TITLE
v3.8.x版本存在大量数据库连接

### ISSUE THREAD

**Issue by kofeng** [Tencent/bk-cmdb#4355]
问题描述
===========
v3.5.x版本升级到v3.8.x版本发现数据库连接从10个左右变成600个左右
rs0:PRIMARY> db.serverStatus().connections
{
        "current" : 559,
        "available" : 11750,
        "totalCreated" : 632,
        "active" : 2
}

重现方法
================

关键信息
=========

请提供以下信息:

 - [v3.8.6] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [4.2.1] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
这个是可配置的，你可以配置连接池的大小。

**Comment by kofeng** [comment]
配置/V3.8.6/cmdb_adminserver/configures/mongodb.conf 
maxOpenConns = 200
maxIdleConns = 100

rs0:PRIMARY> db.serverStatus().connections
{
        "current" : 677,
        "available" : 7515,
        "totalCreated" : 1347,
        "active" : 12
}
还是有600多个连接，请问这是正常的现象吗？之前的版本3.5.28只有十几个连接
刚开始从3.5.x升级3.8.x的时候一下涌入大量的数据库连接mongodb报Too many open files直接挂了，cmdb_coreservice也挂了,改大了ulimit才升级成功的

**Comment by breezelxp** [comment]
新版的连接是会增加，你可以调整mongo.conf的配置，调整连接数的量。

**Comment by kofeng** [comment]
好的感谢
