### ISSUE TITLE
docker启动无法访问

### ISSUE THREAD

**Issue by pptfz** [Tencent/bk-cmdb#4383]
按照官方的命令
```
docker run -d -p 8081:8090 ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:latest
```

容器可以启动成功，但是无法访问，浏览器报错如下
```
无法访问此网站127.0.0.1 拒绝了我们的连接请求。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_REFUSED

```

并且使用`docker logs -f 容器名`查看日志无报错
什么情况？？？

**Comment by kofeng** [comment]
latest版本的开启了登录功能，先访问/login登录，用户名密码是admin:admin,但是会跳转到127.0.0.1:8090，还要改一下容器内脚本：`docker exec -it 容器名 vi run.sh`   修改--blueking_cmdb_url 的值为http://你的ip:8081

**Comment by pptfz** [comment]
改了 现在是能运行了 但是一堆错误啊

docker报错mongo无法连接，手动进入容器中手动启动也不行
```
{"result":false,"bk_error_code":1105000,"bk_error_msg":"迁移数据失败, getVersion failed, err: server selection error: server selection timeout\ncurrent topology: Type: ReplicaSetNoPrimary\nServers:\nAddr: 127.0.0.1:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection(127.0.0.1:27017[-225]) connection is closed\n","permission":null,"data":null}
```

qq群里边根本没人回复问题，全都是问问题的，一个回答的也没有。。。虽然这很符合国情但这不是腾讯的东西嘛
还有，这个真的是 腾讯的 产品？？？

**Comment by breezelxp** [comment]
我们看下

**Comment by pptfz** [comment]
@breezelxp 麻烦文档更新一下吧，感觉还有很多地方没有说明
修改run.sh是一个问题，应该还有别的问题

**Comment by zhouhuicong** [comment]
同问，这个问题现在还没有解决

**Comment by chenxs-sx** [comment]
> latest版本的开启了登录功能，先访问/login登录，用户名密码是admin:admin,但是会跳转到127.0.0.1:8090，还要改一下容器内脚本：`docker exec -it 容器名 vi run.sh` 修改--blueking_cmdb_url的值为[http: //你的ip:8081](http://%E4%BD%A0%E7%9A%84ip:8081)

未知或未能识别的异常，一直提示这个。

**Comment by zhouhuicong** [comment]
> > latest版本的开启了登录功能，先访问/login登录，用户名密码是admin:admin,但是会跳转到127.0.0.1:8090，还要改一下容器内脚本：`docker exec -it 容器名 vi run.sh` 修改--blueking_cmdb_url的值为[http: //你的ip:8081](http://%E4%BD%A0%E7%9A%84ip:8081)
> 
> 未知或未能识别的异常，一直提示这个。

我也改了，同样的报错，建议去腾讯蓝鲸官网使用那个5.1的docker ，用起来还方便点。 github上这个不好用，别折腾了。

**Comment by chenxs-sx** [comment]
> > > latest版本的开启了登录功能，先访问/login登录，用户名密码是admin:admin,但是会跳转到127.0.0.1:8090，还要改一下容器内脚本：`docker exec -it 容器名 vi run.sh` 修改--blueking_cmdb_url的值为[http: //你的ip:8081](http://%E4%BD%A0%E7%9A%84ip:8081)
> > 
> > 
> > 未知或未能识别的异常，一直提示这个。
> 
> 我也改了，同样的报错，建议去腾讯蓝鲸官网使用那个5.1的docker ，用起来还方便点。 github上这个不好用，别折腾了。

我半天没找到docker镜像地址。。。尴尬

**Comment by breezelxp** [comment]
@zhouhuicong @chenxs-sx 这个我们正在看，处理完后，会在这里反馈哈

**Comment by zhouhuicong** [comment]
> > > > latest版本的开启了登录功能，先访问/login登录，用户名密码是admin:admin,但是会跳转到127.0.0.1:8090，还要改一下容器内脚本：`docker exec -it 容器名 vi run.sh` 修改--blueking_cmdb_url的值为[http: //你的ip:8081](http://%E4%BD%A0%E7%9A%84ip:8081)
> > > 
> > > 
> > > 未知或未能识别的异常，一直提示这个。
> > 
> > 
> > 我也改了，同样的报错，建议去腾讯蓝鲸官网使用那个5.1的docker ，用起来还方便点。 github上这个不好用，别折腾了。
> 
> 我半天没找到docker镜像地址。。。尴尬

https://bk.tencent.com/download/    进这个网址，然后下载5.1.26-Beta mini体验版 这个版本的，里面有readme的操作说明。 部署很快，注意部署完成后不要restart，重启后服务就无法自动拉起来了。 想好好试用的，最好装一个单机版的

**Comment by chenxs-sx** [comment]
> > > > > latest版本的开启了登录功能，先访问/login登录，用户名密码是admin:admin,但是会跳转到127.0.0.1:8090，还要改一下容器内脚本：`docker exec -it 容器名 vi run.sh` 修改--blueking_cmdb_url的值为[http: //你的ip:8081](http://%E4%BD%A0%E7%9A%84ip:8081)
> > > > 
> > > > 
> > > > 未知或未能识别的异常，一直提示这个。
> > > 
> > > 
> > > 我也改了，同样的报错，建议去腾讯蓝鲸官网使用那个5.1的docker ，用起来还方便点。 github上这个不好用，别折腾了。
> > 
> > 
> > 我半天没找到docker镜像地址。。。尴尬
> 
> https://bk.tencent.com/download/ 进这个网址，然后下载5.1.26-Beta mini体验版 这个版本的，里面有readme的操作说明。 部署很快，注意部署完成后不要docker restart，重启后服务就无法自动拉起来了。 想好好试用的，最好装一个单机版的

谢谢。正在下载完整版了。装个完整版试用吧。谢谢您提供的帮助

**Comment by zhouhuicong** [comment]
> @zhouhuicong @chenxs-sx 这个我们正在看，处理完后，会在这里反馈哈

不得不说，你们蓝鲸官网的手册和QQ群，比github这里状况好多了，还不如放个链接，直接转到官网呢。

**Comment by zhouhuicong** [comment]
> @zhouhuicong @chenxs-sx 这个我们正在看，处理完后，会在这里反馈哈

不得不说，你们蓝鲸官网的手册和QQ群，比github这里状况好多了，还不如放个链接，直接转到官网呢。

**Comment by breezelxp** [comment]
> > @zhouhuicong @chenxs-sx 这个我们正在看，处理完后，会在这里反馈哈
> 
> 不得不说，你们蓝鲸官网的手册和QQ群，比github这里状况好多了，还不如放个链接，直接转到官网呢。

官网版本比较老，是近2年前的版本，更新比较慢。github这里的版本比较新。

**Comment by pptfz** [comment]
qq群更辣鸡 根本没有人回复 github早就说了 看一下问题 都看了多少天了 3.5k star 我尼玛就呵呵了 是真能刷

**Comment by somenzz** [comment]
首次启动容器的命令：
`docker run -d -p 8081:8090 ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:latest /bin/bash /data/run.sh 127.0.0.1 8081`
再次进入容器：
`docker exec -it [CONTAINER ID] /bin/bash`

**Comment by LieLieLiekey** [comment]
> 首次启动容器的命令：
> `docker run -d -p 8081:8090 ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:latest /bin/bash /data/run.sh 127.0.0.1 8081`
> 再次进入容器：
> `docker exec -it [CONTAINER ID] /bin/bash`

想了想新的镜像用法太麻烦，所以镜像用法又回归原样了😓，而且已经修复之前的问题了

**Comment by LieLieLiekey** [comment]
有问题的话请好好提问，看 issues 的时候如果知道就会去回答的😄

**Comment by rentiansheng** [comment]
> 改了 现在是能运行了 但是一堆错误啊
> 
> docker报错mongo无法连接，手动进入容器中手动启动也不行
> 
> ```
> {"result":false,"bk_error_code":1105000,"bk_error_msg":"迁移数据失败, getVersion failed, err: server selection error: server selection timeout\ncurrent topology: Type: ReplicaSetNoPrimary\nServers:\nAddr: 127.0.0.1:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection(127.0.0.1:27017[-225]) connection is closed\n","permission":null,"data":null}
> ```
> 
> qq群里边根本没人回复问题，全都是问问题的，一个回答的也没有。。。虽然这很符合国情但这不是腾讯的东西嘛
> 还有，这个真的是 腾讯的 产品？？？

http://www.ireage.com/tcp/network/2020/03/02/mongoset_con.html 看下这个， 这个是由于mongodb driver 连接mongodb 使用你配置rs 使用的地址问题造成， 你需要用可以对外访问ip:port来来组成rs模式

**Comment by suyar** [comment]
> latest版本的开启了登录功能，先访问/login登录，用户名密码是admin:admin,但是会跳转到127.0.0.1:8090，还要改一下容器内脚本：`docker exec -it 容器名 vi run.sh` 修改--blueking_cmdb_url 的值为[http://你的ip:8081](http://%E4%BD%A0%E7%9A%84ip:8081)

用了这个办法解决了

**Comment by hanshou101** [comment]
非常奇怪的，我在使用  对应【release-v3.9.28】版本的latest镜像时，

最初也出现了同样的问题；并且，试用了上述的方法，都仍然【打不开网页】。

查看报错日志时，看到了【init_db.sh: Permission denied】这样的报错。

————————

但是，我之后删除了 container 容器，重启了系统（虚拟机）。重启之后，再创建container，就一切正常了。

0.0

并没有搞明白是什么原因。

**Comment by linfang-canway** [comment]
最新版本的latest镜像已经更新，之前此版本存在不能自动启动的问题，现已经解决

**Comment by YitingWang1** [comment]
今天下载了最新的镜像启动，还是遇到了和 @pptfz 一样的问题。
在aws ec2[ami2]上启动后，遇到报错有2个：
NETWORK  [listener] Error accepting new connection on 0.0.0.0:27017: Too many open files
init_db没有执行权限
修改镜像run.sh
cd cmdb_adminserver && chmod 755 ./init_db.sh && ./init_db.sh
启动命令
docker run -d \
    --name bk-cmdb \
    --ulimit nofile=65535:65535 \
    -p 18090:8090 \
    ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:v3.9.28-xxx

在macOS Mojave 10.14.6上遇到
./run.sh: line 27: ./init_db.sh: Permission denied
给init_db.sh授予执行权限，以及登陆到mongo后，给cc这个用户授予root权限
db.createUser(
    {
        user:"cc",
        pwd:"cc",
        roles:["root"]
    }
)
