### ISSUE TITLE
qq群根本没有人回复，3.5k的star是刷的吧

### ISSUE THREAD

**Issue by pptfz** [Tencent/bk-cmdb#4409]
按照文档操作都一堆问题，qq群也没人回复，3.5k的star是刷的吧

**Comment by zhouhuicong** [comment]
同问，按照文档操作还有一堆坑，我也是醉了， docker 镜像也不能直接使用。

**Comment by pptfz** [comment]
问了也白问 明显是刷的

**Comment by zhouhuicong** [comment]
> 问了也白问 明显是刷的
我现在选择去蓝鲸官网直接下他们整个平台的安装包试用了，这次安装还比较顺利。就是组件也比较多。他们这个cmdb还要结合其他模块才行。 
https://bk.tencent.com/

**Comment by zhouhuicong** [comment]
> > 问了也白问 明显是刷的
> > 我现在选择去蓝鲸官网直接下他们整个平台的安装包试用了，这次安装还比较顺利。就是组件也比较多。他们这个cmdb还要结合其他模块才行。
> > https://bk.tencent.com/

友情提示。最好不要用他们平台最新docker版的restart一下服务就拉不起来了。

**Comment by pptfz** [comment]
一个字 辣鸡
