### ISSUE TITLE
自检模型使用了“bk_parent_id“ 时，新建实例会报：未能识别的异常 错误

### ISSUE THREAD

**Issue by DemoLiang** [Tencent/bk-cmdb#4451]
问题描述
===========

1.自检模型，并且增加自定义模型字段：bk_parent_id
2.在资源管理里面，新建此模型的实例，提交时会报：未能识别的异常，新建实例失败

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: V3.8.x
 - [x] bk-cmdb 异常日志
E0716 10:03:02.610122    5271 operation/inst.go:278] [operation-inst] failed to get the object(bk_tenant) mainline parent, err: EOF, rid: cc0000bs7raljfgf9lfv4or2u0
E0716 10:03:02.610189    5271 operation/inst.go:319] [operation-inst] the mainline object(bk_tenant) parent id invalid,

**Comment by breezelxp** [comment]
请描述下具体的场景，bk_parent_id是系统内置字段，不能使用。

**Comment by DemoLiang** [comment]
1. 新建自定义模型
2. 配置模型字段
3.添加自定义字段，自定义字段的标识为：bk_parent_id
4. 去自定义模型下新建模型实例，然后填入相应的字段内容，
5.点击提交时，就会报：未能识别的异常，新建不了实例。
