### ISSUE TITLE
创建新业务时,"运维人员"无可用用户选择

### ISSUE THREAD

**Issue by orcswang-lang** [Tencent/bk-cmdb#4452]
问题描述
===========
创建新业务时,运维人员无可用用户选择.

当前版本可用用户的获取是通过pass平台的接口获取的,
接口:/api/c/compapi/v2/usermanage/fs_list_users/?app_code=bk-magicbox&exact_lookups=admin&page_size=100&page=1&callback=USER_LIST_CALLBACK_0

v3.2.1版本获取可用用户接口:/user/list?fuzzy_lookups=admin

能否配置使用哪种接口去获取用户呢?

 - [x] bk-cmdb   版本:     : 
Branch   : v3.9.x

**Comment by breezelxp** [comment]
根据你的描述，你用的是应该是社区版吧？

v3.9中使用的接口是新版的用户管理接口，需要配套的paas，目前配套的paas还没有发布社区版。如果要使用高版本的cmdb，需要等社区更新新的版本。

**Comment by orcswang-lang** [comment]
> 根据你的描述，你用的是应该是社区版吧？
> 
> v3.9中使用的接口是新版的用户管理接口，需要配套的paas，目前配套的paas还没有发布社区版。如果要使用高版本的cmdb，需要等社区更新新的版本。

好的

**Comment by dylan120** [comment]
创建新业务时,填写运维人员显示http请求失败
paas : bk-PaaS-5.1
cmdb : v3.8.9
cmdb 的comom.conf配置了
`[login]
version=blueking`

看日志请求的接口是/api/c/compapi/v2/usermanage/list_users,
是不是paas的版本没对应上

**Comment by breezelxp** [comment]
开源版的paas接口暂不兼容，我们很快会发布新的社区版。届时即可使用。

**Comment by dylan120** [comment]
开源版paas的有计划兼容吗,如果有什么时候会有对应开源兼容版本

**Comment by dylan120** [comment]
> 开源版的paas接口暂不兼容，我们很快会发布新的社区版。届时即可使用。

开源版paas的有计划兼容吗,如果有什么时候会有对应开源兼容版本
