### ISSUE TITLE
文档稀烂，docker正式版没有，/api/{version}/是几个意思

### ISSUE THREAD

**Issue by a1258771** [Tencent/bk-cmdb#4453]

**Comment by Baiang** [comment]
文档确实稀烂，你用v3试下

**Comment by a1258771** [comment]
看了下，issues别人的问题，  有个带api地址， /api/v3/host 成功了， 感谢

**Comment by a1258771** [comment]
可惜， 405带鉴权的不知道怎么办。   一定要完整版蓝鲸嘛。。。  本来就想cmdb， api上传，下载就差不多了

**Comment by Baiang** [comment]
这个就需要你进入容器/data/cmdb/，找到启动的cmdb_adminserver、cmdb_apiserver、服务等的start.sh脚本，在后面加上 --enable-auth=false 再重启下就可以了
