### ISSUE TITLE
python init.py 生成的配置有问题

### ISSUE THREAD

**Issue by ericdong2012** [Tencent/bk-cmdb#4472]
问题描述
===========

python init.py 生成的配置文件只有5个， 后续start.sh 启动的服务只有5个，init_db.sh 失败
用的最新release-3.8.9 的代码

![Snipaste_2020-07-22_14-12-19](https://user-images.githubusercontent.com/36787305/88141435-30563100-cc26-11ea-89e1-8a1d14a06ecd.png)
![Snipaste_2020-07-22_14-12-34](https://user-images.githubusercontent.com/36787305/88141446-364c1200-cc26-11ea-9aa1-c9a9b5a267ec.png)

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本:  3.8.9
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by ericdong2012** [comment]
都是安装系统建议的软件版本

**Comment by LieLieLiekey** [comment]
3.8.9版本生成配置文件的个数是5个，这个正常。你有一些服务没有起来，去对应的文件夹logs下看一下日志。核心服务是coreserver，先看这个错误信息

**Comment by LieLieLiekey** [comment]
init_db.sh失败的原因是因为服务没有启动成功，所以不能向服务器请求并迁移数据。

**Comment by ericdong2012** [comment]
> 3.8.9版本生成配置文件的个数是5个，这个正常。你有一些服务没有起来，去对应的文件夹logs下看一下日志。核心服务是coreserver，先看这个错误信息

看到了，原来是redis的一个配置有问题，导致各种服务启动不起来
