### ISSUE TITLE
bk_cmdb 中 mongodb 4.2.8  配置 replicaset 后还是报错

### ISSUE THREAD

**Issue by ericdong2012** [Tencent/bk-cmdb#4479]
问题描述
===========

本地mongodb  4.2.8 ，  配置了rs ，但是init_db.sh 执行还是报错 。
 配置如下：
/usr/bin/mongod --dbpath=/opt/cmdb/mongodb/db/27017 --logpath=/opt/cmdb/mongodb/log/mongodb_27017.log --fork  --replSet=rs0 --bind_ip 192.168.19.151 --port=27017

/usr/bin/mongod --dbpath=/opt/cmdb/mongodb/db/27018 --logpath=/opt/cmdb/mongodb/log/mongodb_27018.log --fork  --replSet=rs0 --bind_ip 192.168.19.151 --port=27018

/usr/bin/mongod --dbpath=/opt/cmdb/mongodb/db/27019 --logpath=/opt/cmdb/mongodb/log/mongodb_27019.log --fork  --replSet=rs0 --bind_ip 192.168.19.151 --port=27019

rs.initiate({ _id : "rs0",
members: [
			{ _id: 0, host: "192.168.19.151:27017"},
			{ _id: 1, host: "192.168.19.151:27018"},
			{ _id: 2, host: "192.168.19.151:27019", arbiterOnly: true }, 
		 ]
	})

rs.status() 能获取到相应的结果

执行init_db.sh 报错如下：
{"result":false,"bk_error_code":1105000,"bk_error_msg":"迁移数据失败, getVersion failed, err: connection() : auth error: sasl conversation error: unable to authenticate using mechanism \"SCRAM-SHA-1\": (AuthenticationFailed) Authentication failed.","permission":null,"data":null}

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本:  3.8.9
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by ericdong2012** [comment]
参考过 #4224 ，配置的rs , 但是还是不行， 还有其中说到的升级 db权限 是否可以解决这个问题， 如果可以怎么操作？

**Comment by ericdong2012** [comment]
看过 cmdb_adminserver 下的日志，报的错跟上面是一样的，其他地方未看到相应log

**Comment by LieLieLiekey** [comment]
有在cmdb数据库中创建用户吗？要先use cmdb ，然后再db.createUser({user: <USER_NAME>,pwd: <PASSWD>,roles: [ { role: "readWrite", db: "cmdb" } ]})

**Comment by LieLieLiekey** [comment]
可以先use admin，然后db.system.users.find().pretty()查看创建的用户的是否在cmdb数据库

**Comment by ericdong2012** [comment]
> 可以先use admin，然后db.system.users.find().pretty()查看创建的用户的是否在cmdb数据库

看过， 在的

**Comment by LieLieLiekey** [comment]
> > 可以先use admin，然后db.system.users.find().pretty()查看创建的用户的是否在cmdb数据库
> 
> 看过， 在的

coreserver服务启动成功了吗？如果没启动成功看下日志信息是什么

**Comment by LieLieLiekey** [comment]
> > 可以先use admin，然后db.system.users.find().pretty()查看创建的用户的是否在cmdb数据库
> 
> 看过， 在的

coreserver应该是有报错的，在`cmdb_coreserver/logs/cmdb_***.ERROR`， 你可以发一下错误信息。

**Comment by ericdong2012** [comment]
> > > 可以先use admin，然后db.system.users.find().pretty()查看创建的用户的是否在cmdb数据库
> > 
> > 
> > 看过， 在的
> 
> coreserver服务启动成功了吗？如果没启动成功看下日志信息是什么
没有启动成功， 日志和上面差不多  coreservice/main.go:46] process stopped by new business cache failed, err: run biz cache failed, err: watch collection: cc_ApplicationBase failed, err: connection() : auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.，这个报错还是和mongo有关，SCRAM-SHA-1 在mongodb.cnf 里出现过，也尝试过修改system.version , 还是不行

> use admin 
switched to db admin 
>  var schema = db.system.version.findOne({"_id" : "authSchema"}) 
> schema.currentVersion = 3 
3 
> db.system.version.save(schema) 
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })

**Comment by breezelxp** [comment]
报错里说的很清楚，你是mongodb的认证信息不正确，导致连接mongodb失败。

**Comment by ericdong2012** [comment]
> 报错里说的很清楚，你是mongodb的认证信息不正确，导致连接mongodb失败。
是的，是认证的问题，只是试了很久没找到怎么去整个正确的认证信息，从配置，到用户的创建等等，我上面贴的那些信息不知哪里有问题，望明示

**Comment by LieLieLiekey** [comment]
我只能猜测几种可能的原因

- init.py 初始化配置时，有关mongod的配置信息不正确。  
- mongod的用户没有在指定的cmdb数据库下创建(我之前就犯过这种错误)，如果创建在cmdb数据库下，那么用户的_id是`cmdb.<USERNAME>`

**Comment by ericdong2012** [comment]
之前可能是尝试单机，rs单节点，rs多节点，以及各种配置完全乱掉了，问题怎么也解决不了 ， 从快照恢复 重新安装mongo,  直接按照 rs 模式 (rs不建议用单节点模式，大概率报错) 配置，启动，初始化， 问题得到解决。 

下面列出一些配置，其他人碰到类似问题，可供参考：
1. 启动mongo rs , 当前是在一台机器上通过不同端口实现
```
> /usr/bin/mongod --dbpath=/opt/cmdb/mongodb/db/27017 --logpath=/opt/cmdb/mongodb/log/mongodb_27017.log --fork  --replSet=rs0 --bind_ip 192.168.19.151 --port=27017
> /usr/bin/mongod --dbpath=/opt/cmdb/mongodb/db/27018 --logpath=/opt/cmdb/mongodb/log/mongodb_27018.log --fork  --replSet=rs0 --bind_ip 192.168.19.151 --port=27018
> /usr/bin/mongod --dbpath=/opt/cmdb/mongodb/db/27019 --logpath=/opt/cmdb/mongodb/log/mongodb_27019.log --fork  --replSet=rs0 --bind_ip 192.168.19.151 --port=27019
```

2. 
```
# 进入mongo 
> mongo 192.168.19.151:27017 


> use admin 

# 初始化rs
> rs.initiate({ _id : "rs0",
	members: [
				{ _id: 0, host: "192.168.19.151:27017", priority: 1},
				{ _id: 1, host: "192.168.19.151:27018", priority: 2},
				{ _id: 2, host: "192.168.19.151:27019", arbiterOnly: true }, 
			 ]
		})
	
# 查看rs状态
> rs.status()


# 创建root
> db.createUser({user:'root',pwd:'mongo',roles:['root']})
Successfully added user: { "user" : "root", "roles" : [ "root" ] }

> db.auth('root','mongo')
1

# 创建cc 
> use cmdb
switched to db cmdb

> db.createUser({user:"cc",pwd:"cc",roles:[{role:"readWrite",db:"cmdb"}]})
Successfully added user: {
	"user" : "cc",
	"roles" : [
		{
			"role" : "readWrite",
			"db" : "cmdb"
		}
	]
}

# 查看有哪些user
> use admin 
> db.system.users.find().pretty()
```
