### ISSUE TITLE
关于模型至少需要一组必填的唯一校验的请教

### ISSUE THREAD

**Issue by yfl1** [Tencent/bk-cmdb#4480]
问题描述
===========

v3.5.28版本，请问 	"1101069":"模型至少需要有一组的必填唯一校验项"  的目的是什么？我想修改源码去掉至少一组唯一校验的限制，这样做会带来什么问题吗
release-v3.5.28\bk-cmdb-release-v3.5.28\src\scene_server\topo_server\service\unique.go
```
	if len(uniques) <= 1 {
		blog.Errorf("[DeleteObjectUnique][%s] unique should have more than one, rid: %s", objectID, params.ReqID)
		return nil, params.Err.Error(common.CCErrTopoObjectUniqueShouldHaveMoreThanOne)
	}
```

重现方法
================

关键信息
=========

请提供以下信息:

 - [v3.5.28] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by Baiang** [comment]
这样会有个问题，调用接口数据可能会重复插入数据库，所以需要唯一校验来，保证数据是唯一，不会重复。这是我的猜测

**Comment by breezelxp** [comment]
> 这样会有个问题，调用接口数据可能会重复插入数据库，所以需要唯一校验来，保证数据是唯一，不会重复。这是我的猜测

确实是这个原因

**Comment by yfl1** [comment]
好的，谢谢
