### ISSUE TITLE
登录时无限跳转

### ISSUE THREAD

**Issue by shenxg13** [Tencent/bk-cmdb#4483]
问题描述
===========
登录时无限跳转

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
[bk@cc01 cmdb_apiserver]$ ./cmdb_apiserver --version
Version  : v3.8.9
Tag      : release-v3.8.9
BuildTime: 2020-07-23T00:08:21+0800
GitHash  : 822f841d0a5c16175c56ba491fa57d237b90503e
RunMode  : product
 - [x] Redis     版本: 4.0.14
 - [ ] MongoDB   版本: 4.2.8
 - [ ] ZooKeeper 版本: 3.4.14
 - [ ] 操作系统      : Centos 7.5
 - [ ] bk-cmdb 异常日志

E0724 19:27:53.684011    4981 middleware/login.go:109] session key bk_token not found, rid: cc0000bsdcbe8la1u16t87v7cg
E0724 19:27:53.684047    4981 open_source/userinfo.go:61] login user not found, rid: cc0000bsdcbe8la1u16t87v7cg
[GIN] 2020/07/24 - 19:27:53 | 302 |     1.21703ms |   192.168.0.124 | GET      //login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083///login?c_url=http://192.168.0.83:8083//

**Comment by breezelxp** [comment]
看下配置说明，默认的登陆需要在配置文件里配置用户与密码信息。

**Comment by shenxg13** [comment]
> 看下配置说明，默认的登陆需要在配置文件里配置用户与密码信息。

您好，没有找到类似说明，能稍微具体一些吗？谢谢。

**Comment by LieLieLiekey** [comment]
请发下你的cmdb_adminserver/configure/common.conf配置信息

**Comment by LieLieLiekey** [comment]
> > 看下配置说明，默认的登陆需要在配置文件里配置用户与密码信息。
> 
> 您好，没有找到类似说明，能稍微具体一些吗？谢谢。

请发下你的cmdb_adminserver/configure/common.conf配置信息

**Comment by shenxg13** [comment]
> > > 看下配置说明，默认的登陆需要在配置文件里配置用户与密码信息。
> > 
> > 
> > 您好，没有找到类似说明，能稍微具体一些吗？谢谢。
> 
> 请发下你的cmdb_adminserver/configure/common.conf配置信息

[auth]
address =
appCode = bk_cmdb
appSecret =

[gse]
addr = 127.0.0.1:2181
user = bkzk
pwd = L%blKas

[timer]
spec = 00:30  # 00:00 - 23:59

[es]
full_text_search = on
url=http://127.0.0.1:9200
usr =
pwd =

[api]
version = v3
[session]
name = cc3
defaultlanguage = zh-cn
multiple_owner = 0
user_info=
[site]
domain_url = http://192.168.0.83:8083/
bk_login_url = http://127.0.0.1/login/?app_id=%s&c_url=%s
app_code = cc
check_url = http://127.0.0.1/login/accounts/get_user/?bk_token=
bk_account_url = http://127.0.0.1/login/accounts/get_all_user/?bk_token=%s
resources_path = /tmp/
html_root = ../web
full_text_search = on
[app]
agent_app_url = http://127.0.0.1/console/?app=bk_agent_setup
authscheme = internal
[login]
version=opensource

**Comment by ZQHcode** [comment]
> > > > 看下配置说明，默认的登陆需要在配置文件里配置用户与密码信息。
> > > 
> > > 
> > > 您好，没有找到类似说明，能稍微具体一些吗？谢谢。
> > 
> > 
> > 请发下你的cmdb_adminserver/configure/common.conf配置信息
> 
> [auth]
> address =
> appCode = bk_cmdb
> appSecret =
> 
> [gse]
> addr = 127.0.0.1:2181
> user = bkzk
> pwd = L%blKas
> 
> [timer]
> spec = 00:30 # 00:00 - 23:59
> 
> [es]
> full_text_search = on
> url=http://127.0.0.1:9200
> usr =
> pwd =
> 
> [api]
> version = v3
> [session]
> name = cc3
> defaultlanguage = zh-cn
> multiple_owner = 0
> user_info=
> [site]
> domain_url = http://192.168.0.83:8083/
> bk_login_url = http://127.0.0.1/login/?app_id=%s&c_url=%s
> app_code = cc
> check_url = http://127.0.0.1/login/accounts/get_user/?bk_token=
> bk_account_url = http://127.0.0.1/login/accounts/get_all_user/?bk_token=%s
> resources_path = /tmp/
> html_root = ../web
> full_text_search = on
> [app]
> agent_app_url = http://127.0.0.1/console/?app=bk_agent_setup
> authscheme = internal
> [login]
> version=opensource

user_info=  这里写账号密码，用：分割，比如 cc:cc
然后登陆的时候进入 /login 页面进行登录即可

**Comment by shenxg13** [comment]
> > > > > 看下配置说明，默认的登陆需要在配置文件里配置用户与密码信息。
> > > > 
> > > > 
> > > > 您好，没有找到类似说明，能稍微具体一些吗？谢谢。
> > > 
> > > 
> > > 请发下你的cmdb_adminserver/configure/common.conf配置信息
> > 
> > 
> > [auth]
> > address =
> > appCode = bk_cmdb
> > appSecret =
> > [gse]
> > addr = 127.0.0.1:2181
> > user = bkzk
> > pwd = L%blKas
> > [timer]
> > spec = 00:30 # 00:00 - 23:59
> > [es]
> > full_text_search = on
> > url=http://127.0.0.1:9200
> > usr =
> > pwd =
> > [api]
> > version = v3
> > [session]
> > name = cc3
> > defaultlanguage = zh-cn
> > multiple_owner = 0
> > user_info=
> > [site]
> > domain_url = http://192.168.0.83:8083/
> > bk_login_url = http://127.0.0.1/login/?app_id=%s&c_url=%s
> > app_code = cc
> > check_url = http://127.0.0.1/login/accounts/get_user/?bk_token=
> > bk_account_url = http://127.0.0.1/login/accounts/get_all_user/?bk_token=%s
> > resources_path = /tmp/
> > html_root = ../web
> > full_text_search = on
> > [app]
> > agent_app_url = http://127.0.0.1/console/?app=bk_agent_setup
> > authscheme = internal
> > [login]
> > version=opensource
> 
> user_info= 这里写账号密码，用：分割，比如 cc:cc
> 然后登陆的时候进入 /login 页面进行登录即可

[auth]
address =
appCode = bk_cmdb
appSecret =

[gse]
addr = 127.0.0.1:2181
user = bkzk
pwd = L%blKas

[timer]
spec = 00:30  # 00:00 - 23:59

[es]
full_text_search = on
url=http://127.0.0.1:9200
usr =
pwd =

[api]
version = v3
[session]
name = cc3
defaultlanguage = zh-cn
multiple_owner = 0
user_info= cc:cc
[site]
domain_url = http://192.168.0.83:8083/
bk_login_url = http://127.0.0.1/login/?app_id=%s&c_url=%s
app_code = cc
check_url = http://127.0.0.1/login/accounts/get_user/?bk_token=
bk_account_url = http://127.0.0.1/login/accounts/get_all_user/?bk_token=%s
resources_path = /tmp/
html_root = ../web
full_text_search = on
[app]
agent_app_url = http://127.0.0.1/console/?app=bk_agent_setup
authscheme = internal
[login]
version=opensource

重启以后还是报一样的错误

**Comment by shenxg13** [comment]
> > > > > 看下配置说明，默认的登陆需要在配置文件里配置用户与密码信息。
> > > > 
> > > > 
> > > > 您好，没有找到类似说明，能稍微具体一些吗？谢谢。
> > > 
> > > 
> > > 请发下你的cmdb_adminserver/configure/common.conf配置信息
> > 
> > 
> > [auth]
> > address =
> > appCode = bk_cmdb
> > appSecret =
> > [gse]
> > addr = 127.0.0.1:2181
> > user = bkzk
> > pwd = L%blKas
> > [timer]
> > spec = 00:30 # 00:00 - 23:59
> > [es]
> > full_text_search = on
> > url=http://127.0.0.1:9200
> > usr =
> > pwd =
> > [api]
> > version = v3
> > [session]
> > name = cc3
> > defaultlanguage = zh-cn
> > multiple_owner = 0
> > user_info=
> > [site]
> > domain_url = http://192.168.0.83:8083/
> > bk_login_url = http://127.0.0.1/login/?app_id=%s&c_url=%s
> > app_code = cc
> > check_url = http://127.0.0.1/login/accounts/get_user/?bk_token=
> > bk_account_url = http://127.0.0.1/login/accounts/get_all_user/?bk_token=%s
> > resources_path = /tmp/
> > html_root = ../web
> > full_text_search = on
> > [app]
> > agent_app_url = http://127.0.0.1/console/?app=bk_agent_setup
> > authscheme = internal
> > [login]
> > version=opensource
> 
> user_info= 这里写账号密码，用：分割，比如 cc:cc
> 然后登陆的时候进入 /login 页面进行登录即可

可以了，谢谢。

**Comment by HuangJueXiang** [comment]
![image](https://user-images.githubusercontent.com/15144037/92096357-5e27bb80-ee09-11ea-957c-37d7e918cef8.png)
![image](https://user-images.githubusercontent.com/15144037/92096395-6aac1400-ee09-11ea-9378-4863d85cbe11.png)
咨询一下这是什么原因呢

**Comment by breezelxp** [comment]
现在默认是要有登陆的，如果你单独使用蓝鲸cmdb，可以在common.conf中配置对应的登陆信息，然后重启adminserver与webseerver即可正常登陆

**Comment by HuangJueXiang** [comment]
我已经重启好多次了，一直提示这个，比较奇怪

**Comment by HuangJueXiang** [comment]
> 现在默认是要有登陆的，如果你单独使用蓝鲸cmdb，可以在common.conf中配置对应的登陆信息，然后重启adminserver与webseerver即可正常登陆

我已经重启过了，我是拿源代码全部部署的哦，还是不能登录

![image](https://user-images.githubusercontent.com/15144037/92191134-8957ec80-ee95-11ea-9b28-7fa3060c455d.png)

**Comment by breezelxp** [comment]
看有的进程没起来，应该是你的配置有问题，你检查 下你的配置

**Comment by HuangJueXiang** [comment]
> 看有的进程没起来，应该是你的配置有问题，你检查 下你的配置

![image](https://user-images.githubusercontent.com/15144037/92215710-c6d56d80-eec7-11ea-9ffd-b97c88935272.png)
我在mongo.conf   增加了配置，还是报错，这个core服务启动不了
![image](https://user-images.githubusercontent.com/15144037/92215818-eff5fe00-eec7-11ea-83e1-da69677163f6.png)

**Comment by HuangJueXiang** [comment]
> > 看有的进程没起来，应该是你的配置有问题，你检查 下你的配置
> 
> ![image](https://user-images.githubusercontent.com/15144037/92215710-c6d56d80-eec7-11ea-9ffd-b97c88935272.png)
> 我在mongo.conf 增加了配置，还是报错，这个core服务启动不了
> ![image](https://user-images.githubusercontent.com/15144037/92215818-eff5fe00-eec7-11ea-83e1-da69677163f6.png)

来个大神帮忙看下

**Comment by breezelxp** [comment]
mongodb要是rs模式的，看起来你的mongodb不是rs模式

**Comment by HuangJueXiang** [comment]
> mongodb要是rs模式的，看起来你的mongodb不是rs模式

 已经配置了 rs模式
 现在服务 全启动了，就是登录不了，不知道哪里错了
![image](https://user-images.githubusercontent.com/15144037/92352090-e363e680-f10f-11ea-9733-ddfca0d34ed0.png)
![image](https://user-images.githubusercontent.com/15144037/92352202-1dcd8380-f110-11ea-9ff7-5af38fb98421.png)

![image](https://user-images.githubusercontent.com/15144037/92352157-0a221d00-f110-11ea-8f68-bd39fbe04aeb.png)

**Comment by HuangJueXiang** [comment]
> mongodb要是rs模式的，看起来你的mongodb不是rs模式

反复折腾几次，搞定了

**Comment by MrYHM** [comment]
楼主，我遇到了和你一样的问题，请问你是怎么解决的啊
