### ISSUE TITLE
agent在哪里下载

### ISSUE THREAD

**Issue by hanizhong** [Tencent/bk-cmdb#4492]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
bk.tencent.com下载社区版使用。

**Comment by hanizhong** [comment]
想

> bk.tencent.com下载社区版使用。

找不到下载地址--，看来还是得全家桶才行

**Comment by timesking** [comment]
为什么gse, gse agent不开源?
