### ISSUE TITLE
蓝鲸CMDB自定义模块无法和`集群`， `模块` 创建拓补关系的实例.

### ISSUE THREAD

**Issue by Odinbk** [Tencent/bk-cmdb#4519]
问题描述
===========
蓝鲸CMDB自定义模型可以和默认的`集群`， `模块`创建拓补关系，但是无法在自定义模型实例中创建拓补关系的实例。和`业务`， `主机` 则可以，这是为什么呢。

**Comment by breezelxp** [comment]
拓扑是有层级 的，默认是业务、集群、模块、主机

**Comment by Odinbk** [comment]
可能是我没有描述清楚我的问题。默认的拓补层级我们是在使用的。
现在有一个场景是： 
1. 我需要自定一个模型，比如叫做 平台`platform`。 平台属于一个集群`set`。
2. 我在蓝鲸上可以创建 平台 --属于--> 集群的拓补关系。
3. 创建一个平台的实例, 比如叫做 `腾讯QQ`。 现在我想创建一个 `腾讯QQ`平台和某个集群的关联，但是在蓝鲸上没有可以编辑这条关系的地方。

但是假如平台是属于某个业务的，则可以创建实例的关联。 

我想问下这是为什么呢，是设计上就是这样，还是没有找到正确的入口。 如果是设计就是这样的，那意味着需要和`集群`， `模块` 创建关联的自定义模型，都是无法创建关联的。 这样的话数据一致性约束的只能靠人工维护字段，容易出错。

**Comment by Odinbk** [comment]
@breezelxp https://github.com/Tencent/bk-cmdb/issues/1820 在Issue中找到了类似的提问，已经被关闭。

**Comment by breezelxp** [comment]
目前还没放开这方面的关联，可以后续关注一下。

**Comment by Odinbk** [comment]
好的，我们目前只能曲线救国绕过了。
