### ISSUE TITLE
版本升级，关联数据无法展示

### ISSUE THREAD

**Issue by strangercs** [Tencent/bk-cmdb#4522]
问题描述
===========

cmdb 3.2.21版本访问0.0.42版本的mongodb数据库时，关联关系全都没有了，字段的关联关系全都无法读取。基础数据都在，这是什么bug么？？还是数据库字段有变化

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
有报什么错误信息吗？
