### ISSUE TITLE
init.py初始化无法生成对应目录

### ISSUE THREAD

**Issue by liu01100115** [Tencent/bk-cmdb#4550]
问题描述
===========

init.py初始化无法生成对应目录

重现方法
================

python init.py --discovery 127.0.0.1:2181 --database cmdb --redis_ip 127.0.0.1 --redis_port 6379 --redis_pass yxy@2018 --mongo_ip 127.0.0.1 --mongo_port 27017 --mongo_user cc --mongo_pass cc --blueking_cmdb_url http://127.0.0.1:8088 --listen_port 8088

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by LieLieLiekey** [comment]
有无出现失败信息？

**Comment by wcy00000000000000** [comment]
init.py 是用来生成配置文件的，目录是make的时候生成的
