### ISSUE TITLE
3.8.x 版本 web 页面筛选功能失效

### ISSUE THREAD

**Issue by Baiang** [Tencent/bk-cmdb#4554]
> 问题描述

![68322590-07AA-420E-931B-26949140A864](https://user-images.githubusercontent.com/8638857/90489886-7d1f2000-e170-11ea-99a9-38f50edf877b.png)

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
是说排序功能吗？
