### ISSUE TITLE
3.8.x 阿里云 Mongodb 连接数打满

### ISSUE THREAD

**Issue by Baiang** [Tencent/bk-cmdb#4562]
问题描述
===========
在 3.8.x 启动服务后，阿里云 Mongodb  连接数打满

重现方法
================

![image](https://user-images.githubusercontent.com/8638857/90724605-66540700-e2f1-11ea-9e76-9b74de771995.png)

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [x] MongoDB   版本: 4.2.0
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
连接数可以通过配置文件配置，mongo.conf。

**Comment by rentiansheng** [comment]
可以用netstat 看下cmdb是拿个服务发起的连接。

**Comment by Baiang** [comment]
mongodb 设置了连接数，现在阿里 mongodb 监控为 350 左右的连接数，这个有点奇怪。配置如下：

Mongodb 配置情况：阿里 1核2G 最大连接数为 500

```
database = cmdb
maxOpenConns = 10
maxIdleConns = 5
```

**Comment by rentiansheng** [comment]
你再部署cmdb 机器上， 连接mongodb 的都是什么服务， 每个服务的连接个数是多少。

**Comment by Baiang** [comment]
每个服务的连接个数：

- cmdb_admin: 12
- cmdb_core: 166
- cmdb_event: 22
- cmdb_data: 22
- cmdb_task：22
