### ISSUE TITLE
cmdb3.1.0版本中的api超时问题

### ISSUE THREAD

**Issue by xinxin2882** [Tencent/bk-cmdb#4584]
问题描述
===========
数据量少时没有遇到这个问题，数据量大了以后查询和存入inst时遇到的问题

重现方法
================
POST  http://****:8083/api/v3/inst/search/owner/0/object/server

返回信息：
{"result":false,"bk_error_code":1199036,"bk_error_msg":"proxy request failed","data":null}

关键信息
Binary: Built with gc go1.11.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0827 16:03:46.484213   28973 service.go:103] *failed do request[url: http://*******:60002/topo/v3/inst/search/owner/0/object/server] , err: Post http://********:60002/topo/v3/inst/search/owner/0/object/server: net/http: timeout awaiting response headers

请提供以下信息:

 - [x] bk-cmdb   版本:

**Comment by breezelxp** [comment]
针对你查询的场景，优化下cc_ObjectBase的索引看看

**Comment by breezelxp** [comment]
"proxy request failed"这个错和 “awaiting response headers” 这个错是同一个请求里出现的么？
