### ISSUE TITLE
3.8.x  Redis key无法自动过期，keys 一直增长到打满 Redis 服务

### ISSUE THREAD

**Issue by Baiang** [Tencent/bk-cmdb#4593]
问题描述
===========

脚本会每 10 分钟同步 6000 条数据到 CMDB，但是 Redis 对之前的数据没有自动过期，会一直增长。https://github.com/Tencent/bk-cmdb/issues/4562

重现方法
================

![image](https://user-images.githubusercontent.com/8638857/91690257-37168300-eb98-11ea-93fe-6dfa6899d692.png)

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
你用什么脚本，同步的什么数据？

**Comment by Baiang** [comment]
@breezelxp 写的定时及脚本，每十分钟调 CMDB 的添加和修改接口，来同步从阿里云的 ECS 数据到 CMDB。
