### ISSUE TITLE
启动CMDB失败，cmdb_coreservice启动不成功

### ISSUE THREAD

**Issue by Ssstring** [Tencent/bk-cmdb#4619]
问题描述
===========

启动CMDB失败，cmdb_coreservice启动不成功，查看日志报错：
Log file created at: 2020/09/06 16:04:31
Running on machine: VM-253-19-centos
Binary: Built with gc go1.13.14 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0906 16:04:31.030370   16841 event/watch.go:42] mongodb watch failed with conf: {Options:{MajorityCommitted:0xc000b4e050 MaxAwaitTime:1s OperationType:<nil> Filter:map[] EventStruct:0xc000528608 Collection:cc_ApplicationBase StartAfterToken:0xc0000730c0 StartAtTime:<nil>}}, err: (Location40415) BSON field '$changeStream.startAfter' is an unknown field.
E0906 16:04:31.030622   16841 event/flow.go:146] run flow, but watch failed, err: watch collection: cc_ApplicationBase failed, err: (Location40415) BSON field '$changeStream.startAfter' is an unknown field.
E0906 16:04:31.030632   16841 event/event.go:45] run biz event flow failed, err: watch collection: cc_ApplicationBase failed, err: (Location40415) BSON field '$changeStream.startAfter' is an unknown field.
E0906 16:04:31.030641   16841 service/service.go:152] new watch event failed, err: watch collection: cc_ApplicationBase failed, err: (Location40415) BSON field '$changeStream.startAfter' is an unknown field.
E0906 16:04:31.030650   16841 coreservice/main.go:46] process stopped by watch collection: cc_ApplicationBase failed, err: (Location40415) BSON field '$changeStream.startAfter' is an unknown field.

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: v3.5.35
 - [ ] Redis     版本: 
 - [x] MongoDB   版本: 4.0.20
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : centos
 - [ ] bk-cmdb 异常日志

**Comment by LieLieLiekey** [comment]
mongodb版本太低，至少4.2，详情请看首页部署文档。
