### ISSUE TITLE
通过agent导入主机，怎么玩

### ISSUE THREAD

**Issue by HuangJueXiang** [Tencent/bk-cmdb#4620]
http://127.0.0.1/console/?app=bk_agent_setup  打不开

**Comment by HuangJueXiang** [comment]
/usr/local/gse/agent/etc/agent.conf   Agent在哪里怎么玩咯

**Comment by HuangJueXiang** [comment]
求大神回答

**Comment by breezelxp** [comment]
这个需要使用蓝鲸社区版才可以，具体可以在bk.tencent.com了解
