### ISSUE TITLE
导入主机资源的时候，提示资源池业务不存在

### ISSUE THREAD

**Issue by luluming** [Tencent/bk-cmdb#47]
![image](https://user-images.githubusercontent.com/29649477/28951204-1d4f5684-78fc-11e7-9af5-c924aeb04626.png)

**Comment by luluming** [comment]
![image](https://user-images.githubusercontent.com/29649477/28952303-da519c28-7902-11e7-9fb3-a7bc342d4d7e.png)
现在一直停留在导入界面，日志报错，内容如图所示，不知道怎么来处理了

**Comment by rentiansheng** [comment]
php -i|grep zip看看 php的zip扩展是不是存在
