### ISSUE TITLE
【功能】模型拓扑存储

### ISSUE THREAD

**Issue by uriwang** [Tencent/bk-cmdb#470]
1. 可以存储任意模型的全局拓扑
2. 提供存储和查询接口

**Comment by wusendong** [comment]
#  查询普通对象模型的拓扑图

- API: POST  /api/{version}/objects/topographics/scope_type/{scope_type}/scope_id/{scope_id}/action/search
- API 名称: search_object_topo_graphics
- 功能说明：
    - 中文：查询普通模型拓扑
    - english：search a topo graphics

- input body

``` json
none
```

**注:以上 JSON 数据中各字段的取值仅为示例数据。实际使用中可以按照查询的需求填写多个字段。**

- input 字段说明

| 字段|类型|必填|默认值|说明|Description|
|---|---|---|---|---| ---|
|scope_type|string|否|无|图形范围类型,可选global,biz,cls(当前只有global)|the graphical scope type, could be global,biz,cls|
|scope_id|string|否|无|图形范围类型下的ID,如果为global,则填0|the id under the graphical scope, should be 0 when socope type is global |


- output

``` json
{
    "result": true,
    "bk_error_code": 0,
    "bk_error_msg": null,
    "data": [
        {
            "node_type": "obj",
            "bk_obj_id": "switch",
            "bk_inst_id": 0,
            "node_name": "switch",
            "position": {
                "x": 100,
                "y": 100
            },
            "fext": {},
            "bk_obj_icon": "icon-cc-switch2",
            "scope_type": "global",
            "scope_id": "",
            "bk_biz_id": 1,
            "bk_supplier_account": "0",
            "assts": [
                {
                    "bk_asst_type": "singleasst",
                    "node_type": "obj",
                    "bk_obj_id": "host",
                    "bk_inst_id": 0,
                    "bk_object_att_id": "host_id",
                    "lable": {}
                }
            ]
        }
    ]
}
```

**注:以上 JSON 数据中各字段的取值仅为示例数据。**

- output 字段说明

| 字段|类型|说明|Description|
|---|---|---|---|
|result|bool|ture：成功，false：失败 |true:success, false: failure|
| bk_error_code | int | 错误编码。 0表示success，>0表示失败错误 |error code. 0 represent success, >0 represent failure code |
| bk_error_msg | string | 请求失败返回的错误信息 |error message from failed request|
|data|array|结果数据|the result|

data 字段说明

| 字段|类型|说明|Description|
|---|---|---|---|
|node_type|string|节点类型,可选obj,inst|node type, could be obj,inst|
|bk_obj_id|string|对象模型的ID|the object identifier|
|bk_inst_id|int|实例ID|the inst identifier|
|node_name|string|节点名,当node_type为obj时是模型名称,当node_type为inst时是实例名称|the node name|
|position|string|节点在图中的位置|the node position in the graphics|
|fext|object|前端扩展字段|the extention field for frondend|
|bk_obj_icon|string|对象模型的图标|the object icon|
|scope_type|string|图形范围类型,可选global,biz,cls(当前只有global)|the graphical scope type, could be global,biz,cls|
|scope_id|string|图形范围类型下的ID,如果为global,则填0|the id under the graphical scope, should be 0 when socope type is global |
|bk_biz_id|int|业务id|business id|
|bk_supplier_account|string|开发商账号|supplier account code|
|assts|array|关联节点|the associated end point|

assts 字段说明

| 字段|类型|说明|Description|
|---|---|---|---|
|bk_asst_type|string|关联类型|association type|
|node_type|string|节点类型,可选obj,inst|node type, could be obj,inst|
|bk_obj_id|string|对象模型的ID|the object identifier|
|bk_inst_id|int|实例ID|the inst identifier|
|bk_object_att_id|string|关联的属性|the associated attribute|
|lable|object|标签,扩展字段,未启用|the association lable|

**Comment by wusendong** [comment]
#  更新拓扑图

- API: POST  /api/{version}/objects/topographics/scope_type/{scope_type}/scope_id/{scope_id}/action/update
- API 名称: update_object_topo_graphics
- 功能说明：
    - 中文：更新拓扑图形
    - english：update a topo graphics

- input body

``` json
[
    {
        "node_type": "obj",
        "bk_obj_id": "switch",
        "bk_inst_id": 0,
        "position": {
            "x": 100,
            "y": 100
        },
        "fext": {},
        "bk_obj_icon": "icon-cc-switch2",
    }
]
```

**注:以上 JSON 数据中各字段的取值仅为示例数据。实际使用中可以按照查询的需求填写多个字段。**

- input 字段说明

| 字段|类型|必填|默认值|说明|Description|
|---|---|---|---|---| ---|
|scope_type|string|是|无|图形范围类型,可选global,biz,cls(当前只有global)|the graphical scope type, could be global,biz,cls|
|scope_id|string|是|无|图形范围类型下的ID,如果为global,则填0|the id under the graphical scope, should be 0 when socope type is global |
|node_type|string|是|无|节点类型,可选obj,inst|node type, could be obj,inst|
|bk_obj_id|string|是|无|对象模型的ID|the object identifier|
|bk_inst_id|int|是|无|实例ID|the inst identifier|
|position|string|否|无|节点在图中的位置|the node position in the graphics|
|fext|object|否|无|前端扩展字段|the extention field for frondend|
|bk_obj_icon|string|否|无|对象模型的图标|the object icon|

> node_type,bk_obj_id,bk_inst_id三者唯一确定每张图的一个节点,故必填

**注:以上 JSON 数据中各字段的取值仅为示例数据。**

- output

``` json
{
    "result": true,
    "bk_error_code": 0,
    "bk_error_msg": null,
    "data": "success"
}
```


**注:以上 JSON 数据中各字段的取值仅为示例数据。**

- output 字段说明

| 字段|类型|说明|Description|
|---|---|---|---|
|result|bool|ture：成功，false：失败 |true:success, false: failure|
| bk_error_code | int | 错误编码。 0表示success，>0表示失败错误 |error code. 0 represent success, >0 represent failure code |
| bk_error_msg | string | 请求失败返回的错误信息 |error message from failed request|
|data|string|结果数据|the result|

**Comment by joe511230** [comment]
fext建议更名为ext或者extension，更有语义些，不用特指前端

**Comment by lowenitt** [comment]
更新请求建议改为post方式

**Comment by wusendong** [comment]
@joe511230 好的，fext 已改为ext
