### ISSUE TITLE
zk重启导致服务不可用

### ISSUE THREAD

**Issue by a775189488** [Tencent/bk-cmdb#4948]
问题描述
===========
zk重启导致服务不可用

重现方法
================
1. 正常启动cmdb各个服务，在前端可以正常crud
2. 重启zk后，等待10s左右
3. 前端访问时报错 oop 。进入zk查看 /cc/service/endpoints/apiserver 下的地址为空
4. 查看cmdb_apiserver后台日志 ，发现关键日志
```
watch register node(/cc/services/endpoints/coreservice/127.0.0.1) exist changed, event({EventNotWatching StateDisconnected /cc/services/endpoints/coreservice/_c_469ea3f182eb49c4fe40768a3405f740-127.0.0.10000000005 zk: zookeeper is closing
```
5. 经过代码排查，zk重启后 src/common/registerdiscover/zkregdiscv.go:RegisterAndWatch 函数中 ExistW调用阻塞，没有进行地址再写入
6. 经过反复重试。目前apiserver和hostserver，datacollection，eventserver都出现类似情况

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 3.8x
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 3.4.14
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
好的，我们看下，感谢反馈

**Comment by breezelxp** [comment]
@a775189488 确认了一下，烦请升级到v3.9使用

**Comment by a775189488** [comment]
> @a775189488 确认了一下，烦请升级到v3.9使用

能把相应问题的commit连接发一下吗。

**Comment by breezelxp** [comment]
> > @a775189488 确认了一下，烦请升级到v3.9使用
> 
> 能把相应问题的commit连接发一下吗。

https://github.com/Tencent/bk-cmdb/tree/v3.9.x

**Comment by a775189488** [comment]
> > > @a775189488 确认了一下，烦请升级到v3.9使用
> > 
> > 
> > 能把相应问题的commit连接发一下吗。
> 
> https://github.com/Tencent/bk-cmdb/tree/v3.9.x

我指的是fix这个问题的commit。。。或者关键代码位置告诉我也行
