### ISSUE TITLE
编译到 make ui时会出现JavaScript heap out of memory

### ISSUE THREAD

**Issue by wing731** [Tencent/bk-cmdb#4966]
问题描述
===========
编译 v3.9.12或3.9.14版本时，当编译到 make ui时会出现JavaScript heap out of memory

#15 313.3 > node build/build.js "BUILD_OUTPUT=/data/src/configcenter/src/bin/build/v3.9.14"
#15 313.3
#15 484.9
#15 484.9 <--- Last few GCs --->
#15 484.9
#15 484.9 [88:0x4665cc0]   168962 ms: Mark-sweep 969.6 (1009.1) -> 965.2 (1011.1) MB, 874.1 / 0.0 ms  (average mu = 0.152, current mu = 0.042) allocation failure scavenge might not succeed
#15 484.9 [88:0x4665cc0]   170231 ms: Mark-sweep 971.8 (1011.1) -> 967.3 (1012.8) MB, 1243.8 / 0.0 ms  (average mu = 0.079, current mu = 0.020) allocation failure scavenge might not succeed
#15 484.9
#15 484.9
#15 484.9 <--- JS stacktrace --->
#15 484.9
#15 484.9 ==== JS stack trace =========================================
#15 484.9
#15 484.9     0: ExitFrame [pc: 0x13da519]
#15 484.9 Security context: 0x24bd23e40921 <JSObject>
#15 484.9     1: token(aka token) [0x1d473f89a431] [0x2516315c04b9 <undefined>:~1918] [pc=0x1c970792d474](this=0x2516315c04b9 <undefined>,0x28ac18923ef1 <String[#4]: punc>,0x2516315c6261 <String[#1]: ]>,0x2516315c04b9 <undefined>)
#15 484.9     2: next_token [0x1d473f899fb1] [0x2516315c04b9 <undefined>:~2289] [pc=0x1c97077bb2bf](this=0x1d473f89a129 <Object map = 0x139dc8a78611>,0x25...
#15 484.9
#15 484.9 FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
#15 485.0  1: 0xa0e670 node::Abort() [node]
#15 485.0  2: 0xa0ea9c node::OnFatalError(char const*, char const*) [node]
#15 485.0  3: 0xb83afe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
#15 485.0  4: 0xb83e79 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
#15 485.0  5: 0xd32305  [node]
#15 485.0  6: 0xd32996 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
#15 485.0  7: 0xd41209 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
#15 485.0  8: 0xd42045 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
#15 485.0  9: 0xd44b1c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
#15 485.0 10: 0xd0b6f4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
#15 485.0 11: 0x105790e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
#15 485.0 12: 0x13da519  [node]
#15 485.1 Aborted
#15 485.1 npm ERR! code ELIFECYCLE
#15 485.1 npm ERR! errno 134
#15 485.1 npm ERR! bk-cmdb-ui@1.0.0 build: `node build/build.js "BUILD_OUTPUT=/data/src/configcenter/src/bin/build/v3.9.14"`
#15 485.1 npm ERR! Exit status 134
#15 485.1 npm ERR!
#15 485.1 npm ERR! Failed at the bk-cmdb-ui@1.0.0 build script.
#15 485.1 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#15 485.1
#15 485.1 npm ERR! A complete log of this run can be found in:
#15 485.1 npm ERR!     /root/.npm/_logs/2020-12-16T03_19_37_177Z-debug.log
#15 485.2 make: *** [Makefile:40: ui] Error 134
------
executor failed running [/bin/sh -c cd /data/src/configcenter/src/ && export GOPATH=/data/  && make ui]: exit code: 2

重现方法
================
make ui

关键信息
=========

 - [x] bk-cmdb   版本: 
Version  : oc-19.01.30
Tag      : 
Branch   : v3.9.12和v3.9.14
BuildTime: 2019-01-30T11:29:27+0800

**Comment by joe511230** [comment]
编译机多大的内存？

**Comment by wing731** [comment]
16G

**Comment by wing731** [comment]
> 编译机多大的内存？

16G的内存

**Comment by wing731** [comment]
通过添加export NODE_OPTIONS="--max_old_space_size=4096"，解决了OOM问题，但是编译UI还是失败

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   'BUILD_OUTPUT=/data/src/configcenter/src/bin/build/v3.9.14'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.14.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle bk-cmdb-ui@1.0.0~prebuild: bk-cmdb-ui@1.0.0
6 info lifecycle bk-cmdb-ui@1.0.0~build: bk-cmdb-ui@1.0.0
7 verbose lifecycle bk-cmdb-ui@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle bk-cmdb-ui@1.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/data/src/configcenter/src/ui/node_modules/.bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle bk-cmdb-ui@1.0.0~build: CWD: /data/src/configcenter/src/ui
10 silly lifecycle bk-cmdb-ui@1.0.0~build: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'node build/build.js "BUILD_OUTPUT=/data/src/configcenter/src/bin/build/v3.9.14"'
10 silly lifecycle ]
11 silly lifecycle bk-cmdb-ui@1.0.0~build: Returned: code: 137  signal: null
12 info lifecycle bk-cmdb-ui@1.0.0~build: Failed to exec build script
13 verbose stack Error: bk-cmdb-ui@1.0.0 build: `node build/build.js "BUILD_OUTPUT=/data/src/configcenter/src/bin/build/v3.9.14"`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid bk-cmdb-ui@1.0.0
15 verbose cwd /data/src/configcenter/src/ui
16 verbose Linux 4.19.121-linuxkit
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "BUILD_OUTPUT=/data/src/configcenter/src/bin/build/v3.9.14"
18 verbose node v13.14.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 137
22 error bk-cmdb-ui@1.0.0 build: `node build/build.js "BUILD_OUTPUT=/data/src/configcenter/src/bin/build/v3.9.14"`
22 error Exit status 137
23 error Failed at the bk-cmdb-ui@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]`

**Comment by joe511230** [comment]
用node10或者12试试

**Comment by wing731** [comment]
换成node 12可以了

**Comment by shiftwinting** [comment]
可以试一试：npm 升级为8.3.0，源可以试一试 腾讯或者阿里，gcc：9.3.1
目前试过：如果是用make ui NPM=cnpm 很容易内存崩溃。

目前版本：
系统：
node v14.17.0
npm： 8.3.0
go： 1.17
CentOS Linux release 7.9.2009
gcc：9.3.1
下载github master代码 可以编译通过。

**Comment by King-Connor** [comment]
> 

我也遇到 make ui NPM=cnpm的内存崩溃错误了
