### ISSUE TITLE
cmdb系统点击注销，返回http://127.0.0.1/login ，如何修改为服务器ip地址

### ISSUE THREAD

**Issue by hj00494yong** [Tencent/bk-cmdb#4988]
问题描述
===========
服务器下载腾讯云 cmdb：v3.9.5 镜像，修改 run.sh 里 ip ，访问服务器ip+端口 正常，功能也正常使用，但是点击注销后跳转连接还是http://127.0.0.1/login/?app_id=cc&c_url=http://ip:8081, 无法找到页面  ，请问如何修改注销跳转地址

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
请问这个容器镜像，你是用的我们的体验镜像吗？

**Comment by hj00494yong** [comment]
对的 ，腾讯云公共镜像  ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:v3.9.5

**Comment by breezelxp** [comment]
可以调整下common.yaml中的这两个参数，指定到你想要的地址。
bkLoginUrl: 
bkHttpsLoginUrl:
