### ISSUE TITLE
CMDB由社区版3.2.21升级到社区版3.9.11，MongoDB数据不匹配，需要做什么升级

### ISSUE THREAD

**Issue by lxyang1997** [Tencent/bk-cmdb#4998]
问题描述
===========
CMDB由社区版3.2.21升级到社区版3.9.11，MongoDB数据不匹配，需要做什么升级

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
重复issue: https://github.com/Tencent/bk-cmdb/issues/4997
