### ISSUE TITLE
点击URL为空/account/login?cburl= 

### ISSUE THREAD

**Issue by franklyu** [Tencent/bk-cmdb#5]
/account/login?cburl=   URL为空；
![image](https://cloud.githubusercontent.com/assets/10069795/21383384/765c3bec-c7a0-11e6-8b5f-996674a10581.png)

**Comment by lowenitt** [comment]
把配置文件贴下吧，应该是
![image](https://cloud.githubusercontent.com/assets/14356794/21385551/e5edbde2-c7a9-11e6-92f1-89a611e619d8.png)
这里的配置有问题

**Comment by radiogit** [comment]
这个问题怎么解决的啊？

**Comment by franklyu** [comment]
主要是以下问题：

#fastcgi_index  index.php;
fastcgi_index  /opt/app/bk-cmdb/index.php;
fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;


之后就OK了。




在 2016-12-22 15:15:03，"陈希忠" <notifications@github.com> 写道：


这个问题怎么解决的啊？

**Comment by lowenitt** [comment]
ok!
