### ISSUE TITLE
2021-01-17 按文档下载编译报错：building server...  bash: ./build.sh: No such file or directory

### ISSUE THREAD

**Issue by LQCong** [Tencent/bk-cmdb#5024]
问题描述
===========
日期：2021/1/17   git clone 下载源码，按文档编译报错：
[root@localhost opt]# cd configcenter/src/
[root@localhost src]# make

building server... 
bash: ./build.sh: No such file or directory
make: *** [default] Error 127

重现方法
================
[root@localhost opt]# git clone https://github.com/Tencent/bk-cmdb  configcenter
[root@localhost opt]# configcenter/src
[root@localhost src]# make
[root@localhost opt]# cd configcenter/src/
[root@localhost src]# make

building server... 
bash: ./build.sh: No such file or directory
make: *** [default] Error 127

关键信息
=========
操作系统：CentOS Linux release 7.7.1908

**Comment by breezelxp** [comment]
需要配置下GOPATH环境变量

**Comment by LQCong** [comment]
@breezelxp 非常感谢，配置GOPATH就可以了，新版本GOLANG安装没要求要配置这个变量，没配置
