### ISSUE TITLE
请问这个CMDB是不包含对具体业务服务配置文件的管理嘛？

### ISSUE THREAD

**Issue by whulyx** [Tencent/bk-cmdb#5070]
问题描述
===========
最近我们也在设计实现一套自己的CMDB，所以找了很多开源的项目进行学习参考，也对蓝鲸进行了体验，发现这套CMDB好像是没有设计去管理各种服务进程的配置文件的？包括配置的发布、生效等等。

**Comment by mrmgxxxx** [comment]
@whulyx  thanks for asking,

- 目前没有在CMDB上直接支持服务配置文件的管理；
- 蓝鲸体系内具备服务配置文件管理的能力；
- 目前针对服务配置文件的管理在蓝鲸BSCP，支持进程和容器环境的配置文件纳管；
- 蓝鲸SaaS产品中GSEKit目前具备针对进程环境的纳管，后续会发布对容器环境的支持；

**Comment by whulyx** [comment]
@mrmgxxxx 多谢老哥的回复。

**Comment by whulyx** [comment]
@mrmgxxxx 多谢老哥的回复。

**Comment by whulyx** [comment]
@mrmgxxxx 多谢老哥的回复。

- 请问蓝鲸BSCP指的是https://github.com/Tencent/bk-bcs这个项目嘛？
- 想请教下就是你们在BSCP里面管理配置文件的时候，有没有对配置文件进行结构化的抽象？还是说直接管理的不同格式的配置文本内容？

**Comment by mrmgxxxx** [comment]
> @mrmgxxxx 多谢老哥的回复。
> 
> * 请问蓝鲸BSCP指的是[https://github.com/Tencent/bk-bcs这个项目嘛？](https://github.com/Tencent/bk-bcs%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E5%98%9B%EF%BC%9F)
> * 想请教下就是你们在BSCP里面管理配置文件的时候，有没有对配置文件进行结构化的抽象？还是说直接管理的不同格式的配置文本内容？

BSCP是蓝鲸基础服务配置管理平台的简称，基于容器起步目前在bk-bcs下做开源版本的代码托管。
配置结构纳管业界常见做法有两种：
一种是针对不同格式做适配，例如kv、json、yaml、xml、execl等, 适合前后台紧密的架构，存储层面结构相比较为复杂；
另一种是采用通用的抽象纳管不同配置数据，这种多以平台级产品为主，BSCP属于该类，提供通用的KV、文件配置管理。蓝鲸BSCP的思想是做为配置中心的原子平台，需求方可以基于原子接口打造出符合自己业务场景的配置SaaS。

**Comment by whulyx** [comment]
> > @mrmgxxxx 多谢老哥的回复。
> > 
> > * 请问蓝鲸BSCP指的是[https://github.com/Tencent/bk-bcs这个项目嘛？](https://github.com/Tencent/bk-bcs%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E5%98%9B%EF%BC%9F)
> > * 想请教下就是你们在BSCP里面管理配置文件的时候，有没有对配置文件进行结构化的抽象？还是说直接管理的不同格式的配置文本内容？
> 
> BSCP是蓝鲸基础服务配置管理平台的简称，基于容器起步目前在bk-bcs下做开源版本的代码托管。
> 配置结构纳管业界常见做法有两种：
> 一种是针对不同格式做适配，例如kv、json、yaml、xml、execl等, 适合前后台紧密的架构，存储层面结构相比较为复杂；
> 另一种是采用通用的抽象纳管不同配置数据，这种多以平台级产品为主，BSCP属于该类，提供通用的KV、文件配置管理。蓝鲸BSCP的思想是做为配置中心的原子平台，需求方可以基于原子接口打造出符合自己业务场景的配置SaaS。

多谢回复。我们的设想也是第二种思路，将配置抽象为通用的kv概念，不过抽象之后，就相当于把用户（可能大部分都是开发同学）原来接触的很熟悉的配置文件转化为了比较陌生的结构化信息，这样就增加了管理维护上的成本，同时相比于直接管理原始配置文件，结构化的抽象配置在发布生效的步骤上也会增加复杂度，不知道你们针对这些问题有没有什么比较好的解决方法呀？

**Comment by mrmgxxxx** [comment]
> > > @mrmgxxxx 多谢老哥的回复。
> > > 
> > > * 请问蓝鲸BSCP指的是[https://github.com/Tencent/bk-bcs这个项目嘛？](https://github.com/Tencent/bk-bcs%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E5%98%9B%EF%BC%9F)
> > > * 想请教下就是你们在BSCP里面管理配置文件的时候，有没有对配置文件进行结构化的抽象？还是说直接管理的不同格式的配置文本内容？
> > 
> > 
> > BSCP是蓝鲸基础服务配置管理平台的简称，基于容器起步目前在bk-bcs下做开源版本的代码托管。
> > 配置结构纳管业界常见做法有两种：
> > 一种是针对不同格式做适配，例如kv、json、yaml、xml、execl等, 适合前后台紧密的架构，存储层面结构相比较为复杂；
> > 另一种是采用通用的抽象纳管不同配置数据，这种多以平台级产品为主，BSCP属于该类，提供通用的KV、文件配置管理。蓝鲸BSCP的思想是做为配置中心的原子平台，需求方可以基于原子接口打造出符合自己业务场景的配置SaaS。
> 
> 多谢回复。我们的设想也是第二种思路，将配置抽象为通用的kv概念，不过抽象之后，就相当于把用户（可能大部分都是开发同学）原来接触的很熟悉的配置文件转化为了比较陌生的结构化信息，这样就增加了管理维护上的成本，同时相比于直接管理原始配置文件，结构化的抽象配置在发布生效的步骤上也会增加复杂度，不知道你们针对这些问题有没有什么比较好的解决方法呀？

这个成本的增加是肯定的，需要一定的学习成本，但这个可能还不是主要问题，在产品层面上由配置文件转为KV的问题可能更大。
一个是文件格式不同本质上不一定能做好转换，特别是一些私有格式文件、二进制格式，单纯的KV很难支持，同时对老业务接入侵入性过大。我们在这个问题上采用的是通用Config模型，KV和文件抽象是一样的三要素（name、content、namespace），单一配置做为App内最小单元进行管理和下发，在发布后通过reload控制版本检查，在落地环节以内存KV和磁盘文件两种方式呈现。这样整体上看无论任何结构都是统一的，通用的，可控的。在SaaS层面可以做丰富的结构化呈现，但原子层都是一致视图。

**Comment by whulyx** [comment]
> > > > @mrmgxxxx 多谢老哥的回复。
> > > > 
> > > > * 请问蓝鲸BSCP指的是[https://github.com/Tencent/bk-bcs这个项目嘛？](https://github.com/Tencent/bk-bcs%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E5%98%9B%EF%BC%9F)
> > > > * 想请教下就是你们在BSCP里面管理配置文件的时候，有没有对配置文件进行结构化的抽象？还是说直接管理的不同格式的配置文本内容？
> > > 
> > > 
> > > BSCP是蓝鲸基础服务配置管理平台的简称，基于容器起步目前在bk-bcs下做开源版本的代码托管。
> > > 配置结构纳管业界常见做法有两种：
> > > 一种是针对不同格式做适配，例如kv、json、yaml、xml、execl等, 适合前后台紧密的架构，存储层面结构相比较为复杂；
> > > 另一种是采用通用的抽象纳管不同配置数据，这种多以平台级产品为主，BSCP属于该类，提供通用的KV、文件配置管理。蓝鲸BSCP的思想是做为配置中心的原子平台，需求方可以基于原子接口打造出符合自己业务场景的配置SaaS。
> > 
> > 
> > 多谢回复。我们的设想也是第二种思路，将配置抽象为通用的kv概念，不过抽象之后，就相当于把用户（可能大部分都是开发同学）原来接触的很熟悉的配置文件转化为了比较陌生的结构化信息，这样就增加了管理维护上的成本，同时相比于直接管理原始配置文件，结构化的抽象配置在发布生效的步骤上也会增加复杂度，不知道你们针对这些问题有没有什么比较好的解决方法呀？
> 
> 这个成本的增加是肯定的，需要一定的学习成本，但这个可能还不是主要问题，在产品层面上由配置文件转为KV的问题可能更大。
> 一个是文件格式不同本质上不一定能做好转换，特别是一些私有格式文件、二进制格式，单纯的KV很难支持，同时对老业务接入侵入性过大。我们在这个问题上采用的是通用Config模型，KV和文件抽象是一样的三要素（name、content、namespace），单一配置做为App内最小单元进行管理和下发，在发布后通过reload控制版本检查，在落地环节以内存KV和磁盘文件两种方式呈现。这样整体上看无论任何结构都是统一的，通用的，可控的。在SaaS层面可以做丰富的结构化呈现，但原子层都是一致视图。

多谢老哥分享思路，我也再去结合需求综合考虑一下，后续有机会可以再一起交流一下哈哈。

**Comment by mrmgxxxx** [comment]
> > > > > @mrmgxxxx 多谢老哥的回复。
> > > > > 
> > > > > * 请问蓝鲸BSCP指的是[https://github.com/Tencent/bk-bcs这个项目嘛？](https://github.com/Tencent/bk-bcs%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E5%98%9B%EF%BC%9F)
> > > > > * 想请教下就是你们在BSCP里面管理配置文件的时候，有没有对配置文件进行结构化的抽象？还是说直接管理的不同格式的配置文本内容？
> > > > 
> > > > 
> > > > BSCP是蓝鲸基础服务配置管理平台的简称，基于容器起步目前在bk-bcs下做开源版本的代码托管。
> > > > 配置结构纳管业界常见做法有两种：
> > > > 一种是针对不同格式做适配，例如kv、json、yaml、xml、execl等, 适合前后台紧密的架构，存储层面结构相比较为复杂；
> > > > 另一种是采用通用的抽象纳管不同配置数据，这种多以平台级产品为主，BSCP属于该类，提供通用的KV、文件配置管理。蓝鲸BSCP的思想是做为配置中心的原子平台，需求方可以基于原子接口打造出符合自己业务场景的配置SaaS。
> > > 
> > > 
> > > 多谢回复。我们的设想也是第二种思路，将配置抽象为通用的kv概念，不过抽象之后，就相当于把用户（可能大部分都是开发同学）原来接触的很熟悉的配置文件转化为了比较陌生的结构化信息，这样就增加了管理维护上的成本，同时相比于直接管理原始配置文件，结构化的抽象配置在发布生效的步骤上也会增加复杂度，不知道你们针对这些问题有没有什么比较好的解决方法呀？
> > 
> > 
> > 这个成本的增加是肯定的，需要一定的学习成本，但这个可能还不是主要问题，在产品层面上由配置文件转为KV的问题可能更大。
> > 一个是文件格式不同本质上不一定能做好转换，特别是一些私有格式文件、二进制格式，单纯的KV很难支持，同时对老业务接入侵入性过大。我们在这个问题上采用的是通用Config模型，KV和文件抽象是一样的三要素（name、content、namespace），单一配置做为App内最小单元进行管理和下发，在发布后通过reload控制版本检查，在落地环节以内存KV和磁盘文件两种方式呈现。这样整体上看无论任何结构都是统一的，通用的，可控的。在SaaS层面可以做丰富的结构化呈现，但原子层都是一致视图。
> 
> 多谢老哥分享思路，我也再去结合需求综合考虑一下，后续有机会可以再一起交流一下哈哈。

🤝，感谢关注蓝鲸https://bk.tencent.com，欢迎交流和提建议。
