### ISSUE TITLE
拉取镜像报403

### ISSUE THREAD

**Issue by nanshihui** [Tencent/bk-cmdb#5082]
问题描述
===========

拉取镜像报403 无法拉取镜像
重现方法
`docker pull ccr.ccs.tencentyun.com/bk.io/cmdb-standalone

Using default tag: latest
latest: Pulling from bk.io/cmdb-standalone
18b8eb7e7f01: Already exists
61cb1f08289f: Already exists
e3074b765e1f: Pulling fs layer
487ac69139aa: Pulling fs layer
error pulling image configuration: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<?xml version='1.0' encoding='utf-8' ?>\n<Error>\n\t<Code>SignatureDoesNotMatch</Code>\n\t<Message>The Signature you specified is invalid.</Message>\n\t<StringToSign>sha1\n1614666925;1614668125\n86ee1f43da612f1bdb907226f297ee195ff51a3c\n</StringToSign>\n\t<FormatString>get\n/docker/registry/v2/blobs/sha256/d7/d7463c2febd47ec401a873f325b9b89c9be9dff53d265752e03cd69cadcab4e7/data\n\nhost=ccr-1253687700.cn-south.myqcloud.com%3A80\n</FormatString>\n\t<Resource>ccr-1253687700.cn-south.myqcloud.com:80/docker/registry/v2/blobs/sha256/d7/d7463c2febd47ec401a873f325b9b89c9be9dff53d265752e03cd69cadcab4e7/data</Resource>\n\t<RequestId>NjAzZGRjYWZfZWZiYzJiMDlfMmRjNjNfOGQ3ZmRiMw==</RequestId>\n\t<TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTQyYWVlY2QwZTk2MDVmZDQ3MmI2Y2I4ZmI5ZmM4ODFjNzgzOTgwNzViNjMzYmIzOWU0OGIzNDBiMjIxNTkwZTk=</TraceId>\n</Error>\n\n"`

**Comment by breezelxp** [comment]
看起来是你的签名有问题，你重试下看看

**Comment by nanshihui** [comment]
重试无用， 是要添加什么源嘛？
