### ISSUE TITLE
资源池管理->导入主机，导不进去，提示{请导入xxxxxx文件}

### ISSUE THREAD

**Issue by opser-gavin** [Tencent/bk-cmdb#51]
资源池管理->导入主机，导不进去，提示{请导入xxxxxx文件}
修改多次excel文件，都不行

**Comment by amazingbing** [comment]
![image](https://user-images.githubusercontent.com/25680177/29555301-c9ac43c2-8754-11e7-82c9-49d76af8f507.png)

**Comment by amazingbing** [comment]
怎么改都报，上面的错误！

**Comment by lowenitt** [comment]
可以尝试看下日志中文件的类型记录

**Comment by rentiansheng** [comment]
请使用v3新版本
