### ISSUE TITLE
打开首页时候出现错误:[owner_id]授权信息查询失败

### ISSUE THREAD

**Issue by raulooxiao** [Tencent/bk-cmdb#5129]
问题描述
===========
1. cmdb为编译安装，各个中间件均按照推荐版本安装
2. cmdb 版本 3.9.x

打开首页时候出现错误：[owner_id]授权信息查询失败
![image](https://user-images.githubusercontent.com/7604446/111859437-e6bc1280-897b-11eb-9f58-d3a880da5766.png)

重现方法
================
打开cmdb前端各个页面均会出现以上报错

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
Version     :
Tag         :
BuildTime   : 2021-03-19T17:04:25+0800
GitHash     :
RunMode     : product
Distribution: community
ServiceName : apiserver

**Comment by lgp520** [comment]
请问如何解决的？
