### ISSUE TITLE
业务拓扑中新增的自定义模型无法删除

### ISSUE THREAD

**Issue by vincentor** [Tencent/bk-cmdb#517]
问题描述
===========
后台配置——模型管理——业务拓扑——点击 线上的+号 增加了一个模型，发现模型直接影响了所有的业务拓扑展示，并且无法删除

重现方法
================

1. 后台配置——模型管理——业务拓扑——点击 线上的+号 增加了一个模型
2. 点击模型——其他操作——发现模型停用和模型删除 按钮无法点击，并且没有提示为何无法删除

关键信息
=========

![image](https://user-images.githubusercontent.com/2193194/40604357-5f078374-6291-11e8-8733-b201a865668e.png)

请提供以下信息:

 - [x] bk-cmdb   3.0.6

**Comment by lowenitt** [comment]
@techfindd

**Comment by techfindd** [comment]
是因为拉取了master分支，这个分支实时更新，但是不够稳定
