### ISSUE TITLE
关于业务拓扑的疑问和交流

### ISSUE THREAD

**Issue by vincentor** [Tencent/bk-cmdb#518]
当前的实现业务拓扑是直接跟所有业务关联，并且自定义的模型和模型分组，似乎没法定义和形成类似业务拓扑一样的层级业务结构，这种情况下在以下的场景下不太适用。

1. A 类业务是游戏业务，其拓扑结构为： 项目—> 大区—>游戏服—>模块
2. B 类业务是 web 业务， 其拓扑结构为：项目—>集群—> 服务—> vhost

在这种情况下，虽然可以通过自定义模型和模型关系将上述两个业务结构数据存储下来，但是无法通过直观的树形业务拓扑将整个业务展示给用户，让用户直观的添加业务集群和实例。

这一方面有什么改进计划或者使用上的建议么？

**Comment by lowenitt** [comment]
@techfindd

**Comment by lowenitt** [comment]
@vincentor    可以在模型中的主线模型添加  ，来自定义主线拓扑的层级   从而去管理类似的需求， 但是我们有一点限制，  最少是3级  即业务->(自定义层级)->集群->模块->主机

**Comment by vincentor** [comment]
@lowenitt 请问主线模型具体是指？是指下面这个么：
![image](https://user-images.githubusercontent.com/2193194/40711825-c20fa6f6-642e-11e8-8bd1-a793927bc2ec.png)

如果是，那如何解决不同业务需要不同拓扑层级的问题呢？
