### ISSUE TITLE
批量更新主机提示“主机已存在”

### ISSUE THREAD

**Issue by qinglu111** [Tencent/bk-cmdb#5180]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by qinglu111** [comment]
![image](https://user-images.githubusercontent.com/82210108/114160869-f6ff5600-9959-11eb-8e31-e1f938c98b34.png)

**Comment by qinglu111** [comment]
看文档得知：录入同样内网 IP，是属性覆盖的操作，可以使用此特性对主机属性进行批量更新。
但是实际操作的时候报错 ，如上图。
安装的版本为v3.9.22

**Comment by wcy00000000000000** [comment]
3.9.22版本的主机导入分成了新增和更新两种，导入主机按钮是导入新增的主机，如果要对主机属性通过excel导入进行更新的话需要使用编辑按钮下拉栏的导入编辑按钮
![image](https://user-images.githubusercontent.com/40779709/114172372-29b04b00-9968-11eb-8375-f06a8fb84798.png)
