### ISSUE TITLE
创建模型失败建议给出明确的失败原因

### ISSUE THREAD

**Issue by vincentor** [Tencent/bk-cmdb#522]
问题描述
===========
创建模型失败的提示原因不明确，例如 已经存在重复的模型 等基础的情况没有明确提示

重现方法
================
在不同的模型分组下创建同名的模型（同名不同英文名）
![image](https://user-images.githubusercontent.com/2193194/40609701-0bc1184a-62a2-11e8-8b91-4c9676b170e3.png)

只提示了创建模型失败，但是没有给出失败原因

关键信息
=========

 - [x] bk-cmdb  3.0.6

**Comment by lowenitt** [comment]
@techfindd        目前项目正在对这一部分的输出进行整改

**Comment by uriwang** [comment]
@vincentor 错误信息反馈，这里正在调整，后续迭代会陆续改进。感谢反馈。

**Comment by uriwang** [comment]
新版本已在优化中。
