### ISSUE TITLE
编译完cmdb后，启动cmdb以及初始化数据库时出问题

### ISSUE THREAD

**Issue by dfdjoker** [Tencent/bk-cmdb#5227]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by dfdjoker** [comment]
运行start.sh发现有几个服务没有起来
![image](https://user-images.githubusercontent.com/7483406/116207519-8dad7e80-a772-11eb-92ad-097882d03ac2.png)
运行init_db.sh时，报collection already exists
![image](https://user-images.githubusercontent.com/7483406/116207784-d5340a80-a772-11eb-9530-c8925e89f162.png)

**Comment by ddyllen-z** [comment]
我也遇到这个问题，这是怎么回事？
