### ISSUE TITLE
【bug】连接mongo问题

### ISSUE THREAD

**Issue by zonzpoo** [Tencent/bk-cmdb#525]
问题描述
===========
mongo实例端口如果不是27017，运行init.py指定--mongo_port也报错
![image](https://user-images.githubusercontent.com/12594210/40635404-67ca04b4-632c-11e8-8d20-0d9c03177126.png)

关键信息
=========
```
	dialInfo := &mgo.DialInfo{
		Addrs:     []string{m.host},
		Direct:    false,
		Timeout:   time.Second * 5,
		Database:  m.dbName,
		Source:    "",
		Username:  m.usr,
		Password:  m.pwd,
		PoolLimit: 4096,
		Mechanism: m.mechanism,
	}
```
这里的Addrs的参数应该改为 m.host:m.port

**Comment by wusendong** [comment]
fixed in #511
