### ISSUE TITLE
容器化安装导入主机选择自动导入无法访问

### ISSUE THREAD

**Issue by Hyakusenrenma** [Tencent/bk-cmdb#5263]
使用容器化安装，导入主机选择自动导入{点此进入节点管理}按钮会跳转到http://127.0.0.1/console/?app=bk_agent_setup无法访问，是我少装东西了吗

**Comment by breezelxp** [comment]
使用蓝鲸社区版才会有这个功能，具体见bk.tencent.com

**Comment by Hyakusenrenma** [comment]
> 使用蓝鲸社区版才会有这个功能，具体见bk.tencent.com

谢谢您的回复，我在[社区版](https://bk.tencent.com/download/)这个下载地址里点击立即下载后填写完信息提交，表单关闭后没有任何反应，不返回任何链接或者开始下载，不知道您那可以吗，或者有其他的下载地址。

**Comment by breezelxp** [comment]
这个功能是跳转到节点管理这个saas，你容器化部署配置的地址是127.0.0.1回环地址，访问不了paas的saas，所以才会出上面的问题。
你可以启动的时候用host模式启动，然后这个地址在配置文件里把127.0.0.1的地址填paas的真实地址即可。
