### ISSUE TITLE
添加批量创建通用模型实例的接口

### ISSUE THREAD

**Issue by chalice-1831** [Tencent/bk-cmdb#5266]
问题描述
=========
添加批量创建通用模型实例的接口
用于SaaS或其他api方式调用，批量创建通用模型实例

关键信息
=========
- [x] bk-cmdb 版本: v3.10.x

注意：该接口不允许创建自定义主线层级模型实例，最大数量为200个实例，需要鉴权

### 接口地址

POST /createmany/instance/object/{bk_obj_id}

### 请求参数

接口参数

| 参数      | 类型   | 必选 | 描述               |
| -------- | ------ | ---- | ------------------ |
| bk_obj_id | string | 是   | 用于创建的模型id，只允许创建通用模型的实例   |
| details   | array | 是   | 需要创建的实例内容，最多不能超过200个，内容为实例的属性，具体可参考示例 |

### 请求参数示例

```json
{
 	"bk_obj_id":"bk_switch",
	"details":[
		{
			"bk_inst_name": "s1",
    		"bk_asset_id":"test_001",
			"bk_sn": "00000001",
    		"bk_operator": "admin"
  		},
	  	{
			"bk_inst_name": "s2",
    		"bk_asset_id":"test_002",
    		"bk_sn": "00000002",
    		"bk_operator": "admin"
		},
    	{
			"bk_inst_name": "s3",
    		"bk_asset_id":"test_003",
      		"bk_sn": "00000003",
      		"bk_operator": "admin
	    }，
	]
}
```

### 返回结果示例

```json
{
	"result": true,
 	"code": 0,
	"message": "",
	"data": {
        "success_created": {
             "1": 1001,
             "2": 1002
          },
        "error_msg": {
             "0": "数据唯一性校验失败， [bk_asset_id: test_001] 重复",
          }
    }
}
```

#### data

| 字段            | 类型 | 描述                                                     |
| -------------- | ---- | -------------------------------------------------------- |
| success_created | map | key为实例在参数details中的index，value为创建成功的实例id |
| error_msg       | map | key为实例在参数details中的index，value为失败信息          |

**Comment by mrmgxxxx** [comment]
## 模型实例和实例关系方案

    弱化场景层逻辑，将设计IO的批量动作尽量下沉到CoreService
    

## 模型实例

* 将CoreService中CreateManyInstance接口进行改造
* TopoServer中只保留单纯的参数校验，创建动作在CoreService完成

### CreateManyInstance接口改造

* 返回结构按照批量模式返回，错误码列表（保证错误码和实例列表idx对应即可，不用显示增加idx到返回结构体中）
* 创建动作在CoreService中进行批量插入执行, 循环处理的只保留参数等校验，特别是唯一性校验，要依赖mongodb的索引完成
* 涉及ProcServer、HostServer中的调用，一并修改（处理返回结果逻辑）

### TopoServer接口实现

* 入参校验，返回结构处理
* 去除接口级别的唯一性校验


## 模型关系实例

* 将CoreService中CreateManyInstanceAssociation接口进行改造
* TopoServer中只保留单纯的参数校验，创建动作在CoreService完成

### CreateManyInstanceAssociation接口改造

* 接口外吐
* 关系实例存在性依靠：模型实例 + 关联模型实例 + 关系去判断唯一性
* 接口返回批量模式错误码列表

### TopoServer接口实现

* 入参校验，返回结构处理
* 去除接口级的唯一性校验（关系的mapping类型判断等依赖 模型实例 + 关联模型实例 + 关系在CoreService完成）

**Comment by chalice-1831** [comment]
## 针对Insert方法批量插入测试

- 允许单次插入多个数据
- 插入的数据可非顺序顺序检查
- 数据错误，Bulk的报错没有对应关系

## 结论

- 驱动无法优化，对于批量数据的插入仍需循环插入
- 对于mongo的操作无法调整，只能减少场景层网络IO环节
