### ISSUE TITLE
 get proc addr from service discovery module error: there is no proc servers

### ISSUE THREAD

**Issue by lixiaomeng8520** [Tencent/bk-cmdb#531]
问题描述
===========
init_db.sh  报502
cmdb_adminserver.ERROR里  get proc addr from service discovery module error: there is no proc servers

**Comment by rentiansheng** [comment]
1. 检查下 cmdb_procserver 是否启动， 
2. 已经启动，检查下端口是否在监听
3. 如果端口已经监听，请查看日志。看下哪里出现报错了
