### ISSUE TITLE
导入的EXCEL无法准确识别“数字类型”的文本

### ISSUE THREAD

**Issue by vincentor** [Tencent/bk-cmdb#532]
问题描述
===========
使用上传 excel 的方式导入模型实例，如果某个模型字段类型为 短文本，无法将以下类型的字段信息识别成文本。

如：有个字段 gid 类型为文本（因为要同时兼容 001 和 101 这种 id），因此在 excel 中对应字段的单元格格式设置为“文本格式”，但是上传的时候，依然将其识别成数字，而导致上传失败。

重现方法
================
1. 定义某个模型，设置字段（如 gid ）为 短文本 类型
2. 导入模型实例时， excel 对应列，单元格格式设置为 文本 格式，对应值包括 001， 101， 1002 这种类型的文本值
3. 对应 excel 上传，会提示 gid 的类型必须为字符串类型

![image](https://user-images.githubusercontent.com/2193194/40649662-148a4ca4-6364-11e8-8a0a-8d3f188cc7c9.png)

![image](https://user-images.githubusercontent.com/2193194/40649791-5c5e0606-6364-11e8-9dd3-ec0b5d42326c.png)

建议解析 excel 的时候，按单元格属性解析

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb  3.0.6

**Comment by rentiansheng** [comment]
@vincentor  你用的导入文件是下载的模板还是导出数据的excel。 你用的excel 是office 还是wps。 配置平台在excel 的模板中已经设置该列的数据类型。 原则上改列应该为字符串的。  从表现上来，你这一列的数据不是字符串的。 字符串格式的单元格中，输入数字的展示应该是这样的
![image](https://user-images.githubusercontent.com/3955934/40656219-496e4378-6376-11e8-956c-e23aa0db4c20.png)

**Comment by vincentor** [comment]
我用的是 mac os 下的 office 365
![image](https://user-images.githubusercontent.com/2193194/40656494-2066b202-6377-11e8-9cb3-4fc2470af639.png)

我的操作方式是这样的：

**Comment by rentiansheng** [comment]
@vincentor  但是从excel 表现来看，设置excel格式为生效， 你如改文件不涉及敏感信息，可以提供下excel 我测试下。 根据字段类型识别数据。 这个是一个优化项目。 最近应该是没有时间来开发。

**Comment by rentiansheng** [comment]
@vincentor 
先在支持当字段类型为配置平台数字型的时候， 输入数字型的转化

数字转化为字符串暂时未支持的， 因为excel数字以科学计数法存储。填写过大数字，由于科学计数法精度的问题，会造成转化的数字并不是用户填写的数字。
