### ISSUE TITLE
按照编译指南无法成功编译 FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Hyakusenrenma** [Tencent/bk-cmdb#5341]
关键信息
=========
node -v    v12.22.1
go version go1.15.5 linux/amd64
python v 2.7.5
cmdb https://github.com/Tencent/bk-cmdb/archive/refs/tags/release-v3.9.26.tar.gz

按照步骤：https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/source_compile.md
编译报错如下

> bk-cmdb-ui@1.0.0 build /home/qtdev/cmdb/src/configcenter/src/ui
> node builder/build.js "BUILD_OUTPUT=/home/qtdev/cmdb/src/configcenter/src/bin/build/"

fatal: Not a git repository (or any of the parent directories): .git
Ignore: Get commit id failed
  build [====================] 100% (127.6 seconds)

Build completed in 127.591s

  build [====================] 99% (136.1 seconds)
<--- Last few GCs --->

[99944:0x4000880]   202376 ms: Scavenge 2032.0 (2058.2) -> 2026.3 (2073.9) MB, 9.2 / 0.0 ms  (average mu = 0.189, current mu = 0.117) allocation failure
[99944:0x4000880]   203413 ms: Mark-sweep 2036.8 (2073.9) -> 2030.2 (2052.4) MB, 222.7 / 0.6 ms  (+ 751.0 ms in 168 steps since start of marking, biggest step 10.5 ms, walltime since start of marking 1036 ms) (average mu = 0.157, current mu = 0.123) final

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x140de99]
Security context: 0x15b3b9f408d1 <JSObject>
    1: /* anonymous */ [0x3fabaa0c3a81] [/home/qtdev/cmdb/src/configcenter/src/ui/node_modules/_webpack@5.38.1@webpack/lib/FileSystemInfo.js:~2828] [pc=0x3374c05ddb4a](this=0x02968dc428e1 <GlobalObject Object map = 0x187c495d8a39>,0x2abd1b2801b9 <null>,0x0e74591e2499 <JSArray[5]>)
    2: go$readdir$cb [0xd2c5dc7a4a1] [/home/qtdev/cmdb/src/configcenter/src/ui/node...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa1a640 node::Abort() [node]
 2: 0xa1aa4c node::OnFatalError(char const*, char const*) [node]
 3: 0xb9a68e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb9aa09 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd57c85  [node]
 6: 0xd58316 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd64bd5 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd65a85 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd6853c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xd2ef5b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x107158e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x140de99  [node]

**Comment by breezelxp** [comment]
你内存太小了，编译前端至少需要1G以上内存。

**Comment by Hyakusenrenma** [comment]
我64G内存。。在ui的package.json build 里加了个--max_old_space_size=32000也还是能占满

**Comment by Hyakusenrenma** [comment]
我这具体是编译到100%会退回99%，之后开始内存增长，到最后溢出，换了几个环境都是这样。

**Comment by Hyakusenrenma** [comment]
> 你内存太小了，编译前端至少需要1G以上内存。

大哥方便能把您编译好的cmdb.tar.gz给我发一份吗，我这把这个没编译完的运行authserver起不来 ，init_db也有问题
a57080a@hotmail.com

**Comment by wjyfelen** [comment]
已发送请查收~

**Comment by Hyakusenrenma** [comment]
> > 你内存太小了，编译前端至少需要1G以上内存。
> 
> 大哥方便能把您编译好的cmdb.tar.gz给我发一份吗，我这把这个没编译完的运行authserver起不来 ，init_db也有问题
> [a57080a@hotmail.com](mailto:a57080a@hotmail.com)

非常感谢，但是把web移过去还是不行。。方便分享一下您编译环境吗

**Comment by Hyakusenrenma** [comment]
> 已发送请查收~
非常感谢，但是把web移过去还是不行。。方便分享一下您编译环境吗，还有源码是git clone https://github.com/Tencent/bk-cmdb  configcenter 这个嘛

**Comment by Hyakusenrenma** [comment]
同样的环境编译https://github.com/Tencent/bk-cmdb/releases/tag/release-v3.9.5这个就成功了，也能运行

**Comment by wjyfelen** [comment]
附件是我的编译环境信息，源码是基于v3.9.x这个版本







在 2021-06-11 14:45:40，"Hyakusenrenma" ***@***.***> 写道：

已发送请查收~
非常感谢，但是把web移过去还是不行。。方便分享一下您编译环境吗，还有源码是git clone https://github.com/Tencent/bk-cmdb configcenter 这个嘛

**Comment by Hyakusenrenma** [comment]
> 附件是我的编译环境信息，源码是基于v3.9.x这个版本

非常感谢，使用旧版本可以正常编译了

**Comment by woshihaoren** [comment]
@Hyakusenrenma 老哥你怎么搞定的。我npm run dev，3.9.5 没问题，3.9.30不行，起来内存一只涨，然后6g就oom了

**Comment by yangyy** [comment]
@woshihaoren 请确保 npm 版本 < 7

**Comment by woshihaoren** [comment]
@yangyy  是<7的。3.9.25及之后的版本都不行。之前的都没问题。
```
zhan@C0GC4HM ui % npm -v
6.14.14
zhan@C0GC4HM ui % node -v
v12.22.5
```

**Comment by yangyy** [comment]
@woshihaoren 使用 https://github.com/Tencent/bk-cmdb/archive/refs/tags/release-v3.9.30.zip 未能复现，请贴下 npm run dev 运行日志情况？

**Comment by woshihaoren** [comment]
@yangyy 构建完后页面能正常打开，啥都不动，一会就oom了。
```
% export NODE_OPTIONS="--max-old-space-size=8192"
% git branch                                     
* (HEAD detached at release-v3.9.30)
  master
% npm run dev                                    

> bk-cmdb-ui@1.0.0 dev /Users/gaowei02/hb_code/bk-cmdb/src/ui
> node builder/dev.js

  build [                    ] 0% (0.0 seconds)[HPM] Proxy created: /proxy  ->  http://{webserver地址}/
[HPM] Proxy rewrite rule created: "^/proxy" ~> ""
  build [==                  ] 8% (0.2 seconds)ℹ ｢wds｣: Project is running at http://localhost:9090/
ℹ ｢wds｣: webpack output is served from /static/
ℹ ｢wds｣: 404s will fallback to /index.html
  build [==                  ] 10% (0.6 seconds)ℹ ｢wdm｣: wait until bundle finished: /static/index.html
  build [====================] 100% (53.6 seconds)

Build completed in 53.638s

ℹ ｢wdm｣: Compiled with warnings.

<--- Last few GCs --->

[90161:0x102d83000]    88734 ms: Scavenge 3413.0 (3617.1) -> 3397.0 (3617.1) MB, 1.8 / 0.0 ms  (average mu = 0.961, current mu = 0.963) allocation failure 
[90161:0x102d83000]    88755 ms: Scavenge 3413.0 (3617.1) -> 3397.0 (3617.1) MB, 1.5 / 0.0 ms  (average mu = 0.961, current mu = 0.963) allocation failure 
[90161:0x102d83000]    88774 ms: Scavenge 3413.0 (3617.1) -> 3397.0 (3617.1) MB, 1.7 / 0.0 ms  (average mu = 0.961, current mu = 0.963) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x100a04099]
Security context: 0x38a1523408d1 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [0x38a14b87fd99] [/Users/gaowei02/hb_code/bk-cmdb/src/ui/node_modules/_webpack@5.53.0@webpack/lib/FileSystemInfo.js:~3365] [pc=0x29cccdde456c](this=0x38a14d5804b1 <undefined>,0x38a1a5686c21 <String[96]: /Users/gaowei02/hb_code/bk-cmdb/src/ui/node_modules/_validate.io-number@1.0.3@validate.io-number>,0x38a14b851d09 <JS...

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
 1: 0x1011f7a65 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x1000a5fd9 node::Abort() [/usr/local/bin/node]
 3: 0x1000a613f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001efb57 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001efaf7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x100386445 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x10035af4a v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::RootIndex, int, v8::internal::Object, v8::internal::AllocationType) [/usr/local/bin/node]
 8: 0x1004d5a14 v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacity(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/usr/local/bin/node]
 9: 0x10068585c v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
10: 0x100a04099 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
zsh: abort      npm run dev

```

**Comment by shiftwinting** [comment]
可以试一试：npm 升级为8.3.0，源可以试一试 腾讯或者阿里，gcc：9.3.1
目前试过：如果是用make ui NPM=cnpm 很容易内存崩溃。

目前版本：
系统：
node v14.17.0
npm： 8.3.0
go： 1.17
CentOS Linux release 7.9.2009
gcc：9.3.1
下载github master代码 可以编译通过。

**Comment by yuuagoo** [comment]
> 可以试一试：npm 升级为8.3.0，源可以试一试 腾讯或者阿里，gcc：9.3.1 目前试过：如果是用make ui NPM=cnpm 很容易内存崩溃。
> 
> 目前版本： 系统： node v14.17.0 npm： 8.3.0 go： 1.17 CentOS Linux release 7.9.2009 gcc：9.3.1 下载github master代码 可以编译通过。

内核版本：Linux version 5.4.0-107-generic 
系统：Ubuntu 9.4.0-1ubuntu1~20.04.1
gcc： 9.4.0
node：v14.17.0
npm：6.14.13 (不使用cnpm)

master分支编译通过
