### ISSUE TITLE
转成了http://cmdb.jj-inn.com/account/login?cburl= 然后404页面

### ISSUE THREAD

**Issue by tangyawen** [Tencent/bk-cmdb#54]
@lowenitt http://cmdb.jj-inn.com 结果浏览器url跳转成了http://cmdb.jj-inn.com/account/login?cburl= 然后依然是空白页面。在/data/session目录看到3个ci_session*文件…… 请问如何解决此问题

**Comment by lowenitt** [comment]
麻烦贴下配置文件

**Comment by haoyuxy** [comment]
php 7         'dbdriver' => 'mysqli',   这个改改试试

**Comment by rentiansheng** [comment]
请使用v3新版本
