### ISSUE TITLE
get default appid failed: target app not found, init database first and it would try again in 10s seconds later

### ISSUE THREAD

**Issue by Hyakusenrenma** [Tencent/bk-cmdb#5437]
问题描述
===========
三台服务器，其中一台运行一段时间以后DataCollection突然报get default appid failed: target app not found, init database first and it would try again in 10s seconds later，查看redis和mongodb什么的都正常

重现方法
================
[root@logging1 cmdb_datacollection]# cat logs/std.log
begin to discover by watch children of path(/cc/services/endpoints/datacollection)
begin to discover by watch children of path(/cc/services/endpoints/proc)
begin to discover by watch children of path(/cc/services/endpoints/topo)
begin to discover by watch children of path(/cc/services/endpoints/task)
begin to discover by watch children of path(/cc/services/endpoints/auth)
begin to discover by watch children of path(/cc/services/endpoints/cloud)
begin to discover by watch children of path(/cc/services/endpoints/host)
begin to discover by watch children of path(/cc/services/endpoints/migrate)
begin to discover by watch children of path(/cc/services/endpoints/apiserver)
begin to discover by watch children of path(/cc/services/endpoints/eventserver)
begin to discover by watch children of path(/cc/services/endpoints/coreservice)
begin to discover by watch children of path(/cc/services/endpoints/operation)
watch found the children of path(/cc/services/endpoints/datacollection) change. event type:EventNodeChildrenChanged, event err:<nil>
E0702 17:17:32.943412   75320 app/server.go:404] DataCollection| get default appid failed: target app not found, init database first and it would try again in 10s seconds later

关键信息
=========

 - [x] bk-cmdb   版本: 
[root@logging1 cmdb]# ./cmdb_apiserver/cmdb_apiserver --version
Version  :
Tag      :
BuildTime: 2021-06-15T09:01:52+0800
GitHash  :
RunMode  : product

 -->
 - [x] Redis     版本: 3.2.11
 - [ ] MongoDB   版本: 2.8.0
 - [ ] ZooKeeper 版本: 3.4.11
 - [ ] 操作系统      : Centos 7 x64
 - [ ] bk-cmdb 异常日志

**Comment by wcy00000000000000** [comment]
看一下是否有“蓝鲸”这个业务
