### ISSUE TITLE
现在导出excel主机关联信息是否会导出？

### ISSUE THREAD

**Issue by woshihaoren** [Tencent/bk-cmdb#5478]
问题描述
===========
现在导出excel主机关联信息是否会导出？

重现方法
================
导出excel,没看到关联交换机到信息

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 3.9.28
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志
<img width="1446" alt="9F6598DC-F702-4138-ACCE-9965A9F4C6B7" src="https://user-images.githubusercontent.com/4115501/125613764-1b6ab4ff-6c41-420c-86dd-5fb78a7691cc.png">

**Comment by wcy00000000000000** [comment]
会导出的，在assocation这里
![image](https://user-images.githubusercontent.com/40779709/125753259-ff4044a8-086a-477b-9467-31d707a914e6.png)

**Comment by woshihaoren** [comment]
@wcy00000000000000 没有呀，里面是空的。我是哪里做的不对吗？
<img width="819" alt="CA08C445-A167-483C-A55F-E54D06C2BA57" src="https://user-images.githubusercontent.com/4115501/125757961-8449fd9b-4e1c-4113-90e9-d51dbca859f5.png">

我关联了一个交换机。
<img width="1632" alt="switch" src="https://user-images.githubusercontent.com/4115501/125758331-83a33011-eb46-4e2a-9b3e-59d938423dd5.png">
