### ISSUE TITLE
release安装包缺失目录

### ISSUE THREAD

**Issue by dusu0114** [Tencent/bk-cmdb#5499]
刚接触，想搭建cmdb学习下，遇到点问题：

按照安装文档说明下载了release的安装包，下载的安装包解压后跟文档列出的目录结构差异较大，缺少很多目录，直接运行报错configures目录不存在

安装文档说明的目录结果
![image](https://user-images.githubusercontent.com/19700525/126130748-61e6eaff-eecc-4aef-abdb-b6e6b56f9cdb.png)

下载的release版的3.9.28和3.10都是这样的目录结构
![image](https://user-images.githubusercontent.com/19700525/126131051-99a3d412-4ebe-4594-a4f0-31a8837122bb.png)

直接执行初始化提示
![image](https://user-images.githubusercontent.com/19700525/126131182-92c70874-e7d4-4c40-8ffa-58925b3fde28.png)

有人遇到过吗

**Comment by breezelxp** [comment]
你下载的应该是源码，编译可以看这里：
https://github.com/Tencent/bk-cmdb/blob/v3.10.x/docs/overview/source_compile.md
