### ISSUE TITLE
docker 部署3.9.28，容器运行脚本提示没有目录

### ISSUE THREAD

**Issue by jhsswl** [Tencent/bk-cmdb#5514]
问题描述
===========

docker部署，提示没有目录

[root@ ~]# docker logs cocky_golick
ZooKeeper JMX enabled by default
Using config: /data/sidecar/zookeeper/bin/../conf/zoo.cfg
Starting zookeeper ... STARTED
start zookeeper success.
start redis success.
about to fork child process, waiting until server is ready for connections.
forked process: 44
child process started successfully, parent exiting
start mongodb success.
./run.sh: line 13: cd: /data/cmdb: No such file or directory
python: can't open file 'init.py': [Errno 2] No such file or directory
./run.sh: line 17: cd: /data/cmdb/cmdb_adminserver/configures/: No such file or directory
sed: can't read common.conf: No such file or directory
sed: can't read common.yaml: No such file or directory
./run.sh: line 23: cd: /data/cmdb: No such file or directory
./run.sh: line 24: ./start.sh: No such file or directory
./run.sh: line 27: cd: cmdb_adminserver: No such file or directory

[root@cd50576ce097 data]# ls
cmdb_v3.9.28  down.sh  run.sh  sidecar

[root@cd50576ce097 data]# cat run.sh
#!/bin/bash
# invalid in skip-login mode
ip=127.0.0.1
port=8090

cd /data/sidecar && ./initialize.sh

if [ $? != 0 ]
then
	echo "start db fail."
fi

cd /data/cmdb

脚本写到是/data/cmdb，而实际是/data/cmdb_v3.9.28 

重现方法
================

docker run -d -p 8081:8090 ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:latest
docker logs cocky_golick

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by linfang-canway** [comment]
镜像已更新，请重新拉取
