### ISSUE TITLE
无法通过页面创建自定义模型实例和集群实例关系

### ISSUE THREAD

**Issue by zhouyuyong** [Tencent/bk-cmdb#5581]
问题描述
===========
在模型关系中可以创建自定义模型与业务、集群、模块的关系，但是在做自定义模型实例的关联时选取列表中只有和业务的关系，只能选择通过API接口关联

**Comment by zhouyuyong** [comment]
创建模型关系
![image](https://user-images.githubusercontent.com/7124402/129520659-40eeaf6c-bc7d-4640-8851-2ca26c2932f6.png)
创建实例关系
![image](https://user-images.githubusercontent.com/7124402/129521110-b8e8e03b-7b63-478b-b2f8-3ae48df6747a.png)

**Comment by wcy00000000000000** [comment]
目前因为集群和模块属于业务的“主线模型”，是平台的内置形态所以没开放实例的关联关系
