### ISSUE TITLE
无法导入主机

### ISSUE THREAD

**Issue by xymkljb** [Tencent/bk-cmdb#56]
从文件导入主机时提示403，权限检查都没有问题，请帮忙看一下
php-fpm和nginx都以http用户运行的，importPrivateHostByExcel文件夹权限是750，属主属组都是http
![default](https://user-images.githubusercontent.com/11566113/32829769-ff446b42-ca2d-11e7-8259-afadf7b2f2b2.png)
![default](https://user-images.githubusercontent.com/11566113/32829799-1c136318-ca2e-11e7-9929-1c4e3372acb9.png)
![default](https://user-images.githubusercontent.com/11566113/32829874-57bf6ea2-ca2e-11e7-82d4-057fac714f2a.png)

**Comment by lowenitt** [comment]
这个nginx的配置就不正确，麻烦贴下nginx的配置吧

**Comment by xymkljb** [comment]
啊，这个问题已经解决了，当时nginx所在目录权限的问题，非常感谢！
