### ISSUE TITLE
点击注销返回127.0.0.1 。。。。 好像没有权限管理方面

### ISSUE THREAD

**Issue by hj00494yong** [Tencent/bk-cmdb#5614]
直接docker下载的腾讯云镜像    run   运行的     ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:latest

我想问下这个有密码管理吗，访问默认就进系统了。这个蓝鲸cmdb没有开源这些模块吗还是有其他部署方式呢

**Comment by breezelxp** [comment]
这个镜像是体验镜像，禁掉了登陆和权限相关的功能，如果要体验完整功能，可自已编译包部署，或者到bk.tencent.com下载蓝鲸社区版使用。

**Comment by hj00494yong** [comment]
蓝鲸社区版是不是需要完善下企业信息啊，这个有docker一键部署吗或者docker-compose

**Comment by hj00494yong** [comment]
精简版包含用户登陆与权限功能吗
&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/bk-cmdb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月31日(星期二) 上午8:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/bk-cmdb] 点击注销返回127.0.0.1 。。。。 好像没有权限管理方面 (#5614)





 
这个镜像是体验镜像，禁掉了登陆和权限相关的功能，如果要体验完整功能，可自已编译包部署，或者到bk.tencent.com下载蓝鲸社区版使用。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
