### ISSUE TITLE
在点击主机的时候，对已有的短字符的数据数据类型进行修改的时候，内容不合法

### ISSUE THREAD

**Issue by chenjun1206** [Tencent/bk-cmdb#5616]
问题描述
===========
在点击主机的时候，对已有的短字符的数据数据类型进行修改的时候，内容不合法

重现方法
================
![image](https://user-images.githubusercontent.com/45869281/131695914-8232ac17-45c1-4b9e-9d4a-27dbd571a2a4.png)

**Comment by wcy00000000000000** [comment]
麻烦提供下cmdb的版本号，然后看一下这个属性的正则校验配置
