### ISSUE TITLE
master 分支编译构建报错

### ISSUE THREAD

**Issue by heidsoft** [Tencent/bk-cmdb#5617]
go version go1.15.2 darwin/amd64

# configcenter/src/storage/dal/mongo/local
../storage/dal/mongo/local/transaction.go:35:2: undefined: mongo.CmdbPrepareCommitOrAbort
../storage/dal/mongo/local/transaction.go:63:2: undefined: mongo.CmdbPrepareCommitOrAbort
../storage/dal/mongo/local/txn_manager.go:93:62: undefined: mongo.SessionInfo
../storage/dal/mongo/local/txn_manager.go:94:9: undefined: mongo.CmdbReloadSession
../storage/dal/mongo/local/txn_manager.go:129:11: undefined: mongo.SessionInfo
../storage/dal/mongo/local/txn_manager.go:134:8: undefined: mongo.CmdbReloadSession
../storage/dal/mongo/local/txn_manager.go:163:13: undefined: mongo.CmdbContextWithSession
../storage/dal/mongo/local/txn_manager.go:224:13: undefined: mongo.CmdbContextWithSession
make[1]: *** [cmdb_apiserver] Error 2
make: *** [default] Error 2

**Comment by ponyhuang** [comment]
export GO111MODULE=off
请尝试先执行上面命令禁用模块支持，再执行编译

**Comment by heidsoft** [comment]
已经解决，将vendor中的参考自己建立了
github.com/rentiansheng/xlsx =》 github.com/heidsoft/xlsx
github.com/holmeswang/contrib/sessions => github.com/heidsoft/contrib/sessions

**Comment by chenjun1206** [comment]
请问一下，这个是怎么解决的呢

**Comment by chenjun1206** [comment]
> 已经解决，将vendor中的参考自己建立了
> github.com/rentiansheng/xlsx =》 github.com/heidsoft/xlsx
> github.com/holmeswang/contrib/sessions => github.com/heidsoft/contrib/sessions

你好  这个是怎么建立呢

**Comment by zhjdhx** [comment]
同问，如何解决？
