### ISSUE TITLE
master 分支编译构建报错

### ISSUE THREAD

**Issue by h920553245** [Tencent/bk-cmdb#5644]
使用master分支构建报错

系统：Macos
go：go version go1.17 darwin/amd64

在$GOPATH/src/configcenter/src下使用  make 
日志如下

building server... 
enter directory:  /Users/hergua/go/src/configcenter/src/apiserver

building the target: cmdb_apiserver... 

go build -i -ldflags "-X configcenter/src/common/version.CCVersion=master -X configcenter/src/common/version.CCBuildTime=2021-09-15T11:53:38+0800 -X configcenter/src/common/version.CCGitHash=5a64a47fa0f974ec13c64f1695dd055c39ed7e47 -X configcenter/src/common/version.CCTag=master -X configcenter/src/common/version.CCDistro=community" -o /Users/hergua/go/src/configcenter/src/bin/build/master/cmdb_apiserver/cmdb_apiserver
go: cannot find main module, but found vendor/vendor.json in /Users/hergua/go/src/configcenter
	to create a module there, run:
	cd ../.. && go mod init
make[1]: *** [cmdb_apiserver] Error 1
make: *** [default] Error 2

**Comment by snailshen2014** [comment]
解决了吗？我也遇到相同的问题
