### ISSUE TITLE
模型资源搜索时增加大小写不敏感

### ISSUE THREAD

**Issue by hongyuxuan** [Tencent/bk-cmdb#5650]
问题描述
===========
对某模型资源进行搜索时，目前大小写是敏感的，能否支持大小写不敏感？mongodb本身查询时可以用"$option":"i"支持大小写不敏感，但调用接口时增加"$option":"i"不起作用。

重现方法
================

资源视图选择任意一个资源模型，右上角搜索时输入关键词，必须严格匹配大小写才能查询出结果，无法支持不区分大小写。

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: v3.9.28
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by wcy00000000000000** [comment]
勾选“模糊”选项时是大小写不敏感的模糊搜索
![image](https://user-images.githubusercontent.com/40779709/200779670-58e4d922-14b3-4f90-b3d3-f98a84ef11ac.png)
