### ISSUE TITLE
cmdb_cloudserver无法开启

### ISSUE THREAD

**Issue by JFeng0820** [Tencent/bk-cmdb#5754]
问题描述
===========
cmdb_cloudserver无法开启

报错信息：
E1108 18:51:11.532463    4872 cloud_server/cloud.go:50] process stoped by connect mongo server failed, err: error parsing uri: must have at least 1 host

同一台机器开了三个mongodb实例

重现方法
================
下载后直接启动即可

=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [x] Redis     版本: 3.2.11
 - [x] MongoDB   版本: 4.2.0
 - [x] ZooKeeper 版本:  3.4.11
 - [x] 操作系统      :  Centos 7， debian9.5
 - [x] bk-cmdb 异常日志

E1108 18:51:11.390335    4872 mongo/config.go:92] parse mongo.maxOpenConns config error: strconv.ParseUint: parsing "": invalid syntax, use default value: 1000
E1108 18:51:11.390340    4872 mongo/config.go:103] parse mongo.maxIdleConns config encounters error strconv.ParseUint: parsing "": invalid syntax or 0 less than minimum value, use minimum value 50
E1108 18:51:11.532463    4872 cloud_server/cloud.go:50] process stoped by connect mongo server failed, err: error parsing uri: must have at least 1 host

**Comment by breezelxp** [comment]
应该是你的配置文件有问题，可以确认下
