### ISSUE TITLE
在业务创建时，无法选择人员

### ISSUE THREAD

**Issue by JFeng0820** [Tencent/bk-cmdb#5757]
问题描述
===========
在业务创建时，无法选择人员
![image](https://user-images.githubusercontent.com/51046768/141221620-7f798b42-f1e2-4bc5-9f19-0c1f944eb2fd.png)

重现方法
================
正常启动全部服务后，无法创建业务

关键信息
=========
GetUserList failed
 unsupported protocol scheme

请提供以下信息:

 - [x] bk-cmdb   版本: 
Version  : cmdbv3.9.x
Tag      : cmdbv3.9.x
BuildTime: 2021-11-08T18:13:26-0800
GitHash  : 0280d1fa9ef704adb60899502e5dfcfc026efe54
RunMode  : product

 - [x] Redis     版本: 3.2.11
 - [x] MongoDB   版本: 4.2.0
 - [x] ZooKeeper 版本:  3.4.11
 - [x] 操作系统      :  Centos 7， debian9.5
 - [x] bk-cmdb 异常日志
E1110 00:39:28.478416   23345 service/user.go:51] GetUserList failed, err: Get /api/c/compapi/v2/usermanage/list_users/?bk_app_code=&bk_app_secret=&bk_username=admin&fields=username%2Cid%2Cdisplay_name&fuzzy_lookups=ad&no_page=true: unsupported protocol scheme "", rid: cc0000c65oag7170hlmccj3s4g
E1110 00:39:41.944686   23345 rest/request.go:302] [apimachinery][peek] GET /api/c/compapi/v2/usermanage/list_users/?bk_app_code=&bk_app_secret=&bk_username=admin&fields=username%2Cid%2Cdisplay_name&fuzzy_lookups=ad&no_page=true with body , but Get /api/c/compapi/v2/usermanage/list_users/?bk_app_code=&bk_app_secret=&bk_username=admin&fields=username%2Cid%2Cdisplay_name&fuzzy_lookups=ad&no_page=true: unsupported protocol scheme "", rid: cc0000c65oajf170hlmccj3s50
E1110 00:39:41.944717   23345 logics/user.go:33] get users by esb client failed, http failed, err: Get /api/c/compapi/v2/usermanage/list_users/?bk_app_code=&bk_app_secret=&bk_username=admin&fields=username%2Cid%2Cdisplay_name&fuzzy_lookups=ad&no_page=true: unsupported protocol scheme "", rid: cc0000c65oajf170hlmccj3s50
E1110 00:39:41.944724   23345 service/user.go:51] GetUserList failed, err: Get /api/c/compapi/v2/usermanage/list_users/?bk_app_code=&bk_app_secret=&bk_username=admin&fields=username%2Cid%2Cdisplay_name&fuzzy_lookups=ad&no_page=true: unsupported protocol scheme "", rid: cc0000c65oajf170hlmccj3s50

**Comment by chalice-1831** [comment]
cmdb配置文件中的common.yaml中的webServer等配置项中没有配置esb地址导致请求失败，请根据如下配置项参考在common.yaml中配置esb的参数，具体的appsecret和appcode等可以在paas平台上获取
  esb:
    addr: {esb_url}
    appCode: bk_cmdb
    appSecret: {cmdb_secret}
    insecureSkipVerify: true
    certFile:
    keyFile:
    caFile:
    password:

**Comment by JFeng0820** [comment]
如果cmdb是单体应用，没有pass的话有其他解决方案吗

**Comment by chalice-1831** [comment]
可以将common.yaml中webserver的login设置为version: opensource然后设置session中的userinfo: {username}:{password}，或者将login改为version: skip-login

webServer:
  #会话相关
  session:
    #账号密码，以 : 分割
    userInfo: admin:blueking
  login:
    #登录模式
    version: opensource

或者
webServer:
  login:
    #登录模式
    version: skip-login

**Comment by JFeng0820** [comment]
python init.py配置的数据没有传入cmdb代码里面，这个应该怎么处理。现在运行起来的都是把ip端口数据之间写死在源码中。

**Comment by chalice-1831** [comment]
在启动cmdb_adminserver的时候附加参数./cmdb_adminserver --addrport={ip} --logtostderr=false --log-dir=./logs --v=3 --config=configures/migrate.yaml 具体参数可根据情况修改，--config后跟着的就是migrate.yaml文件的地址，启动后配置文件就会写入到cmdb中

**Comment by JFeng0820** [comment]
能加一下你QQ或者微信吗，有一些问题想请教一下
