### ISSUE TITLE
helm3  v3.10. cmdb安装 ./run.sh: line 27: ./init_db.sh: Permission denied 报错

### ISSUE THREAD

**Issue by xshi0001** [Tencent/bk-cmdb#5769]
问题描述
===========

按照文档k8s部署，helm3  v3.10. cmdb安装 ./run.sh: line 27: ./init_db.sh: Permission denied 报错

![image](https://user-images.githubusercontent.com/28589533/142381257-2fbd8b0d-f707-4fed-a57a-e87f283d9ba6.png)

重现方法
================

可以参考这个部署一下 https://github.com/Tencent/bk-cmdb/tree/v3.10.x/helm

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by miahwk** [comment]
我也是这个问题 不知道什么问题
