### ISSUE TITLE
运行./init_db.sh报错

### ISSUE THREAD

**Issue by kris-tang** [Tencent/bk-cmdb#5823]
问题描述
===========
执行./init_db.sh报错
{"result":false,"bk_error_code":1105000,"bk_error_msg":"迁移数据失败, server selection error: server selection timeout\ncurrent topology: Type: ReplicaSetNoPrimary\nServers:\n","permission":null,"data":null}

重现方法
================
重新执行./init_db.sh仍然显示{"result":false,"bk_error_code":1105000,"bk_error_msg":"迁移数据失败, server selection error: server selection timeout\ncurrent topology: Type: ReplicaSetNoPrimary\nServers:\n","permission":null,"data":null}

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 3.2.19
 
 - [ ] Redis     版本: 6.2.6
 - [ ] MongoDB   版本: 5.0.5
 - [ ] ZooKeeper 版本: 3.4.11
 - [ ] 操作系统      : macOS version11.1
 - [ ] bk-cmdb 异常日志

**Comment by ZQHcode** [comment]
mongo配置副本集有问题，检查下是否配置成功
