### ISSUE TITLE
Not Running:cmdb_authserver 和 Not Running：cmdb_webserver

### ISSUE THREAD

**Issue by kris-tang** [Tencent/bk-cmdb#5826]
问题描述
===========
在cmdb中运行./restart.sh
starting: cmdb_webserver
  501 42256     1   0 10:23AM ttys001    0:00.18 ./cmdb_adminserver --addrport=172.31.0.37:60004 --logtostderr=false --log-dir=./logs --v=3 --config=configures/migrate.yaml --register-ip=cmdb.domain.com
  501 42267     1   0 10:23AM ttys001    0:00.16 ./cmdb_apiserver --addrport=172.31.0.37:8080 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false --register-ip=cmdb.domain.com
  501 42289     1   0 10:23AM ttys001    0:00.27 ./cmdb_cacheservice --addrport=172.31.0.37:50010 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --register-ip=cmdb.domain.com
  501 42302     1   0 10:23AM ttys001    0:00.17 ./cmdb_cloudserver --addrport=172.31.0.37:60013 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false --enable_cryptor=false --register-ip=cmdb.domain.com
  501 42321     1   0 10:23AM ttys001    0:00.13 ./cmdb_coreservice --addrport=172.31.0.37:50009 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --register-ip=cmdb.domain.com
  501 42334     1   0 10:23AM ttys001    0:00.11 ./cmdb_datacollection --addrport=172.31.0.37:60005 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false --register-ip=cmdb.domain.com
  501 42345     1   0 10:23AM ttys001    0:00.18 ./cmdb_eventserver --addrport=172.31.0.37:60009 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false --register-ip=cmdb.domain.com
  501 42357     1   0 10:23AM ttys001    0:00.10 ./cmdb_hostserver --addrport=172.31.0.37:60001 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false --register-ip=cmdb.domain.com
  501 42369     1   0 10:23AM ttys001    0:00.10 ./cmdb_operationserver --addrport=172.31.0.37:60011 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false --register-ip=cmdb.domain.com
  501 42380     1   0 10:23AM ttys001    0:00.10 ./cmdb_procserver --addrport=172.31.0.37:60003 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false --register-ip=cmdb.domain.com
  501 42392     1   0 10:23AM ttys001    0:00.15 ./cmdb_taskserver --addrport=172.31.0.37:60012 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --register-ip=cmdb.domain.com
  501 42403     1   0 10:23AM ttys001    0:00.11 ./cmdb_toposerver --addrport=172.31.0.37:60002 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false --register-ip=cmdb.domain.com
  501 42414     1   0 10:23AM ttys001    0:00.00 ./cmdb_webserver --addrport=172.31.0.37:8080 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --register-ip=cmdb.domain.com
process count should be: 12 , now:       13
Not Running: cmdb_authserver
Not Running: cmdb_webserver

重现方法
================
重新运行./restart.sh后还是出现相同的情况。

关键信息
=========

1、查看cmdb_authserver.ERROR显示如下信息：
Log file created at: 2021/12/15 10:23:45
Running on machine: MacBook-Pro
Binary: Built with gc go1.15.6 for darwin/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1215 10:23:45.590755   42278 app/server.go:80] new iam client, err: no iam address
E1215 10:23:45.591858   42278 auth_server/auth.go:50] process stopped by no iam address
2、查看cmdb_webserver.ERROR显示如下信息：
请提供以下信息:
Log file created at: 2021/12/15 10:23:48
Running on machine: pauldeMacBook-Pro
Binary: Built with gc go1.15.6 for darwin/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F1215 10:23:48.503177   42414 backbone/http.go:75] listen and serve failed, err: listen tcp 172.31.0.37:8080: bind: address already in use
goroutine 62 [running]:
configcenter/src/common/blog/glog.stacks(0xc00012c001, 0xc0005aa000, 0x403, 0x2710)
	/Users/paul/bluewhale/src/configcenter/src/common/blog/glog/glog.go:781 +0xb9
 - [x] bk-cmdb   版本: 3.2.19
 
 - [ ] Redis     版本: 6.2.6
 - [ ] MongoDB   版本: 5.0.5
 - [ ] ZooKeeper 版本: 3.4.11
 - [ ] 操作系统      : macOS version11.1
 - [ ] bk-cmdb 异常日志

**Comment by zhanghao123321** [comment]
解决了么 我也是这个问题

**Comment by King-Connor** [comment]
请问如何解决 cmdb_authserver无法启动的问题的？ 我本地没有配置iam服务器
