### ISSUE TITLE
编译releasev3.10.10版本失败

### ISSUE THREAD

**Issue by zs1621** [Tencent/bk-cmdb#5871]
问题描述
===========
开源版本  release-v3.10.10 版本编译问题
go 版本 1.16.12

重现方法
================
安装编译文档执行  编译 

关键信息
=========
![image](https://user-images.githubusercontent.com/1854527/147481050-a4c5a9a5-c2c7-4c10-8413-dd7275e88c23.png)
![image](https://user-images.githubusercontent.com/1854527/147481160-b536e7c2-194b-4df7-8b93-cd51f855cbaa.png)

**Comment by ZQHcode** [comment]
是第一次使用cmdb然后编译报错吗，麻烦执行下go env提供下更多的信息
