### ISSUE TITLE
容器化部署版本（v3.9.28）无法新建业务

### ISSUE THREAD

**Issue by monkeyWuKong** [Tencent/bk-cmdb#5877]
问题描述
===========
容器化部署的版本无法新建业务
ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:v3.9.28

```
E1228 02:57:58.235945     729 instances/instance_validate.go:203] validCreateInstanceData failed, 
key: bk_childid, value: %!s(<nil>), err: 未知类型：%s, rid: cc0000c757qdfmr8igm3dbtic0


E1228 02:57:58.342211     729 instances/instance.go:73] CreateModelInstance failed, 
validCreateInstanceData error:未知类型：, objID:set, data:mapstr.MapStr
{"bk_biz_id":"14", "bk_capacity":interface {}(nil),
 "bk_childid":interface {}(nil), 
 "bk_parent_id":"14", 
 "bk_service_status":"1", 
 "bk_set_desc":"", 
 "bk_set_env":"3", 
 "bk_set_name":"空闲机池", 
 "bk_supplier_account":"0", 
 "default":"1", 
 "description":"", 
 "set_template_id":"0", 
 "set_template_version":interface {}(nil)}, rid:cc0000c757qdfmr8igm3dbtic0
 



E1228 02:57:58.429949    2639 inst/inst.go:148] 
failed to create object instance ,error info is 未知类型：, rid: cc0000c757qdfmr8igm3dbtic0


E1228 02:57:58.447772    2639 operation/inst.go:354] [operation-inst] 
failed to save the object(set) inst data 
(mapstr.MapStr{"bk_biz_id":14, "bk_parent_id":14, "bk_set_name":"空闲机池", "default":1, "set_template_id":0}), 
err: 未知类型：, rid: cc0000c757qdfmr8igm3dbtic0


E1228 02:57:58.477925    2639 operation/inst_set.go:124] 
create set instance failed, object: 
{"id":3,"bk_classification_id":"bk_biz_topo","bk_obj_icon":"icon-cc-set","bk_obj_id":"set",
"bk_obj_name":"集群","bk_ishidden":false,"ispre":true,"bk_ispaused":false,"position":"","bk_supplier_account":"0",
"description":"","creator":"cc_system","modifier":"","create_time":"0001-01-01 00:00:00","last_time":"0001-01-01 00:00:00"}, 
data: {"bk_biz_id":14,"bk_parent_id":14,"bk_set_name":"空闲机池","default":1,"set_template_id":0}, err: 未知类型：, rid: "cc0000c757qdfmr8igm3dbtic0"



E1228 02:57:58.477986    2639 operation/inst_business.go:184] 
create business failed to create business, error info is 未知类型：, rid: cc0000c757qdfmr8igm3dbtic0


E1228 02:57:58.478020    2639 service/inst_business.go:66] 
create business failed, err: 未知类型：, rid: cc0000c757qdfmr8igm3dbtic0


E1228 02:57:58.478054    2639 service/inst_business.go:62] 
run transaction, but run() function failed, err: 未知类型：, rid: cc0000c757qdfmr8igm3dbtic0


E1228 02:57:58.480847    2639 service/inst_business.go:98] rid: cc0000c757qdfmr8igm3dbtic0, err: 未知类型：
```

**Comment by wuzhouqin** [comment]
拉的最新的镜像(lastest)，同样的问题

**Comment by zhucaipeng** [comment]
拉的最新的镜像(lastest)，同样无法新建业务， 报“未知类型”。

**Comment by hackerain** [comment]
看样子是 bk_childid  这些字段已经被删了，但是这个all in one的没有跑数据库升级的脚本，手动跑下就可以了，登录到容器里，执行下 init_db.sh:

`
root@infra:~# docker exec -it flamboyant_villani bash
[root@87fe614d51f2 data]#
[root@87fe614d51f2 data]#
[root@87fe614d51f2 data]# ls
cmdb  down.sh  run.sh  sidecar
[root@87fe614d51f2 data]# cd cmdb/cmdb_coreservice/
[root@87fe614d51f2 cmdb_coreservice]# sh init_db.sh
localIp:172.17.0.2
{
 "result": true,
 "bk_error_code": 0,
 "bk_error_msg": "",
 "permission": null,
 "data": "migrate success",
 "pre_version": "y3.9.202008121631",
 "current_version": "y3.9.202107011154",
 "finished_migrations": [
  "y3.9.202008172134",
  "y3.9.202010131456",
  "y3.9.202010151455",
  "y3.9.202010151650",
  "y3.9.202010211805",
  "y3.9.202010281615",
  "y3.9.202011021415",
  "y3.9.202011021501",
  "y3.9.202011171550",
  "y3.9.202011172152",
  "y3.9.202011192014",
  "y3.9.202011201146",
  "y3.9.202011241510",
  "y3.9.202011251014",
  "y3.9.202011301723",
  "y3.9.202012011450",
  "y3.9.202101061721",
  "y3.9.202102011055",
  "y3.9.202102261105",
  "y3.9.202103031533",
  "y3.9.202103231621",
  "y3.9.202104011012",
  "y3.9.202104211151",
  "y3.9.202105261459",
  "y3.9.202106031151",
  "y3.9.202106291420",
  "y3.9.202106301910",
  "y3.9.202107011154"
 ]
}
`
