### ISSUE TITLE
./init_db.sh 失败

### ISSUE THREAD

**Issue by bksadas** [Tencent/bk-cmdb#5884]
./init_db.sh 
localIp:172.16.244.232
{"result":false,"bk_error_code":1105000,"bk_error_msg":"迁移数据失败, server selection error: server selection timeout\ncurrent topology: Type: ReplicaSetNoPrimary\nServers:\n","permission":null,"data":null}

**Comment by wcy00000000000000** [comment]
mongo副本集配置有问题，检查下是否配置成功
