### ISSUE TITLE
请求 API [owner_id]授权信息查询失败

### ISSUE THREAD

**Issue by FrancisDrakeK** [Tencent/bk-cmdb#5916]
问题描述
===========
请求 API [owner_id]授权信息查询失败

重现方法
================

![image](https://user-images.githubusercontent.com/42175430/149722159-cd427b9e-fb7f-4ac7-9029-09cab206ec0c.png)
![image](https://user-images.githubusercontent.com/42175430/149722247-00dff199-e501-46d8-ac6f-d3f966f942a5.png)

关键信息
=========
使用的容器版本，另外容器版本能能否创建多个用户

请提供以下信息:

 - [ ] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
带上这个头即可：
![image](https://user-images.githubusercontent.com/26254420/149722624-5a4fcc8a-a147-4d0d-98b3-e692bf0b65f8.png)

**Comment by FrancisDrakeK** [comment]
我的头里已经添加了这个 头

**Comment by FrancisDrakeK** [comment]
> 带上这个头即可： ![image](https://user-images.githubusercontent.com/26254420/149722624-5a4fcc8a-a147-4d0d-98b3-e692bf0b65f8.png)

我的头里已经添加了这个 头

**Comment by breezelxp** [comment]
拿request id查下apiserver的日志

**Comment by FrancisDrakeK** [comment]
> 拿request id查下apiserver的日志

![image](https://user-images.githubusercontent.com/42175430/149723193-3e23f1af-ea30-4be3-9c1b-0ebf4bb70143.png)

**Comment by wcy00000000000000** [comment]
![image](https://user-images.githubusercontent.com/40779709/149724160-674f8c83-2ee1-4af7-b872-9b2390f075a2.png)
复制一下这个试试：HTTP_BLUEKING_SUPPLIER_ID

**Comment by chalice-1831** [comment]
> > 带上这个头即可： ![image](https://user-images.githubusercontent.com/26254420/149722624-5a4fcc8a-a147-4d0d-98b3-e692bf0b65f8.png)
> 
> 我的头里已经添加了这个 头

你截图里的blue打错了

**Comment by breezelxp** [comment]
返回的请求头里是有的
![image](https://user-images.githubusercontent.com/26254420/149724513-d218093f-4c66-4d72-b559-320b7cc8ced6.png)

**Comment by FrancisDrakeK** [comment]
> > > 带上这个头即可： ![image](https://user-images.githubusercontent.com/26254420/149722624-5a4fcc8a-a147-4d0d-98b3-e692bf0b65f8.png)
> > 
> > 
> > 我的头里已经添加了这个 头
> 
> 你截图里的blue打错了

确实打错了，改回来以后 404了
![image](https://user-images.githubusercontent.com/42175430/149724859-20267f14-527f-44be-8f00-4bf824c5c2f3.png)

**Comment by FrancisDrakeK** [comment]
> 返回的请求头里是有的 ![image](https://user-images.githubusercontent.com/26254420/149724513-d218093f-4c66-4d72-b559-320b7cc8ced6.png)
我根据这个去grep log，没有结果

**Comment by FrancisDrakeK** [comment]
> 返回的请求头里是有的 ![image](https://user-images.githubusercontent.com/26254420/149724513-d218093f-4c66-4d72-b559-320b7cc8ced6.png)

![image](https://user-images.githubusercontent.com/42175430/149726413-4b9ea4f1-1069-4c7c-af68-b1fe01e67580.png)
主机查询的API是变动了么？ /api/v3/hosts/search 直接报 404

**Comment by FrancisDrakeK** [comment]
已经可以，感谢各位的支持
