### ISSUE TITLE
用户管理员工在职状态与配置管理不联动

### ISSUE THREAD

**Issue by tingyu-bian** [Tencent/bk-cmdb#5946]
问题描述
===========
1.在用户管理将A用户设为离职状态，配置平台中的三级模块还可以添加该名员工为主要维护人或备份维护人
2.在用户管理将A用户设为禁用状态，配置平台中的三级模块还可以添加该名员工为主要维护人或备份维护人

重现方法
================

关键信息
=========

请提供以下信息:

 - [ ] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
CMDB中的用户数据是以用户管理中的数据为准
