### ISSUE TITLE
cmdb启动 cmdb_weserver 连接zk节点失败

### ISSUE THREAD

**Issue by jiaohongtao** [Tencent/bk-cmdb#5953]
问题描述
===========
cmdb第一次启动成功，访问后 cmdb_weserver 服务，停掉，查看日志看到连接zk节点失败，详情请查看截图

关键信息
=========

 - [ ] bk-cmdb   版本: 
Version  : master
Tag      : master
BuildTime: 2022-02-07T17:52:03+0800
GitHash  : 011400903fb92cf1c444ea32a6196ae4c457ee37
RunMode  : product

 - [ ] Redis     版本: 4.0.14
 - [ ] MongoDB   版本:  v4.0.26
 - [ ] ZooKeeper 版本:  3.7.0
 - [ ] 操作系统      :  Centos 7 (x64）
 - [ ] bk-cmdb 异常日志
![截图](https://user-images.githubusercontent.com/44717089/153788186-c01ffde3-d811-4c89-900d-c2fa08ae0e14.png)

**Comment by breezelxp** [comment]
和这个报错没有关系，这个是动态调整日志级别的

**Comment by jiaohongtao** [comment]
> 和这个报错没有关系，这个是动态调整日志级别的

嗯嗯，要怎么看一下排错呢
