### ISSUE TITLE
3.10.10版本 中国区aws同步报错

### ISSUE THREAD

**Issue by sswolf** [Tencent/bk-cmdb#5997]
问题描述
===========
3.10.10版本 中国区aws同步报错

重现方法
================
云账户-->新建--> 选择亚马逊云   输入ID和key  提示不匹配   

关键信息
![Z_WJTP__4(4@AVJP6D@JH8F](https://user-images.githubusercontent.com/15525497/156089878-b047d7df-3fc9-4cba-ab34-d14acc1d3670.png)

请提供以下信息:

3.10.10

**Comment by breezelxp** [comment]
报错不是很清楚了？

**Comment by sswolf** [comment]
问题是ID和key是匹配的呀

**Comment by breezelxp** [comment]
看下cloudserver都报了什么错
