### ISSUE TITLE
低级错误

### ISSUE THREAD

**Issue by wenskys** [Tencent/bk-cmdb#6]
php编译参数扩展 ./configure --prefix= -enable-fpm --with-mysql with-mysqli -with-curl -enable-pcnt -enable-mbregex --with-mhash -enable-zip --enable-mbstring --with-openssl

with-mysqlli应该是--with-mysqlli,-enable-pcnt应该是--enable-pcntl，
虽然-enable-mbregex没错，但规范应该是--enable-mbregex才对，映像中腾讯都是很注重细节的
这个低级错误太明显了，开源的童鞋太粗心了

**Comment by lowenitt** [comment]
感谢提醒，这个我们修复下
