### ISSUE TITLE
全选用起来很奇怪

### ISSUE THREAD

**Issue by sitanya** [Tencent/bk-cmdb#60]
抱歉我不知道是我安装问题还是什么，我全选时过滤不会生效
比如我有300台机器，我搜索一个主机名，搜索出20台机器。
这时候我按“内网IP”标签左边的勾，发现勾选到的是300台机器而不是20台机器

**Comment by lowenitt** [comment]
目前开源的此版本的配置平台将不作升级维护，敬请关注04.02上线的3.0版本。
