### ISSUE TITLE
编译时提示找不到go.mod

### ISSUE THREAD

**Issue by wilikeit** [Tencent/bk-cmdb#6017]
问题描述
===========
cd $GOPATH/src
git clone https://github.com/Tencent/bk-cmdb  configcenter
cd $GOPATH/src/configcenter/src
make NPM=cnpm时报错
# go build -i -ldflags "-X configcenter/src/common/version.CCVersion=master -X configcenter/src/common/version.CCBuildTime=2022-03-08T16:07:15+0800 -X configcenter/src/common/version.CCGitHash=4347923164dc5bdd2ecd166e58d00c5a394b5c10 -X configcenter/src/common/version.CCTag=master -X configcenter/src/common/version.CCDistro=community" -o /jb/go/src/configcenter/src/bin/build/master/cmdb_apiserver/cmdb_apiserver
# go: cannot find main module, but found vendor/vendor.json in /jb/go/src/configcenter
	# to create a module there, run:
	# cd ../.. && go mod init

重现方法
================
cd  $GOPATH/src/configcenter/src
make NPM=cnpm

关键信息
=========
Branch：v3.10.x
系统：centos7.6.1810
go版本：go version go1.16.13 linux/amd64
node版本：v14.16.0

**Comment by breezelxp** [comment]
这个项目没有使用gomode，所以你禁用下你的gomode

**Comment by sober-wang** [comment]
> 这个项目没有使用gomode，所以你禁用下你的gomode

为什么不使用 go.mode 呢？
