### ISSUE TITLE
3.10.10事件订阅跑哪里去了？

### ISSUE THREAD

**Issue by whaike** [Tencent/bk-cmdb#6018]
问题描述
===========
开源版3.10.10，哪里可以看到新版事件订阅的界面以及接口API ？
![image](https://user-images.githubusercontent.com/17683739/157602936-94e9db4c-3d2d-48d4-bb75-04a928d2e711.png)

重现方法
================
编译3.10.10并运行

关键信息
按照编译文档逐步操作的，下载的是github的3.10.10版本

**Comment by breezelxp** [comment]
3.10版本下线了事件订阅功能，改由更加灵活的resource watch功能替代，可以关注issue看下：https://github.com/Tencent/bk-cmdb/issues/5308

**Comment by whaike** [comment]
> 3.10版本下线了事件订阅功能，改由更加灵活的resource watch功能替代，可以关注issue看下：#5308

嗯，之前也看到过这里，但是一直没理解GSE是什么，gse_syncdata是在release分支外单独编译的一个服务吗? 从release里看到的gse文件夹里可是C的

**Comment by whaike** [comment]
> > 3.10版本下线了事件订阅功能，改由更加灵活的resource watch功能替代，可以关注issue看下：#5308
> 
> 嗯，之前也看到过这里，但是一直没理解GSE是什么，gse_syncdata是在release分支外单独编译的一个服务吗? 从release里看到的gse文件夹里可是C的

其实主要还是没看明白：
1、这个服务怎么起？
2、我该怎么用？

**Comment by breezelxp** [comment]
gse_syncdata这个不用关注，这是蓝鲸的另外一个平台的服务

**Comment by whaike** [comment]
> resource watch

文档看得有点米糊，可以告诉一下我，下载release的3.10.10版本中包含了resource_watch这个功能吗？如果包含了我该在哪里找到它并使用呢？ 如果没有包含，我要从哪里获取这个服务并启动进而使用呢？

**Comment by whaike** [comment]
> gse_syncdata这个不用关注，这是蓝鲸的另外一个平台的服务

文档看得有点米糊，可以告诉一下我，下载release的3.10.10版本中包含了resource_watch这个功能吗？如果包含了我该在哪里找到它并使用呢？ 如果没有包含，我要从哪里获取这个服务并启动进而使用呢？

**Comment by whaike** [comment]
https://bk.tencent.com/docs/document/6.0/167/13341

**Comment by zbhtz** [comment]
在权限中心配置了“事件订阅”功能菜单，登陆配置平台还是没有，怎么才能使用事件订阅？
