### ISSUE TITLE
【v3.10.10】MongoDB连接数很高且配置文件修改连接池数量不生效

### ISSUE THREAD

**Issue by whaike** [Tencent/bk-cmdb#6031]
问题描述
===========
MongoDB连接池数量无法修改。

DBA反应MongoDB集群的连接数超高，我关闭停止cmdb后，将init.py文件内关于MongoDB的配置调整为
```
 maxOpenConns: 10
 maxIdleConns: 5
```
重启初始化，`cmdb_adminserver/configures/mongodb.yaml` 配置正常如下
```
 maxOpenConns: 10
 maxIdleConns: 5
```
调用启动命令`./start.sh`
重新统计连接数，发现依旧是两千多。

代码中mongo.go文件内可以看到连接池确实使用了这个配置作为连接池数量
```
conOpt := options.ClientOptions{
		MaxPoolSize:     &config.MaxOpenConns,
		MinPoolSize:     &config.MaxIdleConns,
		ConnectTimeout:  &timeout,
		SocketTimeout:   &socketTimeout,
		ReplicaSet:      &config.RsName,
		RetryWrites:     &disableWriteRetry,
		MaxConnIdleTime: &maxConnIdleTime,
		AppName:         &appName,
	}
```

重现方法
================
启动cmdb
使用命令行查询当前tcp连接数：
` netstat -anp | grep ESTABLISHED | grep cmdb | wc -l`
结果：2182

登录MongoDB查询连接数：
```
rs0:PRIMARY> db.serverStatus().connections;
{
        "current" : 740,
        "available" : 799260,
        "totalCreated" : 335950,
        "active" : 20
}
```

关键信息
=========

请提供以下信息:

 - [ ] bk-cmdb   版本: 
 Version     : v3.10.10
Tag         : ocr-v3.10.10
BuildTime   : 2022-02-24T09:40:17+0000
GitHash     : v3.10.10
RunMode     : product
Distribution: community
ServiceName : apiserver

 - [ ] Redis     版本: Redis server v=3.2.11 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=6ba7e11a5f8d5320
 - [ ] MongoDB   版本: MongoDB shell version v4.2.18
 - [ ] ZooKeeper 版本: zookeeper-3.4.13
 - [ ] 操作系统      : Ubuntu 18.04.6 LTS

**Comment by ZQHcode** [comment]
每个mongo的client在代码里设置的最小maxIdleConns（对应的MinPoolSize）是50，各个服务启动后的mongo连接数量上述情况是正常的

**Comment by whaike** [comment]
> 每个mongo的client在代码里设置的最小maxIdleConns（对应的MinPoolSize）是50，各个服务启动后的mongo连接数量上述情况是正常的

```
if !parser.isSet(prefix+".maxIdleConns") || parser.getUint64(prefix+".maxIdleConns") < mongo.MinimumMaxIdleOpenConns {
	c.MaxIdleConns = mongo.MinimumMaxIdleOpenConns
} else {
	c.MaxIdleConns = parser.getUint64(prefix + ".maxIdleConns")
}
```
我看到了这样的代码，但是不理解，为什么要设置最小值呢？ 如果这个值调小会有什么问题吗？

**Comment by ZQHcode** [comment]
防止设置过小，当需要操作db时需要频繁建立连接，所以这里加了限制

**Comment by whaike** [comment]
> 防止设置过小，当需要操作db时需要频繁建立连接，所以这里加了限制

由于我这边dba不允许连接这么多个，我如果把这个调为如下值，会产生什么样的问题吗？( 公司内cmdb使用压力暂时没有特别高)
maxOpenConns: 10
maxIdleConns: 5
