### ISSUE TITLE
源码部署cmdb之后，浏览器访问报错

### ISSUE THREAD

**Issue by 251302320** [Tencent/bk-cmdb#6056]
我源码部署了之后，前台能访问，但是会报错，然后60002对应的服务就关了
![1](https://user-images.githubusercontent.com/74352002/161953853-a42e44a3-d156-488f-a1d0-56ed3ab8d77b.png)

**Comment by ToughLama** [comment]
我也是，这个项目好奇怪，自己编译的问题非常多

**Comment by ZQHcode** [comment]
看着是toposerver这个服务的问题，可以看下对应服务的错误日志进行问题排查
