### ISSUE TITLE
前端ui打包报错

### ISSUE THREAD

**Issue by yuuagoo** [Tencent/bk-cmdb#6066]
问题描述
===========
![image](https://user-images.githubusercontent.com/57406595/162410969-9c1aa829-d67e-4f60-a387-004ff866c578.png)

重现方法
================
make ui

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by liucy1983** [comment]
OOM了，你编译的机器内存是多大？

**Comment by yuuagoo** [comment]
与编译机器内存无关，node版本问题，关联回答：https://github.com/Tencent/bk-cmdb/issues/5341
