### ISSUE TITLE
想问一下 目前云资源发现的机制是什么  是定时更新   还是有变更了才会更新

### ISSUE THREAD

**Issue by donallin823** [Tencent/bk-cmdb#6081]
问题描述
===========
想问一下 目前云资源发现的机制是什么  是定时更新   还是有变更了才会更新
因为我看到云发现任务，最近的一次更新已经是昨天的了
![image](https://user-images.githubusercontent.com/62011907/163517189-f44d7419-2246-40ae-ab43-d9230f40b717.png)

关键信息
=========
![image](https://user-images.githubusercontent.com/62011907/163517252-73c40b19-3c6e-416a-8b5b-c9858ebe962f.png)

**Comment by breezelxp** [comment]
定时更新
