### ISSUE TITLE
关于模型关系的应用

### ISSUE THREAD

**Issue by yuezheng** [Tencent/bk-cmdb#6133]
问题描述
===========
CMDB系统里有模型关系的管理功能，如图：
![image](https://user-images.githubusercontent.com/1791214/167797304-a2df1d63-1711-4aff-b987-1d18dc67ef06.png)

在主机分配到具体的(业务-集群-模块)后，为什么在主机-关联页面里面看，这个节点的关联是空的。

已分配到业务的主机：
![image](https://user-images.githubusercontent.com/1791214/167798196-3b28057e-2ce4-409a-8a52-41c6d43e1603.png)

主机的关联信息是空的：
![image](https://user-images.githubusercontent.com/1791214/167798358-68f42218-8838-4a48-9710-028c5e204582.png)

为什么业务-主机的关系维护没有使用到所定义的模型关系？

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by wcy00000000000000** [comment]
`业务-集群-模块-主机` 之间的关联关系是 `拓扑组成` ， 这个关联关系是用于标识主线拓扑的，主线拓扑上的节点的关联关系是用于在业务拓扑中展示拓扑图的，不会在实例的`关联`这个页面里显示
![image](https://user-images.githubusercontent.com/40779709/201101123-de0153c0-9af4-497f-badb-01de5d7b4409.png)
