### ISSUE TITLE
【前端ui】前端ui启动后proxyTable反向代理未生效,路由未正常反向代理到webserver服务

### ISSUE THREAD

**Issue by YokeCheng** [Tencent/bk-cmdb#6139]
问题描述
===========

设置/builder/config/index.js中dev配置后启动ui，路由未正常反向代理到webserver服务

重现方法
================

1. 修改src/ui/builder/config/index.js，内容如下
完整文件内容：[index.txt](https://github.com/Tencent/bk-cmdb/files/8683622/index.txt)
```const dev = {
  // custom config
  config: Object.assign({}, config, {
    API_URL: JSON.stringify('http://192.168.20.94:9090/proxy/'),
    API_VERSION: JSON.stringify('v3'),
    ......
  }),

  // Paths
  assetsSubDirectory: '',
  assetsPublicPath: '/static/',
  proxyTable: {
    '/proxy': {
      logLevel: 'info',
      changeOrigin: true,
      target: 'http://192.168.20.94:8090/',
      pathRewrite: {
        '^/proxy': ''
      }
    }
  },
  ......
}
```
3. npm install
4. npm run dev 
5. 显示跨域错误，其实是未正常反向代理到webserver后端
![4f9d9c07069f0afac0183beefa69285](https://user-images.githubusercontent.com/24696946/168198620-9d77845c-08ae-4319-b799-6f5c13437875.png)

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本:  release-v3.10.16
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by YokeCheng** [comment]
主要是由于API_URL设置有问题。当时看ReadME显示需要填写apiserver的端口地址，其实不需要，只需要写UI本身的地址和端口即可（默认不用改）。问题原因是本身就产生了跨域，所以就没有执行proxy代理

**Comment by yourSwiftie2023** [comment]
所以怎么修改？
