### ISSUE TITLE
部署启动后，请求报错。查看日志显示zk: node does not exist

### ISSUE THREAD

**Issue by YokeCheng** [Tencent/bk-cmdb#6157]
问题描述
===========

部署启动后，请求报错。查看日志显示zk: node does not exist
```
Log file created at: 2022/05/19 17:32:09
Running on machine: zfxx-PC
Binary: Built with gc go1.16.13 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg

E0519 17:32:09.188687  490720 backbone/notice.go:57] log watch failed, will watch after 10s, path: /cc/services/notice/log/192.168.20.94:60004/v, err: zk: node does not exist
```

当前使用docker-compose部署到zookeeper，理解应该是admin-server会初始化自动注册到zookeeper中，目前只知道这些内容，望指导

关键信息
=========

请提供以下信息:

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本:  v3.10.11
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [x] ZooKeeper 版本: v3.6.3
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by ZQHcode** [comment]
还有其他的错误日志吗，看下ERROR文件，目前这个日志看着应该是不影响功能使用的

**Comment by YokeCheng** [comment]
重新down.sh,然后run.sh。大概几次之后，运行正常了
