### ISSUE TITLE
建议放开主机模型中当前状态bk_state字段修改

### ISSUE THREAD

**Issue by damondengxin** [Tencent/bk-cmdb#6221]
问题描述
===========
因业务中主机有时只是单台主机下线，这种情况修改主机状态为已下线。由于bk_state是内置状态无法修改，希望允许修改这个字段，但是不允许删除已内置的枚举类型值。

**Comment by wjyfelen** [comment]
如果是单台主机已经下线的话，可以将主机放到业务空闲机池下的空闲机模块，然后再把主机从空闲机模块归还到主机池中
