### ISSUE TITLE
调用API新增或删除分组失败

### ISSUE THREAD

**Issue by heu235001** [Tencent/bk-cmdb#6298]
问题描述
===========

删除分组基本信息
/api/v3/objectatt/group/groupid/6
响应
{"result":false,"bk_error_code":1199037,"bk_error_msg":"rewrite request failed, unknown requested with backend process","permission":null,"data":null}
版本
3.10.x

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [x] bk-cmdb 异常日志

**Comment by heu235001** [comment]
E0809 17:13:58.452792   21093 service/filter.go:71] rewrite request url[/api/v3/objectatt/group/new] failed, err: unknown requested with backend process, rid: cc0000cbp2aln170hl4pc4ma7g

**Comment by ZQHcode** [comment]
删除模型分组的url应该的是/api/v3/delete/objectclassification/6，模型属性分组是/api/v3/delete/objectattgroup/6

**Comment by heu235001** [comment]
> 删除模型分组的url应该的是/api/v3/delete/objectclassification/6，模型属性分组是/api/v3/delete/objectattgroup/6

谢谢提供！
请问怎么找到这些接口的？API文档里的不是最新的吗？

**Comment by ZQHcode** [comment]
这个没有在维护了，通过esb调用cmdb的文档可以在这里看到 https://bk.tencent.com/docs/document/6.1/190/14275

**Comment by heu235001** [comment]
> 这个没有在维护了，通过esb调用cmdb的文档可以在这里看到 https://bk.tencent.com/docs/document/6.1/190/14275

非常感谢！

**Comment by heu235001** [comment]
建议API说明文档同步更新一下，或者说明一下哪些可用，否则刚接触的人会有点懵。
