### ISSUE TITLE
有docker安装方式吗？

### ISSUE THREAD

**Issue by ppabc** [Tencent/bk-cmdb#63]
有docker安装方式吗？如何快速体验bk-cmdb？有demo吗？

**Comment by uriwang** [comment]
@ppabc
1. 当前没有制作好的镜像。
2. 此处有份常规部署文档可以参考。https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/installation.md

3. 如果需要自己制作镜像，请参考https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/source_compile.md 文档内的内容。

注：在制作镜像前请先执行init.py 进行初始化配置，此脚本会自动生成配置文件。

**Comment by whb1998a** [comment]
@holmeswang 
按照第3点的教程得到了好多个镜像，应该如何启动呢，有容器的启动脚本吗？
