### ISSUE TITLE
同步AD域控用户无法登录

### ISSUE THREAD

**Issue by xiaoxuozi** [Tencent/bk-cmdb#6302]
同步AD域控显示成功，但是登录却显示用户密码不匹配

**Comment by ZQHcode** [comment]
cmdb账号密码登陆可以在cmdb_adminserver/configures/common.yaml文件中配置webServer.login.version为opensource，设置webServer.session.userInfo指定账号密码（通过:分割）；或者webServer.login.version设置为blueking，使用蓝鲸统一登陆

**Comment by xiaoxuozi** [comment]
请问我这边想通过域控的账号密码登录改怎么办，域控用的是微软的

**Comment by wcy00000000000000** [comment]
目前cmdb不支持这种登陆方式，可以参考[这个登陆插件](https://github.com/Tencent/bk-cmdb/tree/v3.10.x/src/web_server/middleware/user/plugins/method/blueking)实现自定义插件支持这种登陆方式
