### ISSUE TITLE
/api/{version}/hosts/search接口返回的biz，module和set为空

### ISSUE THREAD

**Issue by shenxg13** [Tencent/bk-cmdb#6312]
问题描述
===========
/api/{version}/hosts/search接口返回的biz，module和set为空

重现方法
================
{
    "condition":[
        {
            "bk_obj_id":"host",
            "condition":[
                {
                    "field":"xxx",
                    "operator":"$eq",
                    "value":"01"
                }
            ]
        }
    ]
}

{
    "result": true,
    "bk_error_code": 0,
    "bk_error_msg": "success",
    "permission": null,
    "data": {
        "count": 2,
        "info": [
            {
                "biz": [],
                "host": {
                    "bk_cloud_id": [
                        {
                            "id": "0",
                            "bk_obj_id": "plat",
                            "bk_obj_icon": "",
                            "bk_inst_id": 0,
                            "bk_obj_name": "",
                            "bk_inst_name": "..."
                        }
                    ],
                    "bk_host_id": 1,
                    "bk_host_innerip": "10.1.1.1",
                    "bk_host_innerip_v6": "",
                    "bk_supplier_account": "0",
                    "create_time": "2022-08-18T10:18:11.202+08:00",
                    "last_time": "2022-08-18T20:03:32.405+08:00",
                    ...
                },
                "module": [],
                "set": []
            },
            {
                "biz": [],
                "host": {
                    "bk_cloud_id": [
                        {
                            "id": "0",
                            "bk_obj_id": "plat",
                            "bk_obj_icon": "",
                            "bk_inst_id": 0,
                            "bk_obj_name": "",
                            "bk_inst_name": "..."
                        }
                    ],
                    "bk_host_id": 3,
                    "bk_host_innerip": "10.1.1.3",
                    "bk_host_innerip_v6": "",
                    "bk_supplier_account": "0",
                    "create_time": "2022-08-18T10:54:52.692+08:00",
                    "last_time": "2022-08-18T20:11:43.141+08:00",
                    ...
                },
                "module": [],
                "set": []
            }
        ]
    }
}

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
3.10.18

**Comment by ZQHcode** [comment]
请求参数中condition数组中没有加bk_obj_id 为biz、module、set的参数

**Comment by shenxg13** [comment]
请问是这个意思吗，这样请求biz还是为空。
{
    "condition":[
        {
            "bk_obj_id":"biz",
            "condition":[
                {
                    "field":"bk_biz_name",
                    "operator":"$eq",
                    "value":"..."
                }
            ]
        }
    ]
}

{
    "result": true,
    "bk_error_code": 0,
    "bk_error_msg": "success",
    "permission": null,
    "data": {
        "count": 1,
        "info": [
            {
                "biz": [],
                "host": {
                    "bk_cloud_id": [
                        {
                            "id": "0",
                            "bk_obj_id": "plat",
                            "bk_obj_icon": "",
                            "bk_inst_id": 0,
                            "bk_obj_name": "",
                            "bk_inst_name": "..."
                        }
                    ],
                    "bk_host_id": 3,
                    "bk_host_innerip": "10.1.1.3",
                    "bk_host_innerip_v6": "",
                    "bk_supplier_account": "0",
                    "create_time": "2022-08-18T10:54:52.692+08:00",
                    "last_time": "2022-08-18T20:11:43.141+08:00",
                    ...
                },
                "module": [],
                "set": []
            }
        ]
    }
}

**Comment by shenxg13** [comment]
```
{
    "condition":[
        {
            "bk_obj_id":"biz",
            "fields":[
            ]
        },
        {
            "bk_obj_id":"host",
            "fields":[
            ],
            "condition":[
                {
                    "field":"...",
                    "operator":"$eq",
                    "value":"01"
                }
            ]
        }
    ]
}
```
加上fields之后可以查出biz信息了，谢谢。
