### ISSUE TITLE
cmdb周期性异常

### ISSUE THREAD

**Issue by WCJ-Chance** [Tencent/bk-cmdb#6313]
问题描述
===========
蓝鲸604， 周期性出现cmdb、gse服务异常，重启之后能维持正常一段时间。cmdb、gse都是双节点，zk是三节点。

![image](https://user-images.githubusercontent.com/78134833/185841526-5e6ce1cd-31e5-4d6d-8a0f-56324c9ac51a.png)

重现方法
================

周期性出现

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
Version     : v3.9.27
Tag         : release-v3.9.27
BuildTime   : 2021-06-17T15:20:50+0800
GitHash     : 7864c62f1f0423e9ddc61f3e66bdfad848f22459
RunMode     : product
Distribution: community
ServiceName : apiserver

 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: v4.2.3
 - [ ] ZooKeeper 版本: 3.4.14
 - [ ] 操作系统      : Centos 7 (x64）
 - [ ] bk-cmdb 异常日志
 · cmdb_apiserver.ERROR:
```
Log file created at: 2022/08/22 12:22:20
Running on machine: bk_104
Binary: Built with gc go1.12.4 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0822 12:22:20.542765  128981 backbone/notice.go:57] log watch failed, will watch after 10s, path: /cc/services/notice/log/172.52.0.104:9001/v, err: zk: node does notexist
```
· cmdb_webserver：
```
Log file created at: 2022/08/22 12:22:20
Running on machine: bk_104
Binary: Built with gc go1.12.4 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0822 12:22:20.563476  128880 backbone/notice.go:57] log watch failed, will watch after 10s, path: /cc/services/notice/log/172.52.0.104:9013/v, err: zk: node does notexist
```

**Comment by ZQHcode** [comment]
cmdb连接zk异常的问题，之前已经修复了，可以升级到最新3.9的包看看

**Comment by WCJ-Chance** [comment]
> 

v3.9.37吗？

**Comment by WCJ-Chance** [comment]
> cmdb连接zk异常的问题，之前已经修复了，可以升级到最新3.9的包看看

v3.9.37吗？
