### ISSUE TITLE
请问开源版是不是没有“事件推送”的功能？

### ISSUE THREAD

**Issue by heu235001** [Tencent/bk-cmdb#6316]
问题描述
===========

开源版是不是没有“事件推送”的功能？
社区版的好像有，但是开源版不是比社区版的代码更新的吗？

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by ZQHcode** [comment]
指的是3.9版本在页面上能看到的事件推送么，这个在3.10版本已经下线了

**Comment by wcy00000000000000** [comment]
3.10版本可以用resource watch替代，使用方式可以参考issue #5308 的 **2.2 事件管理**

**Comment by heu235001** [comment]
> 3.10版本可以用resource watch替代，使用方式可以参考issue #5308 的 **2.2 事件管理**

非常感谢！请问“事件watch服务”具体怎么调用？

**Comment by wcy00000000000000** [comment]
可以参考这个文档：https://bk.tencent.com/docs/document/6.1/197/14399
