### ISSUE TITLE
无法自动导入主机

### ISSUE THREAD

**Issue by openstack-test** [Tencent/bk-cmdb#6323]
**问题**
无法自动导入主机，没有自动导入操作功能，如下图
![image](https://user-images.githubusercontent.com/12166405/186873392-a41dc802-a604-46ba-8c3f-898a2541778a.png)

看官网文档，提示有这个功能，但是实际为什么没有呢
![image](https://user-images.githubusercontent.com/12166405/186873590-0b51cb7f-6d00-4846-96b9-1c792aa272e6.png)

**版本**
基于master分支，源码编译安装的开源bk-cmdb

寻求帮助，谢谢

**Comment by ZQHcode** [comment]
这个需要安装节点管理，在节点管理那边安装 Agent，然后节点管理会调用接口把主机注册到 cmdb

**Comment by openstack-test** [comment]
@ZQHcode 节点管理 ，是哪个github 项目

**Comment by ZhuoZhuoCrayon** [comment]
> @ZQHcode 节点管理 ，是哪个github 项目

你好，节点管理：https://github.com/TencentBlueKing/bk-nodeman
