### ISSUE TITLE
布尔值是否可以显示成是和否

### ISSUE THREAD

**Issue by shenxg13** [Tencent/bk-cmdb#6360]
问题描述
===========
布尔值是否可以显示成是和否

重现方法
================
![WX20220916-150636@2x](https://user-images.githubusercontent.com/32766763/190577868-2d3db382-c7af-431f-a541-3b3ccb652ad2.png)

关键信息
=========

bk-cmdb版本：3.10.18

**Comment by wcy00000000000000** [comment]
布尔值类型的值就是true或者false的，如果在前端UI展示上有个性化需求需要展示为“是”或者“否”的话，可以修改前端代码自行实现
