### ISSUE TITLE
 init_db.sh 报错

### ISSUE THREAD

**Issue by wang00** [Tencent/bk-cmdb#6370]
问题描述
===========

bash init_db.sh 
localIp:192.168.20.237
{"result":false,"bk_error_code":1105000,"bk_error_msg":"迁移数据失败, server selection error: server selection timeout, current topology: { Type: ReplicaSetNoPrimary, Servers: [] }","permission":null,"data":null}

重现方法
================

bash init_db.sh 

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 3.2.12
 - [ ] MongoDB   版本: 4.4.16
 - [ ] ZooKeeper 版本: 3.5.7
 - [ ] 操作系统      : centos7.6
 - [ ] bk-cmdb 异常日志:fail to watch children for path(/cc/services/endpoints/cacheservice), err:zk: node does not exist
children node(/cc/services/endpoints/cacheservice) is not exist, will watch after 5s

**Comment by ZQHcode** [comment]
可以参考下这个issue解决问题：https://github.com/Tencent/bk-cmdb/issues/6155

**Comment by wang00** [comment]
应该如何操作，帮忙说一下

**Comment by wang00** [comment]
MongoDB shell version v4.4.16
connecting to: mongodb://127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("a59e7db7-5c9e-41a3-bc51-82e0d3235c06") }
MongoDB server version: 4.4.16
---
The server generated these startup warnings when booting: 
        2022-09-19T16:04:03.269+08:00: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem
        2022-09-19T16:04:04.767+08:00: Access control is not enabled for the database. Read and write access to data and configuration is unrestricted
        2022-09-19T16:04:04.767+08:00: /sys/kernel/mm/transparent_hugepage/enabled is 'always'. We suggest setting it to 'never'
        2022-09-19T16:04:04.767+08:00: /sys/kernel/mm/transparent_hugepage/defrag is 'always'. We suggest setting it to 'never'
---
---
        Enable MongoDB's free cloud-based monitoring service, which will then receive and display
        metrics about your deployment (disk utilization, CPU, operation statistics, etc).

        The monitoring data will be available on a MongoDB website with a unique URL accessible to you
        and anyone you share the URL with. MongoDB may use this information to make product
        improvements and to suggest MongoDB products and deployment options to you.

        To enable free monitoring, run the following command: db.enableFreeMonitoring()
        To permanently disable this reminder, run the following command: db.disableFreeMonitoring()
---
> show dbs
admin   0.000GB
config  0.000GB
local   0.000GB
> db.adminCommand( { replSetGetStatus: 1 } )
{
	"ok" : 0,
	"errmsg" : "not running with --replSet",
	"code" : 76,
	"codeName" : "NoReplicationEnabled"
}
> use cmdb
switched to db cmdb
>

**Comment by ZQHcode** [comment]
mongo需要使用Replica Set模式运行，具体的配置，可以参照这里：https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/installation.md

> 应该如何操作，帮忙说一下

**Comment by wang00** [comment]
配置集群中只有单台机器
 >rs.initiate({ _id : "rs0",members: [{ _id: 0, host: "ip:port" }]})

**Comment by wang00** [comment]
replica set模式 ？单节点不可以

**Comment by wang00** [comment]
明白了，试试replica set

**Comment by wang00** [comment]
web启动不了
fail to watch children for path(/cc/services/endpoints/datacollection), err:zk: node does not exist
![image](https://user-images.githubusercontent.com/10595226/191443131-69383e88-d8f1-4a0a-8cfb-bc6c04d294e5.png)

**Comment by wang00** [comment]
init_db 成功

**Comment by wang00** [comment]
zookeeper单节点不可以？

**Comment by ZQHcode** [comment]
> zookeeper单节点不可以？
可以的，可以看下没有启动服务的logs文件夹下的std.log日志文件，查看启动失败的原因

**Comment by wang00** [comment]
begin to discover by watch children of path(/cc/services/endpoints/auth)
begin to discover by watch children of path(/cc/services/endpoints/coreservice)
begin to discover by watch children of path(/cc/services/endpoints/eventserver)
fail to watch children for path(/cc/services/endpoints/apiserver), err:zk: node does not exist
children node(/cc/services/endpoints/apiserver) is not exist, will watch after 5s
children node(/cc/services/endpoints/apiserver) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/webserver), err:zk: node does not exist
children node(/cc/services/endpoints/webserver) is not exist, will watch after 5s
children node(/cc/services/endpoints/webserver) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/auth), err:zk: node does not exist
children node(/cc/services/endpoints/auth) is not exist, will watch after 5s
children node(/cc/services/endpoints/auth) is not exist, will watch after 5s
panic: open ../web/index.html: no such file or directory

goroutine 1 [running]:
html/template.Must(...)
	/data/cmdb/go/src/html/template/template.go:374
github.com/gin-gonic/gin.(*Engine).LoadHTMLFiles(0xc0007d51e0, {0xc000398de0, 0x2, 0x2})
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:244 +0x2ec
configcenter/src/web_server/service.(*Service).WebService(0xc000368440)
	/data/cmdb/configcenter/src/web_server/service/service.go:82 +0x369
configcenter/src/web_server/app.Run({0x13e46a0, 0xc000368400}, 0x46769b, 0xc00053ff48)
	/data/cmdb/configcenter/src/web_server/app/server.go:108 +0x7f9
main.main()
	/data/cmdb/configcenter/src/web_server/ui.go:44 +0x1cf

**Comment by wang00** [comment]
process count should be: 12 , now: 12
Not Running: cmdb_apiserver
Not Running: cmdb_authserver
Not Running: cmdb_webserver

**Comment by ZQHcode** [comment]
> 
看原因是找不到前端的目录
排查方式：
1. 看下是否有编译成功产生前端的目录，目录名称为web，存放的是前端页面等的资源
2. 若有前端目录，看下common.yaml配置文件中的webServer.site.htmlRoot这个配置对应的路径是否正确
