### ISSUE TITLE
cmdb是否支持连接高可用中间件？

### ISSUE THREAD

**Issue by yyf365** [Tencent/bk-cmdb#6381]
问题描述
===========
请问CMDB所需的MongoDB、Redis、zookeeper等组件是否支持集群连接？ 当前所有文档中和源码里看到的都是单节点连接
如是否支持：mongo集群或副本集连接、Redis集群多节点配置、zookeeper的多节点怎么配置？

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 3.10.18
 
 - [x] Redis     版本: 6.2.6
 - [x] MongoDB   版本: 4.2.22
 - [x] ZooKeeper 版本: 3.4.12
 - [ ] 操作系统      : linux
 - [ ] bk-cmdb 异常日志

**Comment by breezelxp** [comment]
cmdb里所有的服务都支持高可用连接哈

**Comment by yyf365** [comment]
> cmdb里所有的服务都支持高可用连接哈


目前看MongoDB的连接配置好像不支持高可用连接，能否帮忙看看何时支持高可用连接MongoDB？

**Comment by dujiaoyang** [comment]
咋解决的呀
