### ISSUE TITLE
如果安装的MongoDB的版本大于等于3.6，需要手动修改init.py自动生成的配置文件，详细步骤参看init.py相关小节。

### ISSUE THREAD

**Issue by lycclsltt** [Tencent/bk-cmdb#650]
如果安装的MongoDB的版本大于等于3.6，需要手动修改init.py自动生成的配置文件，详细步骤参看init.py相关小节。

请问具体是改什么内容呢？

**Comment by lowenitt** [comment]
![image](https://user-images.githubusercontent.com/14356794/41635040-2a24391e-7479-11e8-9805-c43b1f024557.png)

**Comment by lycclsltt** [comment]
问一下，在模型管理中，如何建立关联关系啊

**Comment by uriwang** [comment]
@lycclsltt 通过为模型建立关联类型的字段的方式建立模型之间的关联关系。
