### ISSUE TITLE
blog如何设置日志等级显示

### ISSUE THREAD

**Issue by gushedaoren** [Tencent/bk-cmdb#6510]
通过如下命令运行cmdb core service：
go run main.go --addrport=10.0.24.47:9004 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=10.0.24.47:2181
默认不打印info日志，请教下如何支持info或者debug日志打印

**Comment by wcy00000000000000** [comment]
日志级别为4及以上时会打印info日志，可以通过--v这个命令行参数设置日志级别，如上述命令可以这样调整设置日志级别为4：
```
go run main.go --addrport=10.0.24.47:9004 --logtostderr=false --log-dir=./logs --v=4 --regdiscv=10.0.24.47:2181
```
