### ISSUE TITLE
获取主机列表

### ISSUE THREAD

**Issue by labbitz** [Tencent/bk-cmdb#6560]
通过 PaaS 的 API 网关调用 /v2/cc/list_resource_pool_hosts/ 接口无法获取主机列表，请求成功，但数据始终是空的，不清楚是调用的接口不对或是其他的问题？

![image](https://user-images.githubusercontent.com/13694747/210033754-28b259b9-72ab-4069-aa55-a48cfee4210e.png)

**Comment by ZQHcode** [comment]
从返回来看应该是调用成功了。需要看下请求的参数条件是什么，以及这个条件在cmdb中是否存在对应的主机
