### ISSUE TITLE
fail to get configure, will get again

### ISSUE THREAD

**Issue by LibraP** [Tencent/bk-cmdb#67]
编译成功，执行过init.py和init_db.sh，运行失败：
cmdb_datacollection进程在但是60005端口起不来，WARNING日志一直报`there is other master process exists, recheck after 10s`
webserver的std.log报错`there is no api servers`
其他组件均报错`fail to get configure, will get again`
请教一下大概的排查方向？

**Comment by uriwang** [comment]
请确认按照以下顺序执行：
1.  编译；
2. 打包；
3. 将打好的包放到预部署的目标机器上解压；
4. 解压后进入cmdb安装包根目录执行./init.py 按照文档配置参数并执行；
5. 在安装包根目录执行./start.sh 启动所有进程的服务；
6. 执行./init_db.sh初始化数据（如果初始化成功过可以不用重复执行此步骤）；

如果以上步骤没有没有成功，请提供以下信息：
1. 部署的系统环境，如：操作系统类型，操作系统内核版本；

看到你上面的错误信息，应该是cmdb服务进程没有全部启动，同时也要判断是否所有进程所在的主机都可以连接到ZooKeeper（zk 在系统中用于服务发现，如果zk运行异常也可能导致系统运行异常）。

@LibraP

**Comment by LibraP** [comment]
换了台机器重试了，重新搭建了redis/mongodb/zk，未重新编译cmdb，错误能重现。依然是60005端口起不来，报错`ccapi.go:92] fail to get configure, will get again`。
机器信息如下：
Red Hat Enterprise Linux Server release 6.2 (Santiago)
Linux 2.6.32-220.el6.x86_64 #1 SMP Wed Nov 9 08:03:13 EST 2011 x86_64 x86_64 x86_64 GNU/Linux
其他可用信息：
1. redis, mongodb, zk和cmdb都跑在一台机器上，全部是新装的
2. mongodb用的2.4版本，并非推荐的2.8，用户和权限都是root
3. init.py返回`initial configurations success, configs could be found at cmdb_adminserver/configures`
4. init_db.sh返回`{"result":true,"bk_error_code":0,"bk_error_msg":"success","data":"migrate success"}`
5. 大概看了redis/mongodb/zk里的数据，并未发现比较异常的内容
6. 多个组件均报`fail to get configure, will get again`

**Comment by uriwang** [comment]
请检查一下和zk 之间的连接是否是通的。
@LibraP

**Comment by amojohn** [comment]
这边也遇到“ccapi.go:89] fail to get configure, will get again”的问题，需要设置Zookeeper的访问权限？当前是没有设置。
# cat host.conf
    [gse]
    addr=127.0.0.1:2181
    user=bkzk
    pwd=L%blKas
    [errors]
    res=conf/errors

**Comment by LibraP** [comment]
1. zookeeper从**单机单实例**换成**三实例的集群**之后就解决了。
2. 60005端口bk团队的人说暂时没监听，影响了排查的方向。重点关注webserver的报错比较好。
3. 我第一次make && make package时，未生成web目录，webserver里的日志会报错找不到index.html， make clean然后重新make后就有了。
最后感谢 @uriwang 的耐心指导

**Comment by uriwang** [comment]
@amojohn zk地址不要监听在127.0.0.1 地址，zk 里面的权限配置 cmdb 会自动配置的。

**Comment by amojohn** [comment]
@uriwang 问题已解决。谢谢！
ZK链接不上的时候，有些服务起不来。这个排除完。
后续是在“cmdb_webserver”日志中发现： there is no api servers。是初始化参数时，--blueking_cmdb_url http://*.*.*.*:8083，端口没有设置正确导致。修正后，系统可正常访问。

**Comment by 876161249** [comment]
> @amojohn zk地址不要监听在127.0.0.1 地址，zk 里面的权限配置 cmdb 会自动配置的。

不要监听是什么意思？init.py的zk地址具体填什么？

**Comment by 876161249** [comment]
> 1. zookeeper从**单机单实例**换成**三实例的集群**之后就解决了。不要监听127.0.0.1这个回环地址的2181端口。
> 2. 60005端口bk团队的人说暂时没监听，影响了排查的方向。重点关注webserver的报错比较好。
> 3. 我第一次make && make package时，未生成web目录，webserver里的日志会报错找不到index.html， make clean然后重新make后就有了。
>    最后感谢 @uriwang 的耐心指导

不要监听是什么意思？是在zoo.cfg里配置吗？

**Comment by 876161249** [comment]
> @uriwang 问题已解决。谢谢！
> ZK链接不上的时候，有些服务起不来。这个排除完。
> 后续是在“cmdb_webserver”日志中发现： there is no api servers。是初始化参数时，--blueking_cmdb_url http://_._._._:8083，端口没有设置正确导致。修正后，系统可正常访问。

你配置在哪个端口？
