### ISSUE TITLE
配置完之后，显示空白页面

### ISSUE THREAD

**Issue by wangyunwei421** [Tencent/bk-cmdb#675]
问题描述
===========
<安装过程中，mongodb是本地安装的，zookeeper和redis是安装在服务器上的，连接的都没有问题。就是启动之后访问页面显示标题，其他都是空白！>

重现方法
================
<列出如何重现的方法或操作步骤>

**重要提醒**: 请优先尝试最新发布的版本 (发布清单： https://github.com/Tencent/bk-cmdb/releases), 如果问题不能在最新发布的版本里重现，说明此问题已经被修复。

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): `<示例： v3.0.6-alpha 或者 git sha. 请不要使用 "最新版本" 或 "当前版本"等无法准确定位代码版本的语句描述>`
 - [ ] Redis     版本: `<示例： 3.2.11>`
 - [ ] MongoDB   版本: `<示例： 2.8.0>`
 - [ ] ZooKeeper 版本: `<示例： 3.4.11>`
 - [x] 操作系统      : `<示例： suse (x64)>`
 - [ ] bk-cmdb 异常日志

**Comment by rentiansheng** [comment]
1. 检查是否做数据初始化
2. 打开浏览器的network 看下api 返回结果

**Comment by wangyunwei421** [comment]
是不是只支持新版本的chrome

**Comment by rentiansheng** [comment]
@joe511230  来回答下

**Comment by wangyunwei421** [comment]
安装了新版的chrome，可以显示页面了，但是在初始化数据库的时候，没有成功。是redis的问题还是mongodb的问题呢？

**Comment by breezelxp** [comment]
@wangyunwei421 你好，由于你长时间没有再更新状态信息，现将该issue关闭，如果你还有关于此issue的任何疑问，可以重新开启该issue.
