### ISSUE TITLE
json反序列化接口出错

### ISSUE THREAD

**Issue by dragonku7** [Tencent/bk-cmdb#69]
webserver的接口：
[GIN] 2018/04/03 - 14:40:12 | 200 |   28.182196ms |    10.5.137.236 | POST     /api/v3/userapi/search/-1

E0403 14:46:22.741627    5742 privilege.go:163] search role privilege json error: json: cannot unmarshal string into Go struct field SearchAppResult.data of type middleware.AppResult

截图如下：
![image](https://user-images.githubusercontent.com/2688115/38234003-112bbfde-374f-11e8-97e6-0a3b271f95a7.png)

**Comment by lowenitt** [comment]
对页面系统有影响吗  ？ 有影响的话  ，方便提供下前端截图@dragonku7

**Comment by dragonku7** [comment]
![image](https://user-images.githubusercontent.com/2688115/38234876-ca664b34-3751-11e8-8b17-f154d90be2bf.png)
前台界面变成如上，左边导航栏出不来了，下放有js提示错误

**Comment by lowenitt** [comment]
看下network 截图

**Comment by dragonku7** [comment]
这会已经好了，我换了一台机器重新部署了，到现在为止还是正常的

**Comment by lowenitt** [comment]
ok
