### ISSUE TITLE
安装部署指导书里的可执行文件链接失效

### ISSUE THREAD

**Issue by NingLee** [Tencent/bk-cmdb#690]
问题描述
===========
安装部署指导书里，二进制文件链接失效
![image](https://user-images.githubusercontent.com/1845374/42160116-a2b5f6a2-7e28-11e8-822f-38f0920bb626.png)

重现方法
================
必现

关键信息
=========

无

**Comment by NingLee** [comment]
![image](https://user-images.githubusercontent.com/1845374/42160178-d52fb1cc-7e28-11e8-9f7d-7a3859f4c0ef.png)

**Comment by lowenitt** [comment]
好的， 我们排查下
