### ISSUE TITLE
页面访问后端的url和后端实际监听的ip地址不匹配

### ISSUE THREAD

**Issue by mdh67899** [Tencent/bk-cmdb#692]
问题描述
===========
默认web界面获取后端信息时用的url为`http://127.0.0.1:8083`, 但实际上本机程序监听的地址是`./cmdb_webserver --addrport=10.21.5.239:8083 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=127.0.0.1:2181`

![hello](https://user-images.githubusercontent.com/8528207/42213982-d2d4f904-7eec-11e8-9c1d-6ea3894e3977.png)

重现方法
================
<列出如何重现的方法或操作步骤>

**重要提醒**: 请优先尝试最新发布的版本 (发布清单： https://github.com/Tencent/bk-cmdb/releases), 如果问题不能在最新发布的版本里重现，说明此问题已经被修复。

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): `<3cbe2b397700cc36a50c4b1dac7998c09f9a9bad>`
 - [ ] Redis     版本: `<示例： 3.2.11>`
 - [ ] MongoDB   版本: `<示例： 2.8.0>`
 - [ ] ZooKeeper 版本: `<示例： 3.4.11>`
 - [ ] 操作系统      : `<示例： Centos 5 (x64)>`
 - [ ] bk-cmdb 异常日志

**Comment by uriwang** [comment]
重新初始化，参考FAQ
