### ISSUE TITLE
运行之后打不开页面

### ISSUE THREAD

**Issue by ykdsg** [Tencent/bk-cmdb#696]
问题描述
===========
在本地的mac os 机器上，根据文档进行配置，启动没提示出错，但是网页打不开。
问下错误的日志可以在哪看到？
cmdb | v3.0.8⚡ ➜  ./start.sh
starting: cmdb_adminserver
starting: cmdb_apiserver
starting: cmdb_auditcontroller
starting: cmdb_datacollection
starting: cmdb_eventserver
starting: cmdb_hostcontroller
starting: cmdb_hostserver
starting: cmdb_objectcontroller
starting: cmdb_proccontroller
starting: cmdb_procserver
starting: cmdb_toposerver
starting: cmdb_webserver
  501 39715     1   0  9:34PM ttys002    0:00.04 ./cmdb_adminserver --addrport=10.0.0.9:60004 --logtostderr=false --log-dir=./logs --v=0 --config=configures/migrate.conf
  501 39725     1   0  9:34PM ttys002    0:00.06 ./cmdb_apiserver --addrport=10.0.0.9:8080 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185
  501 39735     1   0  9:34PM ttys002    0:00.05 ./cmdb_auditcontroller --addrport=10.0.0.9:50005 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185
  501 39745     1   0  9:34PM ttys002    0:00.03 ./cmdb_datacollection --addrport=10.0.0.9:60005 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185
  501 39755     1   0  9:34PM ttys002    0:00.05 ./cmdb_eventserver --addrport=10.0.0.9:60009 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185
  501 39765     1   0  9:34PM ttys002    0:00.05 ./cmdb_hostcontroller --addrport=10.0.0.9:50002 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185
  501 39776     1   0  9:34PM ttys002    0:00.05 ./cmdb_hostserver --addrport=10.0.0.9:60001 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185
  501 39786     1   0  9:34PM ttys002    0:00.05 ./cmdb_objectcontroller --addrport=10.0.0.9:50001 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185
  501 39796     1   0  9:34PM ttys002    0:00.05 ./cmdb_proccontroller --addrport=10.0.0.9:50003 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185
  501 39806     1   0  9:34PM ttys002    0:00.05 ./cmdb_procserver --addrport=10.0.0.9:60003 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185
  501 39816     1   0  9:34PM ttys002    0:00.04 ./cmdb_toposerver --addrport=10.0.0.9:60002 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185
  501 39826     1   0  9:34PM ttys002    0:00.00 ./cmdb_webserver --addrport=10.0.0.9:8083 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185

看了下进程，只有6个
  ps -ef |grep cmdb
  501 46296     1   0  9:39AM ttys002    0:00.11 ./cmdb_adminserver --addrport=10.88.97.230:60004 --logtostderr=false --log-dir=./logs --v=0 --config=configures/migrate.conf
  501 46306     1   0  9:39AM ttys002    0:00.12 ./cmdb_apiserver --addrport=10.88.97.230:8080 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185
  501 46316     1   0  9:39AM ttys002    0:00.10 ./cmdb_auditcontroller --addrport=10.88.97.230:50005 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185
  501 46356     1   0  9:39AM ttys002    0:00.11 ./cmdb_hostserver --addrport=10.88.97.230:60001 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185
  501 46388     1   0  9:39AM ttys002    0:00.10 ./cmdb_procserver --addrport=10.88.97.230:60003 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185
  501 46398     1   0  9:39AM ttys002    0:00.10 ./cmdb_toposerver --addrport=10.88.97.230:60002 --logtostderr=false --log-dir=./logs --v=0 --regdiscv=172.16.13.61:2185
  501 46528 21472   0  9:40AM ttys002    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn cmdb

重现方法
================
使用的是v3.0.8
配置脚本

python init.py --discovery 127.0.0.1:2185 --database cmdb --redis_ip 127.0.0.1 --redis_port 6379 --redis_pass cc --mongo_ip 127.0.0.1 --mongo_port 27017 --mongo_user cc --mongo_pass cc --blueking_cmdb_url http://127.0.0.1:8083 --listen_port 8083

**重要提醒**: 请优先尝试最新发布的版本 (发布清单： https://github.com/Tencent/bk-cmdb/releases), 如果问题不能在最新发布的版本里重现，说明此问题已经被修复。

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): `<示例： v3.0.6-alpha 或者 git sha. 请不要使用 "最新版本" 或 "当前版本"等无法准确定位代码版本的语句描述>`
 - [ ] Redis     版本: `<示例： 3.2.11>`
 - [ ] MongoDB   版本: `<示例： 2.8.0>`
 - [ ] ZooKeeper 版本: `<示例： 3.4.11>`
 - [ ] 操作系统      : `<示例： Centos 5 (x64)>`
 - [ ] bk-cmdb 异常日志

**Comment by rentiansheng** [comment]
@ykdsg 看下没有没有启动程序的 cmdb_xxx/logs 日志

**Comment by breezelxp** [comment]
@ykdsg 你好，由于你长时间没有再更新状态信息，现将该issue关闭，如果你还有关于此issue的任何疑问，可以重新开启该issue.

**Comment by AngieQ1** [comment]
请问最后解决了嘛?
