### ISSUE TITLE
需求：模型有单关联，多关联关系，没有自关联关系的表达。

### ISSUE THREAD

**Issue by Timjava1** [Tencent/bk-cmdb#697]
问题描述
===========
目前针对模型的关系，可以自定义单关联和多关联。可以实现各个实例之前的关系表达。
但对于自己关联自己的关系，目前不知道怎么表达。
例如说A模块依赖B模块。  X进程调用Y进程。

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   版本 (３.0.7)

**Comment by techfindd** [comment]
此版本中暂时没有开放模型自关联的功能， 将在支持网络自动发现的版本中支持自关联的功能

**Comment by Timjava1** [comment]
网络自动发现版本预计是什么时间发布？是自动发现主机、进程吗？

**Comment by techfindd** [comment]
网络自动发现的功能预计在8月中旬发布
