### ISSUE TITLE
请问用户管理的功能目前是没有么？

### ISSUE THREAD

**Issue by ly188128934** [Tencent/bk-cmdb#698]
问题描述
===========
部署好蓝鲸配置平台后，发现不能管理用户，只有admin用户。
也没有找到新增用户的地方。
这是初始化的命令：
python init.py --redis_pass kingsoft --mongo_pass cc  --discovery 127.0.0.1:2181 --redis_ip 127.0.0.1 --mongo_ip 127.0.0.1 --mongo_user cc --blueking_cmdb_url http://10.13.82.159:8083 --listen_port 8083

不知道这个报错是什么意思，我服务能正常起来：
initial configurations success, configs could be found at cmdb_adminserver/configures

使用的代码版本：
commit a8f244518c50de0f87eb843ea04d57469c7f4f5a
tag：
v2.0.0
v3.0.6-alpha
v3.0.7-beta

重现方法
================
<列出如何重现的方法或操作步骤>

**重要提醒**: 请优先尝试最新发布的版本 (发布清单： https://github.com/Tencent/bk-cmdb/releases), 如果问题不能在最新发布的版本里重现，说明此问题已经被修复。

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): `<示例： v3.0.6-alpha 或者 git sha. 请不要使用 "最新版本" 或 "当前版本"等无法准确定位代码版本的语句描述>`
 - [x] Redis     版本: `<示例： 3.2.11>`
 - [x] MongoDB   版本: v4.0.0
 - [x] ZooKeeper 版本: 4.0.10
 - [x] 操作系统      :  centos7.4
 - [ ] bk-cmdb 异常日志

**Comment by ly188128934** [comment]
看了一下服务的介绍，没有发现哪个服务是用来管理用户的

**Comment by lowenitt** [comment]
蓝鲸的用户管理功能在蓝鲸paas 平台实现的，开源的cmdb 目前处于免登陆的模式

**Comment by flashccie** [comment]
【site]
    bk_login_url=${paas_url}/login/?app_id=%s&c_url=%s
    check_url=${paas_url}/login/accounts/get_user/?bk_token=
    bk_account_url=${paas_url}/login/accounts/get_all_user/?bk_token=%s

看了下，用到PAAS平台的功能，也就是这个，能不能把3个功能的输入输出弄个文档呢，这样子就可以自已实现用户管理了。

**Comment by uriwang** [comment]
@flashccie 
登陆认证是通过这些参数配置的认证地址，这里的参数目前只能与蓝鲸体系对接。
