### ISSUE TITLE
php7.0支持吗，执行初始化数据时日志报没有定义mysql_connect()

### ISSUE THREAD

**Issue by huangmeng4520** [Tencent/bk-cmdb#7]
我们目前还没在php7.0环境测试过，没定义mysq_connect 应该是php扩展没编译mysql

**Comment by LHanL** [comment]
貌似是 php 7 在编译时候 --mysql 是无效的？

**Comment by huangmeng4520** [comment]
用php7.0过不去，切换到5.6.20版本继续尝试

**Comment by LHanL** [comment]
@huangmeng4520 5.6.29 已测试通过

**Comment by lowenitt** [comment]
好的，php 7.0的兼容性我们还没完整的测试过

**Comment by raindylong** [comment]
记忆中php7.0已经是不支持旧版本的mysql扩展了，都是推荐直接用pdo_mysql了。

**Comment by lowenitt** [comment]
可以尝试修改db.php中的driver 类型，查看下当前编译的php版本中支持的mysql驱动

**Comment by shitfSign** [comment]
可以使用mysqli 就可以了。

**Comment by amazingbing** [comment]
php7.0去除了mysql_connect   ，改用 new mysqli(.....)  ,

**Comment by Nassir1995** [comment]
在db.php中数据库设置时修改'dbdriver' => 'mysqli',
