### ISSUE TITLE
安装bk-cmdb-3.0.8-rc.1 版本发现提示 "查询主线失败"

### ISSUE THREAD

**Issue by hzchenkj** [Tencent/bk-cmdb#710]
问题描述
===========
安装bk-cmdb-3.0.8-rc.1 版本发现提示 "查询主线失败"

导入下载的ecxcel 模板，提示 "导入不存在字段"

关键信息
=========

 - [x] bk-cmdb   bk-cmdb-3.0.8-rc.1
 - [ ] Redis     版本: redis-3.2.10
 - [ ] MongoDB   版本: mongodb-linux-x86_64-rhel62-4.0.0
 - [ ] ZooKeeper 版本: zookeeper-3.4.12
 - [ ] 操作系统      :   CentOS 7

**Comment by lowenitt** [comment]
你好， 请具体截一下浏览器console 请求失败的信息
