### ISSUE TITLE
3.0.6版本升级3.0.8报错：E0813 16:42:33.035806   23699 conf.go:87] fail to write languate packages to center, err:stat :  no such file or directory

### ISSUE THREAD

**Issue by kyyang** [Tencent/bk-cmdb#904]
问题描述
===========

3.0.6版本升级3.0.8报错
cmdb_adminserver报错日志：
conf.go:87] fail to write languate packages to center, err:stat :  no such file or directory

重现方法
================
1. 上传新版本应包至 ./cmdb 目录
2. 解压出来使用新包里的upgrade.sh脚本升级
`./upgrade.sh cmdb.tar.gz`,
3. 启动 `./stop.sh && ./start.sh`

> 应用包下载地址是安装部署指导里的可执行文件。另外这个包有个问题是，打包是没有清理以 ._ 开头的隐藏文件，会导致在 Linux下面部署时读取文件报错问题。

**重要提醒**: 请优先尝试最新发布的版本 (发布清单： https://github.com/Tencent/bk-cmdb/releases), 如果问题不能在最新发布的版本里重现，说明此问题已经被修复。

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb  3.0.8-rc1 
 - [ ] Redis     版本: `3.2.11`
 - [ ] MongoDB   版本: `2.8.0`
 - [ ] ZooKeeper 版本: ` 3.4.11`
 - [ ] 操作系统      : ` Centos 7 (64)`
 - [ ] bk-cmdb 异常日志

cmdb_adminserver报错日志：
conf.go:87] fail to write languate packages to center, err:stat :  no such file or directory

另外，各组件一直抛以下异常：
Fail to watch context for path(/cc/services/language), err:zk: node does not exist

**Comment by uriwang** [comment]
Fail to watch context for path(/cc/services/language), err:zk: node does not exist
============
这个问题需要检测 个基础组件是否正常运行。可参考FAQ 自查

**Comment by kyyang** [comment]
cmdb_adminserver没有启动起来，报错日志如下：

```
conf.go:87] fail to write languate packages to center, err:stat : no such file or directory
```

另外，隐藏文件之类的东西已经清理了～
