### ISSUE TITLE
agent下载地址404

### ISSUE THREAD

**Issue by doterme** [Tencent/bk-cmdb#947]
问题描述
===========
![image](https://user-images.githubusercontent.com/12495369/44377136-17224280-a52e-11e8-9e4a-e23b2d07c549.png)

点击agent下载地址，404

重现方法
================
<列出如何重现的方法或操作步骤>

**重要提醒**: 请优先尝试最新发布的版本 (发布清单： https://github.com/Tencent/bk-cmdb/releases), 如果问题不能在最新发布的版本里重现，说明此问题已经被修复。

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): `v3.0.8-rc.1`
 - [ ] Redis     版本: `3.2.11`
 - [ ] MongoDB   版本: `2.8.0`
 - [ ] ZooKeeper 版本: ` 3.4.11`
 - [ ] 操作系统      : ` Centos 7 (x64)`
 - [ ] bk-cmdb 异常日志

**Comment by lowenitt** [comment]
这里正常是跳转到agent 安装app的地址， 需要在webserver.conf 里面配置下。

**Comment by yadongwang110** [comment]
@lowenitt 需要配置成什么地址？

**Comment by yadongwang110** [comment]
我们完整安装了3.0.8rc01版本的源码，但是仍然是404的agent地址

**Comment by doterme** [comment]
@lowenitt 求解决，thks

**Comment by doterme** [comment]
基本没人回复

**Comment by lowenitt** [comment]
这里需要完整的蓝鲸社区版或者企业版（有节点管理模块），这个地址才会生效的，  单独的开源cmdb不带此功能

**Comment by doterme** [comment]
@lowenitt 能否把agent也放出来呢？

**Comment by uriwang** [comment]
@doterme agent 暂无开源计划，如果需要可以去蓝鲸官网了解下社区版和企业版。

**Comment by breezelxp** [comment]
@doterme 你好，由于你长时间没有再更新状态信息，现将该issue关闭，如果你还有关于此issue的任何疑问，可以重新开启该issue.
