### ISSUE TITLE
是否可以提供一份docker部署文档

### ISSUE THREAD

**Issue by blair-0** [Tencent/bk-cmdb#958]
是否可以提供一份docker部署文档
===========
image.sh生成了各服务镜像后，怎么像常规部署里面进行初始化？怎么实现数据持久化？

**Comment by lowenitt** [comment]
部署的话， 依赖与你本身的编排工具， 数据持久化是指哪一方面？

**Comment by blair-0** [comment]
比如存储在CMDB里的资产数据，如果删除容器后数据是不是就丢失了？需要挂载主机上的卷到容器中吗？

**Comment by lowenitt** [comment]
生产环境的存储的话，可以走传统方案 ，你说的挂载也是一种方式

**Comment by breezelxp** [comment]
@blair-0 你好，由于你长时间没有再更新状态信息，现将该issue关闭，如果你还有关于此issue的任何疑问，可以重新开启该issue.
