### ISSUE TITLE
过滤条件支持嵌套语句

### ISSUE THREAD

**Issue by Colstuwjx** [Tencent/bk-cmdb#968]
问题描述
===========
Mongo原生是支持嵌套语句查询的，但是好像API不支持。

重现方法
================
如题，想实现mongo里面 `db.inventory.find( { "size.h": { $lt: 15 } } )` 以`.`间隔方式嵌套查询，但是调用bkcmdb API时这样查询是不生效的：
```
        {
            "condition": {
                "vpc":[
                    {	
                        "field": "idc.bk_inst_id",
                        "operator": "$eq",
                        "value": 44529
                    }
                ]
            },
            "fields": {
            },
            "page": {
                "start": 0,
                "limit": 1,
                "sort": ""
            }
        }
```

关键信息
=========

**重要提醒**: 这些关键信息会辅助我们快速定位问题。

请提供以下信息:

 - [x] bk-cmdb   版本 (发布版本号 或 git tag): `v3.0.6`
 - [ ] Redis     版本: `<示例： 3.2.11>`
 - [ ] MongoDB   版本: `<示例： 2.8.0>`
 - [ ] ZooKeeper 版本: `<示例： 3.4.11>`
 - [ ] 操作系统      : `<示例： Centos 5 (x64)>`
 - [ ] bk-cmdb 异常日志

**Comment by lowenitt** [comment]
收到， 我们会考虑在后续的版本中加入对嵌套条件的支持

**Comment by Colstuwjx** [comment]
从 [condition](https://github.com/Tencent/bk-cmdb/blob/master/src/common/condition/condition.go#L44) 转换到 mongo查询的这部分是如何实现的呢？想看看能不能建个PR~

**Comment by uriwang** [comment]
@Colstuwjx  欢迎参与建设
